package com.dao.mapper;

import com.dao.bean.D_curRatioCurvePo;
import com.dao.bean.D_curRatioCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_curRatioCurvePoMapper {

    @Select({
        "select",
        "LD_ID, SYS_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_CURRATIO_1, ",
        "HAR_CURRATIO_2, HAR_CURRATIO_3, HAR_CURRATIO_4, HAR_CURRATIO_5, HAR_CURRATIO_6, ",
        "HAR_CURRATIO_7, HAR_CURRATIO_8, HAR_CURRATIO_9, HAR_CURRATIO_10, HAR_CURRATIO_11, ",
        "HAR_CURRATIO_12, HAR_CURRATIO_13, HAR_CURRATIO_14, HAR_CURRATIO_15, HAR_CURRATIO_16, ",
        "HAR_CURRATIO_17, HAR_CURRATIO_18, HAR_CURRATIO_19, HAR_CURRATIO_20, HAR_CURRATIO_21, ",
        "HAR_CURRATIO_22, HAR_CURRATIO_23, HAR_CURRATIO_24, HAR_CURRATIO_25, HAR_CURRATIO_26, ",
        "HAR_CURRATIO_27, HAR_CURRATIO_28, HAR_CURRATIO_29, HAR_CURRATIO_30, HAR_CURRATIO_31, ",
        "HAR_CURRATIO_32, HAR_CURRATIO_33, HAR_CURRATIO_34, HAR_CURRATIO_35, HAR_CURRATIO_36, ",
        "HAR_CURRATIO_37, HAR_CURRATIO_38, HAR_CURRATIO_39, HAR_CURRATIO_40, HAR_CURRATIO_41, ",
        "HAR_CURRATIO_42, HAR_CURRATIO_43, HAR_CURRATIO_44, HAR_CURRATIO_45, HAR_CURRATIO_46, ",
        "HAR_CURRATIO_47, HAR_CURRATIO_48, HAR_CURRATIO_49, HAR_CURRATIO_50, HAR_CURRATIO_51, ",
        "HAR_CURRATIO_52, HAR_CURRATIO_53, HAR_CURRATIO_54, HAR_CURRATIO_55, HAR_CURRATIO_56, ",
        "HAR_CURRATIO_57, HAR_CURRATIO_58, HAR_CURRATIO_59, HAR_CURRATIO_60, HAR_CURRATIO_61, ",
        "HAR_CURRATIO_62, HAR_CURRATIO_63, HAR_CURRATIO_64, HAR_CURRATIO_65, HAR_CURRATIO_66, ",
        "HAR_CURRATIO_67, HAR_CURRATIO_68, HAR_CURRATIO_69, HAR_CURRATIO_70, HAR_CURRATIO_71, ",
        "HAR_CURRATIO_72, HAR_CURRATIO_73, HAR_CURRATIO_74, HAR_CURRATIO_75, HAR_CURRATIO_76, ",
        "HAR_CURRATIO_77, HAR_CURRATIO_78, HAR_CURRATIO_79, HAR_CURRATIO_80, HAR_CURRATIO_81, ",
        "HAR_CURRATIO_82, HAR_CURRATIO_83, HAR_CURRATIO_84, HAR_CURRATIO_85, HAR_CURRATIO_86, ",
        "HAR_CURRATIO_87, HAR_CURRATIO_88, HAR_CURRATIO_89, HAR_CURRATIO_90, HAR_CURRATIO_91, ",
        "HAR_CURRATIO_92, HAR_CURRATIO_93, HAR_CURRATIO_94, HAR_CURRATIO_95, HAR_CURRATIO_96, ",
        "HAR_CURRATIO_97, HAR_CURRATIO_98, HAR_CURRATIO_99, HAR_CURRATIO_100, HAR_CURRATIO_101, ",
        "HAR_CURRATIO_102, HAR_CURRATIO_103, HAR_CURRATIO_104, HAR_CURRATIO_105, HAR_CURRATIO_106, ",
        "HAR_CURRATIO_107, HAR_CURRATIO_108, HAR_CURRATIO_109, HAR_CURRATIO_110, HAR_CURRATIO_111, ",
        "HAR_CURRATIO_112, HAR_CURRATIO_113, HAR_CURRATIO_114, HAR_CURRATIO_115, HAR_CURRATIO_116, ",
        "HAR_CURRATIO_117, HAR_CURRATIO_118, HAR_CURRATIO_119, HAR_CURRATIO_120, HAR_CURRATIO_121, ",
        "HAR_CURRATIO_122, HAR_CURRATIO_123, HAR_CURRATIO_124, HAR_CURRATIO_125, HAR_CURRATIO_126, ",
        "HAR_CURRATIO_127, HAR_CURRATIO_128, HAR_CURRATIO_129, HAR_CURRATIO_130, HAR_CURRATIO_131, ",
        "HAR_CURRATIO_132, HAR_CURRATIO_133, HAR_CURRATIO_134, HAR_CURRATIO_135, HAR_CURRATIO_136, ",
        "HAR_CURRATIO_137, HAR_CURRATIO_138, HAR_CURRATIO_139, HAR_CURRATIO_140, HAR_CURRATIO_141, ",
        "HAR_CURRATIO_142, HAR_CURRATIO_143, HAR_CURRATIO_144, HAR_CURRATIO_145, HAR_CURRATIO_146, ",
        "HAR_CURRATIO_147, HAR_CURRATIO_148, HAR_CURRATIO_149, HAR_CURRATIO_150, HAR_CURRATIO_151, ",
        "HAR_CURRATIO_152, HAR_CURRATIO_153, HAR_CURRATIO_154, HAR_CURRATIO_155, HAR_CURRATIO_156, ",
        "HAR_CURRATIO_157, HAR_CURRATIO_158, HAR_CURRATIO_159, HAR_CURRATIO_160, HAR_CURRATIO_161, ",
        "HAR_CURRATIO_162, HAR_CURRATIO_163, HAR_CURRATIO_164, HAR_CURRATIO_165, HAR_CURRATIO_166, ",
        "HAR_CURRATIO_167, HAR_CURRATIO_168, HAR_CURRATIO_169, HAR_CURRATIO_170, HAR_CURRATIO_171, ",
        "HAR_CURRATIO_172, HAR_CURRATIO_173, HAR_CURRATIO_174, HAR_CURRATIO_175, HAR_CURRATIO_176, ",
        "HAR_CURRATIO_177, HAR_CURRATIO_178, HAR_CURRATIO_179, HAR_CURRATIO_180, HAR_CURRATIO_181, ",
        "HAR_CURRATIO_182, HAR_CURRATIO_183, HAR_CURRATIO_184, HAR_CURRATIO_185, HAR_CURRATIO_186, ",
        "HAR_CURRATIO_187, HAR_CURRATIO_188, HAR_CURRATIO_189, HAR_CURRATIO_190, HAR_CURRATIO_191, ",
        "HAR_CURRATIO_192, HAR_CURRATIO_193, HAR_CURRATIO_194, HAR_CURRATIO_195, HAR_CURRATIO_196, ",
        "HAR_CURRATIO_197, HAR_CURRATIO_198, HAR_CURRATIO_199, HAR_CURRATIO_200, HAR_CURRATIO_201, ",
        "HAR_CURRATIO_202, HAR_CURRATIO_203, HAR_CURRATIO_204, HAR_CURRATIO_205, HAR_CURRATIO_206, ",
        "HAR_CURRATIO_207, HAR_CURRATIO_208, HAR_CURRATIO_209, HAR_CURRATIO_210, HAR_CURRATIO_211, ",
        "HAR_CURRATIO_212, HAR_CURRATIO_213, HAR_CURRATIO_214, HAR_CURRATIO_215, HAR_CURRATIO_216, ",
        "HAR_CURRATIO_217, HAR_CURRATIO_218, HAR_CURRATIO_219, HAR_CURRATIO_220, HAR_CURRATIO_221, ",
        "HAR_CURRATIO_222, HAR_CURRATIO_223, HAR_CURRATIO_224, HAR_CURRATIO_225, HAR_CURRATIO_226, ",
        "HAR_CURRATIO_227, HAR_CURRATIO_228, HAR_CURRATIO_229, HAR_CURRATIO_230, HAR_CURRATIO_231, ",
        "HAR_CURRATIO_232, HAR_CURRATIO_233, HAR_CURRATIO_234, HAR_CURRATIO_235, HAR_CURRATIO_236, ",
        "HAR_CURRATIO_237, HAR_CURRATIO_238, HAR_CURRATIO_239, HAR_CURRATIO_240, HAR_CURRATIO_241, ",
        "HAR_CURRATIO_242, HAR_CURRATIO_243, HAR_CURRATIO_244, HAR_CURRATIO_245, HAR_CURRATIO_246, ",
        "HAR_CURRATIO_247, HAR_CURRATIO_248, HAR_CURRATIO_249, HAR_CURRATIO_250, HAR_CURRATIO_251, ",
        "HAR_CURRATIO_252, HAR_CURRATIO_253, HAR_CURRATIO_254, HAR_CURRATIO_255, HAR_CURRATIO_256, ",
        "HAR_CURRATIO_257, HAR_CURRATIO_258, HAR_CURRATIO_259, HAR_CURRATIO_260, HAR_CURRATIO_261, ",
        "HAR_CURRATIO_262, HAR_CURRATIO_263, HAR_CURRATIO_264, HAR_CURRATIO_265, HAR_CURRATIO_266, ",
        "HAR_CURRATIO_267, HAR_CURRATIO_268, HAR_CURRATIO_269, HAR_CURRATIO_270, HAR_CURRATIO_271, ",
        "HAR_CURRATIO_272, HAR_CURRATIO_273, HAR_CURRATIO_274, HAR_CURRATIO_275, HAR_CURRATIO_276, ",
        "HAR_CURRATIO_277, HAR_CURRATIO_278, HAR_CURRATIO_279, HAR_CURRATIO_280, HAR_CURRATIO_281, ",
        "HAR_CURRATIO_282, HAR_CURRATIO_283, HAR_CURRATIO_284, HAR_CURRATIO_285, HAR_CURRATIO_286, ",
        "HAR_CURRATIO_287, HAR_CURRATIO_288",
        "from c_mhai_curratio_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="HAR_CURRATIO_1", property="harCurratio1", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_2", property="harCurratio2", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_3", property="harCurratio3", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_4", property="harCurratio4", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_5", property="harCurratio5", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_6", property="harCurratio6", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_7", property="harCurratio7", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_8", property="harCurratio8", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_9", property="harCurratio9", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_10", property="harCurratio10", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_11", property="harCurratio11", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_12", property="harCurratio12", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_13", property="harCurratio13", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_14", property="harCurratio14", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_15", property="harCurratio15", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_16", property="harCurratio16", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_17", property="harCurratio17", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_18", property="harCurratio18", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_19", property="harCurratio19", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_20", property="harCurratio20", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_21", property="harCurratio21", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_22", property="harCurratio22", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_23", property="harCurratio23", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_24", property="harCurratio24", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_25", property="harCurratio25", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_26", property="harCurratio26", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_27", property="harCurratio27", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_28", property="harCurratio28", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_29", property="harCurratio29", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_30", property="harCurratio30", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_31", property="harCurratio31", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_32", property="harCurratio32", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_33", property="harCurratio33", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_34", property="harCurratio34", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_35", property="harCurratio35", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_36", property="harCurratio36", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_37", property="harCurratio37", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_38", property="harCurratio38", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_39", property="harCurratio39", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_40", property="harCurratio40", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_41", property="harCurratio41", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_42", property="harCurratio42", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_43", property="harCurratio43", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_44", property="harCurratio44", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_45", property="harCurratio45", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_46", property="harCurratio46", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_47", property="harCurratio47", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_48", property="harCurratio48", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_49", property="harCurratio49", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_50", property="harCurratio50", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_51", property="harCurratio51", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_52", property="harCurratio52", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_53", property="harCurratio53", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_54", property="harCurratio54", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_55", property="harCurratio55", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_56", property="harCurratio56", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_57", property="harCurratio57", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_58", property="harCurratio58", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_59", property="harCurratio59", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_60", property="harCurratio60", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_61", property="harCurratio61", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_62", property="harCurratio62", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_63", property="harCurratio63", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_64", property="harCurratio64", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_65", property="harCurratio65", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_66", property="harCurratio66", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_67", property="harCurratio67", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_68", property="harCurratio68", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_69", property="harCurratio69", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_70", property="harCurratio70", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_71", property="harCurratio71", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_72", property="harCurratio72", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_73", property="harCurratio73", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_74", property="harCurratio74", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_75", property="harCurratio75", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_76", property="harCurratio76", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_77", property="harCurratio77", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_78", property="harCurratio78", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_79", property="harCurratio79", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_80", property="harCurratio80", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_81", property="harCurratio81", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_82", property="harCurratio82", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_83", property="harCurratio83", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_84", property="harCurratio84", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_85", property="harCurratio85", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_86", property="harCurratio86", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_87", property="harCurratio87", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_88", property="harCurratio88", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_89", property="harCurratio89", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_90", property="harCurratio90", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_91", property="harCurratio91", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_92", property="harCurratio92", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_93", property="harCurratio93", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_94", property="harCurratio94", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_95", property="harCurratio95", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_96", property="harCurratio96", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_97", property="harCurratio97", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_98", property="harCurratio98", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_99", property="harCurratio99", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_100", property="harCurratio100", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_101", property="harCurratio101", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_102", property="harCurratio102", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_103", property="harCurratio103", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_104", property="harCurratio104", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_105", property="harCurratio105", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_106", property="harCurratio106", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_107", property="harCurratio107", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_108", property="harCurratio108", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_109", property="harCurratio109", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_110", property="harCurratio110", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_111", property="harCurratio111", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_112", property="harCurratio112", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_113", property="harCurratio113", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_114", property="harCurratio114", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_115", property="harCurratio115", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_116", property="harCurratio116", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_117", property="harCurratio117", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_118", property="harCurratio118", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_119", property="harCurratio119", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_120", property="harCurratio120", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_121", property="harCurratio121", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_122", property="harCurratio122", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_123", property="harCurratio123", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_124", property="harCurratio124", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_125", property="harCurratio125", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_126", property="harCurratio126", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_127", property="harCurratio127", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_128", property="harCurratio128", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_129", property="harCurratio129", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_130", property="harCurratio130", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_131", property="harCurratio131", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_132", property="harCurratio132", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_133", property="harCurratio133", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_134", property="harCurratio134", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_135", property="harCurratio135", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_136", property="harCurratio136", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_137", property="harCurratio137", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_138", property="harCurratio138", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_139", property="harCurratio139", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_140", property="harCurratio140", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_141", property="harCurratio141", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_142", property="harCurratio142", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_143", property="harCurratio143", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_144", property="harCurratio144", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_145", property="harCurratio145", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_146", property="harCurratio146", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_147", property="harCurratio147", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_148", property="harCurratio148", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_149", property="harCurratio149", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_150", property="harCurratio150", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_151", property="harCurratio151", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_152", property="harCurratio152", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_153", property="harCurratio153", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_154", property="harCurratio154", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_155", property="harCurratio155", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_156", property="harCurratio156", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_157", property="harCurratio157", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_158", property="harCurratio158", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_159", property="harCurratio159", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_160", property="harCurratio160", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_161", property="harCurratio161", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_162", property="harCurratio162", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_163", property="harCurratio163", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_164", property="harCurratio164", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_165", property="harCurratio165", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_166", property="harCurratio166", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_167", property="harCurratio167", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_168", property="harCurratio168", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_169", property="harCurratio169", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_170", property="harCurratio170", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_171", property="harCurratio171", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_172", property="harCurratio172", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_173", property="harCurratio173", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_174", property="harCurratio174", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_175", property="harCurratio175", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_176", property="harCurratio176", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_177", property="harCurratio177", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_178", property="harCurratio178", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_179", property="harCurratio179", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_180", property="harCurratio180", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_181", property="harCurratio181", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_182", property="harCurratio182", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_183", property="harCurratio183", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_184", property="harCurratio184", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_185", property="harCurratio185", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_186", property="harCurratio186", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_187", property="harCurratio187", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_188", property="harCurratio188", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_189", property="harCurratio189", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_190", property="harCurratio190", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_191", property="harCurratio191", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_192", property="harCurratio192", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_193", property="harCurratio193", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_194", property="harCurratio194", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_195", property="harCurratio195", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_196", property="harCurratio196", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_197", property="harCurratio197", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_198", property="harCurratio198", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_199", property="harCurratio199", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_200", property="harCurratio200", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_201", property="harCurratio201", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_202", property="harCurratio202", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_203", property="harCurratio203", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_204", property="harCurratio204", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_205", property="harCurratio205", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_206", property="harCurratio206", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_207", property="harCurratio207", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_208", property="harCurratio208", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_209", property="harCurratio209", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_210", property="harCurratio210", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_211", property="harCurratio211", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_212", property="harCurratio212", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_213", property="harCurratio213", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_214", property="harCurratio214", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_215", property="harCurratio215", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_216", property="harCurratio216", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_217", property="harCurratio217", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_218", property="harCurratio218", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_219", property="harCurratio219", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_220", property="harCurratio220", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_221", property="harCurratio221", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_222", property="harCurratio222", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_223", property="harCurratio223", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_224", property="harCurratio224", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_225", property="harCurratio225", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_226", property="harCurratio226", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_227", property="harCurratio227", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_228", property="harCurratio228", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_229", property="harCurratio229", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_230", property="harCurratio230", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_231", property="harCurratio231", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_232", property="harCurratio232", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_233", property="harCurratio233", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_234", property="harCurratio234", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_235", property="harCurratio235", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_236", property="harCurratio236", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_237", property="harCurratio237", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_238", property="harCurratio238", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_239", property="harCurratio239", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_240", property="harCurratio240", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_241", property="harCurratio241", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_242", property="harCurratio242", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_243", property="harCurratio243", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_244", property="harCurratio244", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_245", property="harCurratio245", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_246", property="harCurratio246", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_247", property="harCurratio247", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_248", property="harCurratio248", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_249", property="harCurratio249", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_250", property="harCurratio250", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_251", property="harCurratio251", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_252", property="harCurratio252", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_253", property="harCurratio253", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_254", property="harCurratio254", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_255", property="harCurratio255", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_256", property="harCurratio256", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_257", property="harCurratio257", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_258", property="harCurratio258", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_259", property="harCurratio259", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_260", property="harCurratio260", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_261", property="harCurratio261", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_262", property="harCurratio262", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_263", property="harCurratio263", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_264", property="harCurratio264", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_265", property="harCurratio265", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_266", property="harCurratio266", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_267", property="harCurratio267", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_268", property="harCurratio268", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_269", property="harCurratio269", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_270", property="harCurratio270", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_271", property="harCurratio271", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_272", property="harCurratio272", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_273", property="harCurratio273", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_274", property="harCurratio274", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_275", property="harCurratio275", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_276", property="harCurratio276", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_277", property="harCurratio277", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_278", property="harCurratio278", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_279", property="harCurratio279", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_280", property="harCurratio280", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_281", property="harCurratio281", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_282", property="harCurratio282", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_283", property="harCurratio283", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_284", property="harCurratio284", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_285", property="harCurratio285", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_286", property="harCurratio286", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_287", property="harCurratio287", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURRATIO_288", property="harCurratio288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_curRatioCurvePo> selectCurRationByDate(String data_date);

    @Select({
            "select",
            "LD_ID, SYS_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_CURRATIO_1, ",
            "HAR_CURRATIO_2, HAR_CURRATIO_3, HAR_CURRATIO_4, HAR_CURRATIO_5, HAR_CURRATIO_6, ",
            "HAR_CURRATIO_7, HAR_CURRATIO_8, HAR_CURRATIO_9, HAR_CURRATIO_10, HAR_CURRATIO_11, ",
            "HAR_CURRATIO_12, HAR_CURRATIO_13, HAR_CURRATIO_14, HAR_CURRATIO_15, HAR_CURRATIO_16, ",
            "HAR_CURRATIO_17, HAR_CURRATIO_18, HAR_CURRATIO_19, HAR_CURRATIO_20, HAR_CURRATIO_21, ",
            "HAR_CURRATIO_22, HAR_CURRATIO_23, HAR_CURRATIO_24, HAR_CURRATIO_25, HAR_CURRATIO_26, ",
            "HAR_CURRATIO_27, HAR_CURRATIO_28, HAR_CURRATIO_29, HAR_CURRATIO_30, HAR_CURRATIO_31, ",
            "HAR_CURRATIO_32, HAR_CURRATIO_33, HAR_CURRATIO_34, HAR_CURRATIO_35, HAR_CURRATIO_36, ",
            "HAR_CURRATIO_37, HAR_CURRATIO_38, HAR_CURRATIO_39, HAR_CURRATIO_40, HAR_CURRATIO_41, ",
            "HAR_CURRATIO_42, HAR_CURRATIO_43, HAR_CURRATIO_44, HAR_CURRATIO_45, HAR_CURRATIO_46, ",
            "HAR_CURRATIO_47, HAR_CURRATIO_48, HAR_CURRATIO_49, HAR_CURRATIO_50, HAR_CURRATIO_51, ",
            "HAR_CURRATIO_52, HAR_CURRATIO_53, HAR_CURRATIO_54, HAR_CURRATIO_55, HAR_CURRATIO_56, ",
            "HAR_CURRATIO_57, HAR_CURRATIO_58, HAR_CURRATIO_59, HAR_CURRATIO_60, HAR_CURRATIO_61, ",
            "HAR_CURRATIO_62, HAR_CURRATIO_63, HAR_CURRATIO_64, HAR_CURRATIO_65, HAR_CURRATIO_66, ",
            "HAR_CURRATIO_67, HAR_CURRATIO_68, HAR_CURRATIO_69, HAR_CURRATIO_70, HAR_CURRATIO_71, ",
            "HAR_CURRATIO_72, HAR_CURRATIO_73, HAR_CURRATIO_74, HAR_CURRATIO_75, HAR_CURRATIO_76, ",
            "HAR_CURRATIO_77, HAR_CURRATIO_78, HAR_CURRATIO_79, HAR_CURRATIO_80, HAR_CURRATIO_81, ",
            "HAR_CURRATIO_82, HAR_CURRATIO_83, HAR_CURRATIO_84, HAR_CURRATIO_85, HAR_CURRATIO_86, ",
            "HAR_CURRATIO_87, HAR_CURRATIO_88, HAR_CURRATIO_89, HAR_CURRATIO_90, HAR_CURRATIO_91, ",
            "HAR_CURRATIO_92, HAR_CURRATIO_93, HAR_CURRATIO_94, HAR_CURRATIO_95, HAR_CURRATIO_96, ",
            "HAR_CURRATIO_97, HAR_CURRATIO_98, HAR_CURRATIO_99, HAR_CURRATIO_100, HAR_CURRATIO_101, ",
            "HAR_CURRATIO_102, HAR_CURRATIO_103, HAR_CURRATIO_104, HAR_CURRATIO_105, HAR_CURRATIO_106, ",
            "HAR_CURRATIO_107, HAR_CURRATIO_108, HAR_CURRATIO_109, HAR_CURRATIO_110, HAR_CURRATIO_111, ",
            "HAR_CURRATIO_112, HAR_CURRATIO_113, HAR_CURRATIO_114, HAR_CURRATIO_115, HAR_CURRATIO_116, ",
            "HAR_CURRATIO_117, HAR_CURRATIO_118, HAR_CURRATIO_119, HAR_CURRATIO_120, HAR_CURRATIO_121, ",
            "HAR_CURRATIO_122, HAR_CURRATIO_123, HAR_CURRATIO_124, HAR_CURRATIO_125, HAR_CURRATIO_126, ",
            "HAR_CURRATIO_127, HAR_CURRATIO_128, HAR_CURRATIO_129, HAR_CURRATIO_130, HAR_CURRATIO_131, ",
            "HAR_CURRATIO_132, HAR_CURRATIO_133, HAR_CURRATIO_134, HAR_CURRATIO_135, HAR_CURRATIO_136, ",
            "HAR_CURRATIO_137, HAR_CURRATIO_138, HAR_CURRATIO_139, HAR_CURRATIO_140, HAR_CURRATIO_141, ",
            "HAR_CURRATIO_142, HAR_CURRATIO_143, HAR_CURRATIO_144, HAR_CURRATIO_145, HAR_CURRATIO_146, ",
            "HAR_CURRATIO_147, HAR_CURRATIO_148, HAR_CURRATIO_149, HAR_CURRATIO_150, HAR_CURRATIO_151, ",
            "HAR_CURRATIO_152, HAR_CURRATIO_153, HAR_CURRATIO_154, HAR_CURRATIO_155, HAR_CURRATIO_156, ",
            "HAR_CURRATIO_157, HAR_CURRATIO_158, HAR_CURRATIO_159, HAR_CURRATIO_160, HAR_CURRATIO_161, ",
            "HAR_CURRATIO_162, HAR_CURRATIO_163, HAR_CURRATIO_164, HAR_CURRATIO_165, HAR_CURRATIO_166, ",
            "HAR_CURRATIO_167, HAR_CURRATIO_168, HAR_CURRATIO_169, HAR_CURRATIO_170, HAR_CURRATIO_171, ",
            "HAR_CURRATIO_172, HAR_CURRATIO_173, HAR_CURRATIO_174, HAR_CURRATIO_175, HAR_CURRATIO_176, ",
            "HAR_CURRATIO_177, HAR_CURRATIO_178, HAR_CURRATIO_179, HAR_CURRATIO_180, HAR_CURRATIO_181, ",
            "HAR_CURRATIO_182, HAR_CURRATIO_183, HAR_CURRATIO_184, HAR_CURRATIO_185, HAR_CURRATIO_186, ",
            "HAR_CURRATIO_187, HAR_CURRATIO_188, HAR_CURRATIO_189, HAR_CURRATIO_190, HAR_CURRATIO_191, ",
            "HAR_CURRATIO_192, HAR_CURRATIO_193, HAR_CURRATIO_194, HAR_CURRATIO_195, HAR_CURRATIO_196, ",
            "HAR_CURRATIO_197, HAR_CURRATIO_198, HAR_CURRATIO_199, HAR_CURRATIO_200, HAR_CURRATIO_201, ",
            "HAR_CURRATIO_202, HAR_CURRATIO_203, HAR_CURRATIO_204, HAR_CURRATIO_205, HAR_CURRATIO_206, ",
            "HAR_CURRATIO_207, HAR_CURRATIO_208, HAR_CURRATIO_209, HAR_CURRATIO_210, HAR_CURRATIO_211, ",
            "HAR_CURRATIO_212, HAR_CURRATIO_213, HAR_CURRATIO_214, HAR_CURRATIO_215, HAR_CURRATIO_216, ",
            "HAR_CURRATIO_217, HAR_CURRATIO_218, HAR_CURRATIO_219, HAR_CURRATIO_220, HAR_CURRATIO_221, ",
            "HAR_CURRATIO_222, HAR_CURRATIO_223, HAR_CURRATIO_224, HAR_CURRATIO_225, HAR_CURRATIO_226, ",
            "HAR_CURRATIO_227, HAR_CURRATIO_228, HAR_CURRATIO_229, HAR_CURRATIO_230, HAR_CURRATIO_231, ",
            "HAR_CURRATIO_232, HAR_CURRATIO_233, HAR_CURRATIO_234, HAR_CURRATIO_235, HAR_CURRATIO_236, ",
            "HAR_CURRATIO_237, HAR_CURRATIO_238, HAR_CURRATIO_239, HAR_CURRATIO_240, HAR_CURRATIO_241, ",
            "HAR_CURRATIO_242, HAR_CURRATIO_243, HAR_CURRATIO_244, HAR_CURRATIO_245, HAR_CURRATIO_246, ",
            "HAR_CURRATIO_247, HAR_CURRATIO_248, HAR_CURRATIO_249, HAR_CURRATIO_250, HAR_CURRATIO_251, ",
            "HAR_CURRATIO_252, HAR_CURRATIO_253, HAR_CURRATIO_254, HAR_CURRATIO_255, HAR_CURRATIO_256, ",
            "HAR_CURRATIO_257, HAR_CURRATIO_258, HAR_CURRATIO_259, HAR_CURRATIO_260, HAR_CURRATIO_261, ",
            "HAR_CURRATIO_262, HAR_CURRATIO_263, HAR_CURRATIO_264, HAR_CURRATIO_265, HAR_CURRATIO_266, ",
            "HAR_CURRATIO_267, HAR_CURRATIO_268, HAR_CURRATIO_269, HAR_CURRATIO_270, HAR_CURRATIO_271, ",
            "HAR_CURRATIO_272, HAR_CURRATIO_273, HAR_CURRATIO_274, HAR_CURRATIO_275, HAR_CURRATIO_276, ",
            "HAR_CURRATIO_277, HAR_CURRATIO_278, HAR_CURRATIO_279, HAR_CURRATIO_280, HAR_CURRATIO_281, ",
            "HAR_CURRATIO_282, HAR_CURRATIO_283, HAR_CURRATIO_284, HAR_CURRATIO_285, HAR_CURRATIO_286, ",
            "HAR_CURRATIO_287, HAR_CURRATIO_288",
            "from c_mhai_curratio_c",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="HAR_CURRATIO_1", property="harCurratio1", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_2", property="harCurratio2", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_3", property="harCurratio3", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_4", property="harCurratio4", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_5", property="harCurratio5", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_6", property="harCurratio6", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_7", property="harCurratio7", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_8", property="harCurratio8", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_9", property="harCurratio9", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_10", property="harCurratio10", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_11", property="harCurratio11", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_12", property="harCurratio12", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_13", property="harCurratio13", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_14", property="harCurratio14", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_15", property="harCurratio15", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_16", property="harCurratio16", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_17", property="harCurratio17", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_18", property="harCurratio18", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_19", property="harCurratio19", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_20", property="harCurratio20", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_21", property="harCurratio21", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_22", property="harCurratio22", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_23", property="harCurratio23", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_24", property="harCurratio24", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_25", property="harCurratio25", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_26", property="harCurratio26", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_27", property="harCurratio27", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_28", property="harCurratio28", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_29", property="harCurratio29", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_30", property="harCurratio30", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_31", property="harCurratio31", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_32", property="harCurratio32", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_33", property="harCurratio33", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_34", property="harCurratio34", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_35", property="harCurratio35", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_36", property="harCurratio36", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_37", property="harCurratio37", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_38", property="harCurratio38", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_39", property="harCurratio39", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_40", property="harCurratio40", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_41", property="harCurratio41", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_42", property="harCurratio42", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_43", property="harCurratio43", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_44", property="harCurratio44", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_45", property="harCurratio45", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_46", property="harCurratio46", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_47", property="harCurratio47", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_48", property="harCurratio48", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_49", property="harCurratio49", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_50", property="harCurratio50", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_51", property="harCurratio51", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_52", property="harCurratio52", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_53", property="harCurratio53", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_54", property="harCurratio54", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_55", property="harCurratio55", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_56", property="harCurratio56", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_57", property="harCurratio57", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_58", property="harCurratio58", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_59", property="harCurratio59", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_60", property="harCurratio60", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_61", property="harCurratio61", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_62", property="harCurratio62", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_63", property="harCurratio63", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_64", property="harCurratio64", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_65", property="harCurratio65", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_66", property="harCurratio66", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_67", property="harCurratio67", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_68", property="harCurratio68", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_69", property="harCurratio69", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_70", property="harCurratio70", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_71", property="harCurratio71", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_72", property="harCurratio72", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_73", property="harCurratio73", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_74", property="harCurratio74", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_75", property="harCurratio75", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_76", property="harCurratio76", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_77", property="harCurratio77", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_78", property="harCurratio78", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_79", property="harCurratio79", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_80", property="harCurratio80", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_81", property="harCurratio81", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_82", property="harCurratio82", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_83", property="harCurratio83", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_84", property="harCurratio84", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_85", property="harCurratio85", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_86", property="harCurratio86", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_87", property="harCurratio87", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_88", property="harCurratio88", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_89", property="harCurratio89", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_90", property="harCurratio90", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_91", property="harCurratio91", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_92", property="harCurratio92", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_93", property="harCurratio93", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_94", property="harCurratio94", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_95", property="harCurratio95", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_96", property="harCurratio96", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_97", property="harCurratio97", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_98", property="harCurratio98", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_99", property="harCurratio99", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_100", property="harCurratio100", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_101", property="harCurratio101", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_102", property="harCurratio102", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_103", property="harCurratio103", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_104", property="harCurratio104", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_105", property="harCurratio105", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_106", property="harCurratio106", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_107", property="harCurratio107", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_108", property="harCurratio108", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_109", property="harCurratio109", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_110", property="harCurratio110", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_111", property="harCurratio111", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_112", property="harCurratio112", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_113", property="harCurratio113", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_114", property="harCurratio114", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_115", property="harCurratio115", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_116", property="harCurratio116", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_117", property="harCurratio117", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_118", property="harCurratio118", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_119", property="harCurratio119", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_120", property="harCurratio120", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_121", property="harCurratio121", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_122", property="harCurratio122", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_123", property="harCurratio123", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_124", property="harCurratio124", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_125", property="harCurratio125", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_126", property="harCurratio126", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_127", property="harCurratio127", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_128", property="harCurratio128", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_129", property="harCurratio129", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_130", property="harCurratio130", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_131", property="harCurratio131", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_132", property="harCurratio132", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_133", property="harCurratio133", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_134", property="harCurratio134", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_135", property="harCurratio135", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_136", property="harCurratio136", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_137", property="harCurratio137", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_138", property="harCurratio138", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_139", property="harCurratio139", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_140", property="harCurratio140", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_141", property="harCurratio141", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_142", property="harCurratio142", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_143", property="harCurratio143", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_144", property="harCurratio144", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_145", property="harCurratio145", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_146", property="harCurratio146", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_147", property="harCurratio147", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_148", property="harCurratio148", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_149", property="harCurratio149", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_150", property="harCurratio150", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_151", property="harCurratio151", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_152", property="harCurratio152", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_153", property="harCurratio153", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_154", property="harCurratio154", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_155", property="harCurratio155", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_156", property="harCurratio156", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_157", property="harCurratio157", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_158", property="harCurratio158", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_159", property="harCurratio159", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_160", property="harCurratio160", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_161", property="harCurratio161", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_162", property="harCurratio162", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_163", property="harCurratio163", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_164", property="harCurratio164", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_165", property="harCurratio165", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_166", property="harCurratio166", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_167", property="harCurratio167", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_168", property="harCurratio168", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_169", property="harCurratio169", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_170", property="harCurratio170", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_171", property="harCurratio171", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_172", property="harCurratio172", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_173", property="harCurratio173", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_174", property="harCurratio174", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_175", property="harCurratio175", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_176", property="harCurratio176", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_177", property="harCurratio177", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_178", property="harCurratio178", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_179", property="harCurratio179", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_180", property="harCurratio180", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_181", property="harCurratio181", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_182", property="harCurratio182", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_183", property="harCurratio183", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_184", property="harCurratio184", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_185", property="harCurratio185", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_186", property="harCurratio186", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_187", property="harCurratio187", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_188", property="harCurratio188", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_189", property="harCurratio189", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_190", property="harCurratio190", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_191", property="harCurratio191", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_192", property="harCurratio192", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_193", property="harCurratio193", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_194", property="harCurratio194", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_195", property="harCurratio195", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_196", property="harCurratio196", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_197", property="harCurratio197", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_198", property="harCurratio198", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_199", property="harCurratio199", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_200", property="harCurratio200", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_201", property="harCurratio201", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_202", property="harCurratio202", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_203", property="harCurratio203", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_204", property="harCurratio204", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_205", property="harCurratio205", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_206", property="harCurratio206", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_207", property="harCurratio207", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_208", property="harCurratio208", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_209", property="harCurratio209", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_210", property="harCurratio210", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_211", property="harCurratio211", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_212", property="harCurratio212", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_213", property="harCurratio213", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_214", property="harCurratio214", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_215", property="harCurratio215", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_216", property="harCurratio216", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_217", property="harCurratio217", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_218", property="harCurratio218", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_219", property="harCurratio219", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_220", property="harCurratio220", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_221", property="harCurratio221", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_222", property="harCurratio222", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_223", property="harCurratio223", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_224", property="harCurratio224", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_225", property="harCurratio225", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_226", property="harCurratio226", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_227", property="harCurratio227", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_228", property="harCurratio228", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_229", property="harCurratio229", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_230", property="harCurratio230", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_231", property="harCurratio231", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_232", property="harCurratio232", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_233", property="harCurratio233", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_234", property="harCurratio234", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_235", property="harCurratio235", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_236", property="harCurratio236", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_237", property="harCurratio237", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_238", property="harCurratio238", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_239", property="harCurratio239", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_240", property="harCurratio240", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_241", property="harCurratio241", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_242", property="harCurratio242", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_243", property="harCurratio243", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_244", property="harCurratio244", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_245", property="harCurratio245", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_246", property="harCurratio246", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_247", property="harCurratio247", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_248", property="harCurratio248", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_249", property="harCurratio249", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_250", property="harCurratio250", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_251", property="harCurratio251", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_252", property="harCurratio252", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_253", property="harCurratio253", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_254", property="harCurratio254", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_255", property="harCurratio255", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_256", property="harCurratio256", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_257", property="harCurratio257", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_258", property="harCurratio258", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_259", property="harCurratio259", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_260", property="harCurratio260", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_261", property="harCurratio261", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_262", property="harCurratio262", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_263", property="harCurratio263", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_264", property="harCurratio264", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_265", property="harCurratio265", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_266", property="harCurratio266", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_267", property="harCurratio267", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_268", property="harCurratio268", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_269", property="harCurratio269", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_270", property="harCurratio270", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_271", property="harCurratio271", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_272", property="harCurratio272", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_273", property="harCurratio273", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_274", property="harCurratio274", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_275", property="harCurratio275", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_276", property="harCurratio276", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_277", property="harCurratio277", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_278", property="harCurratio278", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_279", property="harCurratio279", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_280", property="harCurratio280", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_281", property="harCurratio281", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_282", property="harCurratio282", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_283", property="harCurratio283", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_284", property="harCurratio284", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_285", property="harCurratio285", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_286", property="harCurratio286", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_287", property="harCurratio287", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURRATIO_288", property="harCurratio288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_curRatioCurvePo> selectCurRationBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

}