package com.dao.mapper;

import com.dao.bean.D_curCurvePo;
import com.dao.bean.D_curCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_curCurvePoMapper {


    @Select({
        "select",
        "DSM_SYS_ID SYS_ID, DSM_LD_ID LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, CUR_1, CUR_2, ",
        "CUR_3, CUR_4, CUR_5, CUR_6, CUR_7, CUR_8, CUR_9, CUR_10, CUR_11, CUR_12, CUR_13, ",
        "CUR_14, CUR_15, CUR_16, CUR_17, CUR_18, CUR_19, CUR_20, CUR_21, CUR_22, CUR_23, ",
        "CUR_24, CUR_25, CUR_26, CUR_27, CUR_28, CUR_29, CUR_30, CUR_31, CUR_32, CUR_33, ",
        "CUR_34, CUR_35, CUR_36, CUR_37, CUR_38, CUR_39, CUR_40, CUR_41, CUR_42, CUR_43, ",
        "CUR_44, CUR_45, CUR_46, CUR_47, CUR_48, CUR_49, CUR_50, CUR_51, CUR_52, CUR_53, ",
        "CUR_54, CUR_55, CUR_56, CUR_57, CUR_58, CUR_59, CUR_60, CUR_61, CUR_62, CUR_63, ",
        "CUR_64, CUR_65, CUR_66, CUR_67, CUR_68, CUR_69, CUR_70, CUR_71, CUR_72, CUR_73, ",
        "CUR_74, CUR_75, CUR_76, CUR_77, CUR_78, CUR_79, CUR_80, CUR_81, CUR_82, CUR_83, ",
        "CUR_84, CUR_85, CUR_86, CUR_87, CUR_88, CUR_89, CUR_90, CUR_91, CUR_92, CUR_93, ",
        "CUR_94, CUR_95, CUR_96, CUR_97, CUR_98, CUR_99, CUR_100, CUR_101, CUR_102, CUR_103, ",
        "CUR_104, CUR_105, CUR_106, CUR_107, CUR_108, CUR_109, CUR_110, CUR_111, CUR_112, ",
        "CUR_113, CUR_114, CUR_115, CUR_116, CUR_117, CUR_118, CUR_119, CUR_120, CUR_121, ",
        "CUR_122, CUR_123, CUR_124, CUR_125, CUR_126, CUR_127, CUR_128, CUR_129, CUR_130, ",
        "CUR_131, CUR_132, CUR_133, CUR_134, CUR_135, CUR_136, CUR_137, CUR_138, CUR_139, ",
        "CUR_140, CUR_141, CUR_142, CUR_143, CUR_144, CUR_145, CUR_146, CUR_147, CUR_148, ",
        "CUR_149, CUR_150, CUR_151, CUR_152, CUR_153, CUR_154, CUR_155, CUR_156, CUR_157, ",
        "CUR_158, CUR_159, CUR_160, CUR_161, CUR_162, CUR_163, CUR_164, CUR_165, CUR_166, ",
        "CUR_167, CUR_168, CUR_169, CUR_170, CUR_171, CUR_172, CUR_173, CUR_174, CUR_175, ",
        "CUR_176, CUR_177, CUR_178, CUR_179, CUR_180, CUR_181, CUR_182, CUR_183, CUR_184, ",
        "CUR_185, CUR_186, CUR_187, CUR_188, CUR_189, CUR_190, CUR_191, CUR_192, CUR_193, ",
        "CUR_194, CUR_195, CUR_196, CUR_197, CUR_198, CUR_199, CUR_200, CUR_201, CUR_202, ",
        "CUR_203, CUR_204, CUR_205, CUR_206, CUR_207, CUR_208, CUR_209, CUR_210, CUR_211, ",
        "CUR_212, CUR_213, CUR_214, CUR_215, CUR_216, CUR_217, CUR_218, CUR_219, CUR_220, ",
        "CUR_221, CUR_222, CUR_223, CUR_224, CUR_225, CUR_226, CUR_227, CUR_228, CUR_229, ",
        "CUR_230, CUR_231, CUR_232, CUR_233, CUR_234, CUR_235, CUR_236, CUR_237, CUR_238, ",
        "CUR_239, CUR_240, CUR_241, CUR_242, CUR_243, CUR_244, CUR_245, CUR_246, CUR_247, ",
        "CUR_248, CUR_249, CUR_250, CUR_251, CUR_252, CUR_253, CUR_254, CUR_255, CUR_256, ",
        "CUR_257, CUR_258, CUR_259, CUR_260, CUR_261, CUR_262, CUR_263, CUR_264, CUR_265, ",
        "CUR_266, CUR_267, CUR_268, CUR_269, CUR_270, CUR_271, CUR_272, CUR_273, CUR_274, ",
        "CUR_275, CUR_276, CUR_277, CUR_278, CUR_279, CUR_280, CUR_281, CUR_282, CUR_283, ",
        "CUR_284, CUR_285, CUR_286, CUR_287, CUR_288",
        "from dsm_mmxu_cur_c ",
        "where  DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="CUR_1", property="cur1", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_2", property="cur2", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_3", property="cur3", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_4", property="cur4", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_5", property="cur5", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_6", property="cur6", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_7", property="cur7", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_8", property="cur8", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_9", property="cur9", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_10", property="cur10", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_11", property="cur11", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_12", property="cur12", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_13", property="cur13", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_14", property="cur14", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_15", property="cur15", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_16", property="cur16", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_17", property="cur17", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_18", property="cur18", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_19", property="cur19", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_20", property="cur20", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_21", property="cur21", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_22", property="cur22", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_23", property="cur23", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_24", property="cur24", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_25", property="cur25", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_26", property="cur26", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_27", property="cur27", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_28", property="cur28", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_29", property="cur29", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_30", property="cur30", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_31", property="cur31", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_32", property="cur32", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_33", property="cur33", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_34", property="cur34", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_35", property="cur35", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_36", property="cur36", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_37", property="cur37", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_38", property="cur38", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_39", property="cur39", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_40", property="cur40", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_41", property="cur41", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_42", property="cur42", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_43", property="cur43", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_44", property="cur44", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_45", property="cur45", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_46", property="cur46", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_47", property="cur47", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_48", property="cur48", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_49", property="cur49", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_50", property="cur50", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_51", property="cur51", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_52", property="cur52", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_53", property="cur53", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_54", property="cur54", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_55", property="cur55", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_56", property="cur56", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_57", property="cur57", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_58", property="cur58", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_59", property="cur59", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_60", property="cur60", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_61", property="cur61", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_62", property="cur62", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_63", property="cur63", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_64", property="cur64", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_65", property="cur65", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_66", property="cur66", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_67", property="cur67", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_68", property="cur68", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_69", property="cur69", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_70", property="cur70", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_71", property="cur71", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_72", property="cur72", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_73", property="cur73", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_74", property="cur74", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_75", property="cur75", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_76", property="cur76", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_77", property="cur77", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_78", property="cur78", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_79", property="cur79", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_80", property="cur80", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_81", property="cur81", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_82", property="cur82", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_83", property="cur83", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_84", property="cur84", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_85", property="cur85", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_86", property="cur86", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_87", property="cur87", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_88", property="cur88", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_89", property="cur89", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_90", property="cur90", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_91", property="cur91", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_92", property="cur92", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_93", property="cur93", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_94", property="cur94", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_95", property="cur95", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_96", property="cur96", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_97", property="cur97", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_98", property="cur98", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_99", property="cur99", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_100", property="cur100", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_101", property="cur101", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_102", property="cur102", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_103", property="cur103", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_104", property="cur104", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_105", property="cur105", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_106", property="cur106", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_107", property="cur107", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_108", property="cur108", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_109", property="cur109", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_110", property="cur110", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_111", property="cur111", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_112", property="cur112", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_113", property="cur113", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_114", property="cur114", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_115", property="cur115", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_116", property="cur116", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_117", property="cur117", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_118", property="cur118", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_119", property="cur119", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_120", property="cur120", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_121", property="cur121", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_122", property="cur122", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_123", property="cur123", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_124", property="cur124", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_125", property="cur125", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_126", property="cur126", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_127", property="cur127", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_128", property="cur128", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_129", property="cur129", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_130", property="cur130", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_131", property="cur131", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_132", property="cur132", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_133", property="cur133", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_134", property="cur134", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_135", property="cur135", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_136", property="cur136", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_137", property="cur137", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_138", property="cur138", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_139", property="cur139", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_140", property="cur140", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_141", property="cur141", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_142", property="cur142", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_143", property="cur143", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_144", property="cur144", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_145", property="cur145", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_146", property="cur146", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_147", property="cur147", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_148", property="cur148", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_149", property="cur149", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_150", property="cur150", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_151", property="cur151", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_152", property="cur152", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_153", property="cur153", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_154", property="cur154", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_155", property="cur155", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_156", property="cur156", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_157", property="cur157", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_158", property="cur158", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_159", property="cur159", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_160", property="cur160", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_161", property="cur161", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_162", property="cur162", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_163", property="cur163", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_164", property="cur164", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_165", property="cur165", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_166", property="cur166", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_167", property="cur167", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_168", property="cur168", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_169", property="cur169", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_170", property="cur170", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_171", property="cur171", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_172", property="cur172", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_173", property="cur173", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_174", property="cur174", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_175", property="cur175", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_176", property="cur176", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_177", property="cur177", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_178", property="cur178", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_179", property="cur179", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_180", property="cur180", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_181", property="cur181", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_182", property="cur182", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_183", property="cur183", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_184", property="cur184", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_185", property="cur185", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_186", property="cur186", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_187", property="cur187", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_188", property="cur188", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_189", property="cur189", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_190", property="cur190", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_191", property="cur191", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_192", property="cur192", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_193", property="cur193", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_194", property="cur194", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_195", property="cur195", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_196", property="cur196", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_197", property="cur197", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_198", property="cur198", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_199", property="cur199", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_200", property="cur200", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_201", property="cur201", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_202", property="cur202", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_203", property="cur203", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_204", property="cur204", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_205", property="cur205", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_206", property="cur206", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_207", property="cur207", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_208", property="cur208", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_209", property="cur209", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_210", property="cur210", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_211", property="cur211", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_212", property="cur212", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_213", property="cur213", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_214", property="cur214", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_215", property="cur215", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_216", property="cur216", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_217", property="cur217", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_218", property="cur218", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_219", property="cur219", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_220", property="cur220", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_221", property="cur221", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_222", property="cur222", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_223", property="cur223", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_224", property="cur224", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_225", property="cur225", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_226", property="cur226", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_227", property="cur227", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_228", property="cur228", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_229", property="cur229", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_230", property="cur230", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_231", property="cur231", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_232", property="cur232", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_233", property="cur233", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_234", property="cur234", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_235", property="cur235", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_236", property="cur236", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_237", property="cur237", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_238", property="cur238", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_239", property="cur239", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_240", property="cur240", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_241", property="cur241", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_242", property="cur242", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_243", property="cur243", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_244", property="cur244", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_245", property="cur245", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_246", property="cur246", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_247", property="cur247", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_248", property="cur248", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_249", property="cur249", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_250", property="cur250", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_251", property="cur251", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_252", property="cur252", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_253", property="cur253", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_254", property="cur254", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_255", property="cur255", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_256", property="cur256", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_257", property="cur257", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_258", property="cur258", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_259", property="cur259", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_260", property="cur260", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_261", property="cur261", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_262", property="cur262", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_263", property="cur263", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_264", property="cur264", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_265", property="cur265", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_266", property="cur266", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_267", property="cur267", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_268", property="cur268", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_269", property="cur269", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_270", property="cur270", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_271", property="cur271", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_272", property="cur272", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_273", property="cur273", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_274", property="cur274", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_275", property="cur275", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_276", property="cur276", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_277", property="cur277", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_278", property="cur278", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_279", property="cur279", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_280", property="cur280", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_281", property="cur281", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_282", property="cur282", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_283", property="cur283", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_284", property="cur284", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_285", property="cur285", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_286", property="cur286", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_287", property="cur287", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUR_288", property="cur288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_curCurvePo> selectCurByDate(String data_date);

    @Select({
            "select",
            "DSM_SYS_ID SYS_ID, DSM_LD_ID LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, CUR_1, CUR_2, ",
            "CUR_3, CUR_4, CUR_5, CUR_6, CUR_7, CUR_8, CUR_9, CUR_10, CUR_11, CUR_12, CUR_13, ",
            "CUR_14, CUR_15, CUR_16, CUR_17, CUR_18, CUR_19, CUR_20, CUR_21, CUR_22, CUR_23, ",
            "CUR_24, CUR_25, CUR_26, CUR_27, CUR_28, CUR_29, CUR_30, CUR_31, CUR_32, CUR_33, ",
            "CUR_34, CUR_35, CUR_36, CUR_37, CUR_38, CUR_39, CUR_40, CUR_41, CUR_42, CUR_43, ",
            "CUR_44, CUR_45, CUR_46, CUR_47, CUR_48, CUR_49, CUR_50, CUR_51, CUR_52, CUR_53, ",
            "CUR_54, CUR_55, CUR_56, CUR_57, CUR_58, CUR_59, CUR_60, CUR_61, CUR_62, CUR_63, ",
            "CUR_64, CUR_65, CUR_66, CUR_67, CUR_68, CUR_69, CUR_70, CUR_71, CUR_72, CUR_73, ",
            "CUR_74, CUR_75, CUR_76, CUR_77, CUR_78, CUR_79, CUR_80, CUR_81, CUR_82, CUR_83, ",
            "CUR_84, CUR_85, CUR_86, CUR_87, CUR_88, CUR_89, CUR_90, CUR_91, CUR_92, CUR_93, ",
            "CUR_94, CUR_95, CUR_96, CUR_97, CUR_98, CUR_99, CUR_100, CUR_101, CUR_102, CUR_103, ",
            "CUR_104, CUR_105, CUR_106, CUR_107, CUR_108, CUR_109, CUR_110, CUR_111, CUR_112, ",
            "CUR_113, CUR_114, CUR_115, CUR_116, CUR_117, CUR_118, CUR_119, CUR_120, CUR_121, ",
            "CUR_122, CUR_123, CUR_124, CUR_125, CUR_126, CUR_127, CUR_128, CUR_129, CUR_130, ",
            "CUR_131, CUR_132, CUR_133, CUR_134, CUR_135, CUR_136, CUR_137, CUR_138, CUR_139, ",
            "CUR_140, CUR_141, CUR_142, CUR_143, CUR_144, CUR_145, CUR_146, CUR_147, CUR_148, ",
            "CUR_149, CUR_150, CUR_151, CUR_152, CUR_153, CUR_154, CUR_155, CUR_156, CUR_157, ",
            "CUR_158, CUR_159, CUR_160, CUR_161, CUR_162, CUR_163, CUR_164, CUR_165, CUR_166, ",
            "CUR_167, CUR_168, CUR_169, CUR_170, CUR_171, CUR_172, CUR_173, CUR_174, CUR_175, ",
            "CUR_176, CUR_177, CUR_178, CUR_179, CUR_180, CUR_181, CUR_182, CUR_183, CUR_184, ",
            "CUR_185, CUR_186, CUR_187, CUR_188, CUR_189, CUR_190, CUR_191, CUR_192, CUR_193, ",
            "CUR_194, CUR_195, CUR_196, CUR_197, CUR_198, CUR_199, CUR_200, CUR_201, CUR_202, ",
            "CUR_203, CUR_204, CUR_205, CUR_206, CUR_207, CUR_208, CUR_209, CUR_210, CUR_211, ",
            "CUR_212, CUR_213, CUR_214, CUR_215, CUR_216, CUR_217, CUR_218, CUR_219, CUR_220, ",
            "CUR_221, CUR_222, CUR_223, CUR_224, CUR_225, CUR_226, CUR_227, CUR_228, CUR_229, ",
            "CUR_230, CUR_231, CUR_232, CUR_233, CUR_234, CUR_235, CUR_236, CUR_237, CUR_238, ",
            "CUR_239, CUR_240, CUR_241, CUR_242, CUR_243, CUR_244, CUR_245, CUR_246, CUR_247, ",
            "CUR_248, CUR_249, CUR_250, CUR_251, CUR_252, CUR_253, CUR_254, CUR_255, CUR_256, ",
            "CUR_257, CUR_258, CUR_259, CUR_260, CUR_261, CUR_262, CUR_263, CUR_264, CUR_265, ",
            "CUR_266, CUR_267, CUR_268, CUR_269, CUR_270, CUR_271, CUR_272, CUR_273, CUR_274, ",
            "CUR_275, CUR_276, CUR_277, CUR_278, CUR_279, CUR_280, CUR_281, CUR_282, CUR_283, ",
            "CUR_284, CUR_285, CUR_286, CUR_287, CUR_288",
            "from dsm_mmxu_cur_c ",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="CUR_1", property="cur1", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_2", property="cur2", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_3", property="cur3", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_4", property="cur4", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_5", property="cur5", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_6", property="cur6", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_7", property="cur7", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_8", property="cur8", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_9", property="cur9", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_10", property="cur10", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_11", property="cur11", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_12", property="cur12", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_13", property="cur13", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_14", property="cur14", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_15", property="cur15", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_16", property="cur16", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_17", property="cur17", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_18", property="cur18", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_19", property="cur19", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_20", property="cur20", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_21", property="cur21", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_22", property="cur22", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_23", property="cur23", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_24", property="cur24", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_25", property="cur25", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_26", property="cur26", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_27", property="cur27", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_28", property="cur28", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_29", property="cur29", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_30", property="cur30", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_31", property="cur31", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_32", property="cur32", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_33", property="cur33", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_34", property="cur34", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_35", property="cur35", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_36", property="cur36", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_37", property="cur37", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_38", property="cur38", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_39", property="cur39", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_40", property="cur40", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_41", property="cur41", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_42", property="cur42", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_43", property="cur43", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_44", property="cur44", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_45", property="cur45", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_46", property="cur46", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_47", property="cur47", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_48", property="cur48", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_49", property="cur49", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_50", property="cur50", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_51", property="cur51", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_52", property="cur52", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_53", property="cur53", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_54", property="cur54", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_55", property="cur55", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_56", property="cur56", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_57", property="cur57", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_58", property="cur58", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_59", property="cur59", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_60", property="cur60", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_61", property="cur61", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_62", property="cur62", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_63", property="cur63", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_64", property="cur64", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_65", property="cur65", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_66", property="cur66", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_67", property="cur67", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_68", property="cur68", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_69", property="cur69", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_70", property="cur70", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_71", property="cur71", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_72", property="cur72", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_73", property="cur73", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_74", property="cur74", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_75", property="cur75", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_76", property="cur76", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_77", property="cur77", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_78", property="cur78", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_79", property="cur79", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_80", property="cur80", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_81", property="cur81", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_82", property="cur82", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_83", property="cur83", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_84", property="cur84", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_85", property="cur85", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_86", property="cur86", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_87", property="cur87", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_88", property="cur88", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_89", property="cur89", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_90", property="cur90", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_91", property="cur91", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_92", property="cur92", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_93", property="cur93", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_94", property="cur94", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_95", property="cur95", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_96", property="cur96", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_97", property="cur97", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_98", property="cur98", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_99", property="cur99", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_100", property="cur100", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_101", property="cur101", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_102", property="cur102", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_103", property="cur103", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_104", property="cur104", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_105", property="cur105", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_106", property="cur106", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_107", property="cur107", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_108", property="cur108", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_109", property="cur109", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_110", property="cur110", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_111", property="cur111", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_112", property="cur112", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_113", property="cur113", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_114", property="cur114", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_115", property="cur115", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_116", property="cur116", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_117", property="cur117", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_118", property="cur118", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_119", property="cur119", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_120", property="cur120", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_121", property="cur121", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_122", property="cur122", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_123", property="cur123", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_124", property="cur124", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_125", property="cur125", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_126", property="cur126", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_127", property="cur127", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_128", property="cur128", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_129", property="cur129", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_130", property="cur130", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_131", property="cur131", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_132", property="cur132", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_133", property="cur133", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_134", property="cur134", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_135", property="cur135", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_136", property="cur136", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_137", property="cur137", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_138", property="cur138", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_139", property="cur139", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_140", property="cur140", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_141", property="cur141", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_142", property="cur142", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_143", property="cur143", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_144", property="cur144", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_145", property="cur145", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_146", property="cur146", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_147", property="cur147", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_148", property="cur148", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_149", property="cur149", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_150", property="cur150", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_151", property="cur151", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_152", property="cur152", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_153", property="cur153", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_154", property="cur154", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_155", property="cur155", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_156", property="cur156", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_157", property="cur157", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_158", property="cur158", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_159", property="cur159", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_160", property="cur160", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_161", property="cur161", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_162", property="cur162", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_163", property="cur163", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_164", property="cur164", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_165", property="cur165", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_166", property="cur166", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_167", property="cur167", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_168", property="cur168", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_169", property="cur169", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_170", property="cur170", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_171", property="cur171", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_172", property="cur172", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_173", property="cur173", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_174", property="cur174", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_175", property="cur175", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_176", property="cur176", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_177", property="cur177", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_178", property="cur178", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_179", property="cur179", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_180", property="cur180", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_181", property="cur181", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_182", property="cur182", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_183", property="cur183", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_184", property="cur184", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_185", property="cur185", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_186", property="cur186", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_187", property="cur187", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_188", property="cur188", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_189", property="cur189", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_190", property="cur190", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_191", property="cur191", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_192", property="cur192", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_193", property="cur193", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_194", property="cur194", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_195", property="cur195", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_196", property="cur196", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_197", property="cur197", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_198", property="cur198", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_199", property="cur199", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_200", property="cur200", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_201", property="cur201", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_202", property="cur202", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_203", property="cur203", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_204", property="cur204", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_205", property="cur205", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_206", property="cur206", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_207", property="cur207", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_208", property="cur208", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_209", property="cur209", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_210", property="cur210", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_211", property="cur211", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_212", property="cur212", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_213", property="cur213", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_214", property="cur214", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_215", property="cur215", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_216", property="cur216", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_217", property="cur217", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_218", property="cur218", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_219", property="cur219", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_220", property="cur220", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_221", property="cur221", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_222", property="cur222", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_223", property="cur223", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_224", property="cur224", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_225", property="cur225", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_226", property="cur226", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_227", property="cur227", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_228", property="cur228", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_229", property="cur229", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_230", property="cur230", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_231", property="cur231", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_232", property="cur232", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_233", property="cur233", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_234", property="cur234", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_235", property="cur235", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_236", property="cur236", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_237", property="cur237", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_238", property="cur238", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_239", property="cur239", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_240", property="cur240", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_241", property="cur241", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_242", property="cur242", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_243", property="cur243", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_244", property="cur244", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_245", property="cur245", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_246", property="cur246", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_247", property="cur247", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_248", property="cur248", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_249", property="cur249", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_250", property="cur250", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_251", property="cur251", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_252", property="cur252", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_253", property="cur253", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_254", property="cur254", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_255", property="cur255", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_256", property="cur256", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_257", property="cur257", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_258", property="cur258", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_259", property="cur259", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_260", property="cur260", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_261", property="cur261", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_262", property="cur262", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_263", property="cur263", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_264", property="cur264", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_265", property="cur265", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_266", property="cur266", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_267", property="cur267", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_268", property="cur268", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_269", property="cur269", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_270", property="cur270", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_271", property="cur271", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_272", property="cur272", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_273", property="cur273", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_274", property="cur274", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_275", property="cur275", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_276", property="cur276", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_277", property="cur277", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_278", property="cur278", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_279", property="cur279", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_280", property="cur280", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_281", property="cur281", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_282", property="cur282", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_283", property="cur283", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_284", property="cur284", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_285", property="cur285", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_286", property="cur286", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_287", property="cur287", jdbcType=JdbcType.DECIMAL),
            @Result(column="CUR_288", property="cur288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_curCurvePo> selectCurBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

}