package com.dao.mapper;

import com.dao.bean.D_energyCurvePo;
import com.dao.bean.D_energyCurvePoKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_energyCurvePoMapper {

    @Select({
        "select",
        "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_POINT, DATA_INTERVAL, ENERGY_1, ENERGY_2, ",
        "ENERGY_3, ENERGY_4, ENERGY_5, ENERGY_6, ENERGY_7, ENERGY_8, ENERGY_9, ENERGY_10, ",
        "ENERGY_11, ENERGY_12, ENERGY_13, ENERGY_14, ENERGY_15, ENERGY_16, ENERGY_17, ",
        "ENERGY_18, ENERGY_19, ENERGY_20, ENERGY_21, ENERGY_22, ENERGY_23, ENERGY_24, ",
        "ENERGY_25, ENERGY_26, ENERGY_27, ENERGY_28, ENERGY_29, ENERGY_30, ENERGY_31, ",
        "ENERGY_32, ENERGY_33, ENERGY_34, ENERGY_35, ENERGY_36, ENERGY_37, ENERGY_38, ",
        "ENERGY_39, ENERGY_40, ENERGY_41, ENERGY_42, ENERGY_43, ENERGY_44, ENERGY_45, ",
        "ENERGY_46, ENERGY_47, ENERGY_48, ENERGY_49, ENERGY_50, ENERGY_51, ENERGY_52, ",
        "ENERGY_53, ENERGY_54, ENERGY_55, ENERGY_56, ENERGY_57, ENERGY_58, ENERGY_59, ",
        "ENERGY_60, ENERGY_61, ENERGY_62, ENERGY_63, ENERGY_64, ENERGY_65, ENERGY_66, ",
        "ENERGY_67, ENERGY_68, ENERGY_69, ENERGY_70, ENERGY_71, ENERGY_72, ENERGY_73, ",
        "ENERGY_74, ENERGY_75, ENERGY_76, ENERGY_77, ENERGY_78, ENERGY_79, ENERGY_80, ",
        "ENERGY_81, ENERGY_82, ENERGY_83, ENERGY_84, ENERGY_85, ENERGY_86, ENERGY_87, ",
        "ENERGY_88, ENERGY_89, ENERGY_90, ENERGY_91, ENERGY_92, ENERGY_93, ENERGY_94, ",
        "ENERGY_95, ENERGY_96, ENERGY_97, ENERGY_98, ENERGY_99, ENERGY_100, ENERGY_101, ",
        "ENERGY_102, ENERGY_103, ENERGY_104, ENERGY_105, ENERGY_106, ENERGY_107, ENERGY_108, ",
        "ENERGY_109, ENERGY_110, ENERGY_111, ENERGY_112, ENERGY_113, ENERGY_114, ENERGY_115, ",
        "ENERGY_116, ENERGY_117, ENERGY_118, ENERGY_119, ENERGY_120, ENERGY_121, ENERGY_122, ",
        "ENERGY_123, ENERGY_124, ENERGY_125, ENERGY_126, ENERGY_127, ENERGY_128, ENERGY_129, ",
        "ENERGY_130, ENERGY_131, ENERGY_132, ENERGY_133, ENERGY_134, ENERGY_135, ENERGY_136, ",
        "ENERGY_137, ENERGY_138, ENERGY_139, ENERGY_140, ENERGY_141, ENERGY_142, ENERGY_143, ",
        "ENERGY_144, ENERGY_145, ENERGY_146, ENERGY_147, ENERGY_148, ENERGY_149, ENERGY_150, ",
        "ENERGY_151, ENERGY_152, ENERGY_153, ENERGY_154, ENERGY_155, ENERGY_156, ENERGY_157, ",
        "ENERGY_158, ENERGY_159, ENERGY_160, ENERGY_161, ENERGY_162, ENERGY_163, ENERGY_164, ",
        "ENERGY_165, ENERGY_166, ENERGY_167, ENERGY_168, ENERGY_169, ENERGY_170, ENERGY_171, ",
        "ENERGY_172, ENERGY_173, ENERGY_174, ENERGY_175, ENERGY_176, ENERGY_177, ENERGY_178, ",
        "ENERGY_179, ENERGY_180, ENERGY_181, ENERGY_182, ENERGY_183, ENERGY_184, ENERGY_185, ",
        "ENERGY_186, ENERGY_187, ENERGY_188, ENERGY_189, ENERGY_190, ENERGY_191, ENERGY_192, ",
        "ENERGY_193, ENERGY_194, ENERGY_195, ENERGY_196, ENERGY_197, ENERGY_198, ENERGY_199, ",
        "ENERGY_200, ENERGY_201, ENERGY_202, ENERGY_203, ENERGY_204, ENERGY_205, ENERGY_206, ",
        "ENERGY_207, ENERGY_208, ENERGY_209, ENERGY_210, ENERGY_211, ENERGY_212, ENERGY_213, ",
        "ENERGY_214, ENERGY_215, ENERGY_216, ENERGY_217, ENERGY_218, ENERGY_219, ENERGY_220, ",
        "ENERGY_221, ENERGY_222, ENERGY_223, ENERGY_224, ENERGY_225, ENERGY_226, ENERGY_227, ",
        "ENERGY_228, ENERGY_229, ENERGY_230, ENERGY_231, ENERGY_232, ENERGY_233, ENERGY_234, ",
        "ENERGY_235, ENERGY_236, ENERGY_237, ENERGY_238, ENERGY_239, ENERGY_240, ENERGY_241, ",
        "ENERGY_242, ENERGY_243, ENERGY_244, ENERGY_245, ENERGY_246, ENERGY_247, ENERGY_248, ",
        "ENERGY_249, ENERGY_250, ENERGY_251, ENERGY_252, ENERGY_253, ENERGY_254, ENERGY_255, ",
        "ENERGY_256, ENERGY_257, ENERGY_258, ENERGY_259, ENERGY_260, ENERGY_261, ENERGY_262, ",
        "ENERGY_263, ENERGY_264, ENERGY_265, ENERGY_266, ENERGY_267, ENERGY_268, ENERGY_269, ",
        "ENERGY_270, ENERGY_271, ENERGY_272, ENERGY_273, ENERGY_274, ENERGY_275, ENERGY_276, ",
        "ENERGY_277, ENERGY_278, ENERGY_279, ENERGY_280, ENERGY_281, ENERGY_282, ENERGY_283, ",
        "ENERGY_284, ENERGY_285, ENERGY_286, ENERGY_287, ENERGY_288",
        "from c_mmtr_energy_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="ENERGY_1", property="energy1", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_2", property="energy2", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_3", property="energy3", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_4", property="energy4", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_5", property="energy5", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_6", property="energy6", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_7", property="energy7", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_8", property="energy8", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_9", property="energy9", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_10", property="energy10", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_11", property="energy11", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_12", property="energy12", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_13", property="energy13", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_14", property="energy14", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_15", property="energy15", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_16", property="energy16", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_17", property="energy17", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_18", property="energy18", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_19", property="energy19", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_20", property="energy20", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_21", property="energy21", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_22", property="energy22", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_23", property="energy23", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_24", property="energy24", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_25", property="energy25", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_26", property="energy26", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_27", property="energy27", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_28", property="energy28", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_29", property="energy29", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_30", property="energy30", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_31", property="energy31", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_32", property="energy32", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_33", property="energy33", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_34", property="energy34", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_35", property="energy35", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_36", property="energy36", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_37", property="energy37", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_38", property="energy38", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_39", property="energy39", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_40", property="energy40", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_41", property="energy41", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_42", property="energy42", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_43", property="energy43", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_44", property="energy44", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_45", property="energy45", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_46", property="energy46", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_47", property="energy47", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_48", property="energy48", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_49", property="energy49", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_50", property="energy50", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_51", property="energy51", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_52", property="energy52", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_53", property="energy53", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_54", property="energy54", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_55", property="energy55", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_56", property="energy56", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_57", property="energy57", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_58", property="energy58", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_59", property="energy59", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_60", property="energy60", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_61", property="energy61", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_62", property="energy62", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_63", property="energy63", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_64", property="energy64", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_65", property="energy65", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_66", property="energy66", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_67", property="energy67", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_68", property="energy68", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_69", property="energy69", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_70", property="energy70", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_71", property="energy71", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_72", property="energy72", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_73", property="energy73", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_74", property="energy74", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_75", property="energy75", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_76", property="energy76", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_77", property="energy77", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_78", property="energy78", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_79", property="energy79", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_80", property="energy80", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_81", property="energy81", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_82", property="energy82", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_83", property="energy83", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_84", property="energy84", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_85", property="energy85", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_86", property="energy86", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_87", property="energy87", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_88", property="energy88", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_89", property="energy89", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_90", property="energy90", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_91", property="energy91", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_92", property="energy92", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_93", property="energy93", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_94", property="energy94", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_95", property="energy95", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_96", property="energy96", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_97", property="energy97", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_98", property="energy98", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_99", property="energy99", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_100", property="energy100", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_101", property="energy101", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_102", property="energy102", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_103", property="energy103", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_104", property="energy104", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_105", property="energy105", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_106", property="energy106", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_107", property="energy107", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_108", property="energy108", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_109", property="energy109", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_110", property="energy110", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_111", property="energy111", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_112", property="energy112", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_113", property="energy113", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_114", property="energy114", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_115", property="energy115", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_116", property="energy116", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_117", property="energy117", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_118", property="energy118", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_119", property="energy119", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_120", property="energy120", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_121", property="energy121", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_122", property="energy122", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_123", property="energy123", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_124", property="energy124", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_125", property="energy125", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_126", property="energy126", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_127", property="energy127", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_128", property="energy128", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_129", property="energy129", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_130", property="energy130", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_131", property="energy131", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_132", property="energy132", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_133", property="energy133", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_134", property="energy134", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_135", property="energy135", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_136", property="energy136", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_137", property="energy137", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_138", property="energy138", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_139", property="energy139", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_140", property="energy140", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_141", property="energy141", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_142", property="energy142", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_143", property="energy143", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_144", property="energy144", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_145", property="energy145", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_146", property="energy146", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_147", property="energy147", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_148", property="energy148", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_149", property="energy149", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_150", property="energy150", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_151", property="energy151", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_152", property="energy152", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_153", property="energy153", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_154", property="energy154", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_155", property="energy155", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_156", property="energy156", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_157", property="energy157", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_158", property="energy158", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_159", property="energy159", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_160", property="energy160", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_161", property="energy161", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_162", property="energy162", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_163", property="energy163", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_164", property="energy164", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_165", property="energy165", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_166", property="energy166", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_167", property="energy167", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_168", property="energy168", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_169", property="energy169", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_170", property="energy170", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_171", property="energy171", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_172", property="energy172", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_173", property="energy173", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_174", property="energy174", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_175", property="energy175", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_176", property="energy176", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_177", property="energy177", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_178", property="energy178", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_179", property="energy179", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_180", property="energy180", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_181", property="energy181", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_182", property="energy182", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_183", property="energy183", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_184", property="energy184", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_185", property="energy185", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_186", property="energy186", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_187", property="energy187", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_188", property="energy188", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_189", property="energy189", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_190", property="energy190", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_191", property="energy191", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_192", property="energy192", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_193", property="energy193", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_194", property="energy194", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_195", property="energy195", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_196", property="energy196", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_197", property="energy197", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_198", property="energy198", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_199", property="energy199", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_200", property="energy200", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_201", property="energy201", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_202", property="energy202", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_203", property="energy203", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_204", property="energy204", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_205", property="energy205", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_206", property="energy206", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_207", property="energy207", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_208", property="energy208", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_209", property="energy209", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_210", property="energy210", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_211", property="energy211", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_212", property="energy212", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_213", property="energy213", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_214", property="energy214", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_215", property="energy215", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_216", property="energy216", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_217", property="energy217", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_218", property="energy218", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_219", property="energy219", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_220", property="energy220", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_221", property="energy221", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_222", property="energy222", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_223", property="energy223", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_224", property="energy224", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_225", property="energy225", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_226", property="energy226", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_227", property="energy227", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_228", property="energy228", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_229", property="energy229", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_230", property="energy230", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_231", property="energy231", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_232", property="energy232", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_233", property="energy233", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_234", property="energy234", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_235", property="energy235", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_236", property="energy236", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_237", property="energy237", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_238", property="energy238", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_239", property="energy239", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_240", property="energy240", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_241", property="energy241", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_242", property="energy242", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_243", property="energy243", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_244", property="energy244", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_245", property="energy245", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_246", property="energy246", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_247", property="energy247", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_248", property="energy248", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_249", property="energy249", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_250", property="energy250", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_251", property="energy251", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_252", property="energy252", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_253", property="energy253", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_254", property="energy254", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_255", property="energy255", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_256", property="energy256", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_257", property="energy257", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_258", property="energy258", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_259", property="energy259", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_260", property="energy260", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_261", property="energy261", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_262", property="energy262", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_263", property="energy263", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_264", property="energy264", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_265", property="energy265", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_266", property="energy266", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_267", property="energy267", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_268", property="energy268", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_269", property="energy269", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_270", property="energy270", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_271", property="energy271", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_272", property="energy272", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_273", property="energy273", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_274", property="energy274", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_275", property="energy275", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_276", property="energy276", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_277", property="energy277", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_278", property="energy278", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_279", property="energy279", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_280", property="energy280", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_281", property="energy281", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_282", property="energy282", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_283", property="energy283", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_284", property="energy284", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_285", property="energy285", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_286", property="energy286", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_287", property="energy287", jdbcType=JdbcType.DECIMAL),
        @Result(column="ENERGY_288", property="energy288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_energyCurvePo> selectEnergyByDate(String data_date);

}