package com.dao.mapper;

import com.dao.bean.D_factorCurvePo;
import com.dao.bean.D_factorCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_factorCurvePoMapper {

    @Select({
        "select",
        "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, PF_1, PF_2, ",
        "PF_3, PF_4, PF_5, PF_6, PF_7, PF_8, PF_9, PF_10, PF_11, PF_12, PF_13, PF_14, ",
        "PF_15, PF_16, PF_17, PF_18, PF_19, PF_20, PF_21, PF_22, PF_23, PF_24, PF_25, ",
        "PF_26, PF_27, PF_28, PF_29, PF_30, PF_31, PF_32, PF_33, PF_34, PF_35, PF_36, ",
        "PF_37, PF_38, PF_39, PF_40, PF_41, PF_42, PF_43, PF_44, PF_45, PF_46, PF_47, ",
        "PF_48, PF_49, PF_50, PF_51, PF_52, PF_53, PF_54, PF_55, PF_56, PF_57, PF_58, ",
        "PF_59, PF_60, PF_61, PF_62, PF_63, PF_64, PF_65, PF_66, PF_67, PF_68, PF_69, ",
        "PF_70, PF_71, PF_72, PF_73, PF_74, PF_75, PF_76, PF_77, PF_78, PF_79, PF_80, ",
        "PF_81, PF_82, PF_83, PF_84, PF_85, PF_86, PF_87, PF_88, PF_89, PF_90, PF_91, ",
        "PF_92, PF_93, PF_94, PF_95, PF_96, PF_97, PF_98, PF_99, PF_100, PF_101, PF_102, ",
        "PF_103, PF_104, PF_105, PF_106, PF_107, PF_108, PF_109, PF_110, PF_111, PF_112, ",
        "PF_113, PF_114, PF_115, PF_116, PF_117, PF_118, PF_119, PF_120, PF_121, PF_122, ",
        "PF_123, PF_124, PF_125, PF_126, PF_127, PF_128, PF_129, PF_130, PF_131, PF_132, ",
        "PF_133, PF_134, PF_135, PF_136, PF_137, PF_138, PF_139, PF_140, PF_141, PF_142, ",
        "PF_143, PF_144, PF_145, PF_146, PF_147, PF_148, PF_149, PF_150, PF_151, PF_152, ",
        "PF_153, PF_154, PF_155, PF_156, PF_157, PF_158, PF_159, PF_160, PF_161, PF_162, ",
        "PF_163, PF_164, PF_165, PF_166, PF_167, PF_168, PF_169, PF_170, PF_171, PF_172, ",
        "PF_173, PF_174, PF_175, PF_176, PF_177, PF_178, PF_179, PF_180, PF_181, PF_182, ",
        "PF_183, PF_184, PF_185, PF_186, PF_187, PF_188, PF_189, PF_190, PF_191, PF_192, ",
        "PF_193, PF_194, PF_195, PF_196, PF_197, PF_198, PF_199, PF_200, PF_201, PF_202, ",
        "PF_203, PF_204, PF_205, PF_206, PF_207, PF_208, PF_209, PF_210, PF_211, PF_212, ",
        "PF_213, PF_214, PF_215, PF_216, PF_217, PF_218, PF_219, PF_220, PF_221, PF_222, ",
        "PF_223, PF_224, PF_225, PF_226, PF_227, PF_228, PF_229, PF_230, PF_231, PF_232, ",
        "PF_233, PF_234, PF_235, PF_236, PF_237, PF_238, PF_239, PF_240, PF_241, PF_242, ",
        "PF_243, PF_244, PF_245, PF_246, PF_247, PF_248, PF_249, PF_250, PF_251, PF_252, ",
        "PF_253, PF_254, PF_255, PF_256, PF_257, PF_258, PF_259, PF_260, PF_261, PF_262, ",
        "PF_263, PF_264, PF_265, PF_266, PF_267, PF_268, PF_269, PF_270, PF_271, PF_272, ",
        "PF_273, PF_274, PF_275, PF_276, PF_277, PF_278, PF_279, PF_280, PF_281, PF_282, ",
        "PF_283, PF_284, PF_285, PF_286, PF_287, PF_288",
        "from c_mmxu_pfactor_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="PF_1", property="pf1", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_2", property="pf2", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_3", property="pf3", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_4", property="pf4", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_5", property="pf5", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_6", property="pf6", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_7", property="pf7", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_8", property="pf8", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_9", property="pf9", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_10", property="pf10", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_11", property="pf11", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_12", property="pf12", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_13", property="pf13", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_14", property="pf14", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_15", property="pf15", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_16", property="pf16", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_17", property="pf17", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_18", property="pf18", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_19", property="pf19", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_20", property="pf20", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_21", property="pf21", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_22", property="pf22", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_23", property="pf23", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_24", property="pf24", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_25", property="pf25", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_26", property="pf26", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_27", property="pf27", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_28", property="pf28", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_29", property="pf29", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_30", property="pf30", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_31", property="pf31", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_32", property="pf32", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_33", property="pf33", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_34", property="pf34", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_35", property="pf35", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_36", property="pf36", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_37", property="pf37", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_38", property="pf38", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_39", property="pf39", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_40", property="pf40", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_41", property="pf41", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_42", property="pf42", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_43", property="pf43", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_44", property="pf44", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_45", property="pf45", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_46", property="pf46", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_47", property="pf47", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_48", property="pf48", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_49", property="pf49", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_50", property="pf50", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_51", property="pf51", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_52", property="pf52", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_53", property="pf53", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_54", property="pf54", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_55", property="pf55", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_56", property="pf56", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_57", property="pf57", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_58", property="pf58", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_59", property="pf59", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_60", property="pf60", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_61", property="pf61", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_62", property="pf62", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_63", property="pf63", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_64", property="pf64", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_65", property="pf65", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_66", property="pf66", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_67", property="pf67", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_68", property="pf68", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_69", property="pf69", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_70", property="pf70", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_71", property="pf71", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_72", property="pf72", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_73", property="pf73", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_74", property="pf74", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_75", property="pf75", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_76", property="pf76", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_77", property="pf77", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_78", property="pf78", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_79", property="pf79", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_80", property="pf80", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_81", property="pf81", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_82", property="pf82", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_83", property="pf83", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_84", property="pf84", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_85", property="pf85", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_86", property="pf86", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_87", property="pf87", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_88", property="pf88", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_89", property="pf89", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_90", property="pf90", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_91", property="pf91", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_92", property="pf92", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_93", property="pf93", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_94", property="pf94", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_95", property="pf95", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_96", property="pf96", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_97", property="pf97", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_98", property="pf98", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_99", property="pf99", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_100", property="pf100", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_101", property="pf101", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_102", property="pf102", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_103", property="pf103", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_104", property="pf104", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_105", property="pf105", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_106", property="pf106", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_107", property="pf107", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_108", property="pf108", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_109", property="pf109", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_110", property="pf110", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_111", property="pf111", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_112", property="pf112", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_113", property="pf113", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_114", property="pf114", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_115", property="pf115", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_116", property="pf116", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_117", property="pf117", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_118", property="pf118", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_119", property="pf119", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_120", property="pf120", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_121", property="pf121", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_122", property="pf122", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_123", property="pf123", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_124", property="pf124", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_125", property="pf125", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_126", property="pf126", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_127", property="pf127", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_128", property="pf128", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_129", property="pf129", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_130", property="pf130", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_131", property="pf131", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_132", property="pf132", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_133", property="pf133", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_134", property="pf134", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_135", property="pf135", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_136", property="pf136", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_137", property="pf137", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_138", property="pf138", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_139", property="pf139", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_140", property="pf140", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_141", property="pf141", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_142", property="pf142", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_143", property="pf143", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_144", property="pf144", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_145", property="pf145", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_146", property="pf146", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_147", property="pf147", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_148", property="pf148", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_149", property="pf149", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_150", property="pf150", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_151", property="pf151", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_152", property="pf152", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_153", property="pf153", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_154", property="pf154", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_155", property="pf155", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_156", property="pf156", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_157", property="pf157", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_158", property="pf158", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_159", property="pf159", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_160", property="pf160", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_161", property="pf161", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_162", property="pf162", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_163", property="pf163", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_164", property="pf164", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_165", property="pf165", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_166", property="pf166", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_167", property="pf167", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_168", property="pf168", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_169", property="pf169", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_170", property="pf170", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_171", property="pf171", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_172", property="pf172", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_173", property="pf173", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_174", property="pf174", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_175", property="pf175", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_176", property="pf176", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_177", property="pf177", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_178", property="pf178", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_179", property="pf179", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_180", property="pf180", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_181", property="pf181", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_182", property="pf182", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_183", property="pf183", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_184", property="pf184", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_185", property="pf185", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_186", property="pf186", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_187", property="pf187", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_188", property="pf188", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_189", property="pf189", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_190", property="pf190", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_191", property="pf191", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_192", property="pf192", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_193", property="pf193", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_194", property="pf194", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_195", property="pf195", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_196", property="pf196", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_197", property="pf197", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_198", property="pf198", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_199", property="pf199", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_200", property="pf200", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_201", property="pf201", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_202", property="pf202", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_203", property="pf203", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_204", property="pf204", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_205", property="pf205", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_206", property="pf206", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_207", property="pf207", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_208", property="pf208", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_209", property="pf209", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_210", property="pf210", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_211", property="pf211", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_212", property="pf212", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_213", property="pf213", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_214", property="pf214", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_215", property="pf215", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_216", property="pf216", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_217", property="pf217", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_218", property="pf218", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_219", property="pf219", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_220", property="pf220", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_221", property="pf221", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_222", property="pf222", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_223", property="pf223", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_224", property="pf224", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_225", property="pf225", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_226", property="pf226", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_227", property="pf227", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_228", property="pf228", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_229", property="pf229", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_230", property="pf230", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_231", property="pf231", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_232", property="pf232", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_233", property="pf233", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_234", property="pf234", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_235", property="pf235", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_236", property="pf236", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_237", property="pf237", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_238", property="pf238", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_239", property="pf239", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_240", property="pf240", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_241", property="pf241", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_242", property="pf242", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_243", property="pf243", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_244", property="pf244", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_245", property="pf245", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_246", property="pf246", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_247", property="pf247", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_248", property="pf248", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_249", property="pf249", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_250", property="pf250", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_251", property="pf251", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_252", property="pf252", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_253", property="pf253", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_254", property="pf254", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_255", property="pf255", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_256", property="pf256", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_257", property="pf257", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_258", property="pf258", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_259", property="pf259", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_260", property="pf260", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_261", property="pf261", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_262", property="pf262", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_263", property="pf263", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_264", property="pf264", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_265", property="pf265", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_266", property="pf266", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_267", property="pf267", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_268", property="pf268", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_269", property="pf269", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_270", property="pf270", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_271", property="pf271", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_272", property="pf272", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_273", property="pf273", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_274", property="pf274", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_275", property="pf275", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_276", property="pf276", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_277", property="pf277", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_278", property="pf278", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_279", property="pf279", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_280", property="pf280", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_281", property="pf281", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_282", property="pf282", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_283", property="pf283", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_284", property="pf284", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_285", property="pf285", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_286", property="pf286", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_287", property="pf287", jdbcType=JdbcType.DECIMAL),
        @Result(column="PF_288", property="pf288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_factorCurvePo> selectFactorCurveByDate(String data_date);


    @Select({
            "select",
            "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, PF_1, PF_2, ",
            "PF_3, PF_4, PF_5, PF_6, PF_7, PF_8, PF_9, PF_10, PF_11, PF_12, PF_13, PF_14, ",
            "PF_15, PF_16, PF_17, PF_18, PF_19, PF_20, PF_21, PF_22, PF_23, PF_24, PF_25, ",
            "PF_26, PF_27, PF_28, PF_29, PF_30, PF_31, PF_32, PF_33, PF_34, PF_35, PF_36, ",
            "PF_37, PF_38, PF_39, PF_40, PF_41, PF_42, PF_43, PF_44, PF_45, PF_46, PF_47, ",
            "PF_48, PF_49, PF_50, PF_51, PF_52, PF_53, PF_54, PF_55, PF_56, PF_57, PF_58, ",
            "PF_59, PF_60, PF_61, PF_62, PF_63, PF_64, PF_65, PF_66, PF_67, PF_68, PF_69, ",
            "PF_70, PF_71, PF_72, PF_73, PF_74, PF_75, PF_76, PF_77, PF_78, PF_79, PF_80, ",
            "PF_81, PF_82, PF_83, PF_84, PF_85, PF_86, PF_87, PF_88, PF_89, PF_90, PF_91, ",
            "PF_92, PF_93, PF_94, PF_95, PF_96, PF_97, PF_98, PF_99, PF_100, PF_101, PF_102, ",
            "PF_103, PF_104, PF_105, PF_106, PF_107, PF_108, PF_109, PF_110, PF_111, PF_112, ",
            "PF_113, PF_114, PF_115, PF_116, PF_117, PF_118, PF_119, PF_120, PF_121, PF_122, ",
            "PF_123, PF_124, PF_125, PF_126, PF_127, PF_128, PF_129, PF_130, PF_131, PF_132, ",
            "PF_133, PF_134, PF_135, PF_136, PF_137, PF_138, PF_139, PF_140, PF_141, PF_142, ",
            "PF_143, PF_144, PF_145, PF_146, PF_147, PF_148, PF_149, PF_150, PF_151, PF_152, ",
            "PF_153, PF_154, PF_155, PF_156, PF_157, PF_158, PF_159, PF_160, PF_161, PF_162, ",
            "PF_163, PF_164, PF_165, PF_166, PF_167, PF_168, PF_169, PF_170, PF_171, PF_172, ",
            "PF_173, PF_174, PF_175, PF_176, PF_177, PF_178, PF_179, PF_180, PF_181, PF_182, ",
            "PF_183, PF_184, PF_185, PF_186, PF_187, PF_188, PF_189, PF_190, PF_191, PF_192, ",
            "PF_193, PF_194, PF_195, PF_196, PF_197, PF_198, PF_199, PF_200, PF_201, PF_202, ",
            "PF_203, PF_204, PF_205, PF_206, PF_207, PF_208, PF_209, PF_210, PF_211, PF_212, ",
            "PF_213, PF_214, PF_215, PF_216, PF_217, PF_218, PF_219, PF_220, PF_221, PF_222, ",
            "PF_223, PF_224, PF_225, PF_226, PF_227, PF_228, PF_229, PF_230, PF_231, PF_232, ",
            "PF_233, PF_234, PF_235, PF_236, PF_237, PF_238, PF_239, PF_240, PF_241, PF_242, ",
            "PF_243, PF_244, PF_245, PF_246, PF_247, PF_248, PF_249, PF_250, PF_251, PF_252, ",
            "PF_253, PF_254, PF_255, PF_256, PF_257, PF_258, PF_259, PF_260, PF_261, PF_262, ",
            "PF_263, PF_264, PF_265, PF_266, PF_267, PF_268, PF_269, PF_270, PF_271, PF_272, ",
            "PF_273, PF_274, PF_275, PF_276, PF_277, PF_278, PF_279, PF_280, PF_281, PF_282, ",
            "PF_283, PF_284, PF_285, PF_286, PF_287, PF_288",
            "from c_mmxu_pfactor_c ",
            "where  DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="PF_1", property="pf1", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_2", property="pf2", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_3", property="pf3", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_4", property="pf4", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_5", property="pf5", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_6", property="pf6", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_7", property="pf7", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_8", property="pf8", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_9", property="pf9", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_10", property="pf10", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_11", property="pf11", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_12", property="pf12", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_13", property="pf13", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_14", property="pf14", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_15", property="pf15", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_16", property="pf16", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_17", property="pf17", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_18", property="pf18", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_19", property="pf19", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_20", property="pf20", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_21", property="pf21", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_22", property="pf22", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_23", property="pf23", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_24", property="pf24", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_25", property="pf25", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_26", property="pf26", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_27", property="pf27", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_28", property="pf28", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_29", property="pf29", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_30", property="pf30", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_31", property="pf31", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_32", property="pf32", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_33", property="pf33", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_34", property="pf34", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_35", property="pf35", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_36", property="pf36", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_37", property="pf37", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_38", property="pf38", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_39", property="pf39", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_40", property="pf40", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_41", property="pf41", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_42", property="pf42", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_43", property="pf43", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_44", property="pf44", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_45", property="pf45", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_46", property="pf46", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_47", property="pf47", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_48", property="pf48", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_49", property="pf49", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_50", property="pf50", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_51", property="pf51", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_52", property="pf52", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_53", property="pf53", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_54", property="pf54", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_55", property="pf55", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_56", property="pf56", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_57", property="pf57", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_58", property="pf58", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_59", property="pf59", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_60", property="pf60", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_61", property="pf61", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_62", property="pf62", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_63", property="pf63", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_64", property="pf64", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_65", property="pf65", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_66", property="pf66", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_67", property="pf67", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_68", property="pf68", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_69", property="pf69", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_70", property="pf70", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_71", property="pf71", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_72", property="pf72", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_73", property="pf73", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_74", property="pf74", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_75", property="pf75", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_76", property="pf76", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_77", property="pf77", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_78", property="pf78", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_79", property="pf79", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_80", property="pf80", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_81", property="pf81", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_82", property="pf82", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_83", property="pf83", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_84", property="pf84", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_85", property="pf85", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_86", property="pf86", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_87", property="pf87", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_88", property="pf88", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_89", property="pf89", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_90", property="pf90", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_91", property="pf91", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_92", property="pf92", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_93", property="pf93", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_94", property="pf94", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_95", property="pf95", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_96", property="pf96", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_97", property="pf97", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_98", property="pf98", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_99", property="pf99", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_100", property="pf100", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_101", property="pf101", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_102", property="pf102", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_103", property="pf103", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_104", property="pf104", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_105", property="pf105", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_106", property="pf106", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_107", property="pf107", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_108", property="pf108", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_109", property="pf109", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_110", property="pf110", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_111", property="pf111", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_112", property="pf112", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_113", property="pf113", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_114", property="pf114", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_115", property="pf115", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_116", property="pf116", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_117", property="pf117", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_118", property="pf118", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_119", property="pf119", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_120", property="pf120", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_121", property="pf121", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_122", property="pf122", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_123", property="pf123", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_124", property="pf124", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_125", property="pf125", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_126", property="pf126", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_127", property="pf127", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_128", property="pf128", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_129", property="pf129", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_130", property="pf130", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_131", property="pf131", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_132", property="pf132", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_133", property="pf133", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_134", property="pf134", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_135", property="pf135", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_136", property="pf136", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_137", property="pf137", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_138", property="pf138", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_139", property="pf139", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_140", property="pf140", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_141", property="pf141", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_142", property="pf142", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_143", property="pf143", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_144", property="pf144", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_145", property="pf145", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_146", property="pf146", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_147", property="pf147", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_148", property="pf148", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_149", property="pf149", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_150", property="pf150", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_151", property="pf151", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_152", property="pf152", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_153", property="pf153", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_154", property="pf154", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_155", property="pf155", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_156", property="pf156", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_157", property="pf157", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_158", property="pf158", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_159", property="pf159", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_160", property="pf160", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_161", property="pf161", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_162", property="pf162", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_163", property="pf163", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_164", property="pf164", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_165", property="pf165", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_166", property="pf166", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_167", property="pf167", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_168", property="pf168", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_169", property="pf169", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_170", property="pf170", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_171", property="pf171", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_172", property="pf172", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_173", property="pf173", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_174", property="pf174", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_175", property="pf175", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_176", property="pf176", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_177", property="pf177", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_178", property="pf178", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_179", property="pf179", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_180", property="pf180", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_181", property="pf181", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_182", property="pf182", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_183", property="pf183", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_184", property="pf184", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_185", property="pf185", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_186", property="pf186", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_187", property="pf187", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_188", property="pf188", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_189", property="pf189", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_190", property="pf190", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_191", property="pf191", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_192", property="pf192", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_193", property="pf193", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_194", property="pf194", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_195", property="pf195", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_196", property="pf196", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_197", property="pf197", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_198", property="pf198", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_199", property="pf199", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_200", property="pf200", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_201", property="pf201", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_202", property="pf202", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_203", property="pf203", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_204", property="pf204", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_205", property="pf205", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_206", property="pf206", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_207", property="pf207", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_208", property="pf208", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_209", property="pf209", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_210", property="pf210", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_211", property="pf211", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_212", property="pf212", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_213", property="pf213", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_214", property="pf214", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_215", property="pf215", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_216", property="pf216", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_217", property="pf217", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_218", property="pf218", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_219", property="pf219", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_220", property="pf220", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_221", property="pf221", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_222", property="pf222", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_223", property="pf223", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_224", property="pf224", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_225", property="pf225", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_226", property="pf226", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_227", property="pf227", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_228", property="pf228", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_229", property="pf229", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_230", property="pf230", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_231", property="pf231", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_232", property="pf232", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_233", property="pf233", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_234", property="pf234", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_235", property="pf235", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_236", property="pf236", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_237", property="pf237", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_238", property="pf238", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_239", property="pf239", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_240", property="pf240", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_241", property="pf241", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_242", property="pf242", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_243", property="pf243", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_244", property="pf244", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_245", property="pf245", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_246", property="pf246", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_247", property="pf247", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_248", property="pf248", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_249", property="pf249", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_250", property="pf250", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_251", property="pf251", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_252", property="pf252", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_253", property="pf253", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_254", property="pf254", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_255", property="pf255", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_256", property="pf256", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_257", property="pf257", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_258", property="pf258", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_259", property="pf259", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_260", property="pf260", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_261", property="pf261", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_262", property="pf262", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_263", property="pf263", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_264", property="pf264", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_265", property="pf265", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_266", property="pf266", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_267", property="pf267", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_268", property="pf268", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_269", property="pf269", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_270", property="pf270", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_271", property="pf271", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_272", property="pf272", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_273", property="pf273", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_274", property="pf274", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_275", property="pf275", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_276", property="pf276", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_277", property="pf277", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_278", property="pf278", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_279", property="pf279", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_280", property="pf280", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_281", property="pf281", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_282", property="pf282", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_283", property="pf283", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_284", property="pf284", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_285", property="pf285", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_286", property="pf286", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_287", property="pf287", jdbcType=JdbcType.DECIMAL),
            @Result(column="PF_288", property="pf288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_factorCurvePo> selectFactorCurveBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);
}