package com.dao.mapper;

import com.dao.bean.D_freqCurvePo;
import com.dao.bean.D_freqCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_freqCurvePoMapper {

    @Select({
        "select",
        "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, FREQ_1, FREQ_2, ",
        "FREQ_3, FREQ_4, FREQ_5, FREQ_6, FREQ_7, FREQ_8, FREQ_9, FREQ_10, FREQ_11, FREQ_12, ",
        "FREQ_13, FREQ_14, FREQ_15, FREQ_16, FREQ_17, FREQ_18, FREQ_19, FREQ_20, FREQ_21, ",
        "FREQ_22, FREQ_23, FREQ_24, FREQ_25, FREQ_26, FREQ_27, FREQ_28, FREQ_29, FREQ_30, ",
        "FREQ_31, FREQ_32, FREQ_33, FREQ_34, FREQ_35, FREQ_36, FREQ_37, FREQ_38, FREQ_39, ",
        "FREQ_40, FREQ_41, FREQ_42, FREQ_43, FREQ_44, FREQ_45, FREQ_46, FREQ_47, FREQ_48, ",
        "FREQ_49, FREQ_50, FREQ_51, FREQ_52, FREQ_53, FREQ_54, FREQ_55, FREQ_56, FREQ_57, ",
        "FREQ_58, FREQ_59, FREQ_60, FREQ_61, FREQ_62, FREQ_63, FREQ_64, FREQ_65, FREQ_66, ",
        "FREQ_67, FREQ_68, FREQ_69, FREQ_70, FREQ_71, FREQ_72, FREQ_73, FREQ_74, FREQ_75, ",
        "FREQ_76, FREQ_77, FREQ_78, FREQ_79, FREQ_80, FREQ_81, FREQ_82, FREQ_83, FREQ_84, ",
        "FREQ_85, FREQ_86, FREQ_87, FREQ_88, FREQ_89, FREQ_90, FREQ_91, FREQ_92, FREQ_93, ",
        "FREQ_94, FREQ_95, FREQ_96, FREQ_97, FREQ_98, FREQ_99, FREQ_100, FREQ_101, FREQ_102, ",
        "FREQ_103, FREQ_104, FREQ_105, FREQ_106, FREQ_107, FREQ_108, FREQ_109, FREQ_110, ",
        "FREQ_111, FREQ_112, FREQ_113, FREQ_114, FREQ_115, FREQ_116, FREQ_117, FREQ_118, ",
        "FREQ_119, FREQ_120, FREQ_121, FREQ_122, FREQ_123, FREQ_124, FREQ_125, FREQ_126, ",
        "FREQ_127, FREQ_128, FREQ_129, FREQ_130, FREQ_131, FREQ_132, FREQ_133, FREQ_134, ",
        "FREQ_135, FREQ_136, FREQ_137, FREQ_138, FREQ_139, FREQ_140, FREQ_141, FREQ_142, ",
        "FREQ_143, FREQ_144, FREQ_145, FREQ_146, FREQ_147, FREQ_148, FREQ_149, FREQ_150, ",
        "FREQ_151, FREQ_152, FREQ_153, FREQ_154, FREQ_155, FREQ_156, FREQ_157, FREQ_158, ",
        "FREQ_159, FREQ_160, FREQ_161, FREQ_162, FREQ_163, FREQ_164, FREQ_165, FREQ_166, ",
        "FREQ_167, FREQ_168, FREQ_169, FREQ_170, FREQ_171, FREQ_172, FREQ_173, FREQ_174, ",
        "FREQ_175, FREQ_176, FREQ_177, FREQ_178, FREQ_179, FREQ_180, FREQ_181, FREQ_182, ",
        "FREQ_183, FREQ_184, FREQ_185, FREQ_186, FREQ_187, FREQ_188, FREQ_189, FREQ_190, ",
        "FREQ_191, FREQ_192, FREQ_193, FREQ_194, FREQ_195, FREQ_196, FREQ_197, FREQ_198, ",
        "FREQ_199, FREQ_200, FREQ_201, FREQ_202, FREQ_203, FREQ_204, FREQ_205, FREQ_206, ",
        "FREQ_207, FREQ_208, FREQ_209, FREQ_210, FREQ_211, FREQ_212, FREQ_213, FREQ_214, ",
        "FREQ_215, FREQ_216, FREQ_217, FREQ_218, FREQ_219, FREQ_220, FREQ_221, FREQ_222, ",
        "FREQ_223, FREQ_224, FREQ_225, FREQ_226, FREQ_227, FREQ_228, FREQ_229, FREQ_230, ",
        "FREQ_231, FREQ_232, FREQ_233, FREQ_234, FREQ_235, FREQ_236, FREQ_237, FREQ_238, ",
        "FREQ_239, FREQ_240, FREQ_241, FREQ_242, FREQ_243, FREQ_244, FREQ_245, FREQ_246, ",
        "FREQ_247, FREQ_248, FREQ_249, FREQ_250, FREQ_251, FREQ_252, FREQ_253, FREQ_254, ",
        "FREQ_255, FREQ_256, FREQ_257, FREQ_258, FREQ_259, FREQ_260, FREQ_261, FREQ_262, ",
        "FREQ_263, FREQ_264, FREQ_265, FREQ_266, FREQ_267, FREQ_268, FREQ_269, FREQ_270, ",
        "FREQ_271, FREQ_272, FREQ_273, FREQ_274, FREQ_275, FREQ_276, FREQ_277, FREQ_278, ",
        "FREQ_279, FREQ_280, FREQ_281, FREQ_282, FREQ_283, FREQ_284, FREQ_285, FREQ_286, ",
        "FREQ_287, FREQ_288",
        "from c_mmxu_freq_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="FREQ_1", property="freq1", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_2", property="freq2", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_3", property="freq3", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_4", property="freq4", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_5", property="freq5", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_6", property="freq6", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_7", property="freq7", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_8", property="freq8", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_9", property="freq9", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_10", property="freq10", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_11", property="freq11", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_12", property="freq12", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_13", property="freq13", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_14", property="freq14", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_15", property="freq15", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_16", property="freq16", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_17", property="freq17", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_18", property="freq18", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_19", property="freq19", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_20", property="freq20", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_21", property="freq21", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_22", property="freq22", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_23", property="freq23", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_24", property="freq24", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_25", property="freq25", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_26", property="freq26", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_27", property="freq27", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_28", property="freq28", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_29", property="freq29", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_30", property="freq30", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_31", property="freq31", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_32", property="freq32", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_33", property="freq33", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_34", property="freq34", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_35", property="freq35", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_36", property="freq36", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_37", property="freq37", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_38", property="freq38", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_39", property="freq39", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_40", property="freq40", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_41", property="freq41", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_42", property="freq42", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_43", property="freq43", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_44", property="freq44", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_45", property="freq45", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_46", property="freq46", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_47", property="freq47", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_48", property="freq48", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_49", property="freq49", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_50", property="freq50", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_51", property="freq51", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_52", property="freq52", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_53", property="freq53", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_54", property="freq54", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_55", property="freq55", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_56", property="freq56", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_57", property="freq57", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_58", property="freq58", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_59", property="freq59", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_60", property="freq60", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_61", property="freq61", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_62", property="freq62", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_63", property="freq63", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_64", property="freq64", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_65", property="freq65", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_66", property="freq66", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_67", property="freq67", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_68", property="freq68", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_69", property="freq69", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_70", property="freq70", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_71", property="freq71", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_72", property="freq72", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_73", property="freq73", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_74", property="freq74", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_75", property="freq75", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_76", property="freq76", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_77", property="freq77", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_78", property="freq78", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_79", property="freq79", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_80", property="freq80", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_81", property="freq81", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_82", property="freq82", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_83", property="freq83", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_84", property="freq84", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_85", property="freq85", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_86", property="freq86", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_87", property="freq87", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_88", property="freq88", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_89", property="freq89", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_90", property="freq90", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_91", property="freq91", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_92", property="freq92", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_93", property="freq93", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_94", property="freq94", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_95", property="freq95", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_96", property="freq96", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_97", property="freq97", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_98", property="freq98", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_99", property="freq99", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_100", property="freq100", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_101", property="freq101", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_102", property="freq102", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_103", property="freq103", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_104", property="freq104", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_105", property="freq105", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_106", property="freq106", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_107", property="freq107", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_108", property="freq108", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_109", property="freq109", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_110", property="freq110", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_111", property="freq111", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_112", property="freq112", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_113", property="freq113", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_114", property="freq114", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_115", property="freq115", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_116", property="freq116", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_117", property="freq117", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_118", property="freq118", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_119", property="freq119", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_120", property="freq120", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_121", property="freq121", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_122", property="freq122", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_123", property="freq123", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_124", property="freq124", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_125", property="freq125", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_126", property="freq126", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_127", property="freq127", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_128", property="freq128", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_129", property="freq129", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_130", property="freq130", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_131", property="freq131", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_132", property="freq132", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_133", property="freq133", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_134", property="freq134", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_135", property="freq135", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_136", property="freq136", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_137", property="freq137", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_138", property="freq138", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_139", property="freq139", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_140", property="freq140", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_141", property="freq141", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_142", property="freq142", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_143", property="freq143", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_144", property="freq144", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_145", property="freq145", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_146", property="freq146", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_147", property="freq147", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_148", property="freq148", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_149", property="freq149", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_150", property="freq150", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_151", property="freq151", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_152", property="freq152", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_153", property="freq153", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_154", property="freq154", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_155", property="freq155", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_156", property="freq156", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_157", property="freq157", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_158", property="freq158", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_159", property="freq159", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_160", property="freq160", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_161", property="freq161", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_162", property="freq162", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_163", property="freq163", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_164", property="freq164", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_165", property="freq165", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_166", property="freq166", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_167", property="freq167", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_168", property="freq168", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_169", property="freq169", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_170", property="freq170", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_171", property="freq171", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_172", property="freq172", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_173", property="freq173", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_174", property="freq174", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_175", property="freq175", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_176", property="freq176", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_177", property="freq177", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_178", property="freq178", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_179", property="freq179", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_180", property="freq180", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_181", property="freq181", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_182", property="freq182", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_183", property="freq183", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_184", property="freq184", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_185", property="freq185", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_186", property="freq186", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_187", property="freq187", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_188", property="freq188", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_189", property="freq189", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_190", property="freq190", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_191", property="freq191", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_192", property="freq192", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_193", property="freq193", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_194", property="freq194", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_195", property="freq195", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_196", property="freq196", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_197", property="freq197", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_198", property="freq198", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_199", property="freq199", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_200", property="freq200", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_201", property="freq201", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_202", property="freq202", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_203", property="freq203", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_204", property="freq204", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_205", property="freq205", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_206", property="freq206", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_207", property="freq207", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_208", property="freq208", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_209", property="freq209", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_210", property="freq210", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_211", property="freq211", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_212", property="freq212", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_213", property="freq213", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_214", property="freq214", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_215", property="freq215", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_216", property="freq216", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_217", property="freq217", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_218", property="freq218", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_219", property="freq219", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_220", property="freq220", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_221", property="freq221", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_222", property="freq222", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_223", property="freq223", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_224", property="freq224", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_225", property="freq225", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_226", property="freq226", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_227", property="freq227", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_228", property="freq228", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_229", property="freq229", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_230", property="freq230", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_231", property="freq231", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_232", property="freq232", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_233", property="freq233", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_234", property="freq234", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_235", property="freq235", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_236", property="freq236", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_237", property="freq237", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_238", property="freq238", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_239", property="freq239", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_240", property="freq240", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_241", property="freq241", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_242", property="freq242", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_243", property="freq243", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_244", property="freq244", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_245", property="freq245", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_246", property="freq246", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_247", property="freq247", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_248", property="freq248", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_249", property="freq249", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_250", property="freq250", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_251", property="freq251", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_252", property="freq252", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_253", property="freq253", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_254", property="freq254", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_255", property="freq255", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_256", property="freq256", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_257", property="freq257", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_258", property="freq258", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_259", property="freq259", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_260", property="freq260", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_261", property="freq261", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_262", property="freq262", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_263", property="freq263", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_264", property="freq264", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_265", property="freq265", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_266", property="freq266", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_267", property="freq267", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_268", property="freq268", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_269", property="freq269", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_270", property="freq270", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_271", property="freq271", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_272", property="freq272", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_273", property="freq273", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_274", property="freq274", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_275", property="freq275", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_276", property="freq276", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_277", property="freq277", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_278", property="freq278", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_279", property="freq279", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_280", property="freq280", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_281", property="freq281", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_282", property="freq282", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_283", property="freq283", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_284", property="freq284", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_285", property="freq285", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_286", property="freq286", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_287", property="freq287", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREQ_288", property="freq288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_freqCurvePo> selectByPrimaryKey(String data_date);

    @Select({
            "select",
            "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, FREQ_1, FREQ_2, ",
            "FREQ_3, FREQ_4, FREQ_5, FREQ_6, FREQ_7, FREQ_8, FREQ_9, FREQ_10, FREQ_11, FREQ_12, ",
            "FREQ_13, FREQ_14, FREQ_15, FREQ_16, FREQ_17, FREQ_18, FREQ_19, FREQ_20, FREQ_21, ",
            "FREQ_22, FREQ_23, FREQ_24, FREQ_25, FREQ_26, FREQ_27, FREQ_28, FREQ_29, FREQ_30, ",
            "FREQ_31, FREQ_32, FREQ_33, FREQ_34, FREQ_35, FREQ_36, FREQ_37, FREQ_38, FREQ_39, ",
            "FREQ_40, FREQ_41, FREQ_42, FREQ_43, FREQ_44, FREQ_45, FREQ_46, FREQ_47, FREQ_48, ",
            "FREQ_49, FREQ_50, FREQ_51, FREQ_52, FREQ_53, FREQ_54, FREQ_55, FREQ_56, FREQ_57, ",
            "FREQ_58, FREQ_59, FREQ_60, FREQ_61, FREQ_62, FREQ_63, FREQ_64, FREQ_65, FREQ_66, ",
            "FREQ_67, FREQ_68, FREQ_69, FREQ_70, FREQ_71, FREQ_72, FREQ_73, FREQ_74, FREQ_75, ",
            "FREQ_76, FREQ_77, FREQ_78, FREQ_79, FREQ_80, FREQ_81, FREQ_82, FREQ_83, FREQ_84, ",
            "FREQ_85, FREQ_86, FREQ_87, FREQ_88, FREQ_89, FREQ_90, FREQ_91, FREQ_92, FREQ_93, ",
            "FREQ_94, FREQ_95, FREQ_96, FREQ_97, FREQ_98, FREQ_99, FREQ_100, FREQ_101, FREQ_102, ",
            "FREQ_103, FREQ_104, FREQ_105, FREQ_106, FREQ_107, FREQ_108, FREQ_109, FREQ_110, ",
            "FREQ_111, FREQ_112, FREQ_113, FREQ_114, FREQ_115, FREQ_116, FREQ_117, FREQ_118, ",
            "FREQ_119, FREQ_120, FREQ_121, FREQ_122, FREQ_123, FREQ_124, FREQ_125, FREQ_126, ",
            "FREQ_127, FREQ_128, FREQ_129, FREQ_130, FREQ_131, FREQ_132, FREQ_133, FREQ_134, ",
            "FREQ_135, FREQ_136, FREQ_137, FREQ_138, FREQ_139, FREQ_140, FREQ_141, FREQ_142, ",
            "FREQ_143, FREQ_144, FREQ_145, FREQ_146, FREQ_147, FREQ_148, FREQ_149, FREQ_150, ",
            "FREQ_151, FREQ_152, FREQ_153, FREQ_154, FREQ_155, FREQ_156, FREQ_157, FREQ_158, ",
            "FREQ_159, FREQ_160, FREQ_161, FREQ_162, FREQ_163, FREQ_164, FREQ_165, FREQ_166, ",
            "FREQ_167, FREQ_168, FREQ_169, FREQ_170, FREQ_171, FREQ_172, FREQ_173, FREQ_174, ",
            "FREQ_175, FREQ_176, FREQ_177, FREQ_178, FREQ_179, FREQ_180, FREQ_181, FREQ_182, ",
            "FREQ_183, FREQ_184, FREQ_185, FREQ_186, FREQ_187, FREQ_188, FREQ_189, FREQ_190, ",
            "FREQ_191, FREQ_192, FREQ_193, FREQ_194, FREQ_195, FREQ_196, FREQ_197, FREQ_198, ",
            "FREQ_199, FREQ_200, FREQ_201, FREQ_202, FREQ_203, FREQ_204, FREQ_205, FREQ_206, ",
            "FREQ_207, FREQ_208, FREQ_209, FREQ_210, FREQ_211, FREQ_212, FREQ_213, FREQ_214, ",
            "FREQ_215, FREQ_216, FREQ_217, FREQ_218, FREQ_219, FREQ_220, FREQ_221, FREQ_222, ",
            "FREQ_223, FREQ_224, FREQ_225, FREQ_226, FREQ_227, FREQ_228, FREQ_229, FREQ_230, ",
            "FREQ_231, FREQ_232, FREQ_233, FREQ_234, FREQ_235, FREQ_236, FREQ_237, FREQ_238, ",
            "FREQ_239, FREQ_240, FREQ_241, FREQ_242, FREQ_243, FREQ_244, FREQ_245, FREQ_246, ",
            "FREQ_247, FREQ_248, FREQ_249, FREQ_250, FREQ_251, FREQ_252, FREQ_253, FREQ_254, ",
            "FREQ_255, FREQ_256, FREQ_257, FREQ_258, FREQ_259, FREQ_260, FREQ_261, FREQ_262, ",
            "FREQ_263, FREQ_264, FREQ_265, FREQ_266, FREQ_267, FREQ_268, FREQ_269, FREQ_270, ",
            "FREQ_271, FREQ_272, FREQ_273, FREQ_274, FREQ_275, FREQ_276, FREQ_277, FREQ_278, ",
            "FREQ_279, FREQ_280, FREQ_281, FREQ_282, FREQ_283, FREQ_284, FREQ_285, FREQ_286, ",
            "FREQ_287, FREQ_288",
            "from c_mmxu_freq_c ",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="FREQ_1", property="freq1", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_2", property="freq2", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_3", property="freq3", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_4", property="freq4", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_5", property="freq5", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_6", property="freq6", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_7", property="freq7", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_8", property="freq8", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_9", property="freq9", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_10", property="freq10", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_11", property="freq11", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_12", property="freq12", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_13", property="freq13", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_14", property="freq14", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_15", property="freq15", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_16", property="freq16", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_17", property="freq17", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_18", property="freq18", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_19", property="freq19", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_20", property="freq20", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_21", property="freq21", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_22", property="freq22", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_23", property="freq23", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_24", property="freq24", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_25", property="freq25", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_26", property="freq26", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_27", property="freq27", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_28", property="freq28", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_29", property="freq29", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_30", property="freq30", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_31", property="freq31", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_32", property="freq32", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_33", property="freq33", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_34", property="freq34", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_35", property="freq35", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_36", property="freq36", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_37", property="freq37", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_38", property="freq38", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_39", property="freq39", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_40", property="freq40", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_41", property="freq41", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_42", property="freq42", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_43", property="freq43", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_44", property="freq44", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_45", property="freq45", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_46", property="freq46", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_47", property="freq47", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_48", property="freq48", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_49", property="freq49", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_50", property="freq50", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_51", property="freq51", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_52", property="freq52", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_53", property="freq53", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_54", property="freq54", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_55", property="freq55", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_56", property="freq56", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_57", property="freq57", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_58", property="freq58", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_59", property="freq59", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_60", property="freq60", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_61", property="freq61", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_62", property="freq62", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_63", property="freq63", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_64", property="freq64", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_65", property="freq65", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_66", property="freq66", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_67", property="freq67", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_68", property="freq68", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_69", property="freq69", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_70", property="freq70", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_71", property="freq71", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_72", property="freq72", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_73", property="freq73", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_74", property="freq74", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_75", property="freq75", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_76", property="freq76", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_77", property="freq77", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_78", property="freq78", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_79", property="freq79", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_80", property="freq80", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_81", property="freq81", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_82", property="freq82", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_83", property="freq83", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_84", property="freq84", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_85", property="freq85", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_86", property="freq86", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_87", property="freq87", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_88", property="freq88", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_89", property="freq89", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_90", property="freq90", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_91", property="freq91", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_92", property="freq92", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_93", property="freq93", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_94", property="freq94", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_95", property="freq95", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_96", property="freq96", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_97", property="freq97", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_98", property="freq98", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_99", property="freq99", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_100", property="freq100", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_101", property="freq101", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_102", property="freq102", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_103", property="freq103", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_104", property="freq104", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_105", property="freq105", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_106", property="freq106", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_107", property="freq107", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_108", property="freq108", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_109", property="freq109", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_110", property="freq110", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_111", property="freq111", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_112", property="freq112", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_113", property="freq113", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_114", property="freq114", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_115", property="freq115", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_116", property="freq116", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_117", property="freq117", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_118", property="freq118", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_119", property="freq119", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_120", property="freq120", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_121", property="freq121", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_122", property="freq122", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_123", property="freq123", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_124", property="freq124", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_125", property="freq125", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_126", property="freq126", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_127", property="freq127", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_128", property="freq128", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_129", property="freq129", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_130", property="freq130", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_131", property="freq131", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_132", property="freq132", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_133", property="freq133", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_134", property="freq134", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_135", property="freq135", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_136", property="freq136", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_137", property="freq137", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_138", property="freq138", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_139", property="freq139", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_140", property="freq140", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_141", property="freq141", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_142", property="freq142", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_143", property="freq143", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_144", property="freq144", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_145", property="freq145", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_146", property="freq146", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_147", property="freq147", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_148", property="freq148", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_149", property="freq149", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_150", property="freq150", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_151", property="freq151", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_152", property="freq152", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_153", property="freq153", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_154", property="freq154", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_155", property="freq155", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_156", property="freq156", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_157", property="freq157", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_158", property="freq158", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_159", property="freq159", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_160", property="freq160", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_161", property="freq161", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_162", property="freq162", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_163", property="freq163", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_164", property="freq164", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_165", property="freq165", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_166", property="freq166", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_167", property="freq167", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_168", property="freq168", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_169", property="freq169", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_170", property="freq170", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_171", property="freq171", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_172", property="freq172", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_173", property="freq173", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_174", property="freq174", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_175", property="freq175", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_176", property="freq176", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_177", property="freq177", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_178", property="freq178", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_179", property="freq179", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_180", property="freq180", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_181", property="freq181", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_182", property="freq182", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_183", property="freq183", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_184", property="freq184", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_185", property="freq185", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_186", property="freq186", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_187", property="freq187", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_188", property="freq188", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_189", property="freq189", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_190", property="freq190", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_191", property="freq191", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_192", property="freq192", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_193", property="freq193", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_194", property="freq194", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_195", property="freq195", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_196", property="freq196", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_197", property="freq197", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_198", property="freq198", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_199", property="freq199", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_200", property="freq200", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_201", property="freq201", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_202", property="freq202", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_203", property="freq203", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_204", property="freq204", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_205", property="freq205", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_206", property="freq206", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_207", property="freq207", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_208", property="freq208", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_209", property="freq209", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_210", property="freq210", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_211", property="freq211", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_212", property="freq212", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_213", property="freq213", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_214", property="freq214", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_215", property="freq215", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_216", property="freq216", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_217", property="freq217", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_218", property="freq218", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_219", property="freq219", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_220", property="freq220", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_221", property="freq221", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_222", property="freq222", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_223", property="freq223", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_224", property="freq224", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_225", property="freq225", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_226", property="freq226", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_227", property="freq227", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_228", property="freq228", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_229", property="freq229", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_230", property="freq230", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_231", property="freq231", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_232", property="freq232", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_233", property="freq233", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_234", property="freq234", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_235", property="freq235", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_236", property="freq236", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_237", property="freq237", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_238", property="freq238", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_239", property="freq239", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_240", property="freq240", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_241", property="freq241", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_242", property="freq242", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_243", property="freq243", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_244", property="freq244", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_245", property="freq245", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_246", property="freq246", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_247", property="freq247", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_248", property="freq248", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_249", property="freq249", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_250", property="freq250", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_251", property="freq251", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_252", property="freq252", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_253", property="freq253", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_254", property="freq254", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_255", property="freq255", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_256", property="freq256", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_257", property="freq257", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_258", property="freq258", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_259", property="freq259", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_260", property="freq260", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_261", property="freq261", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_262", property="freq262", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_263", property="freq263", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_264", property="freq264", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_265", property="freq265", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_266", property="freq266", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_267", property="freq267", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_268", property="freq268", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_269", property="freq269", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_270", property="freq270", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_271", property="freq271", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_272", property="freq272", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_273", property="freq273", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_274", property="freq274", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_275", property="freq275", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_276", property="freq276", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_277", property="freq277", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_278", property="freq278", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_279", property="freq279", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_280", property="freq280", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_281", property="freq281", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_282", property="freq282", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_283", property="freq283", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_284", property="freq284", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_285", property="freq285", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_286", property="freq286", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_287", property="freq287", jdbcType=JdbcType.DECIMAL),
            @Result(column="FREQ_288", property="freq288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_freqCurvePo> selectBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

}