package com.dao.mapper;

import com.dao.bean.D_fundVolCurvePo;
import com.dao.bean.D_fundVolCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_fundVolCurvePoMapper {

    @Select({
        "select",
        "LD_ID, SYS_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, FUND_VOL_1, ",
        "FUND_VOL_2, FUND_VOL_3, FUND_VOL_4, FUND_VOL_5, FUND_VOL_6, FUND_VOL_7, FUND_VOL_8, ",
        "FUND_VOL_9, FUND_VOL_10, FUND_VOL_11, FUND_VOL_12, FUND_VOL_13, FUND_VOL_14, ",
        "FUND_VOL_15, FUND_VOL_16, FUND_VOL_17, FUND_VOL_18, FUND_VOL_19, FUND_VOL_20, ",
        "FUND_VOL_21, FUND_VOL_22, FUND_VOL_23, FUND_VOL_24, FUND_VOL_25, FUND_VOL_26, ",
        "FUND_VOL_27, FUND_VOL_28, FUND_VOL_29, FUND_VOL_30, FUND_VOL_31, FUND_VOL_32, ",
        "FUND_VOL_33, FUND_VOL_34, FUND_VOL_35, FUND_VOL_36, FUND_VOL_37, FUND_VOL_38, ",
        "FUND_VOL_39, FUND_VOL_40, FUND_VOL_41, FUND_VOL_42, FUND_VOL_43, FUND_VOL_44, ",
        "FUND_VOL_45, FUND_VOL_46, FUND_VOL_47, FUND_VOL_48, FUND_VOL_49, FUND_VOL_50, ",
        "FUND_VOL_51, FUND_VOL_52, FUND_VOL_53, FUND_VOL_54, FUND_VOL_55, FUND_VOL_56, ",
        "FUND_VOL_57, FUND_VOL_58, FUND_VOL_59, FUND_VOL_60, FUND_VOL_61, FUND_VOL_62, ",
        "FUND_VOL_63, FUND_VOL_64, FUND_VOL_65, FUND_VOL_66, FUND_VOL_67, FUND_VOL_68, ",
        "FUND_VOL_69, FUND_VOL_70, FUND_VOL_71, FUND_VOL_72, FUND_VOL_73, FUND_VOL_74, ",
        "FUND_VOL_75, FUND_VOL_76, FUND_VOL_77, FUND_VOL_78, FUND_VOL_79, FUND_VOL_80, ",
        "FUND_VOL_81, FUND_VOL_82, FUND_VOL_83, FUND_VOL_84, FUND_VOL_85, FUND_VOL_86, ",
        "FUND_VOL_87, FUND_VOL_88, FUND_VOL_89, FUND_VOL_90, FUND_VOL_91, FUND_VOL_92, ",
        "FUND_VOL_93, FUND_VOL_94, FUND_VOL_95, FUND_VOL_96, FUND_VOL_97, FUND_VOL_98, ",
        "FUND_VOL_99, FUND_VOL_100, FUND_VOL_101, FUND_VOL_102, FUND_VOL_103, FUND_VOL_104, ",
        "FUND_VOL_105, FUND_VOL_106, FUND_VOL_107, FUND_VOL_108, FUND_VOL_109, FUND_VOL_110, ",
        "FUND_VOL_111, FUND_VOL_112, FUND_VOL_113, FUND_VOL_114, FUND_VOL_115, FUND_VOL_116, ",
        "FUND_VOL_117, FUND_VOL_118, FUND_VOL_119, FUND_VOL_120, FUND_VOL_121, FUND_VOL_122, ",
        "FUND_VOL_123, FUND_VOL_124, FUND_VOL_125, FUND_VOL_126, FUND_VOL_127, FUND_VOL_128, ",
        "FUND_VOL_129, FUND_VOL_130, FUND_VOL_131, FUND_VOL_132, FUND_VOL_133, FUND_VOL_134, ",
        "FUND_VOL_135, FUND_VOL_136, FUND_VOL_137, FUND_VOL_138, FUND_VOL_139, FUND_VOL_140, ",
        "FUND_VOL_141, FUND_VOL_142, FUND_VOL_143, FUND_VOL_144, FUND_VOL_145, FUND_VOL_146, ",
        "FUND_VOL_147, FUND_VOL_148, FUND_VOL_149, FUND_VOL_150, FUND_VOL_151, FUND_VOL_152, ",
        "FUND_VOL_153, FUND_VOL_154, FUND_VOL_155, FUND_VOL_156, FUND_VOL_157, FUND_VOL_158, ",
        "FUND_VOL_159, FUND_VOL_160, FUND_VOL_161, FUND_VOL_162, FUND_VOL_163, FUND_VOL_164, ",
        "FUND_VOL_165, FUND_VOL_166, FUND_VOL_167, FUND_VOL_168, FUND_VOL_169, FUND_VOL_170, ",
        "FUND_VOL_171, FUND_VOL_172, FUND_VOL_173, FUND_VOL_174, FUND_VOL_175, FUND_VOL_176, ",
        "FUND_VOL_177, FUND_VOL_178, FUND_VOL_179, FUND_VOL_180, FUND_VOL_181, FUND_VOL_182, ",
        "FUND_VOL_183, FUND_VOL_184, FUND_VOL_185, FUND_VOL_186, FUND_VOL_187, FUND_VOL_188, ",
        "FUND_VOL_189, FUND_VOL_190, FUND_VOL_191, FUND_VOL_192, FUND_VOL_193, FUND_VOL_194, ",
        "FUND_VOL_195, FUND_VOL_196, FUND_VOL_197, FUND_VOL_198, FUND_VOL_199, FUND_VOL_200, ",
        "FUND_VOL_201, FUND_VOL_202, FUND_VOL_203, FUND_VOL_204, FUND_VOL_205, FUND_VOL_206, ",
        "FUND_VOL_207, FUND_VOL_208, FUND_VOL_209, FUND_VOL_210, FUND_VOL_211, FUND_VOL_212, ",
        "FUND_VOL_213, FUND_VOL_214, FUND_VOL_215, FUND_VOL_216, FUND_VOL_217, FUND_VOL_218, ",
        "FUND_VOL_219, FUND_VOL_220, FUND_VOL_221, FUND_VOL_222, FUND_VOL_223, FUND_VOL_224, ",
        "FUND_VOL_225, FUND_VOL_226, FUND_VOL_227, FUND_VOL_228, FUND_VOL_229, FUND_VOL_230, ",
        "FUND_VOL_231, FUND_VOL_232, FUND_VOL_233, FUND_VOL_234, FUND_VOL_235, FUND_VOL_236, ",
        "FUND_VOL_237, FUND_VOL_238, FUND_VOL_239, FUND_VOL_240, FUND_VOL_241, FUND_VOL_242, ",
        "FUND_VOL_243, FUND_VOL_244, FUND_VOL_245, FUND_VOL_246, FUND_VOL_247, FUND_VOL_248, ",
        "FUND_VOL_249, FUND_VOL_250, FUND_VOL_251, FUND_VOL_252, FUND_VOL_253, FUND_VOL_254, ",
        "FUND_VOL_255, FUND_VOL_256, FUND_VOL_257, FUND_VOL_258, FUND_VOL_259, FUND_VOL_260, ",
        "FUND_VOL_261, FUND_VOL_262, FUND_VOL_263, FUND_VOL_264, FUND_VOL_265, FUND_VOL_266, ",
        "FUND_VOL_267, FUND_VOL_268, FUND_VOL_269, FUND_VOL_270, FUND_VOL_271, FUND_VOL_272, ",
        "FUND_VOL_273, FUND_VOL_274, FUND_VOL_275, FUND_VOL_276, FUND_VOL_277, FUND_VOL_278, ",
        "FUND_VOL_279, FUND_VOL_280, FUND_VOL_281, FUND_VOL_282, FUND_VOL_283, FUND_VOL_284, ",
        "FUND_VOL_285, FUND_VOL_286, FUND_VOL_287, FUND_VOL_288",
        "from c_mhai_fundvol_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="FUND_VOL_1", property="fundVol1", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_2", property="fundVol2", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_3", property="fundVol3", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_4", property="fundVol4", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_5", property="fundVol5", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_6", property="fundVol6", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_7", property="fundVol7", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_8", property="fundVol8", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_9", property="fundVol9", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_10", property="fundVol10", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_11", property="fundVol11", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_12", property="fundVol12", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_13", property="fundVol13", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_14", property="fundVol14", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_15", property="fundVol15", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_16", property="fundVol16", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_17", property="fundVol17", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_18", property="fundVol18", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_19", property="fundVol19", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_20", property="fundVol20", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_21", property="fundVol21", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_22", property="fundVol22", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_23", property="fundVol23", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_24", property="fundVol24", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_25", property="fundVol25", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_26", property="fundVol26", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_27", property="fundVol27", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_28", property="fundVol28", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_29", property="fundVol29", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_30", property="fundVol30", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_31", property="fundVol31", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_32", property="fundVol32", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_33", property="fundVol33", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_34", property="fundVol34", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_35", property="fundVol35", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_36", property="fundVol36", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_37", property="fundVol37", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_38", property="fundVol38", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_39", property="fundVol39", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_40", property="fundVol40", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_41", property="fundVol41", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_42", property="fundVol42", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_43", property="fundVol43", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_44", property="fundVol44", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_45", property="fundVol45", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_46", property="fundVol46", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_47", property="fundVol47", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_48", property="fundVol48", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_49", property="fundVol49", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_50", property="fundVol50", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_51", property="fundVol51", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_52", property="fundVol52", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_53", property="fundVol53", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_54", property="fundVol54", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_55", property="fundVol55", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_56", property="fundVol56", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_57", property="fundVol57", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_58", property="fundVol58", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_59", property="fundVol59", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_60", property="fundVol60", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_61", property="fundVol61", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_62", property="fundVol62", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_63", property="fundVol63", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_64", property="fundVol64", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_65", property="fundVol65", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_66", property="fundVol66", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_67", property="fundVol67", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_68", property="fundVol68", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_69", property="fundVol69", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_70", property="fundVol70", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_71", property="fundVol71", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_72", property="fundVol72", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_73", property="fundVol73", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_74", property="fundVol74", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_75", property="fundVol75", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_76", property="fundVol76", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_77", property="fundVol77", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_78", property="fundVol78", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_79", property="fundVol79", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_80", property="fundVol80", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_81", property="fundVol81", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_82", property="fundVol82", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_83", property="fundVol83", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_84", property="fundVol84", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_85", property="fundVol85", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_86", property="fundVol86", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_87", property="fundVol87", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_88", property="fundVol88", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_89", property="fundVol89", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_90", property="fundVol90", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_91", property="fundVol91", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_92", property="fundVol92", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_93", property="fundVol93", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_94", property="fundVol94", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_95", property="fundVol95", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_96", property="fundVol96", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_97", property="fundVol97", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_98", property="fundVol98", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_99", property="fundVol99", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_100", property="fundVol100", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_101", property="fundVol101", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_102", property="fundVol102", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_103", property="fundVol103", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_104", property="fundVol104", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_105", property="fundVol105", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_106", property="fundVol106", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_107", property="fundVol107", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_108", property="fundVol108", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_109", property="fundVol109", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_110", property="fundVol110", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_111", property="fundVol111", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_112", property="fundVol112", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_113", property="fundVol113", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_114", property="fundVol114", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_115", property="fundVol115", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_116", property="fundVol116", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_117", property="fundVol117", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_118", property="fundVol118", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_119", property="fundVol119", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_120", property="fundVol120", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_121", property="fundVol121", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_122", property="fundVol122", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_123", property="fundVol123", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_124", property="fundVol124", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_125", property="fundVol125", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_126", property="fundVol126", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_127", property="fundVol127", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_128", property="fundVol128", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_129", property="fundVol129", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_130", property="fundVol130", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_131", property="fundVol131", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_132", property="fundVol132", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_133", property="fundVol133", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_134", property="fundVol134", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_135", property="fundVol135", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_136", property="fundVol136", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_137", property="fundVol137", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_138", property="fundVol138", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_139", property="fundVol139", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_140", property="fundVol140", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_141", property="fundVol141", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_142", property="fundVol142", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_143", property="fundVol143", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_144", property="fundVol144", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_145", property="fundVol145", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_146", property="fundVol146", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_147", property="fundVol147", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_148", property="fundVol148", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_149", property="fundVol149", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_150", property="fundVol150", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_151", property="fundVol151", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_152", property="fundVol152", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_153", property="fundVol153", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_154", property="fundVol154", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_155", property="fundVol155", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_156", property="fundVol156", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_157", property="fundVol157", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_158", property="fundVol158", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_159", property="fundVol159", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_160", property="fundVol160", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_161", property="fundVol161", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_162", property="fundVol162", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_163", property="fundVol163", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_164", property="fundVol164", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_165", property="fundVol165", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_166", property="fundVol166", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_167", property="fundVol167", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_168", property="fundVol168", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_169", property="fundVol169", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_170", property="fundVol170", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_171", property="fundVol171", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_172", property="fundVol172", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_173", property="fundVol173", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_174", property="fundVol174", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_175", property="fundVol175", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_176", property="fundVol176", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_177", property="fundVol177", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_178", property="fundVol178", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_179", property="fundVol179", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_180", property="fundVol180", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_181", property="fundVol181", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_182", property="fundVol182", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_183", property="fundVol183", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_184", property="fundVol184", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_185", property="fundVol185", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_186", property="fundVol186", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_187", property="fundVol187", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_188", property="fundVol188", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_189", property="fundVol189", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_190", property="fundVol190", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_191", property="fundVol191", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_192", property="fundVol192", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_193", property="fundVol193", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_194", property="fundVol194", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_195", property="fundVol195", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_196", property="fundVol196", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_197", property="fundVol197", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_198", property="fundVol198", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_199", property="fundVol199", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_200", property="fundVol200", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_201", property="fundVol201", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_202", property="fundVol202", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_203", property="fundVol203", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_204", property="fundVol204", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_205", property="fundVol205", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_206", property="fundVol206", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_207", property="fundVol207", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_208", property="fundVol208", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_209", property="fundVol209", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_210", property="fundVol210", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_211", property="fundVol211", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_212", property="fundVol212", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_213", property="fundVol213", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_214", property="fundVol214", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_215", property="fundVol215", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_216", property="fundVol216", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_217", property="fundVol217", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_218", property="fundVol218", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_219", property="fundVol219", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_220", property="fundVol220", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_221", property="fundVol221", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_222", property="fundVol222", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_223", property="fundVol223", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_224", property="fundVol224", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_225", property="fundVol225", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_226", property="fundVol226", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_227", property="fundVol227", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_228", property="fundVol228", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_229", property="fundVol229", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_230", property="fundVol230", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_231", property="fundVol231", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_232", property="fundVol232", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_233", property="fundVol233", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_234", property="fundVol234", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_235", property="fundVol235", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_236", property="fundVol236", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_237", property="fundVol237", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_238", property="fundVol238", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_239", property="fundVol239", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_240", property="fundVol240", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_241", property="fundVol241", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_242", property="fundVol242", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_243", property="fundVol243", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_244", property="fundVol244", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_245", property="fundVol245", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_246", property="fundVol246", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_247", property="fundVol247", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_248", property="fundVol248", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_249", property="fundVol249", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_250", property="fundVol250", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_251", property="fundVol251", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_252", property="fundVol252", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_253", property="fundVol253", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_254", property="fundVol254", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_255", property="fundVol255", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_256", property="fundVol256", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_257", property="fundVol257", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_258", property="fundVol258", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_259", property="fundVol259", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_260", property="fundVol260", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_261", property="fundVol261", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_262", property="fundVol262", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_263", property="fundVol263", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_264", property="fundVol264", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_265", property="fundVol265", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_266", property="fundVol266", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_267", property="fundVol267", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_268", property="fundVol268", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_269", property="fundVol269", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_270", property="fundVol270", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_271", property="fundVol271", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_272", property="fundVol272", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_273", property="fundVol273", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_274", property="fundVol274", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_275", property="fundVol275", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_276", property="fundVol276", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_277", property="fundVol277", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_278", property="fundVol278", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_279", property="fundVol279", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_280", property="fundVol280", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_281", property="fundVol281", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_282", property="fundVol282", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_283", property="fundVol283", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_284", property="fundVol284", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_285", property="fundVol285", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_286", property="fundVol286", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_287", property="fundVol287", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_VOL_288", property="fundVol288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_fundVolCurvePo> selectFundCurveByDate(String data_date);

    @Select({
            "select",
            "LD_ID, SYS_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, FUND_VOL_1, ",
            "FUND_VOL_2, FUND_VOL_3, FUND_VOL_4, FUND_VOL_5, FUND_VOL_6, FUND_VOL_7, FUND_VOL_8, ",
            "FUND_VOL_9, FUND_VOL_10, FUND_VOL_11, FUND_VOL_12, FUND_VOL_13, FUND_VOL_14, ",
            "FUND_VOL_15, FUND_VOL_16, FUND_VOL_17, FUND_VOL_18, FUND_VOL_19, FUND_VOL_20, ",
            "FUND_VOL_21, FUND_VOL_22, FUND_VOL_23, FUND_VOL_24, FUND_VOL_25, FUND_VOL_26, ",
            "FUND_VOL_27, FUND_VOL_28, FUND_VOL_29, FUND_VOL_30, FUND_VOL_31, FUND_VOL_32, ",
            "FUND_VOL_33, FUND_VOL_34, FUND_VOL_35, FUND_VOL_36, FUND_VOL_37, FUND_VOL_38, ",
            "FUND_VOL_39, FUND_VOL_40, FUND_VOL_41, FUND_VOL_42, FUND_VOL_43, FUND_VOL_44, ",
            "FUND_VOL_45, FUND_VOL_46, FUND_VOL_47, FUND_VOL_48, FUND_VOL_49, FUND_VOL_50, ",
            "FUND_VOL_51, FUND_VOL_52, FUND_VOL_53, FUND_VOL_54, FUND_VOL_55, FUND_VOL_56, ",
            "FUND_VOL_57, FUND_VOL_58, FUND_VOL_59, FUND_VOL_60, FUND_VOL_61, FUND_VOL_62, ",
            "FUND_VOL_63, FUND_VOL_64, FUND_VOL_65, FUND_VOL_66, FUND_VOL_67, FUND_VOL_68, ",
            "FUND_VOL_69, FUND_VOL_70, FUND_VOL_71, FUND_VOL_72, FUND_VOL_73, FUND_VOL_74, ",
            "FUND_VOL_75, FUND_VOL_76, FUND_VOL_77, FUND_VOL_78, FUND_VOL_79, FUND_VOL_80, ",
            "FUND_VOL_81, FUND_VOL_82, FUND_VOL_83, FUND_VOL_84, FUND_VOL_85, FUND_VOL_86, ",
            "FUND_VOL_87, FUND_VOL_88, FUND_VOL_89, FUND_VOL_90, FUND_VOL_91, FUND_VOL_92, ",
            "FUND_VOL_93, FUND_VOL_94, FUND_VOL_95, FUND_VOL_96, FUND_VOL_97, FUND_VOL_98, ",
            "FUND_VOL_99, FUND_VOL_100, FUND_VOL_101, FUND_VOL_102, FUND_VOL_103, FUND_VOL_104, ",
            "FUND_VOL_105, FUND_VOL_106, FUND_VOL_107, FUND_VOL_108, FUND_VOL_109, FUND_VOL_110, ",
            "FUND_VOL_111, FUND_VOL_112, FUND_VOL_113, FUND_VOL_114, FUND_VOL_115, FUND_VOL_116, ",
            "FUND_VOL_117, FUND_VOL_118, FUND_VOL_119, FUND_VOL_120, FUND_VOL_121, FUND_VOL_122, ",
            "FUND_VOL_123, FUND_VOL_124, FUND_VOL_125, FUND_VOL_126, FUND_VOL_127, FUND_VOL_128, ",
            "FUND_VOL_129, FUND_VOL_130, FUND_VOL_131, FUND_VOL_132, FUND_VOL_133, FUND_VOL_134, ",
            "FUND_VOL_135, FUND_VOL_136, FUND_VOL_137, FUND_VOL_138, FUND_VOL_139, FUND_VOL_140, ",
            "FUND_VOL_141, FUND_VOL_142, FUND_VOL_143, FUND_VOL_144, FUND_VOL_145, FUND_VOL_146, ",
            "FUND_VOL_147, FUND_VOL_148, FUND_VOL_149, FUND_VOL_150, FUND_VOL_151, FUND_VOL_152, ",
            "FUND_VOL_153, FUND_VOL_154, FUND_VOL_155, FUND_VOL_156, FUND_VOL_157, FUND_VOL_158, ",
            "FUND_VOL_159, FUND_VOL_160, FUND_VOL_161, FUND_VOL_162, FUND_VOL_163, FUND_VOL_164, ",
            "FUND_VOL_165, FUND_VOL_166, FUND_VOL_167, FUND_VOL_168, FUND_VOL_169, FUND_VOL_170, ",
            "FUND_VOL_171, FUND_VOL_172, FUND_VOL_173, FUND_VOL_174, FUND_VOL_175, FUND_VOL_176, ",
            "FUND_VOL_177, FUND_VOL_178, FUND_VOL_179, FUND_VOL_180, FUND_VOL_181, FUND_VOL_182, ",
            "FUND_VOL_183, FUND_VOL_184, FUND_VOL_185, FUND_VOL_186, FUND_VOL_187, FUND_VOL_188, ",
            "FUND_VOL_189, FUND_VOL_190, FUND_VOL_191, FUND_VOL_192, FUND_VOL_193, FUND_VOL_194, ",
            "FUND_VOL_195, FUND_VOL_196, FUND_VOL_197, FUND_VOL_198, FUND_VOL_199, FUND_VOL_200, ",
            "FUND_VOL_201, FUND_VOL_202, FUND_VOL_203, FUND_VOL_204, FUND_VOL_205, FUND_VOL_206, ",
            "FUND_VOL_207, FUND_VOL_208, FUND_VOL_209, FUND_VOL_210, FUND_VOL_211, FUND_VOL_212, ",
            "FUND_VOL_213, FUND_VOL_214, FUND_VOL_215, FUND_VOL_216, FUND_VOL_217, FUND_VOL_218, ",
            "FUND_VOL_219, FUND_VOL_220, FUND_VOL_221, FUND_VOL_222, FUND_VOL_223, FUND_VOL_224, ",
            "FUND_VOL_225, FUND_VOL_226, FUND_VOL_227, FUND_VOL_228, FUND_VOL_229, FUND_VOL_230, ",
            "FUND_VOL_231, FUND_VOL_232, FUND_VOL_233, FUND_VOL_234, FUND_VOL_235, FUND_VOL_236, ",
            "FUND_VOL_237, FUND_VOL_238, FUND_VOL_239, FUND_VOL_240, FUND_VOL_241, FUND_VOL_242, ",
            "FUND_VOL_243, FUND_VOL_244, FUND_VOL_245, FUND_VOL_246, FUND_VOL_247, FUND_VOL_248, ",
            "FUND_VOL_249, FUND_VOL_250, FUND_VOL_251, FUND_VOL_252, FUND_VOL_253, FUND_VOL_254, ",
            "FUND_VOL_255, FUND_VOL_256, FUND_VOL_257, FUND_VOL_258, FUND_VOL_259, FUND_VOL_260, ",
            "FUND_VOL_261, FUND_VOL_262, FUND_VOL_263, FUND_VOL_264, FUND_VOL_265, FUND_VOL_266, ",
            "FUND_VOL_267, FUND_VOL_268, FUND_VOL_269, FUND_VOL_270, FUND_VOL_271, FUND_VOL_272, ",
            "FUND_VOL_273, FUND_VOL_274, FUND_VOL_275, FUND_VOL_276, FUND_VOL_277, FUND_VOL_278, ",
            "FUND_VOL_279, FUND_VOL_280, FUND_VOL_281, FUND_VOL_282, FUND_VOL_283, FUND_VOL_284, ",
            "FUND_VOL_285, FUND_VOL_286, FUND_VOL_287, FUND_VOL_288",
            "from c_mhai_fundvol_c",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="FUND_VOL_1", property="fundVol1", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_2", property="fundVol2", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_3", property="fundVol3", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_4", property="fundVol4", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_5", property="fundVol5", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_6", property="fundVol6", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_7", property="fundVol7", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_8", property="fundVol8", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_9", property="fundVol9", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_10", property="fundVol10", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_11", property="fundVol11", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_12", property="fundVol12", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_13", property="fundVol13", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_14", property="fundVol14", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_15", property="fundVol15", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_16", property="fundVol16", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_17", property="fundVol17", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_18", property="fundVol18", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_19", property="fundVol19", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_20", property="fundVol20", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_21", property="fundVol21", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_22", property="fundVol22", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_23", property="fundVol23", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_24", property="fundVol24", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_25", property="fundVol25", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_26", property="fundVol26", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_27", property="fundVol27", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_28", property="fundVol28", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_29", property="fundVol29", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_30", property="fundVol30", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_31", property="fundVol31", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_32", property="fundVol32", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_33", property="fundVol33", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_34", property="fundVol34", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_35", property="fundVol35", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_36", property="fundVol36", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_37", property="fundVol37", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_38", property="fundVol38", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_39", property="fundVol39", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_40", property="fundVol40", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_41", property="fundVol41", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_42", property="fundVol42", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_43", property="fundVol43", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_44", property="fundVol44", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_45", property="fundVol45", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_46", property="fundVol46", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_47", property="fundVol47", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_48", property="fundVol48", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_49", property="fundVol49", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_50", property="fundVol50", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_51", property="fundVol51", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_52", property="fundVol52", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_53", property="fundVol53", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_54", property="fundVol54", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_55", property="fundVol55", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_56", property="fundVol56", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_57", property="fundVol57", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_58", property="fundVol58", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_59", property="fundVol59", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_60", property="fundVol60", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_61", property="fundVol61", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_62", property="fundVol62", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_63", property="fundVol63", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_64", property="fundVol64", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_65", property="fundVol65", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_66", property="fundVol66", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_67", property="fundVol67", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_68", property="fundVol68", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_69", property="fundVol69", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_70", property="fundVol70", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_71", property="fundVol71", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_72", property="fundVol72", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_73", property="fundVol73", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_74", property="fundVol74", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_75", property="fundVol75", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_76", property="fundVol76", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_77", property="fundVol77", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_78", property="fundVol78", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_79", property="fundVol79", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_80", property="fundVol80", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_81", property="fundVol81", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_82", property="fundVol82", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_83", property="fundVol83", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_84", property="fundVol84", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_85", property="fundVol85", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_86", property="fundVol86", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_87", property="fundVol87", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_88", property="fundVol88", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_89", property="fundVol89", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_90", property="fundVol90", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_91", property="fundVol91", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_92", property="fundVol92", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_93", property="fundVol93", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_94", property="fundVol94", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_95", property="fundVol95", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_96", property="fundVol96", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_97", property="fundVol97", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_98", property="fundVol98", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_99", property="fundVol99", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_100", property="fundVol100", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_101", property="fundVol101", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_102", property="fundVol102", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_103", property="fundVol103", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_104", property="fundVol104", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_105", property="fundVol105", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_106", property="fundVol106", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_107", property="fundVol107", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_108", property="fundVol108", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_109", property="fundVol109", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_110", property="fundVol110", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_111", property="fundVol111", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_112", property="fundVol112", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_113", property="fundVol113", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_114", property="fundVol114", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_115", property="fundVol115", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_116", property="fundVol116", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_117", property="fundVol117", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_118", property="fundVol118", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_119", property="fundVol119", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_120", property="fundVol120", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_121", property="fundVol121", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_122", property="fundVol122", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_123", property="fundVol123", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_124", property="fundVol124", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_125", property="fundVol125", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_126", property="fundVol126", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_127", property="fundVol127", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_128", property="fundVol128", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_129", property="fundVol129", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_130", property="fundVol130", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_131", property="fundVol131", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_132", property="fundVol132", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_133", property="fundVol133", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_134", property="fundVol134", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_135", property="fundVol135", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_136", property="fundVol136", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_137", property="fundVol137", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_138", property="fundVol138", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_139", property="fundVol139", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_140", property="fundVol140", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_141", property="fundVol141", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_142", property="fundVol142", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_143", property="fundVol143", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_144", property="fundVol144", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_145", property="fundVol145", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_146", property="fundVol146", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_147", property="fundVol147", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_148", property="fundVol148", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_149", property="fundVol149", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_150", property="fundVol150", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_151", property="fundVol151", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_152", property="fundVol152", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_153", property="fundVol153", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_154", property="fundVol154", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_155", property="fundVol155", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_156", property="fundVol156", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_157", property="fundVol157", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_158", property="fundVol158", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_159", property="fundVol159", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_160", property="fundVol160", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_161", property="fundVol161", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_162", property="fundVol162", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_163", property="fundVol163", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_164", property="fundVol164", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_165", property="fundVol165", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_166", property="fundVol166", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_167", property="fundVol167", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_168", property="fundVol168", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_169", property="fundVol169", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_170", property="fundVol170", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_171", property="fundVol171", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_172", property="fundVol172", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_173", property="fundVol173", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_174", property="fundVol174", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_175", property="fundVol175", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_176", property="fundVol176", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_177", property="fundVol177", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_178", property="fundVol178", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_179", property="fundVol179", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_180", property="fundVol180", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_181", property="fundVol181", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_182", property="fundVol182", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_183", property="fundVol183", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_184", property="fundVol184", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_185", property="fundVol185", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_186", property="fundVol186", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_187", property="fundVol187", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_188", property="fundVol188", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_189", property="fundVol189", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_190", property="fundVol190", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_191", property="fundVol191", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_192", property="fundVol192", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_193", property="fundVol193", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_194", property="fundVol194", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_195", property="fundVol195", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_196", property="fundVol196", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_197", property="fundVol197", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_198", property="fundVol198", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_199", property="fundVol199", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_200", property="fundVol200", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_201", property="fundVol201", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_202", property="fundVol202", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_203", property="fundVol203", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_204", property="fundVol204", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_205", property="fundVol205", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_206", property="fundVol206", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_207", property="fundVol207", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_208", property="fundVol208", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_209", property="fundVol209", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_210", property="fundVol210", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_211", property="fundVol211", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_212", property="fundVol212", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_213", property="fundVol213", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_214", property="fundVol214", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_215", property="fundVol215", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_216", property="fundVol216", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_217", property="fundVol217", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_218", property="fundVol218", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_219", property="fundVol219", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_220", property="fundVol220", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_221", property="fundVol221", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_222", property="fundVol222", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_223", property="fundVol223", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_224", property="fundVol224", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_225", property="fundVol225", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_226", property="fundVol226", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_227", property="fundVol227", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_228", property="fundVol228", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_229", property="fundVol229", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_230", property="fundVol230", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_231", property="fundVol231", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_232", property="fundVol232", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_233", property="fundVol233", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_234", property="fundVol234", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_235", property="fundVol235", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_236", property="fundVol236", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_237", property="fundVol237", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_238", property="fundVol238", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_239", property="fundVol239", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_240", property="fundVol240", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_241", property="fundVol241", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_242", property="fundVol242", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_243", property="fundVol243", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_244", property="fundVol244", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_245", property="fundVol245", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_246", property="fundVol246", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_247", property="fundVol247", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_248", property="fundVol248", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_249", property="fundVol249", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_250", property="fundVol250", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_251", property="fundVol251", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_252", property="fundVol252", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_253", property="fundVol253", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_254", property="fundVol254", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_255", property="fundVol255", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_256", property="fundVol256", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_257", property="fundVol257", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_258", property="fundVol258", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_259", property="fundVol259", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_260", property="fundVol260", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_261", property="fundVol261", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_262", property="fundVol262", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_263", property="fundVol263", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_264", property="fundVol264", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_265", property="fundVol265", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_266", property="fundVol266", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_267", property="fundVol267", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_268", property="fundVol268", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_269", property="fundVol269", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_270", property="fundVol270", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_271", property="fundVol271", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_272", property="fundVol272", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_273", property="fundVol273", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_274", property="fundVol274", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_275", property="fundVol275", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_276", property="fundVol276", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_277", property="fundVol277", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_278", property="fundVol278", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_279", property="fundVol279", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_280", property="fundVol280", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_281", property="fundVol281", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_282", property="fundVol282", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_283", property="fundVol283", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_284", property="fundVol284", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_285", property="fundVol285", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_286", property="fundVol286", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_287", property="fundVol287", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_VOL_288", property="fundVol288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_fundVolCurvePo> selectFundCurveBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

}