package com.dao.mapper;

import com.dao.bean.D_fundCurCurvePo;
import com.dao.bean.D_fundCurCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_fundCurCurvePoMapper {

    @Select({
        "select",
        "LD_ID, SYS_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, FUND_CUR_1, ",
        "FUND_CUR_2, FUND_CUR_3, FUND_CUR_4, FUND_CUR_5, FUND_CUR_6, FUND_CUR_7, FUND_CUR_8, ",
        "FUND_CUR_9, FUND_CUR_10, FUND_CUR_11, FUND_CUR_12, FUND_CUR_13, FUND_CUR_14, ",
        "FUND_CUR_15, FUND_CUR_16, FUND_CUR_17, FUND_CUR_18, FUND_CUR_19, FUND_CUR_20, ",
        "FUND_CUR_21, FUND_CUR_22, FUND_CUR_23, FUND_CUR_24, FUND_CUR_25, FUND_CUR_26, ",
        "FUND_CUR_27, FUND_CUR_28, FUND_CUR_29, FUND_CUR_30, FUND_CUR_31, FUND_CUR_32, ",
        "FUND_CUR_33, FUND_CUR_34, FUND_CUR_35, FUND_CUR_36, FUND_CUR_37, FUND_CUR_38, ",
        "FUND_CUR_39, FUND_CUR_40, FUND_CUR_41, FUND_CUR_42, FUND_CUR_43, FUND_CUR_44, ",
        "FUND_CUR_45, FUND_CUR_46, FUND_CUR_47, FUND_CUR_48, FUND_CUR_49, FUND_CUR_50, ",
        "FUND_CUR_51, FUND_CUR_52, FUND_CUR_53, FUND_CUR_54, FUND_CUR_55, FUND_CUR_56, ",
        "FUND_CUR_57, FUND_CUR_58, FUND_CUR_59, FUND_CUR_60, FUND_CUR_61, FUND_CUR_62, ",
        "FUND_CUR_63, FUND_CUR_64, FUND_CUR_65, FUND_CUR_66, FUND_CUR_67, FUND_CUR_68, ",
        "FUND_CUR_69, FUND_CUR_70, FUND_CUR_71, FUND_CUR_72, FUND_CUR_73, FUND_CUR_74, ",
        "FUND_CUR_75, FUND_CUR_76, FUND_CUR_77, FUND_CUR_78, FUND_CUR_79, FUND_CUR_80, ",
        "FUND_CUR_81, FUND_CUR_82, FUND_CUR_83, FUND_CUR_84, FUND_CUR_85, FUND_CUR_86, ",
        "FUND_CUR_87, FUND_CUR_88, FUND_CUR_89, FUND_CUR_90, FUND_CUR_91, FUND_CUR_92, ",
        "FUND_CUR_93, FUND_CUR_94, FUND_CUR_95, FUND_CUR_96, FUND_CUR_97, FUND_CUR_98, ",
        "FUND_CUR_99, FUND_CUR_100, FUND_CUR_101, FUND_CUR_102, FUND_CUR_103, FUND_CUR_104, ",
        "FUND_CUR_105, FUND_CUR_106, FUND_CUR_107, FUND_CUR_108, FUND_CUR_109, FUND_CUR_110, ",
        "FUND_CUR_111, FUND_CUR_112, FUND_CUR_113, FUND_CUR_114, FUND_CUR_115, FUND_CUR_116, ",
        "FUND_CUR_117, FUND_CUR_118, FUND_CUR_119, FUND_CUR_120, FUND_CUR_121, FUND_CUR_122, ",
        "FUND_CUR_123, FUND_CUR_124, FUND_CUR_125, FUND_CUR_126, FUND_CUR_127, FUND_CUR_128, ",
        "FUND_CUR_129, FUND_CUR_130, FUND_CUR_131, FUND_CUR_132, FUND_CUR_133, FUND_CUR_134, ",
        "FUND_CUR_135, FUND_CUR_136, FUND_CUR_137, FUND_CUR_138, FUND_CUR_139, FUND_CUR_140, ",
        "FUND_CUR_141, FUND_CUR_142, FUND_CUR_143, FUND_CUR_144, FUND_CUR_145, FUND_CUR_146, ",
        "FUND_CUR_147, FUND_CUR_148, FUND_CUR_149, FUND_CUR_150, FUND_CUR_151, FUND_CUR_152, ",
        "FUND_CUR_153, FUND_CUR_154, FUND_CUR_155, FUND_CUR_156, FUND_CUR_157, FUND_CUR_158, ",
        "FUND_CUR_159, FUND_CUR_160, FUND_CUR_161, FUND_CUR_162, FUND_CUR_163, FUND_CUR_164, ",
        "FUND_CUR_165, FUND_CUR_166, FUND_CUR_167, FUND_CUR_168, FUND_CUR_169, FUND_CUR_170, ",
        "FUND_CUR_171, FUND_CUR_172, FUND_CUR_173, FUND_CUR_174, FUND_CUR_175, FUND_CUR_176, ",
        "FUND_CUR_177, FUND_CUR_178, FUND_CUR_179, FUND_CUR_180, FUND_CUR_181, FUND_CUR_182, ",
        "FUND_CUR_183, FUND_CUR_184, FUND_CUR_185, FUND_CUR_186, FUND_CUR_187, FUND_CUR_188, ",
        "FUND_CUR_189, FUND_CUR_190, FUND_CUR_191, FUND_CUR_192, FUND_CUR_193, FUND_CUR_194, ",
        "FUND_CUR_195, FUND_CUR_196, FUND_CUR_197, FUND_CUR_198, FUND_CUR_199, FUND_CUR_200, ",
        "FUND_CUR_201, FUND_CUR_202, FUND_CUR_203, FUND_CUR_204, FUND_CUR_205, FUND_CUR_206, ",
        "FUND_CUR_207, FUND_CUR_208, FUND_CUR_209, FUND_CUR_210, FUND_CUR_211, FUND_CUR_212, ",
        "FUND_CUR_213, FUND_CUR_214, FUND_CUR_215, FUND_CUR_216, FUND_CUR_217, FUND_CUR_218, ",
        "FUND_CUR_219, FUND_CUR_220, FUND_CUR_221, FUND_CUR_222, FUND_CUR_223, FUND_CUR_224, ",
        "FUND_CUR_225, FUND_CUR_226, FUND_CUR_227, FUND_CUR_228, FUND_CUR_229, FUND_CUR_230, ",
        "FUND_CUR_231, FUND_CUR_232, FUND_CUR_233, FUND_CUR_234, FUND_CUR_235, FUND_CUR_236, ",
        "FUND_CUR_237, FUND_CUR_238, FUND_CUR_239, FUND_CUR_240, FUND_CUR_241, FUND_CUR_242, ",
        "FUND_CUR_243, FUND_CUR_244, FUND_CUR_245, FUND_CUR_246, FUND_CUR_247, FUND_CUR_248, ",
        "FUND_CUR_249, FUND_CUR_250, FUND_CUR_251, FUND_CUR_252, FUND_CUR_253, FUND_CUR_254, ",
        "FUND_CUR_255, FUND_CUR_256, FUND_CUR_257, FUND_CUR_258, FUND_CUR_259, FUND_CUR_260, ",
        "FUND_CUR_261, FUND_CUR_262, FUND_CUR_263, FUND_CUR_264, FUND_CUR_265, FUND_CUR_266, ",
        "FUND_CUR_267, FUND_CUR_268, FUND_CUR_269, FUND_CUR_270, FUND_CUR_271, FUND_CUR_272, ",
        "FUND_CUR_273, FUND_CUR_274, FUND_CUR_275, FUND_CUR_276, FUND_CUR_277, FUND_CUR_278, ",
        "FUND_CUR_279, FUND_CUR_280, FUND_CUR_281, FUND_CUR_282, FUND_CUR_283, FUND_CUR_284, ",
        "FUND_CUR_285, FUND_CUR_286, FUND_CUR_287, FUND_CUR_288",
        "from c_mhai_fundcur_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="FUND_CUR_1", property="fundCur1", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_2", property="fundCur2", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_3", property="fundCur3", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_4", property="fundCur4", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_5", property="fundCur5", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_6", property="fundCur6", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_7", property="fundCur7", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_8", property="fundCur8", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_9", property="fundCur9", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_10", property="fundCur10", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_11", property="fundCur11", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_12", property="fundCur12", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_13", property="fundCur13", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_14", property="fundCur14", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_15", property="fundCur15", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_16", property="fundCur16", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_17", property="fundCur17", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_18", property="fundCur18", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_19", property="fundCur19", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_20", property="fundCur20", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_21", property="fundCur21", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_22", property="fundCur22", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_23", property="fundCur23", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_24", property="fundCur24", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_25", property="fundCur25", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_26", property="fundCur26", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_27", property="fundCur27", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_28", property="fundCur28", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_29", property="fundCur29", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_30", property="fundCur30", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_31", property="fundCur31", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_32", property="fundCur32", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_33", property="fundCur33", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_34", property="fundCur34", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_35", property="fundCur35", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_36", property="fundCur36", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_37", property="fundCur37", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_38", property="fundCur38", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_39", property="fundCur39", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_40", property="fundCur40", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_41", property="fundCur41", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_42", property="fundCur42", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_43", property="fundCur43", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_44", property="fundCur44", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_45", property="fundCur45", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_46", property="fundCur46", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_47", property="fundCur47", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_48", property="fundCur48", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_49", property="fundCur49", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_50", property="fundCur50", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_51", property="fundCur51", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_52", property="fundCur52", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_53", property="fundCur53", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_54", property="fundCur54", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_55", property="fundCur55", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_56", property="fundCur56", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_57", property="fundCur57", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_58", property="fundCur58", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_59", property="fundCur59", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_60", property="fundCur60", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_61", property="fundCur61", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_62", property="fundCur62", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_63", property="fundCur63", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_64", property="fundCur64", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_65", property="fundCur65", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_66", property="fundCur66", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_67", property="fundCur67", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_68", property="fundCur68", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_69", property="fundCur69", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_70", property="fundCur70", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_71", property="fundCur71", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_72", property="fundCur72", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_73", property="fundCur73", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_74", property="fundCur74", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_75", property="fundCur75", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_76", property="fundCur76", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_77", property="fundCur77", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_78", property="fundCur78", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_79", property="fundCur79", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_80", property="fundCur80", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_81", property="fundCur81", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_82", property="fundCur82", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_83", property="fundCur83", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_84", property="fundCur84", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_85", property="fundCur85", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_86", property="fundCur86", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_87", property="fundCur87", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_88", property="fundCur88", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_89", property="fundCur89", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_90", property="fundCur90", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_91", property="fundCur91", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_92", property="fundCur92", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_93", property="fundCur93", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_94", property="fundCur94", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_95", property="fundCur95", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_96", property="fundCur96", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_97", property="fundCur97", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_98", property="fundCur98", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_99", property="fundCur99", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_100", property="fundCur100", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_101", property="fundCur101", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_102", property="fundCur102", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_103", property="fundCur103", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_104", property="fundCur104", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_105", property="fundCur105", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_106", property="fundCur106", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_107", property="fundCur107", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_108", property="fundCur108", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_109", property="fundCur109", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_110", property="fundCur110", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_111", property="fundCur111", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_112", property="fundCur112", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_113", property="fundCur113", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_114", property="fundCur114", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_115", property="fundCur115", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_116", property="fundCur116", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_117", property="fundCur117", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_118", property="fundCur118", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_119", property="fundCur119", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_120", property="fundCur120", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_121", property="fundCur121", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_122", property="fundCur122", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_123", property="fundCur123", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_124", property="fundCur124", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_125", property="fundCur125", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_126", property="fundCur126", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_127", property="fundCur127", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_128", property="fundCur128", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_129", property="fundCur129", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_130", property="fundCur130", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_131", property="fundCur131", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_132", property="fundCur132", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_133", property="fundCur133", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_134", property="fundCur134", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_135", property="fundCur135", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_136", property="fundCur136", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_137", property="fundCur137", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_138", property="fundCur138", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_139", property="fundCur139", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_140", property="fundCur140", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_141", property="fundCur141", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_142", property="fundCur142", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_143", property="fundCur143", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_144", property="fundCur144", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_145", property="fundCur145", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_146", property="fundCur146", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_147", property="fundCur147", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_148", property="fundCur148", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_149", property="fundCur149", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_150", property="fundCur150", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_151", property="fundCur151", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_152", property="fundCur152", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_153", property="fundCur153", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_154", property="fundCur154", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_155", property="fundCur155", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_156", property="fundCur156", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_157", property="fundCur157", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_158", property="fundCur158", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_159", property="fundCur159", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_160", property="fundCur160", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_161", property="fundCur161", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_162", property="fundCur162", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_163", property="fundCur163", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_164", property="fundCur164", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_165", property="fundCur165", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_166", property="fundCur166", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_167", property="fundCur167", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_168", property="fundCur168", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_169", property="fundCur169", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_170", property="fundCur170", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_171", property="fundCur171", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_172", property="fundCur172", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_173", property="fundCur173", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_174", property="fundCur174", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_175", property="fundCur175", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_176", property="fundCur176", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_177", property="fundCur177", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_178", property="fundCur178", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_179", property="fundCur179", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_180", property="fundCur180", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_181", property="fundCur181", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_182", property="fundCur182", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_183", property="fundCur183", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_184", property="fundCur184", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_185", property="fundCur185", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_186", property="fundCur186", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_187", property="fundCur187", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_188", property="fundCur188", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_189", property="fundCur189", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_190", property="fundCur190", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_191", property="fundCur191", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_192", property="fundCur192", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_193", property="fundCur193", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_194", property="fundCur194", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_195", property="fundCur195", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_196", property="fundCur196", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_197", property="fundCur197", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_198", property="fundCur198", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_199", property="fundCur199", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_200", property="fundCur200", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_201", property="fundCur201", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_202", property="fundCur202", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_203", property="fundCur203", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_204", property="fundCur204", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_205", property="fundCur205", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_206", property="fundCur206", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_207", property="fundCur207", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_208", property="fundCur208", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_209", property="fundCur209", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_210", property="fundCur210", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_211", property="fundCur211", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_212", property="fundCur212", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_213", property="fundCur213", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_214", property="fundCur214", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_215", property="fundCur215", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_216", property="fundCur216", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_217", property="fundCur217", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_218", property="fundCur218", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_219", property="fundCur219", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_220", property="fundCur220", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_221", property="fundCur221", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_222", property="fundCur222", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_223", property="fundCur223", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_224", property="fundCur224", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_225", property="fundCur225", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_226", property="fundCur226", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_227", property="fundCur227", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_228", property="fundCur228", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_229", property="fundCur229", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_230", property="fundCur230", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_231", property="fundCur231", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_232", property="fundCur232", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_233", property="fundCur233", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_234", property="fundCur234", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_235", property="fundCur235", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_236", property="fundCur236", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_237", property="fundCur237", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_238", property="fundCur238", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_239", property="fundCur239", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_240", property="fundCur240", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_241", property="fundCur241", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_242", property="fundCur242", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_243", property="fundCur243", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_244", property="fundCur244", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_245", property="fundCur245", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_246", property="fundCur246", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_247", property="fundCur247", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_248", property="fundCur248", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_249", property="fundCur249", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_250", property="fundCur250", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_251", property="fundCur251", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_252", property="fundCur252", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_253", property="fundCur253", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_254", property="fundCur254", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_255", property="fundCur255", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_256", property="fundCur256", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_257", property="fundCur257", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_258", property="fundCur258", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_259", property="fundCur259", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_260", property="fundCur260", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_261", property="fundCur261", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_262", property="fundCur262", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_263", property="fundCur263", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_264", property="fundCur264", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_265", property="fundCur265", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_266", property="fundCur266", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_267", property="fundCur267", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_268", property="fundCur268", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_269", property="fundCur269", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_270", property="fundCur270", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_271", property="fundCur271", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_272", property="fundCur272", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_273", property="fundCur273", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_274", property="fundCur274", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_275", property="fundCur275", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_276", property="fundCur276", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_277", property="fundCur277", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_278", property="fundCur278", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_279", property="fundCur279", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_280", property="fundCur280", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_281", property="fundCur281", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_282", property="fundCur282", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_283", property="fundCur283", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_284", property="fundCur284", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_285", property="fundCur285", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_286", property="fundCur286", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_287", property="fundCur287", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUND_CUR_288", property="fundCur288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_fundCurCurvePo> selectFundCurByDate(String data_date);

    @Select({
            "select",
            "LD_ID, SYS_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, FUND_CUR_1, ",
            "FUND_CUR_2, FUND_CUR_3, FUND_CUR_4, FUND_CUR_5, FUND_CUR_6, FUND_CUR_7, FUND_CUR_8, ",
            "FUND_CUR_9, FUND_CUR_10, FUND_CUR_11, FUND_CUR_12, FUND_CUR_13, FUND_CUR_14, ",
            "FUND_CUR_15, FUND_CUR_16, FUND_CUR_17, FUND_CUR_18, FUND_CUR_19, FUND_CUR_20, ",
            "FUND_CUR_21, FUND_CUR_22, FUND_CUR_23, FUND_CUR_24, FUND_CUR_25, FUND_CUR_26, ",
            "FUND_CUR_27, FUND_CUR_28, FUND_CUR_29, FUND_CUR_30, FUND_CUR_31, FUND_CUR_32, ",
            "FUND_CUR_33, FUND_CUR_34, FUND_CUR_35, FUND_CUR_36, FUND_CUR_37, FUND_CUR_38, ",
            "FUND_CUR_39, FUND_CUR_40, FUND_CUR_41, FUND_CUR_42, FUND_CUR_43, FUND_CUR_44, ",
            "FUND_CUR_45, FUND_CUR_46, FUND_CUR_47, FUND_CUR_48, FUND_CUR_49, FUND_CUR_50, ",
            "FUND_CUR_51, FUND_CUR_52, FUND_CUR_53, FUND_CUR_54, FUND_CUR_55, FUND_CUR_56, ",
            "FUND_CUR_57, FUND_CUR_58, FUND_CUR_59, FUND_CUR_60, FUND_CUR_61, FUND_CUR_62, ",
            "FUND_CUR_63, FUND_CUR_64, FUND_CUR_65, FUND_CUR_66, FUND_CUR_67, FUND_CUR_68, ",
            "FUND_CUR_69, FUND_CUR_70, FUND_CUR_71, FUND_CUR_72, FUND_CUR_73, FUND_CUR_74, ",
            "FUND_CUR_75, FUND_CUR_76, FUND_CUR_77, FUND_CUR_78, FUND_CUR_79, FUND_CUR_80, ",
            "FUND_CUR_81, FUND_CUR_82, FUND_CUR_83, FUND_CUR_84, FUND_CUR_85, FUND_CUR_86, ",
            "FUND_CUR_87, FUND_CUR_88, FUND_CUR_89, FUND_CUR_90, FUND_CUR_91, FUND_CUR_92, ",
            "FUND_CUR_93, FUND_CUR_94, FUND_CUR_95, FUND_CUR_96, FUND_CUR_97, FUND_CUR_98, ",
            "FUND_CUR_99, FUND_CUR_100, FUND_CUR_101, FUND_CUR_102, FUND_CUR_103, FUND_CUR_104, ",
            "FUND_CUR_105, FUND_CUR_106, FUND_CUR_107, FUND_CUR_108, FUND_CUR_109, FUND_CUR_110, ",
            "FUND_CUR_111, FUND_CUR_112, FUND_CUR_113, FUND_CUR_114, FUND_CUR_115, FUND_CUR_116, ",
            "FUND_CUR_117, FUND_CUR_118, FUND_CUR_119, FUND_CUR_120, FUND_CUR_121, FUND_CUR_122, ",
            "FUND_CUR_123, FUND_CUR_124, FUND_CUR_125, FUND_CUR_126, FUND_CUR_127, FUND_CUR_128, ",
            "FUND_CUR_129, FUND_CUR_130, FUND_CUR_131, FUND_CUR_132, FUND_CUR_133, FUND_CUR_134, ",
            "FUND_CUR_135, FUND_CUR_136, FUND_CUR_137, FUND_CUR_138, FUND_CUR_139, FUND_CUR_140, ",
            "FUND_CUR_141, FUND_CUR_142, FUND_CUR_143, FUND_CUR_144, FUND_CUR_145, FUND_CUR_146, ",
            "FUND_CUR_147, FUND_CUR_148, FUND_CUR_149, FUND_CUR_150, FUND_CUR_151, FUND_CUR_152, ",
            "FUND_CUR_153, FUND_CUR_154, FUND_CUR_155, FUND_CUR_156, FUND_CUR_157, FUND_CUR_158, ",
            "FUND_CUR_159, FUND_CUR_160, FUND_CUR_161, FUND_CUR_162, FUND_CUR_163, FUND_CUR_164, ",
            "FUND_CUR_165, FUND_CUR_166, FUND_CUR_167, FUND_CUR_168, FUND_CUR_169, FUND_CUR_170, ",
            "FUND_CUR_171, FUND_CUR_172, FUND_CUR_173, FUND_CUR_174, FUND_CUR_175, FUND_CUR_176, ",
            "FUND_CUR_177, FUND_CUR_178, FUND_CUR_179, FUND_CUR_180, FUND_CUR_181, FUND_CUR_182, ",
            "FUND_CUR_183, FUND_CUR_184, FUND_CUR_185, FUND_CUR_186, FUND_CUR_187, FUND_CUR_188, ",
            "FUND_CUR_189, FUND_CUR_190, FUND_CUR_191, FUND_CUR_192, FUND_CUR_193, FUND_CUR_194, ",
            "FUND_CUR_195, FUND_CUR_196, FUND_CUR_197, FUND_CUR_198, FUND_CUR_199, FUND_CUR_200, ",
            "FUND_CUR_201, FUND_CUR_202, FUND_CUR_203, FUND_CUR_204, FUND_CUR_205, FUND_CUR_206, ",
            "FUND_CUR_207, FUND_CUR_208, FUND_CUR_209, FUND_CUR_210, FUND_CUR_211, FUND_CUR_212, ",
            "FUND_CUR_213, FUND_CUR_214, FUND_CUR_215, FUND_CUR_216, FUND_CUR_217, FUND_CUR_218, ",
            "FUND_CUR_219, FUND_CUR_220, FUND_CUR_221, FUND_CUR_222, FUND_CUR_223, FUND_CUR_224, ",
            "FUND_CUR_225, FUND_CUR_226, FUND_CUR_227, FUND_CUR_228, FUND_CUR_229, FUND_CUR_230, ",
            "FUND_CUR_231, FUND_CUR_232, FUND_CUR_233, FUND_CUR_234, FUND_CUR_235, FUND_CUR_236, ",
            "FUND_CUR_237, FUND_CUR_238, FUND_CUR_239, FUND_CUR_240, FUND_CUR_241, FUND_CUR_242, ",
            "FUND_CUR_243, FUND_CUR_244, FUND_CUR_245, FUND_CUR_246, FUND_CUR_247, FUND_CUR_248, ",
            "FUND_CUR_249, FUND_CUR_250, FUND_CUR_251, FUND_CUR_252, FUND_CUR_253, FUND_CUR_254, ",
            "FUND_CUR_255, FUND_CUR_256, FUND_CUR_257, FUND_CUR_258, FUND_CUR_259, FUND_CUR_260, ",
            "FUND_CUR_261, FUND_CUR_262, FUND_CUR_263, FUND_CUR_264, FUND_CUR_265, FUND_CUR_266, ",
            "FUND_CUR_267, FUND_CUR_268, FUND_CUR_269, FUND_CUR_270, FUND_CUR_271, FUND_CUR_272, ",
            "FUND_CUR_273, FUND_CUR_274, FUND_CUR_275, FUND_CUR_276, FUND_CUR_277, FUND_CUR_278, ",
            "FUND_CUR_279, FUND_CUR_280, FUND_CUR_281, FUND_CUR_282, FUND_CUR_283, FUND_CUR_284, ",
            "FUND_CUR_285, FUND_CUR_286, FUND_CUR_287, FUND_CUR_288",
            "from c_mhai_fundcur_c",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="FUND_CUR_1", property="fundCur1", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_2", property="fundCur2", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_3", property="fundCur3", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_4", property="fundCur4", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_5", property="fundCur5", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_6", property="fundCur6", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_7", property="fundCur7", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_8", property="fundCur8", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_9", property="fundCur9", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_10", property="fundCur10", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_11", property="fundCur11", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_12", property="fundCur12", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_13", property="fundCur13", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_14", property="fundCur14", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_15", property="fundCur15", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_16", property="fundCur16", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_17", property="fundCur17", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_18", property="fundCur18", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_19", property="fundCur19", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_20", property="fundCur20", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_21", property="fundCur21", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_22", property="fundCur22", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_23", property="fundCur23", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_24", property="fundCur24", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_25", property="fundCur25", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_26", property="fundCur26", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_27", property="fundCur27", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_28", property="fundCur28", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_29", property="fundCur29", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_30", property="fundCur30", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_31", property="fundCur31", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_32", property="fundCur32", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_33", property="fundCur33", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_34", property="fundCur34", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_35", property="fundCur35", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_36", property="fundCur36", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_37", property="fundCur37", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_38", property="fundCur38", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_39", property="fundCur39", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_40", property="fundCur40", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_41", property="fundCur41", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_42", property="fundCur42", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_43", property="fundCur43", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_44", property="fundCur44", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_45", property="fundCur45", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_46", property="fundCur46", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_47", property="fundCur47", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_48", property="fundCur48", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_49", property="fundCur49", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_50", property="fundCur50", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_51", property="fundCur51", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_52", property="fundCur52", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_53", property="fundCur53", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_54", property="fundCur54", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_55", property="fundCur55", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_56", property="fundCur56", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_57", property="fundCur57", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_58", property="fundCur58", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_59", property="fundCur59", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_60", property="fundCur60", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_61", property="fundCur61", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_62", property="fundCur62", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_63", property="fundCur63", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_64", property="fundCur64", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_65", property="fundCur65", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_66", property="fundCur66", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_67", property="fundCur67", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_68", property="fundCur68", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_69", property="fundCur69", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_70", property="fundCur70", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_71", property="fundCur71", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_72", property="fundCur72", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_73", property="fundCur73", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_74", property="fundCur74", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_75", property="fundCur75", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_76", property="fundCur76", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_77", property="fundCur77", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_78", property="fundCur78", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_79", property="fundCur79", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_80", property="fundCur80", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_81", property="fundCur81", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_82", property="fundCur82", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_83", property="fundCur83", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_84", property="fundCur84", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_85", property="fundCur85", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_86", property="fundCur86", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_87", property="fundCur87", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_88", property="fundCur88", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_89", property="fundCur89", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_90", property="fundCur90", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_91", property="fundCur91", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_92", property="fundCur92", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_93", property="fundCur93", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_94", property="fundCur94", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_95", property="fundCur95", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_96", property="fundCur96", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_97", property="fundCur97", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_98", property="fundCur98", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_99", property="fundCur99", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_100", property="fundCur100", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_101", property="fundCur101", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_102", property="fundCur102", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_103", property="fundCur103", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_104", property="fundCur104", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_105", property="fundCur105", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_106", property="fundCur106", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_107", property="fundCur107", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_108", property="fundCur108", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_109", property="fundCur109", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_110", property="fundCur110", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_111", property="fundCur111", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_112", property="fundCur112", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_113", property="fundCur113", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_114", property="fundCur114", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_115", property="fundCur115", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_116", property="fundCur116", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_117", property="fundCur117", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_118", property="fundCur118", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_119", property="fundCur119", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_120", property="fundCur120", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_121", property="fundCur121", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_122", property="fundCur122", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_123", property="fundCur123", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_124", property="fundCur124", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_125", property="fundCur125", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_126", property="fundCur126", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_127", property="fundCur127", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_128", property="fundCur128", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_129", property="fundCur129", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_130", property="fundCur130", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_131", property="fundCur131", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_132", property="fundCur132", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_133", property="fundCur133", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_134", property="fundCur134", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_135", property="fundCur135", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_136", property="fundCur136", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_137", property="fundCur137", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_138", property="fundCur138", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_139", property="fundCur139", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_140", property="fundCur140", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_141", property="fundCur141", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_142", property="fundCur142", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_143", property="fundCur143", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_144", property="fundCur144", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_145", property="fundCur145", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_146", property="fundCur146", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_147", property="fundCur147", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_148", property="fundCur148", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_149", property="fundCur149", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_150", property="fundCur150", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_151", property="fundCur151", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_152", property="fundCur152", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_153", property="fundCur153", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_154", property="fundCur154", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_155", property="fundCur155", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_156", property="fundCur156", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_157", property="fundCur157", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_158", property="fundCur158", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_159", property="fundCur159", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_160", property="fundCur160", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_161", property="fundCur161", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_162", property="fundCur162", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_163", property="fundCur163", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_164", property="fundCur164", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_165", property="fundCur165", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_166", property="fundCur166", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_167", property="fundCur167", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_168", property="fundCur168", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_169", property="fundCur169", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_170", property="fundCur170", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_171", property="fundCur171", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_172", property="fundCur172", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_173", property="fundCur173", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_174", property="fundCur174", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_175", property="fundCur175", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_176", property="fundCur176", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_177", property="fundCur177", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_178", property="fundCur178", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_179", property="fundCur179", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_180", property="fundCur180", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_181", property="fundCur181", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_182", property="fundCur182", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_183", property="fundCur183", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_184", property="fundCur184", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_185", property="fundCur185", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_186", property="fundCur186", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_187", property="fundCur187", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_188", property="fundCur188", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_189", property="fundCur189", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_190", property="fundCur190", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_191", property="fundCur191", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_192", property="fundCur192", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_193", property="fundCur193", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_194", property="fundCur194", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_195", property="fundCur195", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_196", property="fundCur196", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_197", property="fundCur197", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_198", property="fundCur198", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_199", property="fundCur199", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_200", property="fundCur200", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_201", property="fundCur201", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_202", property="fundCur202", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_203", property="fundCur203", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_204", property="fundCur204", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_205", property="fundCur205", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_206", property="fundCur206", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_207", property="fundCur207", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_208", property="fundCur208", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_209", property="fundCur209", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_210", property="fundCur210", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_211", property="fundCur211", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_212", property="fundCur212", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_213", property="fundCur213", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_214", property="fundCur214", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_215", property="fundCur215", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_216", property="fundCur216", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_217", property="fundCur217", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_218", property="fundCur218", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_219", property="fundCur219", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_220", property="fundCur220", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_221", property="fundCur221", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_222", property="fundCur222", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_223", property="fundCur223", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_224", property="fundCur224", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_225", property="fundCur225", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_226", property="fundCur226", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_227", property="fundCur227", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_228", property="fundCur228", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_229", property="fundCur229", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_230", property="fundCur230", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_231", property="fundCur231", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_232", property="fundCur232", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_233", property="fundCur233", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_234", property="fundCur234", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_235", property="fundCur235", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_236", property="fundCur236", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_237", property="fundCur237", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_238", property="fundCur238", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_239", property="fundCur239", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_240", property="fundCur240", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_241", property="fundCur241", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_242", property="fundCur242", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_243", property="fundCur243", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_244", property="fundCur244", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_245", property="fundCur245", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_246", property="fundCur246", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_247", property="fundCur247", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_248", property="fundCur248", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_249", property="fundCur249", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_250", property="fundCur250", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_251", property="fundCur251", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_252", property="fundCur252", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_253", property="fundCur253", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_254", property="fundCur254", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_255", property="fundCur255", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_256", property="fundCur256", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_257", property="fundCur257", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_258", property="fundCur258", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_259", property="fundCur259", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_260", property="fundCur260", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_261", property="fundCur261", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_262", property="fundCur262", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_263", property="fundCur263", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_264", property="fundCur264", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_265", property="fundCur265", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_266", property="fundCur266", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_267", property="fundCur267", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_268", property="fundCur268", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_269", property="fundCur269", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_270", property="fundCur270", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_271", property="fundCur271", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_272", property="fundCur272", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_273", property="fundCur273", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_274", property="fundCur274", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_275", property="fundCur275", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_276", property="fundCur276", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_277", property="fundCur277", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_278", property="fundCur278", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_279", property="fundCur279", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_280", property="fundCur280", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_281", property="fundCur281", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_282", property="fundCur282", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_283", property="fundCur283", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_284", property="fundCur284", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_285", property="fundCur285", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_286", property="fundCur286", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_287", property="fundCur287", jdbcType=JdbcType.DECIMAL),
            @Result(column="FUND_CUR_288", property="fundCur288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_fundCurCurvePo> selectFundCurBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);
}