package com.dao.mapper;

import com.dao.bean.D_iUnbalanceCurvePo;
import com.dao.bean.D_iUnbalanceCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_iUnbalanceCurvePoMapper {

    @Select({
        "select",
        "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, I_UNBALANCE_1, ",
        "I_UNBALANCE_2, I_UNBALANCE_3, I_UNBALANCE_4, I_UNBALANCE_5, I_UNBALANCE_6, I_UNBALANCE_7, ",
        "I_UNBALANCE_8, I_UNBALANCE_9, I_UNBALANCE_10, I_UNBALANCE_11, I_UNBALANCE_12, ",
        "I_UNBALANCE_13, I_UNBALANCE_14, I_UNBALANCE_15, I_UNBALANCE_16, I_UNBALANCE_17, ",
        "I_UNBALANCE_18, I_UNBALANCE_19, I_UNBALANCE_20, I_UNBALANCE_21, I_UNBALANCE_22, ",
        "I_UNBALANCE_23, I_UNBALANCE_24, I_UNBALANCE_25, I_UNBALANCE_26, I_UNBALANCE_27, ",
        "I_UNBALANCE_28, I_UNBALANCE_29, I_UNBALANCE_30, I_UNBALANCE_31, I_UNBALANCE_32, ",
        "I_UNBALANCE_33, I_UNBALANCE_34, I_UNBALANCE_35, I_UNBALANCE_36, I_UNBALANCE_37, ",
        "I_UNBALANCE_38, I_UNBALANCE_39, I_UNBALANCE_40, I_UNBALANCE_41, I_UNBALANCE_42, ",
        "I_UNBALANCE_43, I_UNBALANCE_44, I_UNBALANCE_45, I_UNBALANCE_46, I_UNBALANCE_47, ",
        "I_UNBALANCE_48, I_UNBALANCE_49, I_UNBALANCE_50, I_UNBALANCE_51, I_UNBALANCE_52, ",
        "I_UNBALANCE_53, I_UNBALANCE_54, I_UNBALANCE_55, I_UNBALANCE_56, I_UNBALANCE_57, ",
        "I_UNBALANCE_58, I_UNBALANCE_59, I_UNBALANCE_60, I_UNBALANCE_61, I_UNBALANCE_62, ",
        "I_UNBALANCE_63, I_UNBALANCE_64, I_UNBALANCE_65, I_UNBALANCE_66, I_UNBALANCE_67, ",
        "I_UNBALANCE_68, I_UNBALANCE_69, I_UNBALANCE_70, I_UNBALANCE_71, I_UNBALANCE_72, ",
        "I_UNBALANCE_73, I_UNBALANCE_74, I_UNBALANCE_75, I_UNBALANCE_76, I_UNBALANCE_77, ",
        "I_UNBALANCE_78, I_UNBALANCE_79, I_UNBALANCE_80, I_UNBALANCE_81, I_UNBALANCE_82, ",
        "I_UNBALANCE_83, I_UNBALANCE_84, I_UNBALANCE_85, I_UNBALANCE_86, I_UNBALANCE_87, ",
        "I_UNBALANCE_88, I_UNBALANCE_89, I_UNBALANCE_90, I_UNBALANCE_91, I_UNBALANCE_92, ",
        "I_UNBALANCE_93, I_UNBALANCE_94, I_UNBALANCE_95, I_UNBALANCE_96, I_UNBALANCE_97, ",
        "I_UNBALANCE_98, I_UNBALANCE_99, I_UNBALANCE_100, I_UNBALANCE_101, I_UNBALANCE_102, ",
        "I_UNBALANCE_103, I_UNBALANCE_104, I_UNBALANCE_105, I_UNBALANCE_106, I_UNBALANCE_107, ",
        "I_UNBALANCE_108, I_UNBALANCE_109, I_UNBALANCE_110, I_UNBALANCE_111, I_UNBALANCE_112, ",
        "I_UNBALANCE_113, I_UNBALANCE_114, I_UNBALANCE_115, I_UNBALANCE_116, I_UNBALANCE_117, ",
        "I_UNBALANCE_118, I_UNBALANCE_119, I_UNBALANCE_120, I_UNBALANCE_121, I_UNBALANCE_122, ",
        "I_UNBALANCE_123, I_UNBALANCE_124, I_UNBALANCE_125, I_UNBALANCE_126, I_UNBALANCE_127, ",
        "I_UNBALANCE_128, I_UNBALANCE_129, I_UNBALANCE_130, I_UNBALANCE_131, I_UNBALANCE_132, ",
        "I_UNBALANCE_133, I_UNBALANCE_134, I_UNBALANCE_135, I_UNBALANCE_136, I_UNBALANCE_137, ",
        "I_UNBALANCE_138, I_UNBALANCE_139, I_UNBALANCE_140, I_UNBALANCE_141, I_UNBALANCE_142, ",
        "I_UNBALANCE_143, I_UNBALANCE_144, I_UNBALANCE_145, I_UNBALANCE_146, I_UNBALANCE_147, ",
        "I_UNBALANCE_148, I_UNBALANCE_149, I_UNBALANCE_150, I_UNBALANCE_151, I_UNBALANCE_152, ",
        "I_UNBALANCE_153, I_UNBALANCE_154, I_UNBALANCE_155, I_UNBALANCE_156, I_UNBALANCE_157, ",
        "I_UNBALANCE_158, I_UNBALANCE_159, I_UNBALANCE_160, I_UNBALANCE_161, I_UNBALANCE_162, ",
        "I_UNBALANCE_163, I_UNBALANCE_164, I_UNBALANCE_165, I_UNBALANCE_166, I_UNBALANCE_167, ",
        "I_UNBALANCE_168, I_UNBALANCE_169, I_UNBALANCE_170, I_UNBALANCE_171, I_UNBALANCE_172, ",
        "I_UNBALANCE_173, I_UNBALANCE_174, I_UNBALANCE_175, I_UNBALANCE_176, I_UNBALANCE_177, ",
        "I_UNBALANCE_178, I_UNBALANCE_179, I_UNBALANCE_180, I_UNBALANCE_181, I_UNBALANCE_182, ",
        "I_UNBALANCE_183, I_UNBALANCE_184, I_UNBALANCE_185, I_UNBALANCE_186, I_UNBALANCE_187, ",
        "I_UNBALANCE_188, I_UNBALANCE_189, I_UNBALANCE_190, I_UNBALANCE_191, I_UNBALANCE_192, ",
        "I_UNBALANCE_193, I_UNBALANCE_194, I_UNBALANCE_195, I_UNBALANCE_196, I_UNBALANCE_197, ",
        "I_UNBALANCE_198, I_UNBALANCE_199, I_UNBALANCE_200, I_UNBALANCE_201, I_UNBALANCE_202, ",
        "I_UNBALANCE_203, I_UNBALANCE_204, I_UNBALANCE_205, I_UNBALANCE_206, I_UNBALANCE_207, ",
        "I_UNBALANCE_208, I_UNBALANCE_209, I_UNBALANCE_210, I_UNBALANCE_211, I_UNBALANCE_212, ",
        "I_UNBALANCE_213, I_UNBALANCE_214, I_UNBALANCE_215, I_UNBALANCE_216, I_UNBALANCE_217, ",
        "I_UNBALANCE_218, I_UNBALANCE_219, I_UNBALANCE_220, I_UNBALANCE_221, I_UNBALANCE_222, ",
        "I_UNBALANCE_223, I_UNBALANCE_224, I_UNBALANCE_225, I_UNBALANCE_226, I_UNBALANCE_227, ",
        "I_UNBALANCE_228, I_UNBALANCE_229, I_UNBALANCE_230, I_UNBALANCE_231, I_UNBALANCE_232, ",
        "I_UNBALANCE_233, I_UNBALANCE_234, I_UNBALANCE_235, I_UNBALANCE_236, I_UNBALANCE_237, ",
        "I_UNBALANCE_238, I_UNBALANCE_239, I_UNBALANCE_240, I_UNBALANCE_241, I_UNBALANCE_242, ",
        "I_UNBALANCE_243, I_UNBALANCE_244, I_UNBALANCE_245, I_UNBALANCE_246, I_UNBALANCE_247, ",
        "I_UNBALANCE_248, I_UNBALANCE_249, I_UNBALANCE_250, I_UNBALANCE_251, I_UNBALANCE_252, ",
        "I_UNBALANCE_253, I_UNBALANCE_254, I_UNBALANCE_255, I_UNBALANCE_256, I_UNBALANCE_257, ",
        "I_UNBALANCE_258, I_UNBALANCE_259, I_UNBALANCE_260, I_UNBALANCE_261, I_UNBALANCE_262, ",
        "I_UNBALANCE_263, I_UNBALANCE_264, I_UNBALANCE_265, I_UNBALANCE_266, I_UNBALANCE_267, ",
        "I_UNBALANCE_268, I_UNBALANCE_269, I_UNBALANCE_270, I_UNBALANCE_271, I_UNBALANCE_272, ",
        "I_UNBALANCE_273, I_UNBALANCE_274, I_UNBALANCE_275, I_UNBALANCE_276, I_UNBALANCE_277, ",
        "I_UNBALANCE_278, I_UNBALANCE_279, I_UNBALANCE_280, I_UNBALANCE_281, I_UNBALANCE_282, ",
        "I_UNBALANCE_283, I_UNBALANCE_284, I_UNBALANCE_285, I_UNBALANCE_286, I_UNBALANCE_287, ",
        "I_UNBALANCE_288",
        "from c_msqi_i_unbalance_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="I_UNBALANCE_1", property="iUnbalance1", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_2", property="iUnbalance2", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_3", property="iUnbalance3", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_4", property="iUnbalance4", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_5", property="iUnbalance5", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_6", property="iUnbalance6", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_7", property="iUnbalance7", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_8", property="iUnbalance8", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_9", property="iUnbalance9", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_10", property="iUnbalance10", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_11", property="iUnbalance11", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_12", property="iUnbalance12", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_13", property="iUnbalance13", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_14", property="iUnbalance14", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_15", property="iUnbalance15", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_16", property="iUnbalance16", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_17", property="iUnbalance17", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_18", property="iUnbalance18", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_19", property="iUnbalance19", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_20", property="iUnbalance20", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_21", property="iUnbalance21", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_22", property="iUnbalance22", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_23", property="iUnbalance23", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_24", property="iUnbalance24", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_25", property="iUnbalance25", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_26", property="iUnbalance26", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_27", property="iUnbalance27", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_28", property="iUnbalance28", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_29", property="iUnbalance29", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_30", property="iUnbalance30", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_31", property="iUnbalance31", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_32", property="iUnbalance32", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_33", property="iUnbalance33", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_34", property="iUnbalance34", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_35", property="iUnbalance35", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_36", property="iUnbalance36", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_37", property="iUnbalance37", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_38", property="iUnbalance38", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_39", property="iUnbalance39", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_40", property="iUnbalance40", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_41", property="iUnbalance41", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_42", property="iUnbalance42", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_43", property="iUnbalance43", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_44", property="iUnbalance44", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_45", property="iUnbalance45", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_46", property="iUnbalance46", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_47", property="iUnbalance47", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_48", property="iUnbalance48", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_49", property="iUnbalance49", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_50", property="iUnbalance50", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_51", property="iUnbalance51", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_52", property="iUnbalance52", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_53", property="iUnbalance53", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_54", property="iUnbalance54", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_55", property="iUnbalance55", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_56", property="iUnbalance56", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_57", property="iUnbalance57", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_58", property="iUnbalance58", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_59", property="iUnbalance59", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_60", property="iUnbalance60", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_61", property="iUnbalance61", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_62", property="iUnbalance62", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_63", property="iUnbalance63", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_64", property="iUnbalance64", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_65", property="iUnbalance65", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_66", property="iUnbalance66", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_67", property="iUnbalance67", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_68", property="iUnbalance68", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_69", property="iUnbalance69", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_70", property="iUnbalance70", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_71", property="iUnbalance71", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_72", property="iUnbalance72", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_73", property="iUnbalance73", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_74", property="iUnbalance74", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_75", property="iUnbalance75", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_76", property="iUnbalance76", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_77", property="iUnbalance77", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_78", property="iUnbalance78", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_79", property="iUnbalance79", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_80", property="iUnbalance80", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_81", property="iUnbalance81", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_82", property="iUnbalance82", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_83", property="iUnbalance83", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_84", property="iUnbalance84", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_85", property="iUnbalance85", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_86", property="iUnbalance86", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_87", property="iUnbalance87", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_88", property="iUnbalance88", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_89", property="iUnbalance89", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_90", property="iUnbalance90", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_91", property="iUnbalance91", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_92", property="iUnbalance92", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_93", property="iUnbalance93", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_94", property="iUnbalance94", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_95", property="iUnbalance95", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_96", property="iUnbalance96", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_97", property="iUnbalance97", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_98", property="iUnbalance98", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_99", property="iUnbalance99", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_100", property="iUnbalance100", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_101", property="iUnbalance101", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_102", property="iUnbalance102", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_103", property="iUnbalance103", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_104", property="iUnbalance104", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_105", property="iUnbalance105", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_106", property="iUnbalance106", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_107", property="iUnbalance107", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_108", property="iUnbalance108", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_109", property="iUnbalance109", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_110", property="iUnbalance110", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_111", property="iUnbalance111", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_112", property="iUnbalance112", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_113", property="iUnbalance113", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_114", property="iUnbalance114", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_115", property="iUnbalance115", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_116", property="iUnbalance116", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_117", property="iUnbalance117", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_118", property="iUnbalance118", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_119", property="iUnbalance119", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_120", property="iUnbalance120", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_121", property="iUnbalance121", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_122", property="iUnbalance122", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_123", property="iUnbalance123", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_124", property="iUnbalance124", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_125", property="iUnbalance125", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_126", property="iUnbalance126", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_127", property="iUnbalance127", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_128", property="iUnbalance128", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_129", property="iUnbalance129", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_130", property="iUnbalance130", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_131", property="iUnbalance131", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_132", property="iUnbalance132", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_133", property="iUnbalance133", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_134", property="iUnbalance134", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_135", property="iUnbalance135", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_136", property="iUnbalance136", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_137", property="iUnbalance137", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_138", property="iUnbalance138", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_139", property="iUnbalance139", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_140", property="iUnbalance140", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_141", property="iUnbalance141", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_142", property="iUnbalance142", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_143", property="iUnbalance143", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_144", property="iUnbalance144", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_145", property="iUnbalance145", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_146", property="iUnbalance146", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_147", property="iUnbalance147", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_148", property="iUnbalance148", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_149", property="iUnbalance149", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_150", property="iUnbalance150", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_151", property="iUnbalance151", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_152", property="iUnbalance152", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_153", property="iUnbalance153", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_154", property="iUnbalance154", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_155", property="iUnbalance155", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_156", property="iUnbalance156", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_157", property="iUnbalance157", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_158", property="iUnbalance158", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_159", property="iUnbalance159", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_160", property="iUnbalance160", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_161", property="iUnbalance161", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_162", property="iUnbalance162", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_163", property="iUnbalance163", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_164", property="iUnbalance164", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_165", property="iUnbalance165", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_166", property="iUnbalance166", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_167", property="iUnbalance167", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_168", property="iUnbalance168", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_169", property="iUnbalance169", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_170", property="iUnbalance170", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_171", property="iUnbalance171", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_172", property="iUnbalance172", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_173", property="iUnbalance173", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_174", property="iUnbalance174", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_175", property="iUnbalance175", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_176", property="iUnbalance176", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_177", property="iUnbalance177", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_178", property="iUnbalance178", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_179", property="iUnbalance179", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_180", property="iUnbalance180", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_181", property="iUnbalance181", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_182", property="iUnbalance182", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_183", property="iUnbalance183", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_184", property="iUnbalance184", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_185", property="iUnbalance185", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_186", property="iUnbalance186", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_187", property="iUnbalance187", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_188", property="iUnbalance188", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_189", property="iUnbalance189", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_190", property="iUnbalance190", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_191", property="iUnbalance191", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_192", property="iUnbalance192", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_193", property="iUnbalance193", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_194", property="iUnbalance194", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_195", property="iUnbalance195", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_196", property="iUnbalance196", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_197", property="iUnbalance197", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_198", property="iUnbalance198", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_199", property="iUnbalance199", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_200", property="iUnbalance200", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_201", property="iUnbalance201", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_202", property="iUnbalance202", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_203", property="iUnbalance203", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_204", property="iUnbalance204", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_205", property="iUnbalance205", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_206", property="iUnbalance206", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_207", property="iUnbalance207", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_208", property="iUnbalance208", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_209", property="iUnbalance209", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_210", property="iUnbalance210", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_211", property="iUnbalance211", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_212", property="iUnbalance212", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_213", property="iUnbalance213", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_214", property="iUnbalance214", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_215", property="iUnbalance215", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_216", property="iUnbalance216", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_217", property="iUnbalance217", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_218", property="iUnbalance218", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_219", property="iUnbalance219", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_220", property="iUnbalance220", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_221", property="iUnbalance221", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_222", property="iUnbalance222", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_223", property="iUnbalance223", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_224", property="iUnbalance224", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_225", property="iUnbalance225", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_226", property="iUnbalance226", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_227", property="iUnbalance227", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_228", property="iUnbalance228", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_229", property="iUnbalance229", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_230", property="iUnbalance230", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_231", property="iUnbalance231", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_232", property="iUnbalance232", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_233", property="iUnbalance233", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_234", property="iUnbalance234", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_235", property="iUnbalance235", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_236", property="iUnbalance236", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_237", property="iUnbalance237", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_238", property="iUnbalance238", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_239", property="iUnbalance239", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_240", property="iUnbalance240", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_241", property="iUnbalance241", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_242", property="iUnbalance242", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_243", property="iUnbalance243", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_244", property="iUnbalance244", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_245", property="iUnbalance245", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_246", property="iUnbalance246", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_247", property="iUnbalance247", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_248", property="iUnbalance248", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_249", property="iUnbalance249", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_250", property="iUnbalance250", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_251", property="iUnbalance251", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_252", property="iUnbalance252", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_253", property="iUnbalance253", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_254", property="iUnbalance254", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_255", property="iUnbalance255", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_256", property="iUnbalance256", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_257", property="iUnbalance257", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_258", property="iUnbalance258", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_259", property="iUnbalance259", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_260", property="iUnbalance260", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_261", property="iUnbalance261", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_262", property="iUnbalance262", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_263", property="iUnbalance263", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_264", property="iUnbalance264", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_265", property="iUnbalance265", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_266", property="iUnbalance266", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_267", property="iUnbalance267", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_268", property="iUnbalance268", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_269", property="iUnbalance269", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_270", property="iUnbalance270", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_271", property="iUnbalance271", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_272", property="iUnbalance272", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_273", property="iUnbalance273", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_274", property="iUnbalance274", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_275", property="iUnbalance275", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_276", property="iUnbalance276", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_277", property="iUnbalance277", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_278", property="iUnbalance278", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_279", property="iUnbalance279", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_280", property="iUnbalance280", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_281", property="iUnbalance281", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_282", property="iUnbalance282", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_283", property="iUnbalance283", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_284", property="iUnbalance284", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_285", property="iUnbalance285", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_286", property="iUnbalance286", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_287", property="iUnbalance287", jdbcType=JdbcType.DECIMAL),
        @Result(column="I_UNBALANCE_288", property="iUnbalance288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_iUnbalanceCurvePo> selectIunbalanceByDate(String data_date);

    @Select({
            "select",
            "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, I_UNBALANCE_1, ",
            "I_UNBALANCE_2, I_UNBALANCE_3, I_UNBALANCE_4, I_UNBALANCE_5, I_UNBALANCE_6, I_UNBALANCE_7, ",
            "I_UNBALANCE_8, I_UNBALANCE_9, I_UNBALANCE_10, I_UNBALANCE_11, I_UNBALANCE_12, ",
            "I_UNBALANCE_13, I_UNBALANCE_14, I_UNBALANCE_15, I_UNBALANCE_16, I_UNBALANCE_17, ",
            "I_UNBALANCE_18, I_UNBALANCE_19, I_UNBALANCE_20, I_UNBALANCE_21, I_UNBALANCE_22, ",
            "I_UNBALANCE_23, I_UNBALANCE_24, I_UNBALANCE_25, I_UNBALANCE_26, I_UNBALANCE_27, ",
            "I_UNBALANCE_28, I_UNBALANCE_29, I_UNBALANCE_30, I_UNBALANCE_31, I_UNBALANCE_32, ",
            "I_UNBALANCE_33, I_UNBALANCE_34, I_UNBALANCE_35, I_UNBALANCE_36, I_UNBALANCE_37, ",
            "I_UNBALANCE_38, I_UNBALANCE_39, I_UNBALANCE_40, I_UNBALANCE_41, I_UNBALANCE_42, ",
            "I_UNBALANCE_43, I_UNBALANCE_44, I_UNBALANCE_45, I_UNBALANCE_46, I_UNBALANCE_47, ",
            "I_UNBALANCE_48, I_UNBALANCE_49, I_UNBALANCE_50, I_UNBALANCE_51, I_UNBALANCE_52, ",
            "I_UNBALANCE_53, I_UNBALANCE_54, I_UNBALANCE_55, I_UNBALANCE_56, I_UNBALANCE_57, ",
            "I_UNBALANCE_58, I_UNBALANCE_59, I_UNBALANCE_60, I_UNBALANCE_61, I_UNBALANCE_62, ",
            "I_UNBALANCE_63, I_UNBALANCE_64, I_UNBALANCE_65, I_UNBALANCE_66, I_UNBALANCE_67, ",
            "I_UNBALANCE_68, I_UNBALANCE_69, I_UNBALANCE_70, I_UNBALANCE_71, I_UNBALANCE_72, ",
            "I_UNBALANCE_73, I_UNBALANCE_74, I_UNBALANCE_75, I_UNBALANCE_76, I_UNBALANCE_77, ",
            "I_UNBALANCE_78, I_UNBALANCE_79, I_UNBALANCE_80, I_UNBALANCE_81, I_UNBALANCE_82, ",
            "I_UNBALANCE_83, I_UNBALANCE_84, I_UNBALANCE_85, I_UNBALANCE_86, I_UNBALANCE_87, ",
            "I_UNBALANCE_88, I_UNBALANCE_89, I_UNBALANCE_90, I_UNBALANCE_91, I_UNBALANCE_92, ",
            "I_UNBALANCE_93, I_UNBALANCE_94, I_UNBALANCE_95, I_UNBALANCE_96, I_UNBALANCE_97, ",
            "I_UNBALANCE_98, I_UNBALANCE_99, I_UNBALANCE_100, I_UNBALANCE_101, I_UNBALANCE_102, ",
            "I_UNBALANCE_103, I_UNBALANCE_104, I_UNBALANCE_105, I_UNBALANCE_106, I_UNBALANCE_107, ",
            "I_UNBALANCE_108, I_UNBALANCE_109, I_UNBALANCE_110, I_UNBALANCE_111, I_UNBALANCE_112, ",
            "I_UNBALANCE_113, I_UNBALANCE_114, I_UNBALANCE_115, I_UNBALANCE_116, I_UNBALANCE_117, ",
            "I_UNBALANCE_118, I_UNBALANCE_119, I_UNBALANCE_120, I_UNBALANCE_121, I_UNBALANCE_122, ",
            "I_UNBALANCE_123, I_UNBALANCE_124, I_UNBALANCE_125, I_UNBALANCE_126, I_UNBALANCE_127, ",
            "I_UNBALANCE_128, I_UNBALANCE_129, I_UNBALANCE_130, I_UNBALANCE_131, I_UNBALANCE_132, ",
            "I_UNBALANCE_133, I_UNBALANCE_134, I_UNBALANCE_135, I_UNBALANCE_136, I_UNBALANCE_137, ",
            "I_UNBALANCE_138, I_UNBALANCE_139, I_UNBALANCE_140, I_UNBALANCE_141, I_UNBALANCE_142, ",
            "I_UNBALANCE_143, I_UNBALANCE_144, I_UNBALANCE_145, I_UNBALANCE_146, I_UNBALANCE_147, ",
            "I_UNBALANCE_148, I_UNBALANCE_149, I_UNBALANCE_150, I_UNBALANCE_151, I_UNBALANCE_152, ",
            "I_UNBALANCE_153, I_UNBALANCE_154, I_UNBALANCE_155, I_UNBALANCE_156, I_UNBALANCE_157, ",
            "I_UNBALANCE_158, I_UNBALANCE_159, I_UNBALANCE_160, I_UNBALANCE_161, I_UNBALANCE_162, ",
            "I_UNBALANCE_163, I_UNBALANCE_164, I_UNBALANCE_165, I_UNBALANCE_166, I_UNBALANCE_167, ",
            "I_UNBALANCE_168, I_UNBALANCE_169, I_UNBALANCE_170, I_UNBALANCE_171, I_UNBALANCE_172, ",
            "I_UNBALANCE_173, I_UNBALANCE_174, I_UNBALANCE_175, I_UNBALANCE_176, I_UNBALANCE_177, ",
            "I_UNBALANCE_178, I_UNBALANCE_179, I_UNBALANCE_180, I_UNBALANCE_181, I_UNBALANCE_182, ",
            "I_UNBALANCE_183, I_UNBALANCE_184, I_UNBALANCE_185, I_UNBALANCE_186, I_UNBALANCE_187, ",
            "I_UNBALANCE_188, I_UNBALANCE_189, I_UNBALANCE_190, I_UNBALANCE_191, I_UNBALANCE_192, ",
            "I_UNBALANCE_193, I_UNBALANCE_194, I_UNBALANCE_195, I_UNBALANCE_196, I_UNBALANCE_197, ",
            "I_UNBALANCE_198, I_UNBALANCE_199, I_UNBALANCE_200, I_UNBALANCE_201, I_UNBALANCE_202, ",
            "I_UNBALANCE_203, I_UNBALANCE_204, I_UNBALANCE_205, I_UNBALANCE_206, I_UNBALANCE_207, ",
            "I_UNBALANCE_208, I_UNBALANCE_209, I_UNBALANCE_210, I_UNBALANCE_211, I_UNBALANCE_212, ",
            "I_UNBALANCE_213, I_UNBALANCE_214, I_UNBALANCE_215, I_UNBALANCE_216, I_UNBALANCE_217, ",
            "I_UNBALANCE_218, I_UNBALANCE_219, I_UNBALANCE_220, I_UNBALANCE_221, I_UNBALANCE_222, ",
            "I_UNBALANCE_223, I_UNBALANCE_224, I_UNBALANCE_225, I_UNBALANCE_226, I_UNBALANCE_227, ",
            "I_UNBALANCE_228, I_UNBALANCE_229, I_UNBALANCE_230, I_UNBALANCE_231, I_UNBALANCE_232, ",
            "I_UNBALANCE_233, I_UNBALANCE_234, I_UNBALANCE_235, I_UNBALANCE_236, I_UNBALANCE_237, ",
            "I_UNBALANCE_238, I_UNBALANCE_239, I_UNBALANCE_240, I_UNBALANCE_241, I_UNBALANCE_242, ",
            "I_UNBALANCE_243, I_UNBALANCE_244, I_UNBALANCE_245, I_UNBALANCE_246, I_UNBALANCE_247, ",
            "I_UNBALANCE_248, I_UNBALANCE_249, I_UNBALANCE_250, I_UNBALANCE_251, I_UNBALANCE_252, ",
            "I_UNBALANCE_253, I_UNBALANCE_254, I_UNBALANCE_255, I_UNBALANCE_256, I_UNBALANCE_257, ",
            "I_UNBALANCE_258, I_UNBALANCE_259, I_UNBALANCE_260, I_UNBALANCE_261, I_UNBALANCE_262, ",
            "I_UNBALANCE_263, I_UNBALANCE_264, I_UNBALANCE_265, I_UNBALANCE_266, I_UNBALANCE_267, ",
            "I_UNBALANCE_268, I_UNBALANCE_269, I_UNBALANCE_270, I_UNBALANCE_271, I_UNBALANCE_272, ",
            "I_UNBALANCE_273, I_UNBALANCE_274, I_UNBALANCE_275, I_UNBALANCE_276, I_UNBALANCE_277, ",
            "I_UNBALANCE_278, I_UNBALANCE_279, I_UNBALANCE_280, I_UNBALANCE_281, I_UNBALANCE_282, ",
            "I_UNBALANCE_283, I_UNBALANCE_284, I_UNBALANCE_285, I_UNBALANCE_286, I_UNBALANCE_287, ",
            "I_UNBALANCE_288",
            "from c_msqi_i_unbalance_c ",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="I_UNBALANCE_1", property="iUnbalance1", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_2", property="iUnbalance2", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_3", property="iUnbalance3", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_4", property="iUnbalance4", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_5", property="iUnbalance5", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_6", property="iUnbalance6", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_7", property="iUnbalance7", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_8", property="iUnbalance8", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_9", property="iUnbalance9", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_10", property="iUnbalance10", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_11", property="iUnbalance11", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_12", property="iUnbalance12", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_13", property="iUnbalance13", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_14", property="iUnbalance14", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_15", property="iUnbalance15", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_16", property="iUnbalance16", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_17", property="iUnbalance17", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_18", property="iUnbalance18", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_19", property="iUnbalance19", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_20", property="iUnbalance20", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_21", property="iUnbalance21", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_22", property="iUnbalance22", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_23", property="iUnbalance23", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_24", property="iUnbalance24", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_25", property="iUnbalance25", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_26", property="iUnbalance26", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_27", property="iUnbalance27", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_28", property="iUnbalance28", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_29", property="iUnbalance29", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_30", property="iUnbalance30", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_31", property="iUnbalance31", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_32", property="iUnbalance32", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_33", property="iUnbalance33", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_34", property="iUnbalance34", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_35", property="iUnbalance35", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_36", property="iUnbalance36", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_37", property="iUnbalance37", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_38", property="iUnbalance38", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_39", property="iUnbalance39", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_40", property="iUnbalance40", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_41", property="iUnbalance41", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_42", property="iUnbalance42", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_43", property="iUnbalance43", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_44", property="iUnbalance44", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_45", property="iUnbalance45", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_46", property="iUnbalance46", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_47", property="iUnbalance47", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_48", property="iUnbalance48", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_49", property="iUnbalance49", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_50", property="iUnbalance50", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_51", property="iUnbalance51", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_52", property="iUnbalance52", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_53", property="iUnbalance53", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_54", property="iUnbalance54", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_55", property="iUnbalance55", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_56", property="iUnbalance56", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_57", property="iUnbalance57", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_58", property="iUnbalance58", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_59", property="iUnbalance59", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_60", property="iUnbalance60", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_61", property="iUnbalance61", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_62", property="iUnbalance62", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_63", property="iUnbalance63", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_64", property="iUnbalance64", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_65", property="iUnbalance65", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_66", property="iUnbalance66", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_67", property="iUnbalance67", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_68", property="iUnbalance68", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_69", property="iUnbalance69", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_70", property="iUnbalance70", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_71", property="iUnbalance71", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_72", property="iUnbalance72", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_73", property="iUnbalance73", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_74", property="iUnbalance74", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_75", property="iUnbalance75", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_76", property="iUnbalance76", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_77", property="iUnbalance77", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_78", property="iUnbalance78", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_79", property="iUnbalance79", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_80", property="iUnbalance80", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_81", property="iUnbalance81", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_82", property="iUnbalance82", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_83", property="iUnbalance83", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_84", property="iUnbalance84", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_85", property="iUnbalance85", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_86", property="iUnbalance86", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_87", property="iUnbalance87", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_88", property="iUnbalance88", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_89", property="iUnbalance89", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_90", property="iUnbalance90", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_91", property="iUnbalance91", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_92", property="iUnbalance92", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_93", property="iUnbalance93", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_94", property="iUnbalance94", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_95", property="iUnbalance95", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_96", property="iUnbalance96", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_97", property="iUnbalance97", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_98", property="iUnbalance98", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_99", property="iUnbalance99", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_100", property="iUnbalance100", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_101", property="iUnbalance101", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_102", property="iUnbalance102", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_103", property="iUnbalance103", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_104", property="iUnbalance104", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_105", property="iUnbalance105", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_106", property="iUnbalance106", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_107", property="iUnbalance107", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_108", property="iUnbalance108", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_109", property="iUnbalance109", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_110", property="iUnbalance110", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_111", property="iUnbalance111", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_112", property="iUnbalance112", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_113", property="iUnbalance113", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_114", property="iUnbalance114", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_115", property="iUnbalance115", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_116", property="iUnbalance116", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_117", property="iUnbalance117", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_118", property="iUnbalance118", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_119", property="iUnbalance119", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_120", property="iUnbalance120", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_121", property="iUnbalance121", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_122", property="iUnbalance122", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_123", property="iUnbalance123", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_124", property="iUnbalance124", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_125", property="iUnbalance125", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_126", property="iUnbalance126", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_127", property="iUnbalance127", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_128", property="iUnbalance128", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_129", property="iUnbalance129", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_130", property="iUnbalance130", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_131", property="iUnbalance131", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_132", property="iUnbalance132", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_133", property="iUnbalance133", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_134", property="iUnbalance134", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_135", property="iUnbalance135", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_136", property="iUnbalance136", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_137", property="iUnbalance137", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_138", property="iUnbalance138", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_139", property="iUnbalance139", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_140", property="iUnbalance140", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_141", property="iUnbalance141", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_142", property="iUnbalance142", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_143", property="iUnbalance143", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_144", property="iUnbalance144", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_145", property="iUnbalance145", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_146", property="iUnbalance146", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_147", property="iUnbalance147", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_148", property="iUnbalance148", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_149", property="iUnbalance149", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_150", property="iUnbalance150", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_151", property="iUnbalance151", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_152", property="iUnbalance152", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_153", property="iUnbalance153", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_154", property="iUnbalance154", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_155", property="iUnbalance155", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_156", property="iUnbalance156", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_157", property="iUnbalance157", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_158", property="iUnbalance158", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_159", property="iUnbalance159", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_160", property="iUnbalance160", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_161", property="iUnbalance161", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_162", property="iUnbalance162", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_163", property="iUnbalance163", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_164", property="iUnbalance164", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_165", property="iUnbalance165", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_166", property="iUnbalance166", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_167", property="iUnbalance167", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_168", property="iUnbalance168", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_169", property="iUnbalance169", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_170", property="iUnbalance170", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_171", property="iUnbalance171", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_172", property="iUnbalance172", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_173", property="iUnbalance173", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_174", property="iUnbalance174", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_175", property="iUnbalance175", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_176", property="iUnbalance176", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_177", property="iUnbalance177", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_178", property="iUnbalance178", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_179", property="iUnbalance179", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_180", property="iUnbalance180", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_181", property="iUnbalance181", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_182", property="iUnbalance182", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_183", property="iUnbalance183", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_184", property="iUnbalance184", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_185", property="iUnbalance185", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_186", property="iUnbalance186", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_187", property="iUnbalance187", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_188", property="iUnbalance188", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_189", property="iUnbalance189", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_190", property="iUnbalance190", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_191", property="iUnbalance191", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_192", property="iUnbalance192", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_193", property="iUnbalance193", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_194", property="iUnbalance194", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_195", property="iUnbalance195", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_196", property="iUnbalance196", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_197", property="iUnbalance197", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_198", property="iUnbalance198", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_199", property="iUnbalance199", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_200", property="iUnbalance200", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_201", property="iUnbalance201", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_202", property="iUnbalance202", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_203", property="iUnbalance203", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_204", property="iUnbalance204", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_205", property="iUnbalance205", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_206", property="iUnbalance206", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_207", property="iUnbalance207", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_208", property="iUnbalance208", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_209", property="iUnbalance209", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_210", property="iUnbalance210", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_211", property="iUnbalance211", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_212", property="iUnbalance212", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_213", property="iUnbalance213", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_214", property="iUnbalance214", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_215", property="iUnbalance215", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_216", property="iUnbalance216", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_217", property="iUnbalance217", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_218", property="iUnbalance218", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_219", property="iUnbalance219", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_220", property="iUnbalance220", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_221", property="iUnbalance221", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_222", property="iUnbalance222", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_223", property="iUnbalance223", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_224", property="iUnbalance224", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_225", property="iUnbalance225", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_226", property="iUnbalance226", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_227", property="iUnbalance227", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_228", property="iUnbalance228", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_229", property="iUnbalance229", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_230", property="iUnbalance230", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_231", property="iUnbalance231", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_232", property="iUnbalance232", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_233", property="iUnbalance233", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_234", property="iUnbalance234", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_235", property="iUnbalance235", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_236", property="iUnbalance236", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_237", property="iUnbalance237", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_238", property="iUnbalance238", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_239", property="iUnbalance239", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_240", property="iUnbalance240", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_241", property="iUnbalance241", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_242", property="iUnbalance242", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_243", property="iUnbalance243", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_244", property="iUnbalance244", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_245", property="iUnbalance245", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_246", property="iUnbalance246", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_247", property="iUnbalance247", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_248", property="iUnbalance248", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_249", property="iUnbalance249", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_250", property="iUnbalance250", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_251", property="iUnbalance251", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_252", property="iUnbalance252", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_253", property="iUnbalance253", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_254", property="iUnbalance254", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_255", property="iUnbalance255", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_256", property="iUnbalance256", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_257", property="iUnbalance257", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_258", property="iUnbalance258", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_259", property="iUnbalance259", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_260", property="iUnbalance260", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_261", property="iUnbalance261", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_262", property="iUnbalance262", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_263", property="iUnbalance263", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_264", property="iUnbalance264", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_265", property="iUnbalance265", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_266", property="iUnbalance266", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_267", property="iUnbalance267", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_268", property="iUnbalance268", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_269", property="iUnbalance269", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_270", property="iUnbalance270", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_271", property="iUnbalance271", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_272", property="iUnbalance272", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_273", property="iUnbalance273", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_274", property="iUnbalance274", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_275", property="iUnbalance275", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_276", property="iUnbalance276", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_277", property="iUnbalance277", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_278", property="iUnbalance278", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_279", property="iUnbalance279", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_280", property="iUnbalance280", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_281", property="iUnbalance281", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_282", property="iUnbalance282", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_283", property="iUnbalance283", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_284", property="iUnbalance284", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_285", property="iUnbalance285", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_286", property="iUnbalance286", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_287", property="iUnbalance287", jdbcType=JdbcType.DECIMAL),
            @Result(column="I_UNBALANCE_288", property="iUnbalance288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_iUnbalanceCurvePo> selectIunbalanceBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

}