package com.dao.mapper;

import com.dao.bean.D_mhaiCurdistCurvePo;
import com.dao.bean.D_mhaiCurdistCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_mhaiCurdistCurvePoMapper {

    @Select({
        "select",
        "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_CURDIST_1, ",
        "HAR_CURDIST_2, HAR_CURDIST_3, HAR_CURDIST_4, HAR_CURDIST_5, HAR_CURDIST_6, HAR_CURDIST_7, ",
        "HAR_CURDIST_8, HAR_CURDIST_9, HAR_CURDIST_10, HAR_CURDIST_11, HAR_CURDIST_12, ",
        "HAR_CURDIST_13, HAR_CURDIST_14, HAR_CURDIST_15, HAR_CURDIST_16, HAR_CURDIST_17, ",
        "HAR_CURDIST_18, HAR_CURDIST_19, HAR_CURDIST_20, HAR_CURDIST_21, HAR_CURDIST_22, ",
        "HAR_CURDIST_23, HAR_CURDIST_24, HAR_CURDIST_25, HAR_CURDIST_26, HAR_CURDIST_27, ",
        "HAR_CURDIST_28, HAR_CURDIST_29, HAR_CURDIST_30, HAR_CURDIST_31, HAR_CURDIST_32, ",
        "HAR_CURDIST_33, HAR_CURDIST_34, HAR_CURDIST_35, HAR_CURDIST_36, HAR_CURDIST_37, ",
        "HAR_CURDIST_38, HAR_CURDIST_39, HAR_CURDIST_40, HAR_CURDIST_41, HAR_CURDIST_42, ",
        "HAR_CURDIST_43, HAR_CURDIST_44, HAR_CURDIST_45, HAR_CURDIST_46, HAR_CURDIST_47, ",
        "HAR_CURDIST_48, HAR_CURDIST_49, HAR_CURDIST_50, HAR_CURDIST_51, HAR_CURDIST_52, ",
        "HAR_CURDIST_53, HAR_CURDIST_54, HAR_CURDIST_55, HAR_CURDIST_56, HAR_CURDIST_57, ",
        "HAR_CURDIST_58, HAR_CURDIST_59, HAR_CURDIST_60, HAR_CURDIST_61, HAR_CURDIST_62, ",
        "HAR_CURDIST_63, HAR_CURDIST_64, HAR_CURDIST_65, HAR_CURDIST_66, HAR_CURDIST_67, ",
        "HAR_CURDIST_68, HAR_CURDIST_69, HAR_CURDIST_70, HAR_CURDIST_71, HAR_CURDIST_72, ",
        "HAR_CURDIST_73, HAR_CURDIST_74, HAR_CURDIST_75, HAR_CURDIST_76, HAR_CURDIST_77, ",
        "HAR_CURDIST_78, HAR_CURDIST_79, HAR_CURDIST_80, HAR_CURDIST_81, HAR_CURDIST_82, ",
        "HAR_CURDIST_83, HAR_CURDIST_84, HAR_CURDIST_85, HAR_CURDIST_86, HAR_CURDIST_87, ",
        "HAR_CURDIST_88, HAR_CURDIST_89, HAR_CURDIST_90, HAR_CURDIST_91, HAR_CURDIST_92, ",
        "HAR_CURDIST_93, HAR_CURDIST_94, HAR_CURDIST_95, HAR_CURDIST_96, HAR_CURDIST_97, ",
        "HAR_CURDIST_98, HAR_CURDIST_99, HAR_CURDIST_100, HAR_CURDIST_101, HAR_CURDIST_102, ",
        "HAR_CURDIST_103, HAR_CURDIST_104, HAR_CURDIST_105, HAR_CURDIST_106, HAR_CURDIST_107, ",
        "HAR_CURDIST_108, HAR_CURDIST_109, HAR_CURDIST_110, HAR_CURDIST_111, HAR_CURDIST_112, ",
        "HAR_CURDIST_113, HAR_CURDIST_114, HAR_CURDIST_115, HAR_CURDIST_116, HAR_CURDIST_117, ",
        "HAR_CURDIST_118, HAR_CURDIST_119, HAR_CURDIST_120, HAR_CURDIST_121, HAR_CURDIST_122, ",
        "HAR_CURDIST_123, HAR_CURDIST_124, HAR_CURDIST_125, HAR_CURDIST_126, HAR_CURDIST_127, ",
        "HAR_CURDIST_128, HAR_CURDIST_129, HAR_CURDIST_130, HAR_CURDIST_131, HAR_CURDIST_132, ",
        "HAR_CURDIST_133, HAR_CURDIST_134, HAR_CURDIST_135, HAR_CURDIST_136, HAR_CURDIST_137, ",
        "HAR_CURDIST_138, HAR_CURDIST_139, HAR_CURDIST_140, HAR_CURDIST_141, HAR_CURDIST_142, ",
        "HAR_CURDIST_143, HAR_CURDIST_144, HAR_CURDIST_145, HAR_CURDIST_146, HAR_CURDIST_147, ",
        "HAR_CURDIST_148, HAR_CURDIST_149, HAR_CURDIST_150, HAR_CURDIST_151, HAR_CURDIST_152, ",
        "HAR_CURDIST_153, HAR_CURDIST_154, HAR_CURDIST_155, HAR_CURDIST_156, HAR_CURDIST_157, ",
        "HAR_CURDIST_158, HAR_CURDIST_159, HAR_CURDIST_160, HAR_CURDIST_161, HAR_CURDIST_162, ",
        "HAR_CURDIST_163, HAR_CURDIST_164, HAR_CURDIST_165, HAR_CURDIST_166, HAR_CURDIST_167, ",
        "HAR_CURDIST_168, HAR_CURDIST_169, HAR_CURDIST_170, HAR_CURDIST_171, HAR_CURDIST_172, ",
        "HAR_CURDIST_173, HAR_CURDIST_174, HAR_CURDIST_175, HAR_CURDIST_176, HAR_CURDIST_177, ",
        "HAR_CURDIST_178, HAR_CURDIST_179, HAR_CURDIST_180, HAR_CURDIST_181, HAR_CURDIST_182, ",
        "HAR_CURDIST_183, HAR_CURDIST_184, HAR_CURDIST_185, HAR_CURDIST_186, HAR_CURDIST_187, ",
        "HAR_CURDIST_188, HAR_CURDIST_189, HAR_CURDIST_190, HAR_CURDIST_191, HAR_CURDIST_192, ",
        "HAR_CURDIST_193, HAR_CURDIST_194, HAR_CURDIST_195, HAR_CURDIST_196, HAR_CURDIST_197, ",
        "HAR_CURDIST_198, HAR_CURDIST_199, HAR_CURDIST_200, HAR_CURDIST_201, HAR_CURDIST_202, ",
        "HAR_CURDIST_203, HAR_CURDIST_204, HAR_CURDIST_205, HAR_CURDIST_206, HAR_CURDIST_207, ",
        "HAR_CURDIST_208, HAR_CURDIST_209, HAR_CURDIST_210, HAR_CURDIST_211, HAR_CURDIST_212, ",
        "HAR_CURDIST_213, HAR_CURDIST_214, HAR_CURDIST_215, HAR_CURDIST_216, HAR_CURDIST_217, ",
        "HAR_CURDIST_218, HAR_CURDIST_219, HAR_CURDIST_220, HAR_CURDIST_221, HAR_CURDIST_222, ",
        "HAR_CURDIST_223, HAR_CURDIST_224, HAR_CURDIST_225, HAR_CURDIST_226, HAR_CURDIST_227, ",
        "HAR_CURDIST_228, HAR_CURDIST_229, HAR_CURDIST_230, HAR_CURDIST_231, HAR_CURDIST_232, ",
        "HAR_CURDIST_233, HAR_CURDIST_234, HAR_CURDIST_235, HAR_CURDIST_236, HAR_CURDIST_237, ",
        "HAR_CURDIST_238, HAR_CURDIST_239, HAR_CURDIST_240, HAR_CURDIST_241, HAR_CURDIST_242, ",
        "HAR_CURDIST_243, HAR_CURDIST_244, HAR_CURDIST_245, HAR_CURDIST_246, HAR_CURDIST_247, ",
        "HAR_CURDIST_248, HAR_CURDIST_249, HAR_CURDIST_250, HAR_CURDIST_251, HAR_CURDIST_252, ",
        "HAR_CURDIST_253, HAR_CURDIST_254, HAR_CURDIST_255, HAR_CURDIST_256, HAR_CURDIST_257, ",
        "HAR_CURDIST_258, HAR_CURDIST_259, HAR_CURDIST_260, HAR_CURDIST_261, HAR_CURDIST_262, ",
        "HAR_CURDIST_263, HAR_CURDIST_264, HAR_CURDIST_265, HAR_CURDIST_266, HAR_CURDIST_267, ",
        "HAR_CURDIST_268, HAR_CURDIST_269, HAR_CURDIST_270, HAR_CURDIST_271, HAR_CURDIST_272, ",
        "HAR_CURDIST_273, HAR_CURDIST_274, HAR_CURDIST_275, HAR_CURDIST_276, HAR_CURDIST_277, ",
        "HAR_CURDIST_278, HAR_CURDIST_279, HAR_CURDIST_280, HAR_CURDIST_281, HAR_CURDIST_282, ",
        "HAR_CURDIST_283, HAR_CURDIST_284, HAR_CURDIST_285, HAR_CURDIST_286, HAR_CURDIST_287, ",
        "HAR_CURDIST_288",
        "from c_mhai_curdist_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="HAR_CURDIST_1", property="harCurdist1", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_2", property="harCurdist2", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_3", property="harCurdist3", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_4", property="harCurdist4", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_5", property="harCurdist5", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_6", property="harCurdist6", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_7", property="harCurdist7", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_8", property="harCurdist8", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_9", property="harCurdist9", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_10", property="harCurdist10", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_11", property="harCurdist11", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_12", property="harCurdist12", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_13", property="harCurdist13", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_14", property="harCurdist14", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_15", property="harCurdist15", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_16", property="harCurdist16", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_17", property="harCurdist17", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_18", property="harCurdist18", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_19", property="harCurdist19", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_20", property="harCurdist20", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_21", property="harCurdist21", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_22", property="harCurdist22", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_23", property="harCurdist23", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_24", property="harCurdist24", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_25", property="harCurdist25", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_26", property="harCurdist26", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_27", property="harCurdist27", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_28", property="harCurdist28", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_29", property="harCurdist29", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_30", property="harCurdist30", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_31", property="harCurdist31", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_32", property="harCurdist32", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_33", property="harCurdist33", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_34", property="harCurdist34", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_35", property="harCurdist35", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_36", property="harCurdist36", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_37", property="harCurdist37", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_38", property="harCurdist38", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_39", property="harCurdist39", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_40", property="harCurdist40", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_41", property="harCurdist41", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_42", property="harCurdist42", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_43", property="harCurdist43", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_44", property="harCurdist44", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_45", property="harCurdist45", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_46", property="harCurdist46", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_47", property="harCurdist47", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_48", property="harCurdist48", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_49", property="harCurdist49", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_50", property="harCurdist50", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_51", property="harCurdist51", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_52", property="harCurdist52", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_53", property="harCurdist53", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_54", property="harCurdist54", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_55", property="harCurdist55", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_56", property="harCurdist56", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_57", property="harCurdist57", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_58", property="harCurdist58", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_59", property="harCurdist59", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_60", property="harCurdist60", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_61", property="harCurdist61", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_62", property="harCurdist62", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_63", property="harCurdist63", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_64", property="harCurdist64", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_65", property="harCurdist65", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_66", property="harCurdist66", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_67", property="harCurdist67", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_68", property="harCurdist68", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_69", property="harCurdist69", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_70", property="harCurdist70", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_71", property="harCurdist71", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_72", property="harCurdist72", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_73", property="harCurdist73", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_74", property="harCurdist74", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_75", property="harCurdist75", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_76", property="harCurdist76", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_77", property="harCurdist77", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_78", property="harCurdist78", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_79", property="harCurdist79", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_80", property="harCurdist80", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_81", property="harCurdist81", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_82", property="harCurdist82", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_83", property="harCurdist83", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_84", property="harCurdist84", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_85", property="harCurdist85", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_86", property="harCurdist86", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_87", property="harCurdist87", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_88", property="harCurdist88", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_89", property="harCurdist89", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_90", property="harCurdist90", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_91", property="harCurdist91", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_92", property="harCurdist92", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_93", property="harCurdist93", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_94", property="harCurdist94", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_95", property="harCurdist95", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_96", property="harCurdist96", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_97", property="harCurdist97", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_98", property="harCurdist98", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_99", property="harCurdist99", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_100", property="harCurdist100", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_101", property="harCurdist101", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_102", property="harCurdist102", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_103", property="harCurdist103", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_104", property="harCurdist104", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_105", property="harCurdist105", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_106", property="harCurdist106", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_107", property="harCurdist107", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_108", property="harCurdist108", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_109", property="harCurdist109", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_110", property="harCurdist110", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_111", property="harCurdist111", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_112", property="harCurdist112", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_113", property="harCurdist113", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_114", property="harCurdist114", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_115", property="harCurdist115", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_116", property="harCurdist116", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_117", property="harCurdist117", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_118", property="harCurdist118", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_119", property="harCurdist119", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_120", property="harCurdist120", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_121", property="harCurdist121", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_122", property="harCurdist122", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_123", property="harCurdist123", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_124", property="harCurdist124", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_125", property="harCurdist125", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_126", property="harCurdist126", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_127", property="harCurdist127", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_128", property="harCurdist128", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_129", property="harCurdist129", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_130", property="harCurdist130", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_131", property="harCurdist131", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_132", property="harCurdist132", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_133", property="harCurdist133", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_134", property="harCurdist134", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_135", property="harCurdist135", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_136", property="harCurdist136", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_137", property="harCurdist137", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_138", property="harCurdist138", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_139", property="harCurdist139", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_140", property="harCurdist140", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_141", property="harCurdist141", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_142", property="harCurdist142", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_143", property="harCurdist143", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_144", property="harCurdist144", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_145", property="harCurdist145", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_146", property="harCurdist146", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_147", property="harCurdist147", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_148", property="harCurdist148", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_149", property="harCurdist149", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_150", property="harCurdist150", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_151", property="harCurdist151", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_152", property="harCurdist152", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_153", property="harCurdist153", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_154", property="harCurdist154", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_155", property="harCurdist155", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_156", property="harCurdist156", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_157", property="harCurdist157", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_158", property="harCurdist158", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_159", property="harCurdist159", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_160", property="harCurdist160", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_161", property="harCurdist161", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_162", property="harCurdist162", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_163", property="harCurdist163", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_164", property="harCurdist164", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_165", property="harCurdist165", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_166", property="harCurdist166", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_167", property="harCurdist167", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_168", property="harCurdist168", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_169", property="harCurdist169", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_170", property="harCurdist170", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_171", property="harCurdist171", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_172", property="harCurdist172", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_173", property="harCurdist173", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_174", property="harCurdist174", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_175", property="harCurdist175", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_176", property="harCurdist176", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_177", property="harCurdist177", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_178", property="harCurdist178", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_179", property="harCurdist179", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_180", property="harCurdist180", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_181", property="harCurdist181", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_182", property="harCurdist182", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_183", property="harCurdist183", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_184", property="harCurdist184", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_185", property="harCurdist185", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_186", property="harCurdist186", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_187", property="harCurdist187", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_188", property="harCurdist188", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_189", property="harCurdist189", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_190", property="harCurdist190", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_191", property="harCurdist191", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_192", property="harCurdist192", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_193", property="harCurdist193", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_194", property="harCurdist194", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_195", property="harCurdist195", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_196", property="harCurdist196", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_197", property="harCurdist197", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_198", property="harCurdist198", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_199", property="harCurdist199", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_200", property="harCurdist200", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_201", property="harCurdist201", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_202", property="harCurdist202", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_203", property="harCurdist203", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_204", property="harCurdist204", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_205", property="harCurdist205", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_206", property="harCurdist206", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_207", property="harCurdist207", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_208", property="harCurdist208", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_209", property="harCurdist209", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_210", property="harCurdist210", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_211", property="harCurdist211", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_212", property="harCurdist212", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_213", property="harCurdist213", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_214", property="harCurdist214", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_215", property="harCurdist215", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_216", property="harCurdist216", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_217", property="harCurdist217", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_218", property="harCurdist218", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_219", property="harCurdist219", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_220", property="harCurdist220", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_221", property="harCurdist221", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_222", property="harCurdist222", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_223", property="harCurdist223", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_224", property="harCurdist224", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_225", property="harCurdist225", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_226", property="harCurdist226", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_227", property="harCurdist227", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_228", property="harCurdist228", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_229", property="harCurdist229", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_230", property="harCurdist230", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_231", property="harCurdist231", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_232", property="harCurdist232", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_233", property="harCurdist233", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_234", property="harCurdist234", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_235", property="harCurdist235", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_236", property="harCurdist236", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_237", property="harCurdist237", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_238", property="harCurdist238", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_239", property="harCurdist239", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_240", property="harCurdist240", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_241", property="harCurdist241", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_242", property="harCurdist242", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_243", property="harCurdist243", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_244", property="harCurdist244", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_245", property="harCurdist245", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_246", property="harCurdist246", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_247", property="harCurdist247", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_248", property="harCurdist248", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_249", property="harCurdist249", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_250", property="harCurdist250", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_251", property="harCurdist251", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_252", property="harCurdist252", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_253", property="harCurdist253", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_254", property="harCurdist254", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_255", property="harCurdist255", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_256", property="harCurdist256", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_257", property="harCurdist257", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_258", property="harCurdist258", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_259", property="harCurdist259", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_260", property="harCurdist260", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_261", property="harCurdist261", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_262", property="harCurdist262", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_263", property="harCurdist263", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_264", property="harCurdist264", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_265", property="harCurdist265", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_266", property="harCurdist266", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_267", property="harCurdist267", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_268", property="harCurdist268", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_269", property="harCurdist269", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_270", property="harCurdist270", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_271", property="harCurdist271", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_272", property="harCurdist272", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_273", property="harCurdist273", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_274", property="harCurdist274", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_275", property="harCurdist275", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_276", property="harCurdist276", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_277", property="harCurdist277", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_278", property="harCurdist278", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_279", property="harCurdist279", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_280", property="harCurdist280", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_281", property="harCurdist281", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_282", property="harCurdist282", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_283", property="harCurdist283", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_284", property="harCurdist284", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_285", property="harCurdist285", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_286", property="harCurdist286", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_287", property="harCurdist287", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CURDIST_288", property="harCurdist288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_mhaiCurdistCurvePo> selectCurdistByDate(String data_date);

    @Select({
            "select",
            "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_CURDIST_1, ",
            "HAR_CURDIST_2, HAR_CURDIST_3, HAR_CURDIST_4, HAR_CURDIST_5, HAR_CURDIST_6, HAR_CURDIST_7, ",
            "HAR_CURDIST_8, HAR_CURDIST_9, HAR_CURDIST_10, HAR_CURDIST_11, HAR_CURDIST_12, ",
            "HAR_CURDIST_13, HAR_CURDIST_14, HAR_CURDIST_15, HAR_CURDIST_16, HAR_CURDIST_17, ",
            "HAR_CURDIST_18, HAR_CURDIST_19, HAR_CURDIST_20, HAR_CURDIST_21, HAR_CURDIST_22, ",
            "HAR_CURDIST_23, HAR_CURDIST_24, HAR_CURDIST_25, HAR_CURDIST_26, HAR_CURDIST_27, ",
            "HAR_CURDIST_28, HAR_CURDIST_29, HAR_CURDIST_30, HAR_CURDIST_31, HAR_CURDIST_32, ",
            "HAR_CURDIST_33, HAR_CURDIST_34, HAR_CURDIST_35, HAR_CURDIST_36, HAR_CURDIST_37, ",
            "HAR_CURDIST_38, HAR_CURDIST_39, HAR_CURDIST_40, HAR_CURDIST_41, HAR_CURDIST_42, ",
            "HAR_CURDIST_43, HAR_CURDIST_44, HAR_CURDIST_45, HAR_CURDIST_46, HAR_CURDIST_47, ",
            "HAR_CURDIST_48, HAR_CURDIST_49, HAR_CURDIST_50, HAR_CURDIST_51, HAR_CURDIST_52, ",
            "HAR_CURDIST_53, HAR_CURDIST_54, HAR_CURDIST_55, HAR_CURDIST_56, HAR_CURDIST_57, ",
            "HAR_CURDIST_58, HAR_CURDIST_59, HAR_CURDIST_60, HAR_CURDIST_61, HAR_CURDIST_62, ",
            "HAR_CURDIST_63, HAR_CURDIST_64, HAR_CURDIST_65, HAR_CURDIST_66, HAR_CURDIST_67, ",
            "HAR_CURDIST_68, HAR_CURDIST_69, HAR_CURDIST_70, HAR_CURDIST_71, HAR_CURDIST_72, ",
            "HAR_CURDIST_73, HAR_CURDIST_74, HAR_CURDIST_75, HAR_CURDIST_76, HAR_CURDIST_77, ",
            "HAR_CURDIST_78, HAR_CURDIST_79, HAR_CURDIST_80, HAR_CURDIST_81, HAR_CURDIST_82, ",
            "HAR_CURDIST_83, HAR_CURDIST_84, HAR_CURDIST_85, HAR_CURDIST_86, HAR_CURDIST_87, ",
            "HAR_CURDIST_88, HAR_CURDIST_89, HAR_CURDIST_90, HAR_CURDIST_91, HAR_CURDIST_92, ",
            "HAR_CURDIST_93, HAR_CURDIST_94, HAR_CURDIST_95, HAR_CURDIST_96, HAR_CURDIST_97, ",
            "HAR_CURDIST_98, HAR_CURDIST_99, HAR_CURDIST_100, HAR_CURDIST_101, HAR_CURDIST_102, ",
            "HAR_CURDIST_103, HAR_CURDIST_104, HAR_CURDIST_105, HAR_CURDIST_106, HAR_CURDIST_107, ",
            "HAR_CURDIST_108, HAR_CURDIST_109, HAR_CURDIST_110, HAR_CURDIST_111, HAR_CURDIST_112, ",
            "HAR_CURDIST_113, HAR_CURDIST_114, HAR_CURDIST_115, HAR_CURDIST_116, HAR_CURDIST_117, ",
            "HAR_CURDIST_118, HAR_CURDIST_119, HAR_CURDIST_120, HAR_CURDIST_121, HAR_CURDIST_122, ",
            "HAR_CURDIST_123, HAR_CURDIST_124, HAR_CURDIST_125, HAR_CURDIST_126, HAR_CURDIST_127, ",
            "HAR_CURDIST_128, HAR_CURDIST_129, HAR_CURDIST_130, HAR_CURDIST_131, HAR_CURDIST_132, ",
            "HAR_CURDIST_133, HAR_CURDIST_134, HAR_CURDIST_135, HAR_CURDIST_136, HAR_CURDIST_137, ",
            "HAR_CURDIST_138, HAR_CURDIST_139, HAR_CURDIST_140, HAR_CURDIST_141, HAR_CURDIST_142, ",
            "HAR_CURDIST_143, HAR_CURDIST_144, HAR_CURDIST_145, HAR_CURDIST_146, HAR_CURDIST_147, ",
            "HAR_CURDIST_148, HAR_CURDIST_149, HAR_CURDIST_150, HAR_CURDIST_151, HAR_CURDIST_152, ",
            "HAR_CURDIST_153, HAR_CURDIST_154, HAR_CURDIST_155, HAR_CURDIST_156, HAR_CURDIST_157, ",
            "HAR_CURDIST_158, HAR_CURDIST_159, HAR_CURDIST_160, HAR_CURDIST_161, HAR_CURDIST_162, ",
            "HAR_CURDIST_163, HAR_CURDIST_164, HAR_CURDIST_165, HAR_CURDIST_166, HAR_CURDIST_167, ",
            "HAR_CURDIST_168, HAR_CURDIST_169, HAR_CURDIST_170, HAR_CURDIST_171, HAR_CURDIST_172, ",
            "HAR_CURDIST_173, HAR_CURDIST_174, HAR_CURDIST_175, HAR_CURDIST_176, HAR_CURDIST_177, ",
            "HAR_CURDIST_178, HAR_CURDIST_179, HAR_CURDIST_180, HAR_CURDIST_181, HAR_CURDIST_182, ",
            "HAR_CURDIST_183, HAR_CURDIST_184, HAR_CURDIST_185, HAR_CURDIST_186, HAR_CURDIST_187, ",
            "HAR_CURDIST_188, HAR_CURDIST_189, HAR_CURDIST_190, HAR_CURDIST_191, HAR_CURDIST_192, ",
            "HAR_CURDIST_193, HAR_CURDIST_194, HAR_CURDIST_195, HAR_CURDIST_196, HAR_CURDIST_197, ",
            "HAR_CURDIST_198, HAR_CURDIST_199, HAR_CURDIST_200, HAR_CURDIST_201, HAR_CURDIST_202, ",
            "HAR_CURDIST_203, HAR_CURDIST_204, HAR_CURDIST_205, HAR_CURDIST_206, HAR_CURDIST_207, ",
            "HAR_CURDIST_208, HAR_CURDIST_209, HAR_CURDIST_210, HAR_CURDIST_211, HAR_CURDIST_212, ",
            "HAR_CURDIST_213, HAR_CURDIST_214, HAR_CURDIST_215, HAR_CURDIST_216, HAR_CURDIST_217, ",
            "HAR_CURDIST_218, HAR_CURDIST_219, HAR_CURDIST_220, HAR_CURDIST_221, HAR_CURDIST_222, ",
            "HAR_CURDIST_223, HAR_CURDIST_224, HAR_CURDIST_225, HAR_CURDIST_226, HAR_CURDIST_227, ",
            "HAR_CURDIST_228, HAR_CURDIST_229, HAR_CURDIST_230, HAR_CURDIST_231, HAR_CURDIST_232, ",
            "HAR_CURDIST_233, HAR_CURDIST_234, HAR_CURDIST_235, HAR_CURDIST_236, HAR_CURDIST_237, ",
            "HAR_CURDIST_238, HAR_CURDIST_239, HAR_CURDIST_240, HAR_CURDIST_241, HAR_CURDIST_242, ",
            "HAR_CURDIST_243, HAR_CURDIST_244, HAR_CURDIST_245, HAR_CURDIST_246, HAR_CURDIST_247, ",
            "HAR_CURDIST_248, HAR_CURDIST_249, HAR_CURDIST_250, HAR_CURDIST_251, HAR_CURDIST_252, ",
            "HAR_CURDIST_253, HAR_CURDIST_254, HAR_CURDIST_255, HAR_CURDIST_256, HAR_CURDIST_257, ",
            "HAR_CURDIST_258, HAR_CURDIST_259, HAR_CURDIST_260, HAR_CURDIST_261, HAR_CURDIST_262, ",
            "HAR_CURDIST_263, HAR_CURDIST_264, HAR_CURDIST_265, HAR_CURDIST_266, HAR_CURDIST_267, ",
            "HAR_CURDIST_268, HAR_CURDIST_269, HAR_CURDIST_270, HAR_CURDIST_271, HAR_CURDIST_272, ",
            "HAR_CURDIST_273, HAR_CURDIST_274, HAR_CURDIST_275, HAR_CURDIST_276, HAR_CURDIST_277, ",
            "HAR_CURDIST_278, HAR_CURDIST_279, HAR_CURDIST_280, HAR_CURDIST_281, HAR_CURDIST_282, ",
            "HAR_CURDIST_283, HAR_CURDIST_284, HAR_CURDIST_285, HAR_CURDIST_286, HAR_CURDIST_287, ",
            "HAR_CURDIST_288",
            "from c_mhai_curdist_c ",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="HAR_CURDIST_1", property="harCurdist1", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_2", property="harCurdist2", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_3", property="harCurdist3", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_4", property="harCurdist4", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_5", property="harCurdist5", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_6", property="harCurdist6", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_7", property="harCurdist7", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_8", property="harCurdist8", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_9", property="harCurdist9", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_10", property="harCurdist10", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_11", property="harCurdist11", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_12", property="harCurdist12", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_13", property="harCurdist13", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_14", property="harCurdist14", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_15", property="harCurdist15", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_16", property="harCurdist16", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_17", property="harCurdist17", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_18", property="harCurdist18", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_19", property="harCurdist19", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_20", property="harCurdist20", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_21", property="harCurdist21", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_22", property="harCurdist22", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_23", property="harCurdist23", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_24", property="harCurdist24", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_25", property="harCurdist25", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_26", property="harCurdist26", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_27", property="harCurdist27", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_28", property="harCurdist28", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_29", property="harCurdist29", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_30", property="harCurdist30", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_31", property="harCurdist31", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_32", property="harCurdist32", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_33", property="harCurdist33", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_34", property="harCurdist34", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_35", property="harCurdist35", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_36", property="harCurdist36", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_37", property="harCurdist37", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_38", property="harCurdist38", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_39", property="harCurdist39", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_40", property="harCurdist40", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_41", property="harCurdist41", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_42", property="harCurdist42", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_43", property="harCurdist43", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_44", property="harCurdist44", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_45", property="harCurdist45", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_46", property="harCurdist46", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_47", property="harCurdist47", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_48", property="harCurdist48", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_49", property="harCurdist49", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_50", property="harCurdist50", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_51", property="harCurdist51", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_52", property="harCurdist52", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_53", property="harCurdist53", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_54", property="harCurdist54", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_55", property="harCurdist55", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_56", property="harCurdist56", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_57", property="harCurdist57", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_58", property="harCurdist58", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_59", property="harCurdist59", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_60", property="harCurdist60", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_61", property="harCurdist61", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_62", property="harCurdist62", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_63", property="harCurdist63", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_64", property="harCurdist64", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_65", property="harCurdist65", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_66", property="harCurdist66", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_67", property="harCurdist67", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_68", property="harCurdist68", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_69", property="harCurdist69", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_70", property="harCurdist70", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_71", property="harCurdist71", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_72", property="harCurdist72", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_73", property="harCurdist73", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_74", property="harCurdist74", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_75", property="harCurdist75", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_76", property="harCurdist76", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_77", property="harCurdist77", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_78", property="harCurdist78", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_79", property="harCurdist79", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_80", property="harCurdist80", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_81", property="harCurdist81", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_82", property="harCurdist82", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_83", property="harCurdist83", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_84", property="harCurdist84", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_85", property="harCurdist85", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_86", property="harCurdist86", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_87", property="harCurdist87", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_88", property="harCurdist88", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_89", property="harCurdist89", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_90", property="harCurdist90", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_91", property="harCurdist91", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_92", property="harCurdist92", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_93", property="harCurdist93", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_94", property="harCurdist94", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_95", property="harCurdist95", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_96", property="harCurdist96", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_97", property="harCurdist97", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_98", property="harCurdist98", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_99", property="harCurdist99", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_100", property="harCurdist100", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_101", property="harCurdist101", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_102", property="harCurdist102", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_103", property="harCurdist103", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_104", property="harCurdist104", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_105", property="harCurdist105", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_106", property="harCurdist106", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_107", property="harCurdist107", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_108", property="harCurdist108", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_109", property="harCurdist109", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_110", property="harCurdist110", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_111", property="harCurdist111", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_112", property="harCurdist112", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_113", property="harCurdist113", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_114", property="harCurdist114", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_115", property="harCurdist115", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_116", property="harCurdist116", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_117", property="harCurdist117", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_118", property="harCurdist118", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_119", property="harCurdist119", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_120", property="harCurdist120", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_121", property="harCurdist121", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_122", property="harCurdist122", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_123", property="harCurdist123", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_124", property="harCurdist124", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_125", property="harCurdist125", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_126", property="harCurdist126", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_127", property="harCurdist127", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_128", property="harCurdist128", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_129", property="harCurdist129", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_130", property="harCurdist130", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_131", property="harCurdist131", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_132", property="harCurdist132", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_133", property="harCurdist133", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_134", property="harCurdist134", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_135", property="harCurdist135", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_136", property="harCurdist136", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_137", property="harCurdist137", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_138", property="harCurdist138", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_139", property="harCurdist139", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_140", property="harCurdist140", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_141", property="harCurdist141", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_142", property="harCurdist142", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_143", property="harCurdist143", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_144", property="harCurdist144", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_145", property="harCurdist145", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_146", property="harCurdist146", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_147", property="harCurdist147", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_148", property="harCurdist148", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_149", property="harCurdist149", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_150", property="harCurdist150", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_151", property="harCurdist151", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_152", property="harCurdist152", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_153", property="harCurdist153", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_154", property="harCurdist154", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_155", property="harCurdist155", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_156", property="harCurdist156", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_157", property="harCurdist157", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_158", property="harCurdist158", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_159", property="harCurdist159", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_160", property="harCurdist160", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_161", property="harCurdist161", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_162", property="harCurdist162", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_163", property="harCurdist163", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_164", property="harCurdist164", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_165", property="harCurdist165", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_166", property="harCurdist166", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_167", property="harCurdist167", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_168", property="harCurdist168", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_169", property="harCurdist169", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_170", property="harCurdist170", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_171", property="harCurdist171", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_172", property="harCurdist172", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_173", property="harCurdist173", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_174", property="harCurdist174", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_175", property="harCurdist175", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_176", property="harCurdist176", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_177", property="harCurdist177", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_178", property="harCurdist178", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_179", property="harCurdist179", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_180", property="harCurdist180", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_181", property="harCurdist181", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_182", property="harCurdist182", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_183", property="harCurdist183", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_184", property="harCurdist184", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_185", property="harCurdist185", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_186", property="harCurdist186", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_187", property="harCurdist187", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_188", property="harCurdist188", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_189", property="harCurdist189", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_190", property="harCurdist190", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_191", property="harCurdist191", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_192", property="harCurdist192", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_193", property="harCurdist193", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_194", property="harCurdist194", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_195", property="harCurdist195", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_196", property="harCurdist196", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_197", property="harCurdist197", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_198", property="harCurdist198", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_199", property="harCurdist199", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_200", property="harCurdist200", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_201", property="harCurdist201", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_202", property="harCurdist202", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_203", property="harCurdist203", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_204", property="harCurdist204", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_205", property="harCurdist205", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_206", property="harCurdist206", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_207", property="harCurdist207", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_208", property="harCurdist208", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_209", property="harCurdist209", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_210", property="harCurdist210", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_211", property="harCurdist211", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_212", property="harCurdist212", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_213", property="harCurdist213", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_214", property="harCurdist214", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_215", property="harCurdist215", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_216", property="harCurdist216", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_217", property="harCurdist217", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_218", property="harCurdist218", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_219", property="harCurdist219", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_220", property="harCurdist220", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_221", property="harCurdist221", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_222", property="harCurdist222", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_223", property="harCurdist223", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_224", property="harCurdist224", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_225", property="harCurdist225", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_226", property="harCurdist226", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_227", property="harCurdist227", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_228", property="harCurdist228", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_229", property="harCurdist229", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_230", property="harCurdist230", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_231", property="harCurdist231", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_232", property="harCurdist232", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_233", property="harCurdist233", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_234", property="harCurdist234", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_235", property="harCurdist235", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_236", property="harCurdist236", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_237", property="harCurdist237", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_238", property="harCurdist238", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_239", property="harCurdist239", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_240", property="harCurdist240", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_241", property="harCurdist241", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_242", property="harCurdist242", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_243", property="harCurdist243", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_244", property="harCurdist244", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_245", property="harCurdist245", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_246", property="harCurdist246", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_247", property="harCurdist247", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_248", property="harCurdist248", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_249", property="harCurdist249", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_250", property="harCurdist250", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_251", property="harCurdist251", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_252", property="harCurdist252", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_253", property="harCurdist253", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_254", property="harCurdist254", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_255", property="harCurdist255", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_256", property="harCurdist256", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_257", property="harCurdist257", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_258", property="harCurdist258", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_259", property="harCurdist259", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_260", property="harCurdist260", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_261", property="harCurdist261", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_262", property="harCurdist262", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_263", property="harCurdist263", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_264", property="harCurdist264", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_265", property="harCurdist265", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_266", property="harCurdist266", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_267", property="harCurdist267", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_268", property="harCurdist268", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_269", property="harCurdist269", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_270", property="harCurdist270", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_271", property="harCurdist271", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_272", property="harCurdist272", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_273", property="harCurdist273", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_274", property="harCurdist274", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_275", property="harCurdist275", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_276", property="harCurdist276", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_277", property="harCurdist277", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_278", property="harCurdist278", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_279", property="harCurdist279", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_280", property="harCurdist280", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_281", property="harCurdist281", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_282", property="harCurdist282", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_283", property="harCurdist283", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_284", property="harCurdist284", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_285", property="harCurdist285", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_286", property="harCurdist286", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_287", property="harCurdist287", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CURDIST_288", property="harCurdist288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_mhaiCurdistCurvePo> selectCurdistBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

}