package com.dao.mapper;

import com.dao.bean.D_mhaiCurCurvePo;
import com.dao.bean.D_mhaiCurCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_mhaiCurCurvePoMapper {

    @Select({
        "select",
        "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_CUR_1, HAR_CUR_2, ",
        "HAR_CUR_3, HAR_CUR_4, HAR_CUR_5, HAR_CUR_6, HAR_CUR_7, HAR_CUR_8, HAR_CUR_9, ",
        "HAR_CUR_10, HAR_CUR_11, HAR_CUR_12, HAR_CUR_13, HAR_CUR_14, HAR_CUR_15, HAR_CUR_16, ",
        "HAR_CUR_17, HAR_CUR_18, HAR_CUR_19, HAR_CUR_20, HAR_CUR_21, HAR_CUR_22, HAR_CUR_23, ",
        "HAR_CUR_24, HAR_CUR_25, HAR_CUR_26, HAR_CUR_27, HAR_CUR_28, HAR_CUR_29, HAR_CUR_30, ",
        "HAR_CUR_31, HAR_CUR_32, HAR_CUR_33, HAR_CUR_34, HAR_CUR_35, HAR_CUR_36, HAR_CUR_37, ",
        "HAR_CUR_38, HAR_CUR_39, HAR_CUR_40, HAR_CUR_41, HAR_CUR_42, HAR_CUR_43, HAR_CUR_44, ",
        "HAR_CUR_45, HAR_CUR_46, HAR_CUR_47, HAR_CUR_48, HAR_CUR_49, HAR_CUR_50, HAR_CUR_51, ",
        "HAR_CUR_52, HAR_CUR_53, HAR_CUR_54, HAR_CUR_55, HAR_CUR_56, HAR_CUR_57, HAR_CUR_58, ",
        "HAR_CUR_59, HAR_CUR_60, HAR_CUR_61, HAR_CUR_62, HAR_CUR_63, HAR_CUR_64, HAR_CUR_65, ",
        "HAR_CUR_66, HAR_CUR_67, HAR_CUR_68, HAR_CUR_69, HAR_CUR_70, HAR_CUR_71, HAR_CUR_72, ",
        "HAR_CUR_73, HAR_CUR_74, HAR_CUR_75, HAR_CUR_76, HAR_CUR_77, HAR_CUR_78, HAR_CUR_79, ",
        "HAR_CUR_80, HAR_CUR_81, HAR_CUR_82, HAR_CUR_83, HAR_CUR_84, HAR_CUR_85, HAR_CUR_86, ",
        "HAR_CUR_87, HAR_CUR_88, HAR_CUR_89, HAR_CUR_90, HAR_CUR_91, HAR_CUR_92, HAR_CUR_93, ",
        "HAR_CUR_94, HAR_CUR_95, HAR_CUR_96, HAR_CUR_97, HAR_CUR_98, HAR_CUR_99, HAR_CUR_100, ",
        "HAR_CUR_101, HAR_CUR_102, HAR_CUR_103, HAR_CUR_104, HAR_CUR_105, HAR_CUR_106, ",
        "HAR_CUR_107, HAR_CUR_108, HAR_CUR_109, HAR_CUR_110, HAR_CUR_111, HAR_CUR_112, ",
        "HAR_CUR_113, HAR_CUR_114, HAR_CUR_115, HAR_CUR_116, HAR_CUR_117, HAR_CUR_118, ",
        "HAR_CUR_119, HAR_CUR_120, HAR_CUR_121, HAR_CUR_122, HAR_CUR_123, HAR_CUR_124, ",
        "HAR_CUR_125, HAR_CUR_126, HAR_CUR_127, HAR_CUR_128, HAR_CUR_129, HAR_CUR_130, ",
        "HAR_CUR_131, HAR_CUR_132, HAR_CUR_133, HAR_CUR_134, HAR_CUR_135, HAR_CUR_136, ",
        "HAR_CUR_137, HAR_CUR_138, HAR_CUR_139, HAR_CUR_140, HAR_CUR_141, HAR_CUR_142, ",
        "HAR_CUR_143, HAR_CUR_144, HAR_CUR_145, HAR_CUR_146, HAR_CUR_147, HAR_CUR_148, ",
        "HAR_CUR_149, HAR_CUR_150, HAR_CUR_151, HAR_CUR_152, HAR_CUR_153, HAR_CUR_154, ",
        "HAR_CUR_155, HAR_CUR_156, HAR_CUR_157, HAR_CUR_158, HAR_CUR_159, HAR_CUR_160, ",
        "HAR_CUR_161, HAR_CUR_162, HAR_CUR_163, HAR_CUR_164, HAR_CUR_165, HAR_CUR_166, ",
        "HAR_CUR_167, HAR_CUR_168, HAR_CUR_169, HAR_CUR_170, HAR_CUR_171, HAR_CUR_172, ",
        "HAR_CUR_173, HAR_CUR_174, HAR_CUR_175, HAR_CUR_176, HAR_CUR_177, HAR_CUR_178, ",
        "HAR_CUR_179, HAR_CUR_180, HAR_CUR_181, HAR_CUR_182, HAR_CUR_183, HAR_CUR_184, ",
        "HAR_CUR_185, HAR_CUR_186, HAR_CUR_187, HAR_CUR_188, HAR_CUR_189, HAR_CUR_190, ",
        "HAR_CUR_191, HAR_CUR_192, HAR_CUR_193, HAR_CUR_194, HAR_CUR_195, HAR_CUR_196, ",
        "HAR_CUR_197, HAR_CUR_198, HAR_CUR_199, HAR_CUR_200, HAR_CUR_201, HAR_CUR_202, ",
        "HAR_CUR_203, HAR_CUR_204, HAR_CUR_205, HAR_CUR_206, HAR_CUR_207, HAR_CUR_208, ",
        "HAR_CUR_209, HAR_CUR_210, HAR_CUR_211, HAR_CUR_212, HAR_CUR_213, HAR_CUR_214, ",
        "HAR_CUR_215, HAR_CUR_216, HAR_CUR_217, HAR_CUR_218, HAR_CUR_219, HAR_CUR_220, ",
        "HAR_CUR_221, HAR_CUR_222, HAR_CUR_223, HAR_CUR_224, HAR_CUR_225, HAR_CUR_226, ",
        "HAR_CUR_227, HAR_CUR_228, HAR_CUR_229, HAR_CUR_230, HAR_CUR_231, HAR_CUR_232, ",
        "HAR_CUR_233, HAR_CUR_234, HAR_CUR_235, HAR_CUR_236, HAR_CUR_237, HAR_CUR_238, ",
        "HAR_CUR_239, HAR_CUR_240, HAR_CUR_241, HAR_CUR_242, HAR_CUR_243, HAR_CUR_244, ",
        "HAR_CUR_245, HAR_CUR_246, HAR_CUR_247, HAR_CUR_248, HAR_CUR_249, HAR_CUR_250, ",
        "HAR_CUR_251, HAR_CUR_252, HAR_CUR_253, HAR_CUR_254, HAR_CUR_255, HAR_CUR_256, ",
        "HAR_CUR_257, HAR_CUR_258, HAR_CUR_259, HAR_CUR_260, HAR_CUR_261, HAR_CUR_262, ",
        "HAR_CUR_263, HAR_CUR_264, HAR_CUR_265, HAR_CUR_266, HAR_CUR_267, HAR_CUR_268, ",
        "HAR_CUR_269, HAR_CUR_270, HAR_CUR_271, HAR_CUR_272, HAR_CUR_273, HAR_CUR_274, ",
        "HAR_CUR_275, HAR_CUR_276, HAR_CUR_277, HAR_CUR_278, HAR_CUR_279, HAR_CUR_280, ",
        "HAR_CUR_281, HAR_CUR_282, HAR_CUR_283, HAR_CUR_284, HAR_CUR_285, HAR_CUR_286, ",
        "HAR_CUR_287, HAR_CUR_288",
        "from c_mhai_cur_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="HAR_CUR_1", property="harCur1", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_2", property="harCur2", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_3", property="harCur3", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_4", property="harCur4", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_5", property="harCur5", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_6", property="harCur6", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_7", property="harCur7", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_8", property="harCur8", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_9", property="harCur9", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_10", property="harCur10", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_11", property="harCur11", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_12", property="harCur12", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_13", property="harCur13", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_14", property="harCur14", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_15", property="harCur15", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_16", property="harCur16", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_17", property="harCur17", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_18", property="harCur18", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_19", property="harCur19", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_20", property="harCur20", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_21", property="harCur21", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_22", property="harCur22", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_23", property="harCur23", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_24", property="harCur24", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_25", property="harCur25", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_26", property="harCur26", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_27", property="harCur27", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_28", property="harCur28", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_29", property="harCur29", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_30", property="harCur30", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_31", property="harCur31", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_32", property="harCur32", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_33", property="harCur33", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_34", property="harCur34", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_35", property="harCur35", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_36", property="harCur36", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_37", property="harCur37", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_38", property="harCur38", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_39", property="harCur39", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_40", property="harCur40", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_41", property="harCur41", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_42", property="harCur42", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_43", property="harCur43", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_44", property="harCur44", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_45", property="harCur45", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_46", property="harCur46", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_47", property="harCur47", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_48", property="harCur48", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_49", property="harCur49", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_50", property="harCur50", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_51", property="harCur51", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_52", property="harCur52", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_53", property="harCur53", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_54", property="harCur54", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_55", property="harCur55", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_56", property="harCur56", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_57", property="harCur57", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_58", property="harCur58", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_59", property="harCur59", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_60", property="harCur60", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_61", property="harCur61", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_62", property="harCur62", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_63", property="harCur63", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_64", property="harCur64", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_65", property="harCur65", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_66", property="harCur66", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_67", property="harCur67", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_68", property="harCur68", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_69", property="harCur69", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_70", property="harCur70", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_71", property="harCur71", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_72", property="harCur72", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_73", property="harCur73", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_74", property="harCur74", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_75", property="harCur75", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_76", property="harCur76", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_77", property="harCur77", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_78", property="harCur78", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_79", property="harCur79", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_80", property="harCur80", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_81", property="harCur81", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_82", property="harCur82", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_83", property="harCur83", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_84", property="harCur84", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_85", property="harCur85", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_86", property="harCur86", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_87", property="harCur87", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_88", property="harCur88", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_89", property="harCur89", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_90", property="harCur90", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_91", property="harCur91", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_92", property="harCur92", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_93", property="harCur93", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_94", property="harCur94", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_95", property="harCur95", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_96", property="harCur96", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_97", property="harCur97", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_98", property="harCur98", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_99", property="harCur99", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_100", property="harCur100", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_101", property="harCur101", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_102", property="harCur102", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_103", property="harCur103", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_104", property="harCur104", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_105", property="harCur105", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_106", property="harCur106", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_107", property="harCur107", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_108", property="harCur108", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_109", property="harCur109", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_110", property="harCur110", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_111", property="harCur111", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_112", property="harCur112", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_113", property="harCur113", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_114", property="harCur114", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_115", property="harCur115", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_116", property="harCur116", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_117", property="harCur117", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_118", property="harCur118", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_119", property="harCur119", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_120", property="harCur120", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_121", property="harCur121", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_122", property="harCur122", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_123", property="harCur123", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_124", property="harCur124", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_125", property="harCur125", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_126", property="harCur126", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_127", property="harCur127", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_128", property="harCur128", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_129", property="harCur129", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_130", property="harCur130", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_131", property="harCur131", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_132", property="harCur132", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_133", property="harCur133", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_134", property="harCur134", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_135", property="harCur135", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_136", property="harCur136", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_137", property="harCur137", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_138", property="harCur138", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_139", property="harCur139", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_140", property="harCur140", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_141", property="harCur141", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_142", property="harCur142", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_143", property="harCur143", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_144", property="harCur144", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_145", property="harCur145", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_146", property="harCur146", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_147", property="harCur147", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_148", property="harCur148", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_149", property="harCur149", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_150", property="harCur150", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_151", property="harCur151", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_152", property="harCur152", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_153", property="harCur153", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_154", property="harCur154", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_155", property="harCur155", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_156", property="harCur156", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_157", property="harCur157", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_158", property="harCur158", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_159", property="harCur159", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_160", property="harCur160", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_161", property="harCur161", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_162", property="harCur162", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_163", property="harCur163", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_164", property="harCur164", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_165", property="harCur165", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_166", property="harCur166", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_167", property="harCur167", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_168", property="harCur168", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_169", property="harCur169", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_170", property="harCur170", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_171", property="harCur171", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_172", property="harCur172", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_173", property="harCur173", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_174", property="harCur174", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_175", property="harCur175", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_176", property="harCur176", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_177", property="harCur177", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_178", property="harCur178", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_179", property="harCur179", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_180", property="harCur180", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_181", property="harCur181", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_182", property="harCur182", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_183", property="harCur183", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_184", property="harCur184", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_185", property="harCur185", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_186", property="harCur186", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_187", property="harCur187", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_188", property="harCur188", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_189", property="harCur189", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_190", property="harCur190", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_191", property="harCur191", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_192", property="harCur192", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_193", property="harCur193", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_194", property="harCur194", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_195", property="harCur195", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_196", property="harCur196", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_197", property="harCur197", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_198", property="harCur198", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_199", property="harCur199", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_200", property="harCur200", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_201", property="harCur201", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_202", property="harCur202", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_203", property="harCur203", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_204", property="harCur204", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_205", property="harCur205", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_206", property="harCur206", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_207", property="harCur207", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_208", property="harCur208", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_209", property="harCur209", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_210", property="harCur210", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_211", property="harCur211", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_212", property="harCur212", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_213", property="harCur213", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_214", property="harCur214", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_215", property="harCur215", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_216", property="harCur216", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_217", property="harCur217", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_218", property="harCur218", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_219", property="harCur219", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_220", property="harCur220", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_221", property="harCur221", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_222", property="harCur222", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_223", property="harCur223", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_224", property="harCur224", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_225", property="harCur225", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_226", property="harCur226", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_227", property="harCur227", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_228", property="harCur228", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_229", property="harCur229", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_230", property="harCur230", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_231", property="harCur231", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_232", property="harCur232", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_233", property="harCur233", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_234", property="harCur234", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_235", property="harCur235", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_236", property="harCur236", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_237", property="harCur237", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_238", property="harCur238", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_239", property="harCur239", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_240", property="harCur240", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_241", property="harCur241", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_242", property="harCur242", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_243", property="harCur243", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_244", property="harCur244", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_245", property="harCur245", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_246", property="harCur246", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_247", property="harCur247", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_248", property="harCur248", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_249", property="harCur249", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_250", property="harCur250", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_251", property="harCur251", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_252", property="harCur252", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_253", property="harCur253", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_254", property="harCur254", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_255", property="harCur255", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_256", property="harCur256", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_257", property="harCur257", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_258", property="harCur258", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_259", property="harCur259", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_260", property="harCur260", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_261", property="harCur261", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_262", property="harCur262", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_263", property="harCur263", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_264", property="harCur264", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_265", property="harCur265", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_266", property="harCur266", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_267", property="harCur267", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_268", property="harCur268", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_269", property="harCur269", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_270", property="harCur270", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_271", property="harCur271", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_272", property="harCur272", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_273", property="harCur273", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_274", property="harCur274", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_275", property="harCur275", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_276", property="harCur276", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_277", property="harCur277", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_278", property="harCur278", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_279", property="harCur279", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_280", property="harCur280", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_281", property="harCur281", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_282", property="harCur282", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_283", property="harCur283", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_284", property="harCur284", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_285", property="harCur285", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_286", property="harCur286", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_287", property="harCur287", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_CUR_288", property="harCur288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_mhaiCurCurvePo> selectHhaiCurByDate(String data_date);


    @Select({
            "select",
            "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_CUR_1, HAR_CUR_2, ",
            "HAR_CUR_3, HAR_CUR_4, HAR_CUR_5, HAR_CUR_6, HAR_CUR_7, HAR_CUR_8, HAR_CUR_9, ",
            "HAR_CUR_10, HAR_CUR_11, HAR_CUR_12, HAR_CUR_13, HAR_CUR_14, HAR_CUR_15, HAR_CUR_16, ",
            "HAR_CUR_17, HAR_CUR_18, HAR_CUR_19, HAR_CUR_20, HAR_CUR_21, HAR_CUR_22, HAR_CUR_23, ",
            "HAR_CUR_24, HAR_CUR_25, HAR_CUR_26, HAR_CUR_27, HAR_CUR_28, HAR_CUR_29, HAR_CUR_30, ",
            "HAR_CUR_31, HAR_CUR_32, HAR_CUR_33, HAR_CUR_34, HAR_CUR_35, HAR_CUR_36, HAR_CUR_37, ",
            "HAR_CUR_38, HAR_CUR_39, HAR_CUR_40, HAR_CUR_41, HAR_CUR_42, HAR_CUR_43, HAR_CUR_44, ",
            "HAR_CUR_45, HAR_CUR_46, HAR_CUR_47, HAR_CUR_48, HAR_CUR_49, HAR_CUR_50, HAR_CUR_51, ",
            "HAR_CUR_52, HAR_CUR_53, HAR_CUR_54, HAR_CUR_55, HAR_CUR_56, HAR_CUR_57, HAR_CUR_58, ",
            "HAR_CUR_59, HAR_CUR_60, HAR_CUR_61, HAR_CUR_62, HAR_CUR_63, HAR_CUR_64, HAR_CUR_65, ",
            "HAR_CUR_66, HAR_CUR_67, HAR_CUR_68, HAR_CUR_69, HAR_CUR_70, HAR_CUR_71, HAR_CUR_72, ",
            "HAR_CUR_73, HAR_CUR_74, HAR_CUR_75, HAR_CUR_76, HAR_CUR_77, HAR_CUR_78, HAR_CUR_79, ",
            "HAR_CUR_80, HAR_CUR_81, HAR_CUR_82, HAR_CUR_83, HAR_CUR_84, HAR_CUR_85, HAR_CUR_86, ",
            "HAR_CUR_87, HAR_CUR_88, HAR_CUR_89, HAR_CUR_90, HAR_CUR_91, HAR_CUR_92, HAR_CUR_93, ",
            "HAR_CUR_94, HAR_CUR_95, HAR_CUR_96, HAR_CUR_97, HAR_CUR_98, HAR_CUR_99, HAR_CUR_100, ",
            "HAR_CUR_101, HAR_CUR_102, HAR_CUR_103, HAR_CUR_104, HAR_CUR_105, HAR_CUR_106, ",
            "HAR_CUR_107, HAR_CUR_108, HAR_CUR_109, HAR_CUR_110, HAR_CUR_111, HAR_CUR_112, ",
            "HAR_CUR_113, HAR_CUR_114, HAR_CUR_115, HAR_CUR_116, HAR_CUR_117, HAR_CUR_118, ",
            "HAR_CUR_119, HAR_CUR_120, HAR_CUR_121, HAR_CUR_122, HAR_CUR_123, HAR_CUR_124, ",
            "HAR_CUR_125, HAR_CUR_126, HAR_CUR_127, HAR_CUR_128, HAR_CUR_129, HAR_CUR_130, ",
            "HAR_CUR_131, HAR_CUR_132, HAR_CUR_133, HAR_CUR_134, HAR_CUR_135, HAR_CUR_136, ",
            "HAR_CUR_137, HAR_CUR_138, HAR_CUR_139, HAR_CUR_140, HAR_CUR_141, HAR_CUR_142, ",
            "HAR_CUR_143, HAR_CUR_144, HAR_CUR_145, HAR_CUR_146, HAR_CUR_147, HAR_CUR_148, ",
            "HAR_CUR_149, HAR_CUR_150, HAR_CUR_151, HAR_CUR_152, HAR_CUR_153, HAR_CUR_154, ",
            "HAR_CUR_155, HAR_CUR_156, HAR_CUR_157, HAR_CUR_158, HAR_CUR_159, HAR_CUR_160, ",
            "HAR_CUR_161, HAR_CUR_162, HAR_CUR_163, HAR_CUR_164, HAR_CUR_165, HAR_CUR_166, ",
            "HAR_CUR_167, HAR_CUR_168, HAR_CUR_169, HAR_CUR_170, HAR_CUR_171, HAR_CUR_172, ",
            "HAR_CUR_173, HAR_CUR_174, HAR_CUR_175, HAR_CUR_176, HAR_CUR_177, HAR_CUR_178, ",
            "HAR_CUR_179, HAR_CUR_180, HAR_CUR_181, HAR_CUR_182, HAR_CUR_183, HAR_CUR_184, ",
            "HAR_CUR_185, HAR_CUR_186, HAR_CUR_187, HAR_CUR_188, HAR_CUR_189, HAR_CUR_190, ",
            "HAR_CUR_191, HAR_CUR_192, HAR_CUR_193, HAR_CUR_194, HAR_CUR_195, HAR_CUR_196, ",
            "HAR_CUR_197, HAR_CUR_198, HAR_CUR_199, HAR_CUR_200, HAR_CUR_201, HAR_CUR_202, ",
            "HAR_CUR_203, HAR_CUR_204, HAR_CUR_205, HAR_CUR_206, HAR_CUR_207, HAR_CUR_208, ",
            "HAR_CUR_209, HAR_CUR_210, HAR_CUR_211, HAR_CUR_212, HAR_CUR_213, HAR_CUR_214, ",
            "HAR_CUR_215, HAR_CUR_216, HAR_CUR_217, HAR_CUR_218, HAR_CUR_219, HAR_CUR_220, ",
            "HAR_CUR_221, HAR_CUR_222, HAR_CUR_223, HAR_CUR_224, HAR_CUR_225, HAR_CUR_226, ",
            "HAR_CUR_227, HAR_CUR_228, HAR_CUR_229, HAR_CUR_230, HAR_CUR_231, HAR_CUR_232, ",
            "HAR_CUR_233, HAR_CUR_234, HAR_CUR_235, HAR_CUR_236, HAR_CUR_237, HAR_CUR_238, ",
            "HAR_CUR_239, HAR_CUR_240, HAR_CUR_241, HAR_CUR_242, HAR_CUR_243, HAR_CUR_244, ",
            "HAR_CUR_245, HAR_CUR_246, HAR_CUR_247, HAR_CUR_248, HAR_CUR_249, HAR_CUR_250, ",
            "HAR_CUR_251, HAR_CUR_252, HAR_CUR_253, HAR_CUR_254, HAR_CUR_255, HAR_CUR_256, ",
            "HAR_CUR_257, HAR_CUR_258, HAR_CUR_259, HAR_CUR_260, HAR_CUR_261, HAR_CUR_262, ",
            "HAR_CUR_263, HAR_CUR_264, HAR_CUR_265, HAR_CUR_266, HAR_CUR_267, HAR_CUR_268, ",
            "HAR_CUR_269, HAR_CUR_270, HAR_CUR_271, HAR_CUR_272, HAR_CUR_273, HAR_CUR_274, ",
            "HAR_CUR_275, HAR_CUR_276, HAR_CUR_277, HAR_CUR_278, HAR_CUR_279, HAR_CUR_280, ",
            "HAR_CUR_281, HAR_CUR_282, HAR_CUR_283, HAR_CUR_284, HAR_CUR_285, HAR_CUR_286, ",
            "HAR_CUR_287, HAR_CUR_288",
            "from c_mhai_cur_c ",
            "where  DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="HAR_CUR_1", property="harCur1", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_2", property="harCur2", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_3", property="harCur3", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_4", property="harCur4", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_5", property="harCur5", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_6", property="harCur6", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_7", property="harCur7", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_8", property="harCur8", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_9", property="harCur9", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_10", property="harCur10", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_11", property="harCur11", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_12", property="harCur12", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_13", property="harCur13", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_14", property="harCur14", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_15", property="harCur15", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_16", property="harCur16", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_17", property="harCur17", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_18", property="harCur18", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_19", property="harCur19", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_20", property="harCur20", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_21", property="harCur21", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_22", property="harCur22", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_23", property="harCur23", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_24", property="harCur24", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_25", property="harCur25", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_26", property="harCur26", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_27", property="harCur27", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_28", property="harCur28", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_29", property="harCur29", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_30", property="harCur30", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_31", property="harCur31", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_32", property="harCur32", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_33", property="harCur33", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_34", property="harCur34", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_35", property="harCur35", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_36", property="harCur36", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_37", property="harCur37", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_38", property="harCur38", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_39", property="harCur39", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_40", property="harCur40", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_41", property="harCur41", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_42", property="harCur42", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_43", property="harCur43", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_44", property="harCur44", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_45", property="harCur45", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_46", property="harCur46", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_47", property="harCur47", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_48", property="harCur48", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_49", property="harCur49", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_50", property="harCur50", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_51", property="harCur51", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_52", property="harCur52", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_53", property="harCur53", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_54", property="harCur54", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_55", property="harCur55", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_56", property="harCur56", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_57", property="harCur57", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_58", property="harCur58", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_59", property="harCur59", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_60", property="harCur60", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_61", property="harCur61", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_62", property="harCur62", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_63", property="harCur63", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_64", property="harCur64", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_65", property="harCur65", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_66", property="harCur66", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_67", property="harCur67", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_68", property="harCur68", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_69", property="harCur69", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_70", property="harCur70", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_71", property="harCur71", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_72", property="harCur72", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_73", property="harCur73", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_74", property="harCur74", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_75", property="harCur75", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_76", property="harCur76", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_77", property="harCur77", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_78", property="harCur78", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_79", property="harCur79", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_80", property="harCur80", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_81", property="harCur81", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_82", property="harCur82", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_83", property="harCur83", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_84", property="harCur84", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_85", property="harCur85", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_86", property="harCur86", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_87", property="harCur87", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_88", property="harCur88", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_89", property="harCur89", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_90", property="harCur90", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_91", property="harCur91", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_92", property="harCur92", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_93", property="harCur93", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_94", property="harCur94", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_95", property="harCur95", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_96", property="harCur96", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_97", property="harCur97", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_98", property="harCur98", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_99", property="harCur99", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_100", property="harCur100", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_101", property="harCur101", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_102", property="harCur102", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_103", property="harCur103", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_104", property="harCur104", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_105", property="harCur105", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_106", property="harCur106", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_107", property="harCur107", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_108", property="harCur108", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_109", property="harCur109", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_110", property="harCur110", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_111", property="harCur111", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_112", property="harCur112", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_113", property="harCur113", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_114", property="harCur114", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_115", property="harCur115", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_116", property="harCur116", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_117", property="harCur117", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_118", property="harCur118", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_119", property="harCur119", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_120", property="harCur120", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_121", property="harCur121", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_122", property="harCur122", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_123", property="harCur123", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_124", property="harCur124", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_125", property="harCur125", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_126", property="harCur126", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_127", property="harCur127", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_128", property="harCur128", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_129", property="harCur129", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_130", property="harCur130", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_131", property="harCur131", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_132", property="harCur132", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_133", property="harCur133", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_134", property="harCur134", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_135", property="harCur135", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_136", property="harCur136", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_137", property="harCur137", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_138", property="harCur138", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_139", property="harCur139", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_140", property="harCur140", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_141", property="harCur141", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_142", property="harCur142", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_143", property="harCur143", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_144", property="harCur144", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_145", property="harCur145", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_146", property="harCur146", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_147", property="harCur147", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_148", property="harCur148", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_149", property="harCur149", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_150", property="harCur150", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_151", property="harCur151", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_152", property="harCur152", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_153", property="harCur153", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_154", property="harCur154", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_155", property="harCur155", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_156", property="harCur156", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_157", property="harCur157", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_158", property="harCur158", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_159", property="harCur159", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_160", property="harCur160", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_161", property="harCur161", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_162", property="harCur162", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_163", property="harCur163", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_164", property="harCur164", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_165", property="harCur165", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_166", property="harCur166", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_167", property="harCur167", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_168", property="harCur168", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_169", property="harCur169", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_170", property="harCur170", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_171", property="harCur171", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_172", property="harCur172", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_173", property="harCur173", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_174", property="harCur174", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_175", property="harCur175", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_176", property="harCur176", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_177", property="harCur177", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_178", property="harCur178", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_179", property="harCur179", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_180", property="harCur180", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_181", property="harCur181", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_182", property="harCur182", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_183", property="harCur183", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_184", property="harCur184", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_185", property="harCur185", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_186", property="harCur186", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_187", property="harCur187", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_188", property="harCur188", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_189", property="harCur189", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_190", property="harCur190", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_191", property="harCur191", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_192", property="harCur192", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_193", property="harCur193", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_194", property="harCur194", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_195", property="harCur195", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_196", property="harCur196", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_197", property="harCur197", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_198", property="harCur198", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_199", property="harCur199", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_200", property="harCur200", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_201", property="harCur201", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_202", property="harCur202", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_203", property="harCur203", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_204", property="harCur204", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_205", property="harCur205", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_206", property="harCur206", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_207", property="harCur207", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_208", property="harCur208", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_209", property="harCur209", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_210", property="harCur210", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_211", property="harCur211", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_212", property="harCur212", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_213", property="harCur213", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_214", property="harCur214", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_215", property="harCur215", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_216", property="harCur216", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_217", property="harCur217", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_218", property="harCur218", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_219", property="harCur219", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_220", property="harCur220", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_221", property="harCur221", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_222", property="harCur222", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_223", property="harCur223", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_224", property="harCur224", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_225", property="harCur225", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_226", property="harCur226", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_227", property="harCur227", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_228", property="harCur228", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_229", property="harCur229", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_230", property="harCur230", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_231", property="harCur231", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_232", property="harCur232", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_233", property="harCur233", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_234", property="harCur234", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_235", property="harCur235", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_236", property="harCur236", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_237", property="harCur237", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_238", property="harCur238", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_239", property="harCur239", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_240", property="harCur240", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_241", property="harCur241", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_242", property="harCur242", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_243", property="harCur243", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_244", property="harCur244", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_245", property="harCur245", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_246", property="harCur246", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_247", property="harCur247", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_248", property="harCur248", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_249", property="harCur249", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_250", property="harCur250", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_251", property="harCur251", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_252", property="harCur252", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_253", property="harCur253", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_254", property="harCur254", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_255", property="harCur255", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_256", property="harCur256", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_257", property="harCur257", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_258", property="harCur258", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_259", property="harCur259", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_260", property="harCur260", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_261", property="harCur261", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_262", property="harCur262", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_263", property="harCur263", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_264", property="harCur264", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_265", property="harCur265", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_266", property="harCur266", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_267", property="harCur267", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_268", property="harCur268", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_269", property="harCur269", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_270", property="harCur270", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_271", property="harCur271", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_272", property="harCur272", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_273", property="harCur273", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_274", property="harCur274", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_275", property="harCur275", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_276", property="harCur276", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_277", property="harCur277", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_278", property="harCur278", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_279", property="harCur279", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_280", property="harCur280", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_281", property="harCur281", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_282", property="harCur282", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_283", property="harCur283", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_284", property="harCur284", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_285", property="harCur285", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_286", property="harCur286", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_287", property="harCur287", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_CUR_288", property="harCur288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_mhaiCurCurvePo> selectHhaiCurBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);
}