package com.dao.mapper;

import com.dao.bean.D_mhaiVolCurvePo;
import com.dao.bean.D_mhaiVolCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_mhaiVolCurvePoMapper {

    @Select({
        "select",
        "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_VOL_1, HAR_VOL_2, ",
        "HAR_VOL_3, HAR_VOL_4, HAR_VOL_5, HAR_VOL_6, HAR_VOL_7, HAR_VOL_8, HAR_VOL_9, ",
        "HAR_VOL_10, HAR_VOL_11, HAR_VOL_12, HAR_VOL_13, HAR_VOL_14, HAR_VOL_15, HAR_VOL_16, ",
        "HAR_VOL_17, HAR_VOL_18, HAR_VOL_19, HAR_VOL_20, HAR_VOL_21, HAR_VOL_22, HAR_VOL_23, ",
        "HAR_VOL_24, HAR_VOL_25, HAR_VOL_26, HAR_VOL_27, HAR_VOL_28, HAR_VOL_29, HAR_VOL_30, ",
        "HAR_VOL_31, HAR_VOL_32, HAR_VOL_33, HAR_VOL_34, HAR_VOL_35, HAR_VOL_36, HAR_VOL_37, ",
        "HAR_VOL_38, HAR_VOL_39, HAR_VOL_40, HAR_VOL_41, HAR_VOL_42, HAR_VOL_43, HAR_VOL_44, ",
        "HAR_VOL_45, HAR_VOL_46, HAR_VOL_47, HAR_VOL_48, HAR_VOL_49, HAR_VOL_50, HAR_VOL_51, ",
        "HAR_VOL_52, HAR_VOL_53, HAR_VOL_54, HAR_VOL_55, HAR_VOL_56, HAR_VOL_57, HAR_VOL_58, ",
        "HAR_VOL_59, HAR_VOL_60, HAR_VOL_61, HAR_VOL_62, HAR_VOL_63, HAR_VOL_64, HAR_VOL_65, ",
        "HAR_VOL_66, HAR_VOL_67, HAR_VOL_68, HAR_VOL_69, HAR_VOL_70, HAR_VOL_71, HAR_VOL_72, ",
        "HAR_VOL_73, HAR_VOL_74, HAR_VOL_75, HAR_VOL_76, HAR_VOL_77, HAR_VOL_78, HAR_VOL_79, ",
        "HAR_VOL_80, HAR_VOL_81, HAR_VOL_82, HAR_VOL_83, HAR_VOL_84, HAR_VOL_85, HAR_VOL_86, ",
        "HAR_VOL_87, HAR_VOL_88, HAR_VOL_89, HAR_VOL_90, HAR_VOL_91, HAR_VOL_92, HAR_VOL_93, ",
        "HAR_VOL_94, HAR_VOL_95, HAR_VOL_96, HAR_VOL_97, HAR_VOL_98, HAR_VOL_99, HAR_VOL_100, ",
        "HAR_VOL_101, HAR_VOL_102, HAR_VOL_103, HAR_VOL_104, HAR_VOL_105, HAR_VOL_106, ",
        "HAR_VOL_107, HAR_VOL_108, HAR_VOL_109, HAR_VOL_110, HAR_VOL_111, HAR_VOL_112, ",
        "HAR_VOL_113, HAR_VOL_114, HAR_VOL_115, HAR_VOL_116, HAR_VOL_117, HAR_VOL_118, ",
        "HAR_VOL_119, HAR_VOL_120, HAR_VOL_121, HAR_VOL_122, HAR_VOL_123, HAR_VOL_124, ",
        "HAR_VOL_125, HAR_VOL_126, HAR_VOL_127, HAR_VOL_128, HAR_VOL_129, HAR_VOL_130, ",
        "HAR_VOL_131, HAR_VOL_132, HAR_VOL_133, HAR_VOL_134, HAR_VOL_135, HAR_VOL_136, ",
        "HAR_VOL_137, HAR_VOL_138, HAR_VOL_139, HAR_VOL_140, HAR_VOL_141, HAR_VOL_142, ",
        "HAR_VOL_143, HAR_VOL_144, HAR_VOL_145, HAR_VOL_146, HAR_VOL_147, HAR_VOL_148, ",
        "HAR_VOL_149, HAR_VOL_150, HAR_VOL_151, HAR_VOL_152, HAR_VOL_153, HAR_VOL_154, ",
        "HAR_VOL_155, HAR_VOL_156, HAR_VOL_157, HAR_VOL_158, HAR_VOL_159, HAR_VOL_160, ",
        "HAR_VOL_161, HAR_VOL_162, HAR_VOL_163, HAR_VOL_164, HAR_VOL_165, HAR_VOL_166, ",
        "HAR_VOL_167, HAR_VOL_168, HAR_VOL_169, HAR_VOL_170, HAR_VOL_171, HAR_VOL_172, ",
        "HAR_VOL_173, HAR_VOL_174, HAR_VOL_175, HAR_VOL_176, HAR_VOL_177, HAR_VOL_178, ",
        "HAR_VOL_179, HAR_VOL_180, HAR_VOL_181, HAR_VOL_182, HAR_VOL_183, HAR_VOL_184, ",
        "HAR_VOL_185, HAR_VOL_186, HAR_VOL_187, HAR_VOL_188, HAR_VOL_189, HAR_VOL_190, ",
        "HAR_VOL_191, HAR_VOL_192, HAR_VOL_193, HAR_VOL_194, HAR_VOL_195, HAR_VOL_196, ",
        "HAR_VOL_197, HAR_VOL_198, HAR_VOL_199, HAR_VOL_200, HAR_VOL_201, HAR_VOL_202, ",
        "HAR_VOL_203, HAR_VOL_204, HAR_VOL_205, HAR_VOL_206, HAR_VOL_207, HAR_VOL_208, ",
        "HAR_VOL_209, HAR_VOL_210, HAR_VOL_211, HAR_VOL_212, HAR_VOL_213, HAR_VOL_214, ",
        "HAR_VOL_215, HAR_VOL_216, HAR_VOL_217, HAR_VOL_218, HAR_VOL_219, HAR_VOL_220, ",
        "HAR_VOL_221, HAR_VOL_222, HAR_VOL_223, HAR_VOL_224, HAR_VOL_225, HAR_VOL_226, ",
        "HAR_VOL_227, HAR_VOL_228, HAR_VOL_229, HAR_VOL_230, HAR_VOL_231, HAR_VOL_232, ",
        "HAR_VOL_233, HAR_VOL_234, HAR_VOL_235, HAR_VOL_236, HAR_VOL_237, HAR_VOL_238, ",
        "HAR_VOL_239, HAR_VOL_240, HAR_VOL_241, HAR_VOL_242, HAR_VOL_243, HAR_VOL_244, ",
        "HAR_VOL_245, HAR_VOL_246, HAR_VOL_247, HAR_VOL_248, HAR_VOL_249, HAR_VOL_250, ",
        "HAR_VOL_251, HAR_VOL_252, HAR_VOL_253, HAR_VOL_254, HAR_VOL_255, HAR_VOL_256, ",
        "HAR_VOL_257, HAR_VOL_258, HAR_VOL_259, HAR_VOL_260, HAR_VOL_261, HAR_VOL_262, ",
        "HAR_VOL_263, HAR_VOL_264, HAR_VOL_265, HAR_VOL_266, HAR_VOL_267, HAR_VOL_268, ",
        "HAR_VOL_269, HAR_VOL_270, HAR_VOL_271, HAR_VOL_272, HAR_VOL_273, HAR_VOL_274, ",
        "HAR_VOL_275, HAR_VOL_276, HAR_VOL_277, HAR_VOL_278, HAR_VOL_279, HAR_VOL_280, ",
        "HAR_VOL_281, HAR_VOL_282, HAR_VOL_283, HAR_VOL_284, HAR_VOL_285, HAR_VOL_286, ",
        "HAR_VOL_287, HAR_VOL_288",
        "from c_mhai_vol_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="HAR_VOL_1", property="harVol1", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_2", property="harVol2", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_3", property="harVol3", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_4", property="harVol4", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_5", property="harVol5", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_6", property="harVol6", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_7", property="harVol7", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_8", property="harVol8", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_9", property="harVol9", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_10", property="harVol10", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_11", property="harVol11", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_12", property="harVol12", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_13", property="harVol13", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_14", property="harVol14", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_15", property="harVol15", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_16", property="harVol16", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_17", property="harVol17", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_18", property="harVol18", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_19", property="harVol19", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_20", property="harVol20", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_21", property="harVol21", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_22", property="harVol22", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_23", property="harVol23", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_24", property="harVol24", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_25", property="harVol25", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_26", property="harVol26", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_27", property="harVol27", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_28", property="harVol28", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_29", property="harVol29", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_30", property="harVol30", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_31", property="harVol31", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_32", property="harVol32", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_33", property="harVol33", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_34", property="harVol34", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_35", property="harVol35", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_36", property="harVol36", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_37", property="harVol37", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_38", property="harVol38", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_39", property="harVol39", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_40", property="harVol40", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_41", property="harVol41", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_42", property="harVol42", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_43", property="harVol43", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_44", property="harVol44", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_45", property="harVol45", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_46", property="harVol46", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_47", property="harVol47", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_48", property="harVol48", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_49", property="harVol49", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_50", property="harVol50", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_51", property="harVol51", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_52", property="harVol52", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_53", property="harVol53", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_54", property="harVol54", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_55", property="harVol55", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_56", property="harVol56", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_57", property="harVol57", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_58", property="harVol58", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_59", property="harVol59", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_60", property="harVol60", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_61", property="harVol61", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_62", property="harVol62", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_63", property="harVol63", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_64", property="harVol64", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_65", property="harVol65", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_66", property="harVol66", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_67", property="harVol67", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_68", property="harVol68", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_69", property="harVol69", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_70", property="harVol70", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_71", property="harVol71", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_72", property="harVol72", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_73", property="harVol73", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_74", property="harVol74", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_75", property="harVol75", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_76", property="harVol76", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_77", property="harVol77", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_78", property="harVol78", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_79", property="harVol79", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_80", property="harVol80", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_81", property="harVol81", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_82", property="harVol82", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_83", property="harVol83", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_84", property="harVol84", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_85", property="harVol85", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_86", property="harVol86", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_87", property="harVol87", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_88", property="harVol88", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_89", property="harVol89", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_90", property="harVol90", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_91", property="harVol91", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_92", property="harVol92", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_93", property="harVol93", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_94", property="harVol94", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_95", property="harVol95", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_96", property="harVol96", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_97", property="harVol97", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_98", property="harVol98", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_99", property="harVol99", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_100", property="harVol100", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_101", property="harVol101", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_102", property="harVol102", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_103", property="harVol103", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_104", property="harVol104", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_105", property="harVol105", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_106", property="harVol106", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_107", property="harVol107", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_108", property="harVol108", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_109", property="harVol109", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_110", property="harVol110", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_111", property="harVol111", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_112", property="harVol112", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_113", property="harVol113", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_114", property="harVol114", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_115", property="harVol115", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_116", property="harVol116", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_117", property="harVol117", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_118", property="harVol118", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_119", property="harVol119", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_120", property="harVol120", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_121", property="harVol121", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_122", property="harVol122", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_123", property="harVol123", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_124", property="harVol124", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_125", property="harVol125", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_126", property="harVol126", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_127", property="harVol127", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_128", property="harVol128", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_129", property="harVol129", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_130", property="harVol130", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_131", property="harVol131", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_132", property="harVol132", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_133", property="harVol133", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_134", property="harVol134", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_135", property="harVol135", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_136", property="harVol136", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_137", property="harVol137", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_138", property="harVol138", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_139", property="harVol139", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_140", property="harVol140", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_141", property="harVol141", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_142", property="harVol142", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_143", property="harVol143", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_144", property="harVol144", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_145", property="harVol145", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_146", property="harVol146", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_147", property="harVol147", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_148", property="harVol148", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_149", property="harVol149", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_150", property="harVol150", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_151", property="harVol151", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_152", property="harVol152", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_153", property="harVol153", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_154", property="harVol154", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_155", property="harVol155", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_156", property="harVol156", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_157", property="harVol157", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_158", property="harVol158", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_159", property="harVol159", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_160", property="harVol160", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_161", property="harVol161", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_162", property="harVol162", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_163", property="harVol163", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_164", property="harVol164", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_165", property="harVol165", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_166", property="harVol166", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_167", property="harVol167", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_168", property="harVol168", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_169", property="harVol169", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_170", property="harVol170", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_171", property="harVol171", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_172", property="harVol172", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_173", property="harVol173", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_174", property="harVol174", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_175", property="harVol175", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_176", property="harVol176", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_177", property="harVol177", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_178", property="harVol178", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_179", property="harVol179", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_180", property="harVol180", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_181", property="harVol181", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_182", property="harVol182", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_183", property="harVol183", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_184", property="harVol184", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_185", property="harVol185", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_186", property="harVol186", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_187", property="harVol187", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_188", property="harVol188", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_189", property="harVol189", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_190", property="harVol190", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_191", property="harVol191", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_192", property="harVol192", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_193", property="harVol193", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_194", property="harVol194", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_195", property="harVol195", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_196", property="harVol196", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_197", property="harVol197", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_198", property="harVol198", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_199", property="harVol199", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_200", property="harVol200", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_201", property="harVol201", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_202", property="harVol202", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_203", property="harVol203", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_204", property="harVol204", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_205", property="harVol205", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_206", property="harVol206", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_207", property="harVol207", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_208", property="harVol208", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_209", property="harVol209", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_210", property="harVol210", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_211", property="harVol211", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_212", property="harVol212", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_213", property="harVol213", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_214", property="harVol214", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_215", property="harVol215", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_216", property="harVol216", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_217", property="harVol217", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_218", property="harVol218", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_219", property="harVol219", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_220", property="harVol220", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_221", property="harVol221", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_222", property="harVol222", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_223", property="harVol223", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_224", property="harVol224", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_225", property="harVol225", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_226", property="harVol226", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_227", property="harVol227", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_228", property="harVol228", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_229", property="harVol229", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_230", property="harVol230", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_231", property="harVol231", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_232", property="harVol232", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_233", property="harVol233", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_234", property="harVol234", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_235", property="harVol235", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_236", property="harVol236", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_237", property="harVol237", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_238", property="harVol238", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_239", property="harVol239", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_240", property="harVol240", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_241", property="harVol241", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_242", property="harVol242", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_243", property="harVol243", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_244", property="harVol244", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_245", property="harVol245", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_246", property="harVol246", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_247", property="harVol247", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_248", property="harVol248", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_249", property="harVol249", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_250", property="harVol250", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_251", property="harVol251", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_252", property="harVol252", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_253", property="harVol253", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_254", property="harVol254", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_255", property="harVol255", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_256", property="harVol256", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_257", property="harVol257", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_258", property="harVol258", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_259", property="harVol259", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_260", property="harVol260", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_261", property="harVol261", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_262", property="harVol262", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_263", property="harVol263", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_264", property="harVol264", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_265", property="harVol265", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_266", property="harVol266", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_267", property="harVol267", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_268", property="harVol268", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_269", property="harVol269", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_270", property="harVol270", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_271", property="harVol271", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_272", property="harVol272", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_273", property="harVol273", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_274", property="harVol274", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_275", property="harVol275", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_276", property="harVol276", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_277", property="harVol277", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_278", property="harVol278", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_279", property="harVol279", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_280", property="harVol280", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_281", property="harVol281", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_282", property="harVol282", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_283", property="harVol283", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_284", property="harVol284", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_285", property="harVol285", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_286", property="harVol286", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_287", property="harVol287", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOL_288", property="harVol288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_mhaiVolCurvePo> selectMhaiVolCurveByDate(String data_date);

    @Select({
            "select",
            "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_VOL_1, HAR_VOL_2, ",
            "HAR_VOL_3, HAR_VOL_4, HAR_VOL_5, HAR_VOL_6, HAR_VOL_7, HAR_VOL_8, HAR_VOL_9, ",
            "HAR_VOL_10, HAR_VOL_11, HAR_VOL_12, HAR_VOL_13, HAR_VOL_14, HAR_VOL_15, HAR_VOL_16, ",
            "HAR_VOL_17, HAR_VOL_18, HAR_VOL_19, HAR_VOL_20, HAR_VOL_21, HAR_VOL_22, HAR_VOL_23, ",
            "HAR_VOL_24, HAR_VOL_25, HAR_VOL_26, HAR_VOL_27, HAR_VOL_28, HAR_VOL_29, HAR_VOL_30, ",
            "HAR_VOL_31, HAR_VOL_32, HAR_VOL_33, HAR_VOL_34, HAR_VOL_35, HAR_VOL_36, HAR_VOL_37, ",
            "HAR_VOL_38, HAR_VOL_39, HAR_VOL_40, HAR_VOL_41, HAR_VOL_42, HAR_VOL_43, HAR_VOL_44, ",
            "HAR_VOL_45, HAR_VOL_46, HAR_VOL_47, HAR_VOL_48, HAR_VOL_49, HAR_VOL_50, HAR_VOL_51, ",
            "HAR_VOL_52, HAR_VOL_53, HAR_VOL_54, HAR_VOL_55, HAR_VOL_56, HAR_VOL_57, HAR_VOL_58, ",
            "HAR_VOL_59, HAR_VOL_60, HAR_VOL_61, HAR_VOL_62, HAR_VOL_63, HAR_VOL_64, HAR_VOL_65, ",
            "HAR_VOL_66, HAR_VOL_67, HAR_VOL_68, HAR_VOL_69, HAR_VOL_70, HAR_VOL_71, HAR_VOL_72, ",
            "HAR_VOL_73, HAR_VOL_74, HAR_VOL_75, HAR_VOL_76, HAR_VOL_77, HAR_VOL_78, HAR_VOL_79, ",
            "HAR_VOL_80, HAR_VOL_81, HAR_VOL_82, HAR_VOL_83, HAR_VOL_84, HAR_VOL_85, HAR_VOL_86, ",
            "HAR_VOL_87, HAR_VOL_88, HAR_VOL_89, HAR_VOL_90, HAR_VOL_91, HAR_VOL_92, HAR_VOL_93, ",
            "HAR_VOL_94, HAR_VOL_95, HAR_VOL_96, HAR_VOL_97, HAR_VOL_98, HAR_VOL_99, HAR_VOL_100, ",
            "HAR_VOL_101, HAR_VOL_102, HAR_VOL_103, HAR_VOL_104, HAR_VOL_105, HAR_VOL_106, ",
            "HAR_VOL_107, HAR_VOL_108, HAR_VOL_109, HAR_VOL_110, HAR_VOL_111, HAR_VOL_112, ",
            "HAR_VOL_113, HAR_VOL_114, HAR_VOL_115, HAR_VOL_116, HAR_VOL_117, HAR_VOL_118, ",
            "HAR_VOL_119, HAR_VOL_120, HAR_VOL_121, HAR_VOL_122, HAR_VOL_123, HAR_VOL_124, ",
            "HAR_VOL_125, HAR_VOL_126, HAR_VOL_127, HAR_VOL_128, HAR_VOL_129, HAR_VOL_130, ",
            "HAR_VOL_131, HAR_VOL_132, HAR_VOL_133, HAR_VOL_134, HAR_VOL_135, HAR_VOL_136, ",
            "HAR_VOL_137, HAR_VOL_138, HAR_VOL_139, HAR_VOL_140, HAR_VOL_141, HAR_VOL_142, ",
            "HAR_VOL_143, HAR_VOL_144, HAR_VOL_145, HAR_VOL_146, HAR_VOL_147, HAR_VOL_148, ",
            "HAR_VOL_149, HAR_VOL_150, HAR_VOL_151, HAR_VOL_152, HAR_VOL_153, HAR_VOL_154, ",
            "HAR_VOL_155, HAR_VOL_156, HAR_VOL_157, HAR_VOL_158, HAR_VOL_159, HAR_VOL_160, ",
            "HAR_VOL_161, HAR_VOL_162, HAR_VOL_163, HAR_VOL_164, HAR_VOL_165, HAR_VOL_166, ",
            "HAR_VOL_167, HAR_VOL_168, HAR_VOL_169, HAR_VOL_170, HAR_VOL_171, HAR_VOL_172, ",
            "HAR_VOL_173, HAR_VOL_174, HAR_VOL_175, HAR_VOL_176, HAR_VOL_177, HAR_VOL_178, ",
            "HAR_VOL_179, HAR_VOL_180, HAR_VOL_181, HAR_VOL_182, HAR_VOL_183, HAR_VOL_184, ",
            "HAR_VOL_185, HAR_VOL_186, HAR_VOL_187, HAR_VOL_188, HAR_VOL_189, HAR_VOL_190, ",
            "HAR_VOL_191, HAR_VOL_192, HAR_VOL_193, HAR_VOL_194, HAR_VOL_195, HAR_VOL_196, ",
            "HAR_VOL_197, HAR_VOL_198, HAR_VOL_199, HAR_VOL_200, HAR_VOL_201, HAR_VOL_202, ",
            "HAR_VOL_203, HAR_VOL_204, HAR_VOL_205, HAR_VOL_206, HAR_VOL_207, HAR_VOL_208, ",
            "HAR_VOL_209, HAR_VOL_210, HAR_VOL_211, HAR_VOL_212, HAR_VOL_213, HAR_VOL_214, ",
            "HAR_VOL_215, HAR_VOL_216, HAR_VOL_217, HAR_VOL_218, HAR_VOL_219, HAR_VOL_220, ",
            "HAR_VOL_221, HAR_VOL_222, HAR_VOL_223, HAR_VOL_224, HAR_VOL_225, HAR_VOL_226, ",
            "HAR_VOL_227, HAR_VOL_228, HAR_VOL_229, HAR_VOL_230, HAR_VOL_231, HAR_VOL_232, ",
            "HAR_VOL_233, HAR_VOL_234, HAR_VOL_235, HAR_VOL_236, HAR_VOL_237, HAR_VOL_238, ",
            "HAR_VOL_239, HAR_VOL_240, HAR_VOL_241, HAR_VOL_242, HAR_VOL_243, HAR_VOL_244, ",
            "HAR_VOL_245, HAR_VOL_246, HAR_VOL_247, HAR_VOL_248, HAR_VOL_249, HAR_VOL_250, ",
            "HAR_VOL_251, HAR_VOL_252, HAR_VOL_253, HAR_VOL_254, HAR_VOL_255, HAR_VOL_256, ",
            "HAR_VOL_257, HAR_VOL_258, HAR_VOL_259, HAR_VOL_260, HAR_VOL_261, HAR_VOL_262, ",
            "HAR_VOL_263, HAR_VOL_264, HAR_VOL_265, HAR_VOL_266, HAR_VOL_267, HAR_VOL_268, ",
            "HAR_VOL_269, HAR_VOL_270, HAR_VOL_271, HAR_VOL_272, HAR_VOL_273, HAR_VOL_274, ",
            "HAR_VOL_275, HAR_VOL_276, HAR_VOL_277, HAR_VOL_278, HAR_VOL_279, HAR_VOL_280, ",
            "HAR_VOL_281, HAR_VOL_282, HAR_VOL_283, HAR_VOL_284, HAR_VOL_285, HAR_VOL_286, ",
            "HAR_VOL_287, HAR_VOL_288",
            "from c_mhai_vol_c ",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="HAR_VOL_1", property="harVol1", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_2", property="harVol2", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_3", property="harVol3", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_4", property="harVol4", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_5", property="harVol5", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_6", property="harVol6", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_7", property="harVol7", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_8", property="harVol8", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_9", property="harVol9", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_10", property="harVol10", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_11", property="harVol11", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_12", property="harVol12", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_13", property="harVol13", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_14", property="harVol14", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_15", property="harVol15", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_16", property="harVol16", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_17", property="harVol17", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_18", property="harVol18", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_19", property="harVol19", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_20", property="harVol20", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_21", property="harVol21", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_22", property="harVol22", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_23", property="harVol23", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_24", property="harVol24", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_25", property="harVol25", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_26", property="harVol26", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_27", property="harVol27", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_28", property="harVol28", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_29", property="harVol29", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_30", property="harVol30", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_31", property="harVol31", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_32", property="harVol32", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_33", property="harVol33", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_34", property="harVol34", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_35", property="harVol35", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_36", property="harVol36", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_37", property="harVol37", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_38", property="harVol38", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_39", property="harVol39", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_40", property="harVol40", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_41", property="harVol41", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_42", property="harVol42", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_43", property="harVol43", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_44", property="harVol44", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_45", property="harVol45", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_46", property="harVol46", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_47", property="harVol47", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_48", property="harVol48", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_49", property="harVol49", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_50", property="harVol50", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_51", property="harVol51", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_52", property="harVol52", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_53", property="harVol53", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_54", property="harVol54", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_55", property="harVol55", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_56", property="harVol56", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_57", property="harVol57", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_58", property="harVol58", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_59", property="harVol59", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_60", property="harVol60", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_61", property="harVol61", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_62", property="harVol62", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_63", property="harVol63", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_64", property="harVol64", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_65", property="harVol65", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_66", property="harVol66", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_67", property="harVol67", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_68", property="harVol68", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_69", property="harVol69", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_70", property="harVol70", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_71", property="harVol71", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_72", property="harVol72", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_73", property="harVol73", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_74", property="harVol74", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_75", property="harVol75", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_76", property="harVol76", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_77", property="harVol77", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_78", property="harVol78", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_79", property="harVol79", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_80", property="harVol80", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_81", property="harVol81", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_82", property="harVol82", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_83", property="harVol83", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_84", property="harVol84", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_85", property="harVol85", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_86", property="harVol86", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_87", property="harVol87", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_88", property="harVol88", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_89", property="harVol89", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_90", property="harVol90", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_91", property="harVol91", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_92", property="harVol92", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_93", property="harVol93", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_94", property="harVol94", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_95", property="harVol95", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_96", property="harVol96", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_97", property="harVol97", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_98", property="harVol98", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_99", property="harVol99", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_100", property="harVol100", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_101", property="harVol101", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_102", property="harVol102", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_103", property="harVol103", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_104", property="harVol104", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_105", property="harVol105", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_106", property="harVol106", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_107", property="harVol107", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_108", property="harVol108", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_109", property="harVol109", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_110", property="harVol110", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_111", property="harVol111", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_112", property="harVol112", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_113", property="harVol113", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_114", property="harVol114", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_115", property="harVol115", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_116", property="harVol116", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_117", property="harVol117", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_118", property="harVol118", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_119", property="harVol119", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_120", property="harVol120", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_121", property="harVol121", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_122", property="harVol122", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_123", property="harVol123", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_124", property="harVol124", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_125", property="harVol125", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_126", property="harVol126", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_127", property="harVol127", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_128", property="harVol128", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_129", property="harVol129", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_130", property="harVol130", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_131", property="harVol131", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_132", property="harVol132", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_133", property="harVol133", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_134", property="harVol134", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_135", property="harVol135", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_136", property="harVol136", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_137", property="harVol137", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_138", property="harVol138", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_139", property="harVol139", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_140", property="harVol140", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_141", property="harVol141", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_142", property="harVol142", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_143", property="harVol143", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_144", property="harVol144", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_145", property="harVol145", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_146", property="harVol146", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_147", property="harVol147", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_148", property="harVol148", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_149", property="harVol149", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_150", property="harVol150", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_151", property="harVol151", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_152", property="harVol152", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_153", property="harVol153", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_154", property="harVol154", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_155", property="harVol155", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_156", property="harVol156", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_157", property="harVol157", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_158", property="harVol158", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_159", property="harVol159", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_160", property="harVol160", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_161", property="harVol161", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_162", property="harVol162", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_163", property="harVol163", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_164", property="harVol164", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_165", property="harVol165", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_166", property="harVol166", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_167", property="harVol167", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_168", property="harVol168", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_169", property="harVol169", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_170", property="harVol170", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_171", property="harVol171", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_172", property="harVol172", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_173", property="harVol173", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_174", property="harVol174", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_175", property="harVol175", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_176", property="harVol176", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_177", property="harVol177", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_178", property="harVol178", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_179", property="harVol179", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_180", property="harVol180", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_181", property="harVol181", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_182", property="harVol182", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_183", property="harVol183", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_184", property="harVol184", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_185", property="harVol185", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_186", property="harVol186", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_187", property="harVol187", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_188", property="harVol188", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_189", property="harVol189", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_190", property="harVol190", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_191", property="harVol191", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_192", property="harVol192", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_193", property="harVol193", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_194", property="harVol194", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_195", property="harVol195", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_196", property="harVol196", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_197", property="harVol197", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_198", property="harVol198", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_199", property="harVol199", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_200", property="harVol200", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_201", property="harVol201", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_202", property="harVol202", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_203", property="harVol203", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_204", property="harVol204", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_205", property="harVol205", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_206", property="harVol206", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_207", property="harVol207", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_208", property="harVol208", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_209", property="harVol209", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_210", property="harVol210", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_211", property="harVol211", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_212", property="harVol212", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_213", property="harVol213", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_214", property="harVol214", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_215", property="harVol215", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_216", property="harVol216", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_217", property="harVol217", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_218", property="harVol218", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_219", property="harVol219", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_220", property="harVol220", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_221", property="harVol221", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_222", property="harVol222", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_223", property="harVol223", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_224", property="harVol224", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_225", property="harVol225", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_226", property="harVol226", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_227", property="harVol227", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_228", property="harVol228", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_229", property="harVol229", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_230", property="harVol230", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_231", property="harVol231", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_232", property="harVol232", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_233", property="harVol233", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_234", property="harVol234", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_235", property="harVol235", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_236", property="harVol236", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_237", property="harVol237", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_238", property="harVol238", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_239", property="harVol239", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_240", property="harVol240", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_241", property="harVol241", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_242", property="harVol242", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_243", property="harVol243", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_244", property="harVol244", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_245", property="harVol245", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_246", property="harVol246", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_247", property="harVol247", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_248", property="harVol248", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_249", property="harVol249", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_250", property="harVol250", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_251", property="harVol251", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_252", property="harVol252", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_253", property="harVol253", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_254", property="harVol254", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_255", property="harVol255", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_256", property="harVol256", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_257", property="harVol257", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_258", property="harVol258", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_259", property="harVol259", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_260", property="harVol260", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_261", property="harVol261", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_262", property="harVol262", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_263", property="harVol263", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_264", property="harVol264", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_265", property="harVol265", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_266", property="harVol266", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_267", property="harVol267", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_268", property="harVol268", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_269", property="harVol269", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_270", property="harVol270", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_271", property="harVol271", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_272", property="harVol272", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_273", property="harVol273", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_274", property="harVol274", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_275", property="harVol275", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_276", property="harVol276", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_277", property="harVol277", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_278", property="harVol278", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_279", property="harVol279", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_280", property="harVol280", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_281", property="harVol281", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_282", property="harVol282", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_283", property="harVol283", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_284", property="harVol284", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_285", property="harVol285", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_286", property="harVol286", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_287", property="harVol287", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOL_288", property="harVol288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_mhaiVolCurvePo> selectMhaiVolCurveBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

}