package com.dao.mapper;

import com.dao.bean.D_mhaiVoldistCurvePo;
import com.dao.bean.D_mhaiVoldistCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_mhaiVoldistCurvePoMapper {

    @Select({
        "select",
        "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_VOLDIST_1, ",
        "HAR_VOLDIST_2, HAR_VOLDIST_3, HAR_VOLDIST_4, HAR_VOLDIST_5, HAR_VOLDIST_6, HAR_VOLDIST_7, ",
        "HAR_VOLDIST_8, HAR_VOLDIST_9, HAR_VOLDIST_10, HAR_VOLDIST_11, HAR_VOLDIST_12, ",
        "HAR_VOLDIST_13, HAR_VOLDIST_14, HAR_VOLDIST_15, HAR_VOLDIST_16, HAR_VOLDIST_17, ",
        "HAR_VOLDIST_18, HAR_VOLDIST_19, HAR_VOLDIST_20, HAR_VOLDIST_21, HAR_VOLDIST_22, ",
        "HAR_VOLDIST_23, HAR_VOLDIST_24, HAR_VOLDIST_25, HAR_VOLDIST_26, HAR_VOLDIST_27, ",
        "HAR_VOLDIST_28, HAR_VOLDIST_29, HAR_VOLDIST_30, HAR_VOLDIST_31, HAR_VOLDIST_32, ",
        "HAR_VOLDIST_33, HAR_VOLDIST_34, HAR_VOLDIST_35, HAR_VOLDIST_36, HAR_VOLDIST_37, ",
        "HAR_VOLDIST_38, HAR_VOLDIST_39, HAR_VOLDIST_40, HAR_VOLDIST_41, HAR_VOLDIST_42, ",
        "HAR_VOLDIST_43, HAR_VOLDIST_44, HAR_VOLDIST_45, HAR_VOLDIST_46, HAR_VOLDIST_47, ",
        "HAR_VOLDIST_48, HAR_VOLDIST_49, HAR_VOLDIST_50, HAR_VOLDIST_51, HAR_VOLDIST_52, ",
        "HAR_VOLDIST_53, HAR_VOLDIST_54, HAR_VOLDIST_55, HAR_VOLDIST_56, HAR_VOLDIST_57, ",
        "HAR_VOLDIST_58, HAR_VOLDIST_59, HAR_VOLDIST_60, HAR_VOLDIST_61, HAR_VOLDIST_62, ",
        "HAR_VOLDIST_63, HAR_VOLDIST_64, HAR_VOLDIST_65, HAR_VOLDIST_66, HAR_VOLDIST_67, ",
        "HAR_VOLDIST_68, HAR_VOLDIST_69, HAR_VOLDIST_70, HAR_VOLDIST_71, HAR_VOLDIST_72, ",
        "HAR_VOLDIST_73, HAR_VOLDIST_74, HAR_VOLDIST_75, HAR_VOLDIST_76, HAR_VOLDIST_77, ",
        "HAR_VOLDIST_78, HAR_VOLDIST_79, HAR_VOLDIST_80, HAR_VOLDIST_81, HAR_VOLDIST_82, ",
        "HAR_VOLDIST_83, HAR_VOLDIST_84, HAR_VOLDIST_85, HAR_VOLDIST_86, HAR_VOLDIST_87, ",
        "HAR_VOLDIST_88, HAR_VOLDIST_89, HAR_VOLDIST_90, HAR_VOLDIST_91, HAR_VOLDIST_92, ",
        "HAR_VOLDIST_93, HAR_VOLDIST_94, HAR_VOLDIST_95, HAR_VOLDIST_96, HAR_VOLDIST_97, ",
        "HAR_VOLDIST_98, HAR_VOLDIST_99, HAR_VOLDIST_100, HAR_VOLDIST_101, HAR_VOLDIST_102, ",
        "HAR_VOLDIST_103, HAR_VOLDIST_104, HAR_VOLDIST_105, HAR_VOLDIST_106, HAR_VOLDIST_107, ",
        "HAR_VOLDIST_108, HAR_VOLDIST_109, HAR_VOLDIST_110, HAR_VOLDIST_111, HAR_VOLDIST_112, ",
        "HAR_VOLDIST_113, HAR_VOLDIST_114, HAR_VOLDIST_115, HAR_VOLDIST_116, HAR_VOLDIST_117, ",
        "HAR_VOLDIST_118, HAR_VOLDIST_119, HAR_VOLDIST_120, HAR_VOLDIST_121, HAR_VOLDIST_122, ",
        "HAR_VOLDIST_123, HAR_VOLDIST_124, HAR_VOLDIST_125, HAR_VOLDIST_126, HAR_VOLDIST_127, ",
        "HAR_VOLDIST_128, HAR_VOLDIST_129, HAR_VOLDIST_130, HAR_VOLDIST_131, HAR_VOLDIST_132, ",
        "HAR_VOLDIST_133, HAR_VOLDIST_134, HAR_VOLDIST_135, HAR_VOLDIST_136, HAR_VOLDIST_137, ",
        "HAR_VOLDIST_138, HAR_VOLDIST_139, HAR_VOLDIST_140, HAR_VOLDIST_141, HAR_VOLDIST_142, ",
        "HAR_VOLDIST_143, HAR_VOLDIST_144, HAR_VOLDIST_145, HAR_VOLDIST_146, HAR_VOLDIST_147, ",
        "HAR_VOLDIST_148, HAR_VOLDIST_149, HAR_VOLDIST_150, HAR_VOLDIST_151, HAR_VOLDIST_152, ",
        "HAR_VOLDIST_153, HAR_VOLDIST_154, HAR_VOLDIST_155, HAR_VOLDIST_156, HAR_VOLDIST_157, ",
        "HAR_VOLDIST_158, HAR_VOLDIST_159, HAR_VOLDIST_160, HAR_VOLDIST_161, HAR_VOLDIST_162, ",
        "HAR_VOLDIST_163, HAR_VOLDIST_164, HAR_VOLDIST_165, HAR_VOLDIST_166, HAR_VOLDIST_167, ",
        "HAR_VOLDIST_168, HAR_VOLDIST_169, HAR_VOLDIST_170, HAR_VOLDIST_171, HAR_VOLDIST_172, ",
        "HAR_VOLDIST_173, HAR_VOLDIST_174, HAR_VOLDIST_175, HAR_VOLDIST_176, HAR_VOLDIST_177, ",
        "HAR_VOLDIST_178, HAR_VOLDIST_179, HAR_VOLDIST_180, HAR_VOLDIST_181, HAR_VOLDIST_182, ",
        "HAR_VOLDIST_183, HAR_VOLDIST_184, HAR_VOLDIST_185, HAR_VOLDIST_186, HAR_VOLDIST_187, ",
        "HAR_VOLDIST_188, HAR_VOLDIST_189, HAR_VOLDIST_190, HAR_VOLDIST_191, HAR_VOLDIST_192, ",
        "HAR_VOLDIST_193, HAR_VOLDIST_194, HAR_VOLDIST_195, HAR_VOLDIST_196, HAR_VOLDIST_197, ",
        "HAR_VOLDIST_198, HAR_VOLDIST_199, HAR_VOLDIST_200, HAR_VOLDIST_201, HAR_VOLDIST_202, ",
        "HAR_VOLDIST_203, HAR_VOLDIST_204, HAR_VOLDIST_205, HAR_VOLDIST_206, HAR_VOLDIST_207, ",
        "HAR_VOLDIST_208, HAR_VOLDIST_209, HAR_VOLDIST_210, HAR_VOLDIST_211, HAR_VOLDIST_212, ",
        "HAR_VOLDIST_213, HAR_VOLDIST_214, HAR_VOLDIST_215, HAR_VOLDIST_216, HAR_VOLDIST_217, ",
        "HAR_VOLDIST_218, HAR_VOLDIST_219, HAR_VOLDIST_220, HAR_VOLDIST_221, HAR_VOLDIST_222, ",
        "HAR_VOLDIST_223, HAR_VOLDIST_224, HAR_VOLDIST_225, HAR_VOLDIST_226, HAR_VOLDIST_227, ",
        "HAR_VOLDIST_228, HAR_VOLDIST_229, HAR_VOLDIST_230, HAR_VOLDIST_231, HAR_VOLDIST_232, ",
        "HAR_VOLDIST_233, HAR_VOLDIST_234, HAR_VOLDIST_235, HAR_VOLDIST_236, HAR_VOLDIST_237, ",
        "HAR_VOLDIST_238, HAR_VOLDIST_239, HAR_VOLDIST_240, HAR_VOLDIST_241, HAR_VOLDIST_242, ",
        "HAR_VOLDIST_243, HAR_VOLDIST_244, HAR_VOLDIST_245, HAR_VOLDIST_246, HAR_VOLDIST_247, ",
        "HAR_VOLDIST_248, HAR_VOLDIST_249, HAR_VOLDIST_250, HAR_VOLDIST_251, HAR_VOLDIST_252, ",
        "HAR_VOLDIST_253, HAR_VOLDIST_254, HAR_VOLDIST_255, HAR_VOLDIST_256, HAR_VOLDIST_257, ",
        "HAR_VOLDIST_258, HAR_VOLDIST_259, HAR_VOLDIST_260, HAR_VOLDIST_261, HAR_VOLDIST_262, ",
        "HAR_VOLDIST_263, HAR_VOLDIST_264, HAR_VOLDIST_265, HAR_VOLDIST_266, HAR_VOLDIST_267, ",
        "HAR_VOLDIST_268, HAR_VOLDIST_269, HAR_VOLDIST_270, HAR_VOLDIST_271, HAR_VOLDIST_272, ",
        "HAR_VOLDIST_273, HAR_VOLDIST_274, HAR_VOLDIST_275, HAR_VOLDIST_276, HAR_VOLDIST_277, ",
        "HAR_VOLDIST_278, HAR_VOLDIST_279, HAR_VOLDIST_280, HAR_VOLDIST_281, HAR_VOLDIST_282, ",
        "HAR_VOLDIST_283, HAR_VOLDIST_284, HAR_VOLDIST_285, HAR_VOLDIST_286, HAR_VOLDIST_287, ",
        "HAR_VOLDIST_288",
        "from c_mhai_voldist_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="HAR_VOLDIST_1", property="harVoldist1", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_2", property="harVoldist2", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_3", property="harVoldist3", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_4", property="harVoldist4", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_5", property="harVoldist5", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_6", property="harVoldist6", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_7", property="harVoldist7", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_8", property="harVoldist8", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_9", property="harVoldist9", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_10", property="harVoldist10", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_11", property="harVoldist11", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_12", property="harVoldist12", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_13", property="harVoldist13", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_14", property="harVoldist14", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_15", property="harVoldist15", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_16", property="harVoldist16", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_17", property="harVoldist17", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_18", property="harVoldist18", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_19", property="harVoldist19", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_20", property="harVoldist20", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_21", property="harVoldist21", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_22", property="harVoldist22", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_23", property="harVoldist23", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_24", property="harVoldist24", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_25", property="harVoldist25", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_26", property="harVoldist26", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_27", property="harVoldist27", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_28", property="harVoldist28", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_29", property="harVoldist29", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_30", property="harVoldist30", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_31", property="harVoldist31", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_32", property="harVoldist32", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_33", property="harVoldist33", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_34", property="harVoldist34", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_35", property="harVoldist35", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_36", property="harVoldist36", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_37", property="harVoldist37", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_38", property="harVoldist38", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_39", property="harVoldist39", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_40", property="harVoldist40", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_41", property="harVoldist41", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_42", property="harVoldist42", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_43", property="harVoldist43", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_44", property="harVoldist44", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_45", property="harVoldist45", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_46", property="harVoldist46", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_47", property="harVoldist47", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_48", property="harVoldist48", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_49", property="harVoldist49", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_50", property="harVoldist50", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_51", property="harVoldist51", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_52", property="harVoldist52", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_53", property="harVoldist53", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_54", property="harVoldist54", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_55", property="harVoldist55", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_56", property="harVoldist56", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_57", property="harVoldist57", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_58", property="harVoldist58", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_59", property="harVoldist59", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_60", property="harVoldist60", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_61", property="harVoldist61", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_62", property="harVoldist62", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_63", property="harVoldist63", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_64", property="harVoldist64", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_65", property="harVoldist65", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_66", property="harVoldist66", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_67", property="harVoldist67", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_68", property="harVoldist68", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_69", property="harVoldist69", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_70", property="harVoldist70", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_71", property="harVoldist71", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_72", property="harVoldist72", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_73", property="harVoldist73", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_74", property="harVoldist74", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_75", property="harVoldist75", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_76", property="harVoldist76", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_77", property="harVoldist77", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_78", property="harVoldist78", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_79", property="harVoldist79", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_80", property="harVoldist80", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_81", property="harVoldist81", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_82", property="harVoldist82", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_83", property="harVoldist83", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_84", property="harVoldist84", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_85", property="harVoldist85", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_86", property="harVoldist86", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_87", property="harVoldist87", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_88", property="harVoldist88", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_89", property="harVoldist89", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_90", property="harVoldist90", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_91", property="harVoldist91", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_92", property="harVoldist92", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_93", property="harVoldist93", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_94", property="harVoldist94", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_95", property="harVoldist95", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_96", property="harVoldist96", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_97", property="harVoldist97", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_98", property="harVoldist98", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_99", property="harVoldist99", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_100", property="harVoldist100", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_101", property="harVoldist101", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_102", property="harVoldist102", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_103", property="harVoldist103", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_104", property="harVoldist104", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_105", property="harVoldist105", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_106", property="harVoldist106", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_107", property="harVoldist107", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_108", property="harVoldist108", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_109", property="harVoldist109", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_110", property="harVoldist110", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_111", property="harVoldist111", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_112", property="harVoldist112", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_113", property="harVoldist113", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_114", property="harVoldist114", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_115", property="harVoldist115", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_116", property="harVoldist116", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_117", property="harVoldist117", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_118", property="harVoldist118", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_119", property="harVoldist119", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_120", property="harVoldist120", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_121", property="harVoldist121", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_122", property="harVoldist122", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_123", property="harVoldist123", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_124", property="harVoldist124", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_125", property="harVoldist125", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_126", property="harVoldist126", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_127", property="harVoldist127", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_128", property="harVoldist128", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_129", property="harVoldist129", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_130", property="harVoldist130", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_131", property="harVoldist131", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_132", property="harVoldist132", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_133", property="harVoldist133", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_134", property="harVoldist134", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_135", property="harVoldist135", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_136", property="harVoldist136", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_137", property="harVoldist137", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_138", property="harVoldist138", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_139", property="harVoldist139", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_140", property="harVoldist140", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_141", property="harVoldist141", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_142", property="harVoldist142", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_143", property="harVoldist143", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_144", property="harVoldist144", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_145", property="harVoldist145", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_146", property="harVoldist146", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_147", property="harVoldist147", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_148", property="harVoldist148", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_149", property="harVoldist149", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_150", property="harVoldist150", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_151", property="harVoldist151", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_152", property="harVoldist152", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_153", property="harVoldist153", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_154", property="harVoldist154", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_155", property="harVoldist155", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_156", property="harVoldist156", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_157", property="harVoldist157", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_158", property="harVoldist158", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_159", property="harVoldist159", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_160", property="harVoldist160", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_161", property="harVoldist161", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_162", property="harVoldist162", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_163", property="harVoldist163", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_164", property="harVoldist164", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_165", property="harVoldist165", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_166", property="harVoldist166", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_167", property="harVoldist167", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_168", property="harVoldist168", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_169", property="harVoldist169", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_170", property="harVoldist170", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_171", property="harVoldist171", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_172", property="harVoldist172", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_173", property="harVoldist173", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_174", property="harVoldist174", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_175", property="harVoldist175", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_176", property="harVoldist176", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_177", property="harVoldist177", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_178", property="harVoldist178", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_179", property="harVoldist179", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_180", property="harVoldist180", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_181", property="harVoldist181", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_182", property="harVoldist182", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_183", property="harVoldist183", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_184", property="harVoldist184", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_185", property="harVoldist185", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_186", property="harVoldist186", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_187", property="harVoldist187", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_188", property="harVoldist188", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_189", property="harVoldist189", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_190", property="harVoldist190", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_191", property="harVoldist191", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_192", property="harVoldist192", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_193", property="harVoldist193", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_194", property="harVoldist194", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_195", property="harVoldist195", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_196", property="harVoldist196", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_197", property="harVoldist197", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_198", property="harVoldist198", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_199", property="harVoldist199", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_200", property="harVoldist200", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_201", property="harVoldist201", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_202", property="harVoldist202", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_203", property="harVoldist203", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_204", property="harVoldist204", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_205", property="harVoldist205", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_206", property="harVoldist206", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_207", property="harVoldist207", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_208", property="harVoldist208", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_209", property="harVoldist209", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_210", property="harVoldist210", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_211", property="harVoldist211", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_212", property="harVoldist212", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_213", property="harVoldist213", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_214", property="harVoldist214", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_215", property="harVoldist215", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_216", property="harVoldist216", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_217", property="harVoldist217", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_218", property="harVoldist218", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_219", property="harVoldist219", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_220", property="harVoldist220", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_221", property="harVoldist221", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_222", property="harVoldist222", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_223", property="harVoldist223", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_224", property="harVoldist224", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_225", property="harVoldist225", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_226", property="harVoldist226", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_227", property="harVoldist227", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_228", property="harVoldist228", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_229", property="harVoldist229", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_230", property="harVoldist230", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_231", property="harVoldist231", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_232", property="harVoldist232", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_233", property="harVoldist233", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_234", property="harVoldist234", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_235", property="harVoldist235", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_236", property="harVoldist236", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_237", property="harVoldist237", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_238", property="harVoldist238", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_239", property="harVoldist239", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_240", property="harVoldist240", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_241", property="harVoldist241", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_242", property="harVoldist242", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_243", property="harVoldist243", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_244", property="harVoldist244", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_245", property="harVoldist245", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_246", property="harVoldist246", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_247", property="harVoldist247", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_248", property="harVoldist248", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_249", property="harVoldist249", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_250", property="harVoldist250", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_251", property="harVoldist251", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_252", property="harVoldist252", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_253", property="harVoldist253", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_254", property="harVoldist254", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_255", property="harVoldist255", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_256", property="harVoldist256", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_257", property="harVoldist257", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_258", property="harVoldist258", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_259", property="harVoldist259", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_260", property="harVoldist260", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_261", property="harVoldist261", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_262", property="harVoldist262", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_263", property="harVoldist263", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_264", property="harVoldist264", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_265", property="harVoldist265", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_266", property="harVoldist266", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_267", property="harVoldist267", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_268", property="harVoldist268", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_269", property="harVoldist269", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_270", property="harVoldist270", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_271", property="harVoldist271", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_272", property="harVoldist272", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_273", property="harVoldist273", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_274", property="harVoldist274", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_275", property="harVoldist275", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_276", property="harVoldist276", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_277", property="harVoldist277", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_278", property="harVoldist278", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_279", property="harVoldist279", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_280", property="harVoldist280", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_281", property="harVoldist281", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_282", property="harVoldist282", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_283", property="harVoldist283", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_284", property="harVoldist284", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_285", property="harVoldist285", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_286", property="harVoldist286", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_287", property="harVoldist287", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLDIST_288", property="harVoldist288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_mhaiVoldistCurvePo> selectVoldistCurveByDate(String data_date);

    @Select({
            "select",
            "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_VOLDIST_1, ",
            "HAR_VOLDIST_2, HAR_VOLDIST_3, HAR_VOLDIST_4, HAR_VOLDIST_5, HAR_VOLDIST_6, HAR_VOLDIST_7, ",
            "HAR_VOLDIST_8, HAR_VOLDIST_9, HAR_VOLDIST_10, HAR_VOLDIST_11, HAR_VOLDIST_12, ",
            "HAR_VOLDIST_13, HAR_VOLDIST_14, HAR_VOLDIST_15, HAR_VOLDIST_16, HAR_VOLDIST_17, ",
            "HAR_VOLDIST_18, HAR_VOLDIST_19, HAR_VOLDIST_20, HAR_VOLDIST_21, HAR_VOLDIST_22, ",
            "HAR_VOLDIST_23, HAR_VOLDIST_24, HAR_VOLDIST_25, HAR_VOLDIST_26, HAR_VOLDIST_27, ",
            "HAR_VOLDIST_28, HAR_VOLDIST_29, HAR_VOLDIST_30, HAR_VOLDIST_31, HAR_VOLDIST_32, ",
            "HAR_VOLDIST_33, HAR_VOLDIST_34, HAR_VOLDIST_35, HAR_VOLDIST_36, HAR_VOLDIST_37, ",
            "HAR_VOLDIST_38, HAR_VOLDIST_39, HAR_VOLDIST_40, HAR_VOLDIST_41, HAR_VOLDIST_42, ",
            "HAR_VOLDIST_43, HAR_VOLDIST_44, HAR_VOLDIST_45, HAR_VOLDIST_46, HAR_VOLDIST_47, ",
            "HAR_VOLDIST_48, HAR_VOLDIST_49, HAR_VOLDIST_50, HAR_VOLDIST_51, HAR_VOLDIST_52, ",
            "HAR_VOLDIST_53, HAR_VOLDIST_54, HAR_VOLDIST_55, HAR_VOLDIST_56, HAR_VOLDIST_57, ",
            "HAR_VOLDIST_58, HAR_VOLDIST_59, HAR_VOLDIST_60, HAR_VOLDIST_61, HAR_VOLDIST_62, ",
            "HAR_VOLDIST_63, HAR_VOLDIST_64, HAR_VOLDIST_65, HAR_VOLDIST_66, HAR_VOLDIST_67, ",
            "HAR_VOLDIST_68, HAR_VOLDIST_69, HAR_VOLDIST_70, HAR_VOLDIST_71, HAR_VOLDIST_72, ",
            "HAR_VOLDIST_73, HAR_VOLDIST_74, HAR_VOLDIST_75, HAR_VOLDIST_76, HAR_VOLDIST_77, ",
            "HAR_VOLDIST_78, HAR_VOLDIST_79, HAR_VOLDIST_80, HAR_VOLDIST_81, HAR_VOLDIST_82, ",
            "HAR_VOLDIST_83, HAR_VOLDIST_84, HAR_VOLDIST_85, HAR_VOLDIST_86, HAR_VOLDIST_87, ",
            "HAR_VOLDIST_88, HAR_VOLDIST_89, HAR_VOLDIST_90, HAR_VOLDIST_91, HAR_VOLDIST_92, ",
            "HAR_VOLDIST_93, HAR_VOLDIST_94, HAR_VOLDIST_95, HAR_VOLDIST_96, HAR_VOLDIST_97, ",
            "HAR_VOLDIST_98, HAR_VOLDIST_99, HAR_VOLDIST_100, HAR_VOLDIST_101, HAR_VOLDIST_102, ",
            "HAR_VOLDIST_103, HAR_VOLDIST_104, HAR_VOLDIST_105, HAR_VOLDIST_106, HAR_VOLDIST_107, ",
            "HAR_VOLDIST_108, HAR_VOLDIST_109, HAR_VOLDIST_110, HAR_VOLDIST_111, HAR_VOLDIST_112, ",
            "HAR_VOLDIST_113, HAR_VOLDIST_114, HAR_VOLDIST_115, HAR_VOLDIST_116, HAR_VOLDIST_117, ",
            "HAR_VOLDIST_118, HAR_VOLDIST_119, HAR_VOLDIST_120, HAR_VOLDIST_121, HAR_VOLDIST_122, ",
            "HAR_VOLDIST_123, HAR_VOLDIST_124, HAR_VOLDIST_125, HAR_VOLDIST_126, HAR_VOLDIST_127, ",
            "HAR_VOLDIST_128, HAR_VOLDIST_129, HAR_VOLDIST_130, HAR_VOLDIST_131, HAR_VOLDIST_132, ",
            "HAR_VOLDIST_133, HAR_VOLDIST_134, HAR_VOLDIST_135, HAR_VOLDIST_136, HAR_VOLDIST_137, ",
            "HAR_VOLDIST_138, HAR_VOLDIST_139, HAR_VOLDIST_140, HAR_VOLDIST_141, HAR_VOLDIST_142, ",
            "HAR_VOLDIST_143, HAR_VOLDIST_144, HAR_VOLDIST_145, HAR_VOLDIST_146, HAR_VOLDIST_147, ",
            "HAR_VOLDIST_148, HAR_VOLDIST_149, HAR_VOLDIST_150, HAR_VOLDIST_151, HAR_VOLDIST_152, ",
            "HAR_VOLDIST_153, HAR_VOLDIST_154, HAR_VOLDIST_155, HAR_VOLDIST_156, HAR_VOLDIST_157, ",
            "HAR_VOLDIST_158, HAR_VOLDIST_159, HAR_VOLDIST_160, HAR_VOLDIST_161, HAR_VOLDIST_162, ",
            "HAR_VOLDIST_163, HAR_VOLDIST_164, HAR_VOLDIST_165, HAR_VOLDIST_166, HAR_VOLDIST_167, ",
            "HAR_VOLDIST_168, HAR_VOLDIST_169, HAR_VOLDIST_170, HAR_VOLDIST_171, HAR_VOLDIST_172, ",
            "HAR_VOLDIST_173, HAR_VOLDIST_174, HAR_VOLDIST_175, HAR_VOLDIST_176, HAR_VOLDIST_177, ",
            "HAR_VOLDIST_178, HAR_VOLDIST_179, HAR_VOLDIST_180, HAR_VOLDIST_181, HAR_VOLDIST_182, ",
            "HAR_VOLDIST_183, HAR_VOLDIST_184, HAR_VOLDIST_185, HAR_VOLDIST_186, HAR_VOLDIST_187, ",
            "HAR_VOLDIST_188, HAR_VOLDIST_189, HAR_VOLDIST_190, HAR_VOLDIST_191, HAR_VOLDIST_192, ",
            "HAR_VOLDIST_193, HAR_VOLDIST_194, HAR_VOLDIST_195, HAR_VOLDIST_196, HAR_VOLDIST_197, ",
            "HAR_VOLDIST_198, HAR_VOLDIST_199, HAR_VOLDIST_200, HAR_VOLDIST_201, HAR_VOLDIST_202, ",
            "HAR_VOLDIST_203, HAR_VOLDIST_204, HAR_VOLDIST_205, HAR_VOLDIST_206, HAR_VOLDIST_207, ",
            "HAR_VOLDIST_208, HAR_VOLDIST_209, HAR_VOLDIST_210, HAR_VOLDIST_211, HAR_VOLDIST_212, ",
            "HAR_VOLDIST_213, HAR_VOLDIST_214, HAR_VOLDIST_215, HAR_VOLDIST_216, HAR_VOLDIST_217, ",
            "HAR_VOLDIST_218, HAR_VOLDIST_219, HAR_VOLDIST_220, HAR_VOLDIST_221, HAR_VOLDIST_222, ",
            "HAR_VOLDIST_223, HAR_VOLDIST_224, HAR_VOLDIST_225, HAR_VOLDIST_226, HAR_VOLDIST_227, ",
            "HAR_VOLDIST_228, HAR_VOLDIST_229, HAR_VOLDIST_230, HAR_VOLDIST_231, HAR_VOLDIST_232, ",
            "HAR_VOLDIST_233, HAR_VOLDIST_234, HAR_VOLDIST_235, HAR_VOLDIST_236, HAR_VOLDIST_237, ",
            "HAR_VOLDIST_238, HAR_VOLDIST_239, HAR_VOLDIST_240, HAR_VOLDIST_241, HAR_VOLDIST_242, ",
            "HAR_VOLDIST_243, HAR_VOLDIST_244, HAR_VOLDIST_245, HAR_VOLDIST_246, HAR_VOLDIST_247, ",
            "HAR_VOLDIST_248, HAR_VOLDIST_249, HAR_VOLDIST_250, HAR_VOLDIST_251, HAR_VOLDIST_252, ",
            "HAR_VOLDIST_253, HAR_VOLDIST_254, HAR_VOLDIST_255, HAR_VOLDIST_256, HAR_VOLDIST_257, ",
            "HAR_VOLDIST_258, HAR_VOLDIST_259, HAR_VOLDIST_260, HAR_VOLDIST_261, HAR_VOLDIST_262, ",
            "HAR_VOLDIST_263, HAR_VOLDIST_264, HAR_VOLDIST_265, HAR_VOLDIST_266, HAR_VOLDIST_267, ",
            "HAR_VOLDIST_268, HAR_VOLDIST_269, HAR_VOLDIST_270, HAR_VOLDIST_271, HAR_VOLDIST_272, ",
            "HAR_VOLDIST_273, HAR_VOLDIST_274, HAR_VOLDIST_275, HAR_VOLDIST_276, HAR_VOLDIST_277, ",
            "HAR_VOLDIST_278, HAR_VOLDIST_279, HAR_VOLDIST_280, HAR_VOLDIST_281, HAR_VOLDIST_282, ",
            "HAR_VOLDIST_283, HAR_VOLDIST_284, HAR_VOLDIST_285, HAR_VOLDIST_286, HAR_VOLDIST_287, ",
            "HAR_VOLDIST_288",
            "from c_mhai_voldist_c ",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="HAR_VOLDIST_1", property="harVoldist1", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_2", property="harVoldist2", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_3", property="harVoldist3", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_4", property="harVoldist4", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_5", property="harVoldist5", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_6", property="harVoldist6", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_7", property="harVoldist7", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_8", property="harVoldist8", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_9", property="harVoldist9", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_10", property="harVoldist10", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_11", property="harVoldist11", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_12", property="harVoldist12", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_13", property="harVoldist13", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_14", property="harVoldist14", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_15", property="harVoldist15", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_16", property="harVoldist16", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_17", property="harVoldist17", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_18", property="harVoldist18", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_19", property="harVoldist19", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_20", property="harVoldist20", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_21", property="harVoldist21", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_22", property="harVoldist22", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_23", property="harVoldist23", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_24", property="harVoldist24", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_25", property="harVoldist25", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_26", property="harVoldist26", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_27", property="harVoldist27", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_28", property="harVoldist28", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_29", property="harVoldist29", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_30", property="harVoldist30", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_31", property="harVoldist31", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_32", property="harVoldist32", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_33", property="harVoldist33", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_34", property="harVoldist34", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_35", property="harVoldist35", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_36", property="harVoldist36", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_37", property="harVoldist37", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_38", property="harVoldist38", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_39", property="harVoldist39", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_40", property="harVoldist40", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_41", property="harVoldist41", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_42", property="harVoldist42", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_43", property="harVoldist43", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_44", property="harVoldist44", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_45", property="harVoldist45", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_46", property="harVoldist46", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_47", property="harVoldist47", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_48", property="harVoldist48", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_49", property="harVoldist49", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_50", property="harVoldist50", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_51", property="harVoldist51", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_52", property="harVoldist52", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_53", property="harVoldist53", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_54", property="harVoldist54", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_55", property="harVoldist55", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_56", property="harVoldist56", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_57", property="harVoldist57", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_58", property="harVoldist58", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_59", property="harVoldist59", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_60", property="harVoldist60", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_61", property="harVoldist61", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_62", property="harVoldist62", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_63", property="harVoldist63", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_64", property="harVoldist64", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_65", property="harVoldist65", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_66", property="harVoldist66", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_67", property="harVoldist67", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_68", property="harVoldist68", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_69", property="harVoldist69", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_70", property="harVoldist70", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_71", property="harVoldist71", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_72", property="harVoldist72", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_73", property="harVoldist73", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_74", property="harVoldist74", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_75", property="harVoldist75", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_76", property="harVoldist76", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_77", property="harVoldist77", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_78", property="harVoldist78", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_79", property="harVoldist79", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_80", property="harVoldist80", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_81", property="harVoldist81", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_82", property="harVoldist82", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_83", property="harVoldist83", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_84", property="harVoldist84", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_85", property="harVoldist85", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_86", property="harVoldist86", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_87", property="harVoldist87", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_88", property="harVoldist88", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_89", property="harVoldist89", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_90", property="harVoldist90", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_91", property="harVoldist91", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_92", property="harVoldist92", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_93", property="harVoldist93", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_94", property="harVoldist94", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_95", property="harVoldist95", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_96", property="harVoldist96", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_97", property="harVoldist97", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_98", property="harVoldist98", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_99", property="harVoldist99", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_100", property="harVoldist100", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_101", property="harVoldist101", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_102", property="harVoldist102", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_103", property="harVoldist103", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_104", property="harVoldist104", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_105", property="harVoldist105", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_106", property="harVoldist106", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_107", property="harVoldist107", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_108", property="harVoldist108", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_109", property="harVoldist109", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_110", property="harVoldist110", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_111", property="harVoldist111", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_112", property="harVoldist112", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_113", property="harVoldist113", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_114", property="harVoldist114", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_115", property="harVoldist115", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_116", property="harVoldist116", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_117", property="harVoldist117", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_118", property="harVoldist118", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_119", property="harVoldist119", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_120", property="harVoldist120", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_121", property="harVoldist121", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_122", property="harVoldist122", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_123", property="harVoldist123", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_124", property="harVoldist124", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_125", property="harVoldist125", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_126", property="harVoldist126", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_127", property="harVoldist127", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_128", property="harVoldist128", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_129", property="harVoldist129", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_130", property="harVoldist130", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_131", property="harVoldist131", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_132", property="harVoldist132", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_133", property="harVoldist133", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_134", property="harVoldist134", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_135", property="harVoldist135", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_136", property="harVoldist136", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_137", property="harVoldist137", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_138", property="harVoldist138", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_139", property="harVoldist139", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_140", property="harVoldist140", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_141", property="harVoldist141", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_142", property="harVoldist142", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_143", property="harVoldist143", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_144", property="harVoldist144", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_145", property="harVoldist145", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_146", property="harVoldist146", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_147", property="harVoldist147", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_148", property="harVoldist148", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_149", property="harVoldist149", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_150", property="harVoldist150", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_151", property="harVoldist151", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_152", property="harVoldist152", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_153", property="harVoldist153", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_154", property="harVoldist154", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_155", property="harVoldist155", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_156", property="harVoldist156", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_157", property="harVoldist157", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_158", property="harVoldist158", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_159", property="harVoldist159", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_160", property="harVoldist160", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_161", property="harVoldist161", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_162", property="harVoldist162", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_163", property="harVoldist163", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_164", property="harVoldist164", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_165", property="harVoldist165", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_166", property="harVoldist166", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_167", property="harVoldist167", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_168", property="harVoldist168", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_169", property="harVoldist169", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_170", property="harVoldist170", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_171", property="harVoldist171", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_172", property="harVoldist172", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_173", property="harVoldist173", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_174", property="harVoldist174", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_175", property="harVoldist175", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_176", property="harVoldist176", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_177", property="harVoldist177", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_178", property="harVoldist178", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_179", property="harVoldist179", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_180", property="harVoldist180", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_181", property="harVoldist181", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_182", property="harVoldist182", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_183", property="harVoldist183", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_184", property="harVoldist184", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_185", property="harVoldist185", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_186", property="harVoldist186", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_187", property="harVoldist187", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_188", property="harVoldist188", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_189", property="harVoldist189", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_190", property="harVoldist190", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_191", property="harVoldist191", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_192", property="harVoldist192", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_193", property="harVoldist193", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_194", property="harVoldist194", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_195", property="harVoldist195", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_196", property="harVoldist196", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_197", property="harVoldist197", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_198", property="harVoldist198", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_199", property="harVoldist199", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_200", property="harVoldist200", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_201", property="harVoldist201", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_202", property="harVoldist202", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_203", property="harVoldist203", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_204", property="harVoldist204", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_205", property="harVoldist205", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_206", property="harVoldist206", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_207", property="harVoldist207", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_208", property="harVoldist208", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_209", property="harVoldist209", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_210", property="harVoldist210", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_211", property="harVoldist211", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_212", property="harVoldist212", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_213", property="harVoldist213", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_214", property="harVoldist214", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_215", property="harVoldist215", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_216", property="harVoldist216", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_217", property="harVoldist217", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_218", property="harVoldist218", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_219", property="harVoldist219", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_220", property="harVoldist220", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_221", property="harVoldist221", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_222", property="harVoldist222", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_223", property="harVoldist223", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_224", property="harVoldist224", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_225", property="harVoldist225", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_226", property="harVoldist226", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_227", property="harVoldist227", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_228", property="harVoldist228", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_229", property="harVoldist229", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_230", property="harVoldist230", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_231", property="harVoldist231", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_232", property="harVoldist232", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_233", property="harVoldist233", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_234", property="harVoldist234", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_235", property="harVoldist235", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_236", property="harVoldist236", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_237", property="harVoldist237", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_238", property="harVoldist238", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_239", property="harVoldist239", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_240", property="harVoldist240", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_241", property="harVoldist241", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_242", property="harVoldist242", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_243", property="harVoldist243", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_244", property="harVoldist244", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_245", property="harVoldist245", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_246", property="harVoldist246", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_247", property="harVoldist247", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_248", property="harVoldist248", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_249", property="harVoldist249", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_250", property="harVoldist250", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_251", property="harVoldist251", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_252", property="harVoldist252", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_253", property="harVoldist253", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_254", property="harVoldist254", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_255", property="harVoldist255", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_256", property="harVoldist256", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_257", property="harVoldist257", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_258", property="harVoldist258", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_259", property="harVoldist259", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_260", property="harVoldist260", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_261", property="harVoldist261", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_262", property="harVoldist262", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_263", property="harVoldist263", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_264", property="harVoldist264", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_265", property="harVoldist265", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_266", property="harVoldist266", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_267", property="harVoldist267", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_268", property="harVoldist268", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_269", property="harVoldist269", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_270", property="harVoldist270", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_271", property="harVoldist271", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_272", property="harVoldist272", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_273", property="harVoldist273", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_274", property="harVoldist274", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_275", property="harVoldist275", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_276", property="harVoldist276", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_277", property="harVoldist277", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_278", property="harVoldist278", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_279", property="harVoldist279", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_280", property="harVoldist280", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_281", property="harVoldist281", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_282", property="harVoldist282", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_283", property="harVoldist283", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_284", property="harVoldist284", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_285", property="harVoldist285", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_286", property="harVoldist286", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_287", property="harVoldist287", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLDIST_288", property="harVoldist288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_mhaiVoldistCurvePo> selectVoldistCurveBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

}