package com.dao.mapper;

import com.dao.bean.D_powerCurvePo;
import com.dao.bean.D_powerCurvePoKey;
import com.dao.bean.D_powerPo;
import com.dao.provider.PoDataProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_powerCurvePoMapper {

    /**
     * 查询所有功率曲线
     * @param data_date
     * @return
     */
    @Select({
        "select",
        "DSM_SYS_ID SYS_ID, DSM_LD_ID LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, POWER_1, POWER_3, ",
        "POWER_2, POWER_4, POWER_5, POWER_6, POWER_7, POWER_8, POWER_9, POWER_10, POWER_11, ",
        "POWER_12, POWER_13, POWER_14, POWER_15, POWER_16, POWER_17, POWER_18, POWER_19, ",
        "POWER_20, POWER_21, POWER_22, POWER_23, POWER_24, POWER_25, POWER_26, POWER_27, ",
        "POWER_28, POWER_29, POWER_30, POWER_31, POWER_32, POWER_33, POWER_34, POWER_35, ",
        "POWER_36, POWER_37, POWER_38, POWER_39, POWER_40, POWER_41, POWER_42, POWER_43, ",
        "POWER_44, POWER_45, POWER_46, POWER_47, POWER_48, POWER_49, POWER_50, POWER_51, ",
        "POWER_52, POWER_53, POWER_54, POWER_55, POWER_56, POWER_57, POWER_58, POWER_59, ",
        "POWER_60, POWER_61, POWER_62, POWER_63, POWER_64, POWER_65, POWER_66, POWER_67, ",
        "POWER_68, POWER_69, POWER_70, POWER_71, POWER_72, POWER_73, POWER_74, POWER_75, ",
        "POWER_76, POWER_77, POWER_78, POWER_79, POWER_80, POWER_81, POWER_82, POWER_83, ",
        "POWER_84, POWER_85, POWER_86, POWER_87, POWER_88, POWER_89, POWER_90, POWER_91, ",
        "POWER_92, POWER_93, POWER_94, POWER_95, POWER_96, POWER_97, POWER_98, POWER_99, ",
        "POWER_100, POWER_101, POWER_102, POWER_103, POWER_104, POWER_105, POWER_106, ",
        "POWER_107, POWER_108, POWER_109, POWER_110, POWER_111, POWER_112, POWER_113, ",
        "POWER_114, POWER_115, POWER_116, POWER_117, POWER_118, POWER_119, POWER_120, ",
        "POWER_121, POWER_122, POWER_123, POWER_124, POWER_125, POWER_126, POWER_127, ",
        "POWER_128, POWER_129, POWER_130, POWER_131, POWER_132, POWER_133, POWER_134, ",
        "POWER_135, POWER_136, POWER_137, POWER_138, POWER_139, POWER_140, POWER_141, ",
        "POWER_142, POWER_143, POWER_144, POWER_145, POWER_146, POWER_147, POWER_148, ",
        "POWER_149, POWER_150, POWER_151, POWER_152, POWER_153, POWER_154, POWER_155, ",
        "POWER_156, POWER_157, POWER_158, POWER_159, POWER_160, POWER_161, POWER_162, ",
        "POWER_163, POWER_164, POWER_165, POWER_166, POWER_167, POWER_168, POWER_169, ",
        "POWER_170, POWER_171, POWER_172, POWER_173, POWER_174, POWER_175, POWER_176, ",
        "POWER_177, POWER_178, POWER_179, POWER_180, POWER_181, POWER_182, POWER_183, ",
        "POWER_184, POWER_185, POWER_186, POWER_187, POWER_188, POWER_189, POWER_190, ",
        "POWER_191, POWER_192, POWER_193, POWER_194, POWER_195, POWER_196, POWER_197, ",
        "POWER_198, POWER_199, POWER_200, POWER_201, POWER_202, POWER_203, POWER_204, ",
        "POWER_205, POWER_206, POWER_207, POWER_208, POWER_209, POWER_210, POWER_211, ",
        "POWER_212, POWER_213, POWER_214, POWER_215, POWER_216, POWER_217, POWER_218, ",
        "POWER_219, POWER_220, POWER_221, POWER_222, POWER_223, POWER_224, POWER_225, ",
        "POWER_226, POWER_227, POWER_228, POWER_229, POWER_230, POWER_231, POWER_232, ",
        "POWER_233, POWER_234, POWER_235, POWER_236, POWER_237, POWER_238, POWER_239, ",
        "POWER_240, POWER_241, POWER_242, POWER_243, POWER_244, POWER_245, POWER_246, ",
        "POWER_247, POWER_248, POWER_249, POWER_250, POWER_251, POWER_252, POWER_253, ",
        "POWER_254, POWER_255, POWER_256, POWER_257, POWER_258, POWER_259, POWER_260, ",
        "POWER_261, POWER_262, POWER_263, POWER_264, POWER_265, POWER_266, POWER_267, ",
        "POWER_268, POWER_269, POWER_270, POWER_271, POWER_272, POWER_273, POWER_274, ",
        "POWER_275, POWER_276, POWER_277, POWER_278, POWER_279, POWER_280, POWER_281, ",
        "POWER_282, POWER_283, POWER_284, POWER_285, POWER_286, POWER_287, POWER_288",
        "from dsm_mmxu_power_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="POWER_1", property="power1", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_3", property="power3", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_2", property="power2", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_4", property="power4", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_5", property="power5", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_6", property="power6", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_7", property="power7", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_8", property="power8", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_9", property="power9", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_10", property="power10", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_11", property="power11", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_12", property="power12", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_13", property="power13", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_14", property="power14", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_15", property="power15", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_16", property="power16", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_17", property="power17", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_18", property="power18", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_19", property="power19", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_20", property="power20", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_21", property="power21", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_22", property="power22", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_23", property="power23", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_24", property="power24", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_25", property="power25", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_26", property="power26", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_27", property="power27", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_28", property="power28", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_29", property="power29", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_30", property="power30", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_31", property="power31", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_32", property="power32", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_33", property="power33", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_34", property="power34", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_35", property="power35", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_36", property="power36", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_37", property="power37", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_38", property="power38", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_39", property="power39", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_40", property="power40", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_41", property="power41", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_42", property="power42", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_43", property="power43", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_44", property="power44", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_45", property="power45", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_46", property="power46", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_47", property="power47", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_48", property="power48", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_49", property="power49", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_50", property="power50", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_51", property="power51", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_52", property="power52", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_53", property="power53", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_54", property="power54", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_55", property="power55", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_56", property="power56", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_57", property="power57", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_58", property="power58", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_59", property="power59", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_60", property="power60", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_61", property="power61", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_62", property="power62", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_63", property="power63", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_64", property="power64", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_65", property="power65", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_66", property="power66", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_67", property="power67", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_68", property="power68", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_69", property="power69", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_70", property="power70", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_71", property="power71", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_72", property="power72", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_73", property="power73", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_74", property="power74", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_75", property="power75", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_76", property="power76", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_77", property="power77", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_78", property="power78", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_79", property="power79", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_80", property="power80", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_81", property="power81", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_82", property="power82", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_83", property="power83", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_84", property="power84", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_85", property="power85", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_86", property="power86", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_87", property="power87", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_88", property="power88", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_89", property="power89", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_90", property="power90", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_91", property="power91", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_92", property="power92", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_93", property="power93", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_94", property="power94", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_95", property="power95", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_96", property="power96", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_97", property="power97", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_98", property="power98", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_99", property="power99", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_100", property="power100", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_101", property="power101", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_102", property="power102", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_103", property="power103", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_104", property="power104", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_105", property="power105", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_106", property="power106", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_107", property="power107", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_108", property="power108", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_109", property="power109", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_110", property="power110", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_111", property="power111", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_112", property="power112", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_113", property="power113", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_114", property="power114", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_115", property="power115", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_116", property="power116", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_117", property="power117", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_118", property="power118", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_119", property="power119", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_120", property="power120", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_121", property="power121", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_122", property="power122", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_123", property="power123", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_124", property="power124", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_125", property="power125", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_126", property="power126", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_127", property="power127", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_128", property="power128", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_129", property="power129", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_130", property="power130", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_131", property="power131", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_132", property="power132", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_133", property="power133", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_134", property="power134", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_135", property="power135", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_136", property="power136", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_137", property="power137", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_138", property="power138", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_139", property="power139", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_140", property="power140", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_141", property="power141", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_142", property="power142", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_143", property="power143", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_144", property="power144", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_145", property="power145", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_146", property="power146", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_147", property="power147", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_148", property="power148", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_149", property="power149", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_150", property="power150", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_151", property="power151", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_152", property="power152", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_153", property="power153", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_154", property="power154", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_155", property="power155", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_156", property="power156", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_157", property="power157", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_158", property="power158", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_159", property="power159", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_160", property="power160", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_161", property="power161", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_162", property="power162", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_163", property="power163", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_164", property="power164", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_165", property="power165", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_166", property="power166", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_167", property="power167", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_168", property="power168", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_169", property="power169", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_170", property="power170", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_171", property="power171", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_172", property="power172", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_173", property="power173", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_174", property="power174", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_175", property="power175", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_176", property="power176", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_177", property="power177", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_178", property="power178", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_179", property="power179", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_180", property="power180", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_181", property="power181", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_182", property="power182", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_183", property="power183", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_184", property="power184", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_185", property="power185", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_186", property="power186", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_187", property="power187", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_188", property="power188", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_189", property="power189", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_190", property="power190", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_191", property="power191", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_192", property="power192", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_193", property="power193", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_194", property="power194", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_195", property="power195", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_196", property="power196", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_197", property="power197", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_198", property="power198", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_199", property="power199", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_200", property="power200", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_201", property="power201", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_202", property="power202", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_203", property="power203", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_204", property="power204", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_205", property="power205", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_206", property="power206", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_207", property="power207", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_208", property="power208", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_209", property="power209", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_210", property="power210", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_211", property="power211", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_212", property="power212", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_213", property="power213", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_214", property="power214", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_215", property="power215", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_216", property="power216", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_217", property="power217", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_218", property="power218", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_219", property="power219", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_220", property="power220", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_221", property="power221", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_222", property="power222", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_223", property="power223", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_224", property="power224", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_225", property="power225", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_226", property="power226", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_227", property="power227", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_228", property="power228", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_229", property="power229", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_230", property="power230", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_231", property="power231", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_232", property="power232", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_233", property="power233", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_234", property="power234", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_235", property="power235", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_236", property="power236", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_237", property="power237", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_238", property="power238", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_239", property="power239", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_240", property="power240", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_241", property="power241", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_242", property="power242", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_243", property="power243", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_244", property="power244", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_245", property="power245", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_246", property="power246", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_247", property="power247", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_248", property="power248", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_249", property="power249", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_250", property="power250", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_251", property="power251", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_252", property="power252", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_253", property="power253", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_254", property="power254", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_255", property="power255", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_256", property="power256", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_257", property="power257", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_258", property="power258", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_259", property="power259", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_260", property="power260", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_261", property="power261", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_262", property="power262", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_263", property="power263", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_264", property="power264", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_265", property="power265", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_266", property="power266", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_267", property="power267", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_268", property="power268", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_269", property="power269", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_270", property="power270", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_271", property="power271", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_272", property="power272", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_273", property="power273", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_274", property="power274", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_275", property="power275", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_276", property="power276", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_277", property="power277", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_278", property="power278", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_279", property="power279", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_280", property="power280", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_281", property="power281", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_282", property="power282", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_283", property="power283", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_284", property="power284", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_285", property="power285", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_286", property="power286", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_287", property="power287", jdbcType=JdbcType.DECIMAL),
        @Result(column="POWER_288", property="power288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_powerCurvePo> selectByDate(String data_date);

    /**
     * 查询两个日期之间所有功率曲线
     * @param start_date
     * @param end_date
     * @return
     */
    @Select({
            "select",
            "DSM_SYS_ID SYS_ID, DSM_LD_ID LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, POWER_1, POWER_3, ",
            "POWER_2, POWER_4, POWER_5, POWER_6, POWER_7, POWER_8, POWER_9, POWER_10, POWER_11, ",
            "POWER_12, POWER_13, POWER_14, POWER_15, POWER_16, POWER_17, POWER_18, POWER_19, ",
            "POWER_20, POWER_21, POWER_22, POWER_23, POWER_24, POWER_25, POWER_26, POWER_27, ",
            "POWER_28, POWER_29, POWER_30, POWER_31, POWER_32, POWER_33, POWER_34, POWER_35, ",
            "POWER_36, POWER_37, POWER_38, POWER_39, POWER_40, POWER_41, POWER_42, POWER_43, ",
            "POWER_44, POWER_45, POWER_46, POWER_47, POWER_48, POWER_49, POWER_50, POWER_51, ",
            "POWER_52, POWER_53, POWER_54, POWER_55, POWER_56, POWER_57, POWER_58, POWER_59, ",
            "POWER_60, POWER_61, POWER_62, POWER_63, POWER_64, POWER_65, POWER_66, POWER_67, ",
            "POWER_68, POWER_69, POWER_70, POWER_71, POWER_72, POWER_73, POWER_74, POWER_75, ",
            "POWER_76, POWER_77, POWER_78, POWER_79, POWER_80, POWER_81, POWER_82, POWER_83, ",
            "POWER_84, POWER_85, POWER_86, POWER_87, POWER_88, POWER_89, POWER_90, POWER_91, ",
            "POWER_92, POWER_93, POWER_94, POWER_95, POWER_96, POWER_97, POWER_98, POWER_99, ",
            "POWER_100, POWER_101, POWER_102, POWER_103, POWER_104, POWER_105, POWER_106, ",
            "POWER_107, POWER_108, POWER_109, POWER_110, POWER_111, POWER_112, POWER_113, ",
            "POWER_114, POWER_115, POWER_116, POWER_117, POWER_118, POWER_119, POWER_120, ",
            "POWER_121, POWER_122, POWER_123, POWER_124, POWER_125, POWER_126, POWER_127, ",
            "POWER_128, POWER_129, POWER_130, POWER_131, POWER_132, POWER_133, POWER_134, ",
            "POWER_135, POWER_136, POWER_137, POWER_138, POWER_139, POWER_140, POWER_141, ",
            "POWER_142, POWER_143, POWER_144, POWER_145, POWER_146, POWER_147, POWER_148, ",
            "POWER_149, POWER_150, POWER_151, POWER_152, POWER_153, POWER_154, POWER_155, ",
            "POWER_156, POWER_157, POWER_158, POWER_159, POWER_160, POWER_161, POWER_162, ",
            "POWER_163, POWER_164, POWER_165, POWER_166, POWER_167, POWER_168, POWER_169, ",
            "POWER_170, POWER_171, POWER_172, POWER_173, POWER_174, POWER_175, POWER_176, ",
            "POWER_177, POWER_178, POWER_179, POWER_180, POWER_181, POWER_182, POWER_183, ",
            "POWER_184, POWER_185, POWER_186, POWER_187, POWER_188, POWER_189, POWER_190, ",
            "POWER_191, POWER_192, POWER_193, POWER_194, POWER_195, POWER_196, POWER_197, ",
            "POWER_198, POWER_199, POWER_200, POWER_201, POWER_202, POWER_203, POWER_204, ",
            "POWER_205, POWER_206, POWER_207, POWER_208, POWER_209, POWER_210, POWER_211, ",
            "POWER_212, POWER_213, POWER_214, POWER_215, POWER_216, POWER_217, POWER_218, ",
            "POWER_219, POWER_220, POWER_221, POWER_222, POWER_223, POWER_224, POWER_225, ",
            "POWER_226, POWER_227, POWER_228, POWER_229, POWER_230, POWER_231, POWER_232, ",
            "POWER_233, POWER_234, POWER_235, POWER_236, POWER_237, POWER_238, POWER_239, ",
            "POWER_240, POWER_241, POWER_242, POWER_243, POWER_244, POWER_245, POWER_246, ",
            "POWER_247, POWER_248, POWER_249, POWER_250, POWER_251, POWER_252, POWER_253, ",
            "POWER_254, POWER_255, POWER_256, POWER_257, POWER_258, POWER_259, POWER_260, ",
            "POWER_261, POWER_262, POWER_263, POWER_264, POWER_265, POWER_266, POWER_267, ",
            "POWER_268, POWER_269, POWER_270, POWER_271, POWER_272, POWER_273, POWER_274, ",
            "POWER_275, POWER_276, POWER_277, POWER_278, POWER_279, POWER_280, POWER_281, ",
            "POWER_282, POWER_283, POWER_284, POWER_285, POWER_286, POWER_287, POWER_288",
            "from dsm_mmxu_power_c ",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="POWER_1", property="power1", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_3", property="power3", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_2", property="power2", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_4", property="power4", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_5", property="power5", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_6", property="power6", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_7", property="power7", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_8", property="power8", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_9", property="power9", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_10", property="power10", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_11", property="power11", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_12", property="power12", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_13", property="power13", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_14", property="power14", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_15", property="power15", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_16", property="power16", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_17", property="power17", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_18", property="power18", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_19", property="power19", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_20", property="power20", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_21", property="power21", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_22", property="power22", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_23", property="power23", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_24", property="power24", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_25", property="power25", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_26", property="power26", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_27", property="power27", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_28", property="power28", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_29", property="power29", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_30", property="power30", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_31", property="power31", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_32", property="power32", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_33", property="power33", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_34", property="power34", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_35", property="power35", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_36", property="power36", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_37", property="power37", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_38", property="power38", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_39", property="power39", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_40", property="power40", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_41", property="power41", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_42", property="power42", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_43", property="power43", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_44", property="power44", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_45", property="power45", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_46", property="power46", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_47", property="power47", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_48", property="power48", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_49", property="power49", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_50", property="power50", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_51", property="power51", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_52", property="power52", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_53", property="power53", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_54", property="power54", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_55", property="power55", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_56", property="power56", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_57", property="power57", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_58", property="power58", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_59", property="power59", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_60", property="power60", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_61", property="power61", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_62", property="power62", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_63", property="power63", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_64", property="power64", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_65", property="power65", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_66", property="power66", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_67", property="power67", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_68", property="power68", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_69", property="power69", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_70", property="power70", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_71", property="power71", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_72", property="power72", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_73", property="power73", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_74", property="power74", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_75", property="power75", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_76", property="power76", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_77", property="power77", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_78", property="power78", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_79", property="power79", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_80", property="power80", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_81", property="power81", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_82", property="power82", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_83", property="power83", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_84", property="power84", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_85", property="power85", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_86", property="power86", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_87", property="power87", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_88", property="power88", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_89", property="power89", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_90", property="power90", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_91", property="power91", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_92", property="power92", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_93", property="power93", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_94", property="power94", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_95", property="power95", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_96", property="power96", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_97", property="power97", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_98", property="power98", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_99", property="power99", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_100", property="power100", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_101", property="power101", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_102", property="power102", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_103", property="power103", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_104", property="power104", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_105", property="power105", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_106", property="power106", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_107", property="power107", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_108", property="power108", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_109", property="power109", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_110", property="power110", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_111", property="power111", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_112", property="power112", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_113", property="power113", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_114", property="power114", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_115", property="power115", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_116", property="power116", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_117", property="power117", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_118", property="power118", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_119", property="power119", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_120", property="power120", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_121", property="power121", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_122", property="power122", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_123", property="power123", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_124", property="power124", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_125", property="power125", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_126", property="power126", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_127", property="power127", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_128", property="power128", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_129", property="power129", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_130", property="power130", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_131", property="power131", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_132", property="power132", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_133", property="power133", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_134", property="power134", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_135", property="power135", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_136", property="power136", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_137", property="power137", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_138", property="power138", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_139", property="power139", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_140", property="power140", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_141", property="power141", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_142", property="power142", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_143", property="power143", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_144", property="power144", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_145", property="power145", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_146", property="power146", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_147", property="power147", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_148", property="power148", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_149", property="power149", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_150", property="power150", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_151", property="power151", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_152", property="power152", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_153", property="power153", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_154", property="power154", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_155", property="power155", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_156", property="power156", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_157", property="power157", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_158", property="power158", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_159", property="power159", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_160", property="power160", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_161", property="power161", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_162", property="power162", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_163", property="power163", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_164", property="power164", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_165", property="power165", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_166", property="power166", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_167", property="power167", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_168", property="power168", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_169", property="power169", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_170", property="power170", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_171", property="power171", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_172", property="power172", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_173", property="power173", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_174", property="power174", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_175", property="power175", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_176", property="power176", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_177", property="power177", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_178", property="power178", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_179", property="power179", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_180", property="power180", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_181", property="power181", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_182", property="power182", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_183", property="power183", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_184", property="power184", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_185", property="power185", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_186", property="power186", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_187", property="power187", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_188", property="power188", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_189", property="power189", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_190", property="power190", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_191", property="power191", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_192", property="power192", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_193", property="power193", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_194", property="power194", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_195", property="power195", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_196", property="power196", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_197", property="power197", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_198", property="power198", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_199", property="power199", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_200", property="power200", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_201", property="power201", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_202", property="power202", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_203", property="power203", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_204", property="power204", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_205", property="power205", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_206", property="power206", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_207", property="power207", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_208", property="power208", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_209", property="power209", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_210", property="power210", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_211", property="power211", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_212", property="power212", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_213", property="power213", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_214", property="power214", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_215", property="power215", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_216", property="power216", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_217", property="power217", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_218", property="power218", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_219", property="power219", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_220", property="power220", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_221", property="power221", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_222", property="power222", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_223", property="power223", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_224", property="power224", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_225", property="power225", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_226", property="power226", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_227", property="power227", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_228", property="power228", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_229", property="power229", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_230", property="power230", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_231", property="power231", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_232", property="power232", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_233", property="power233", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_234", property="power234", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_235", property="power235", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_236", property="power236", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_237", property="power237", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_238", property="power238", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_239", property="power239", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_240", property="power240", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_241", property="power241", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_242", property="power242", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_243", property="power243", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_244", property="power244", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_245", property="power245", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_246", property="power246", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_247", property="power247", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_248", property="power248", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_249", property="power249", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_250", property="power250", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_251", property="power251", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_252", property="power252", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_253", property="power253", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_254", property="power254", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_255", property="power255", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_256", property="power256", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_257", property="power257", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_258", property="power258", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_259", property="power259", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_260", property="power260", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_261", property="power261", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_262", property="power262", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_263", property="power263", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_264", property="power264", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_265", property="power265", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_266", property="power266", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_267", property="power267", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_268", property="power268", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_269", property="power269", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_270", property="power270", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_271", property="power271", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_272", property="power272", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_273", property="power273", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_274", property="power274", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_275", property="power275", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_276", property="power276", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_277", property="power277", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_278", property="power278", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_279", property="power279", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_280", property="power280", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_281", property="power281", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_282", property="power282", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_283", property="power283", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_284", property="power284", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_285", property="power285", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_286", property="power286", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_287", property="power287", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_288", property="power288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_powerCurvePo> selectBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

    /**
     * 通过greatest获取最大值，但是无法获取最大值的时间 放弃
     * @param start_date
     * @param end_date
     * @return
     */
    @Select({
            "select",
            "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, GREATEST(POWER_1, POWER_3, ",
            "POWER_2, POWER_4, POWER_5, POWER_6, POWER_7, POWER_8, POWER_9, POWER_10, POWER_11, ",
            "POWER_12, POWER_13, POWER_14, POWER_15, POWER_16, POWER_17, POWER_18, POWER_19, ",
            "POWER_20, POWER_21, POWER_22, POWER_23, POWER_24, POWER_25, POWER_26, POWER_27, ",
            "POWER_28, POWER_29, POWER_30, POWER_31, POWER_32, POWER_33, POWER_34, POWER_35, ",
            "POWER_36, POWER_37, POWER_38, POWER_39, POWER_40, POWER_41, POWER_42, POWER_43, ",
            "POWER_44, POWER_45, POWER_46, POWER_47, POWER_48, POWER_49, POWER_50, POWER_51, ",
            "POWER_52, POWER_53, POWER_54, POWER_55, POWER_56, POWER_57, POWER_58, POWER_59, ",
            "POWER_60, POWER_61, POWER_62, POWER_63, POWER_64, POWER_65, POWER_66, POWER_67, ",
            "POWER_68, POWER_69, POWER_70, POWER_71, POWER_72, POWER_73, POWER_74, POWER_75, ",
            "POWER_76, POWER_77, POWER_78, POWER_79, POWER_80, POWER_81, POWER_82, POWER_83, ",
            "POWER_84, POWER_85, POWER_86, POWER_87, POWER_88, POWER_89, POWER_90, POWER_91, ",
            "POWER_92, POWER_93, POWER_94, POWER_95, POWER_96, POWER_97, POWER_98, POWER_99, ",
            "POWER_100, POWER_101, POWER_102, POWER_103, POWER_104, POWER_105, POWER_106, ",
            "POWER_107, POWER_108, POWER_109, POWER_110, POWER_111, POWER_112, POWER_113, ",
            "POWER_114, POWER_115, POWER_116, POWER_117, POWER_118, POWER_119, POWER_120, ",
            "POWER_121, POWER_122, POWER_123, POWER_124, POWER_125, POWER_126, POWER_127, ",
            "POWER_128, POWER_129, POWER_130, POWER_131, POWER_132, POWER_133, POWER_134, ",
            "POWER_135, POWER_136, POWER_137, POWER_138, POWER_139, POWER_140, POWER_141, ",
            "POWER_142, POWER_143, POWER_144, POWER_145, POWER_146, POWER_147, POWER_148, ",
            "POWER_149, POWER_150, POWER_151, POWER_152, POWER_153, POWER_154, POWER_155, ",
            "POWER_156, POWER_157, POWER_158, POWER_159, POWER_160, POWER_161, POWER_162, ",
            "POWER_163, POWER_164, POWER_165, POWER_166, POWER_167, POWER_168, POWER_169, ",
            "POWER_170, POWER_171, POWER_172, POWER_173, POWER_174, POWER_175, POWER_176, ",
            "POWER_177, POWER_178, POWER_179, POWER_180, POWER_181, POWER_182, POWER_183, ",
            "POWER_184, POWER_185, POWER_186, POWER_187, POWER_188, POWER_189, POWER_190, ",
            "POWER_191, POWER_192, POWER_193, POWER_194, POWER_195, POWER_196, POWER_197, ",
            "POWER_198, POWER_199, POWER_200, POWER_201, POWER_202, POWER_203, POWER_204, ",
            "POWER_205, POWER_206, POWER_207, POWER_208, POWER_209, POWER_210, POWER_211, ",
            "POWER_212, POWER_213, POWER_214, POWER_215, POWER_216, POWER_217, POWER_218, ",
            "POWER_219, POWER_220, POWER_221, POWER_222, POWER_223, POWER_224, POWER_225, ",
            "POWER_226, POWER_227, POWER_228, POWER_229, POWER_230, POWER_231, POWER_232, ",
            "POWER_233, POWER_234, POWER_235, POWER_236, POWER_237, POWER_238, POWER_239, ",
            "POWER_240, POWER_241, POWER_242, POWER_243, POWER_244, POWER_245, POWER_246, ",
            "POWER_247, POWER_248, POWER_249, POWER_250, POWER_251, POWER_252, POWER_253, ",
            "POWER_254, POWER_255, POWER_256, POWER_257, POWER_258, POWER_259, POWER_260, ",
            "POWER_261, POWER_262, POWER_263, POWER_264, POWER_265, POWER_266, POWER_267, ",
            "POWER_268, POWER_269, POWER_270, POWER_271, POWER_272, POWER_273, POWER_274, ",
            "POWER_275, POWER_276, POWER_277, POWER_278, POWER_279, POWER_280, POWER_281, ",
            "POWER_282, POWER_283, POWER_284, POWER_285, POWER_286, POWER_287, POWER_288) max_value",
            "POWER_1, POWER_3, ",
            "POWER_2, POWER_4, POWER_5, POWER_6, POWER_7, POWER_8, POWER_9, POWER_10, POWER_11, ",
            "POWER_12, POWER_13, POWER_14, POWER_15, POWER_16, POWER_17, POWER_18, POWER_19, ",
            "POWER_20, POWER_21, POWER_22, POWER_23, POWER_24, POWER_25, POWER_26, POWER_27, ",
            "POWER_28, POWER_29, POWER_30, POWER_31, POWER_32, POWER_33, POWER_34, POWER_35, ",
            "POWER_36, POWER_37, POWER_38, POWER_39, POWER_40, POWER_41, POWER_42, POWER_43, ",
            "POWER_44, POWER_45, POWER_46, POWER_47, POWER_48, POWER_49, POWER_50, POWER_51, ",
            "POWER_52, POWER_53, POWER_54, POWER_55, POWER_56, POWER_57, POWER_58, POWER_59, ",
            "POWER_60, POWER_61, POWER_62, POWER_63, POWER_64, POWER_65, POWER_66, POWER_67, ",
            "POWER_68, POWER_69, POWER_70, POWER_71, POWER_72, POWER_73, POWER_74, POWER_75, ",
            "POWER_76, POWER_77, POWER_78, POWER_79, POWER_80, POWER_81, POWER_82, POWER_83, ",
            "POWER_84, POWER_85, POWER_86, POWER_87, POWER_88, POWER_89, POWER_90, POWER_91, ",
            "POWER_92, POWER_93, POWER_94, POWER_95, POWER_96, POWER_97, POWER_98, POWER_99, ",
            "POWER_100, POWER_101, POWER_102, POWER_103, POWER_104, POWER_105, POWER_106, ",
            "POWER_107, POWER_108, POWER_109, POWER_110, POWER_111, POWER_112, POWER_113, ",
            "POWER_114, POWER_115, POWER_116, POWER_117, POWER_118, POWER_119, POWER_120, ",
            "POWER_121, POWER_122, POWER_123, POWER_124, POWER_125, POWER_126, POWER_127, ",
            "POWER_128, POWER_129, POWER_130, POWER_131, POWER_132, POWER_133, POWER_134, ",
            "POWER_135, POWER_136, POWER_137, POWER_138, POWER_139, POWER_140, POWER_141, ",
            "POWER_142, POWER_143, POWER_144, POWER_145, POWER_146, POWER_147, POWER_148, ",
            "POWER_149, POWER_150, POWER_151, POWER_152, POWER_153, POWER_154, POWER_155, ",
            "POWER_156, POWER_157, POWER_158, POWER_159, POWER_160, POWER_161, POWER_162, ",
            "POWER_163, POWER_164, POWER_165, POWER_166, POWER_167, POWER_168, POWER_169, ",
            "POWER_170, POWER_171, POWER_172, POWER_173, POWER_174, POWER_175, POWER_176, ",
            "POWER_177, POWER_178, POWER_179, POWER_180, POWER_181, POWER_182, POWER_183, ",
            "POWER_184, POWER_185, POWER_186, POWER_187, POWER_188, POWER_189, POWER_190, ",
            "POWER_191, POWER_192, POWER_193, POWER_194, POWER_195, POWER_196, POWER_197, ",
            "POWER_198, POWER_199, POWER_200, POWER_201, POWER_202, POWER_203, POWER_204, ",
            "POWER_205, POWER_206, POWER_207, POWER_208, POWER_209, POWER_210, POWER_211, ",
            "POWER_212, POWER_213, POWER_214, POWER_215, POWER_216, POWER_217, POWER_218, ",
            "POWER_219, POWER_220, POWER_221, POWER_222, POWER_223, POWER_224, POWER_225, ",
            "POWER_226, POWER_227, POWER_228, POWER_229, POWER_230, POWER_231, POWER_232, ",
            "POWER_233, POWER_234, POWER_235, POWER_236, POWER_237, POWER_238, POWER_239, ",
            "POWER_240, POWER_241, POWER_242, POWER_243, POWER_244, POWER_245, POWER_246, ",
            "POWER_247, POWER_248, POWER_249, POWER_250, POWER_251, POWER_252, POWER_253, ",
            "POWER_254, POWER_255, POWER_256, POWER_257, POWER_258, POWER_259, POWER_260, ",
            "POWER_261, POWER_262, POWER_263, POWER_264, POWER_265, POWER_266, POWER_267, ",
            "POWER_268, POWER_269, POWER_270, POWER_271, POWER_272, POWER_273, POWER_274, ",
            "POWER_275, POWER_276, POWER_277, POWER_278, POWER_279, POWER_280, POWER_281, ",
            "POWER_282, POWER_283, POWER_284, POWER_285, POWER_286, POWER_287, POWER_288",
            "from dsm_mmxu_power_c ",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="POWER_1", property="power1", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_3", property="power3", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_2", property="power2", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_4", property="power4", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_5", property="power5", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_6", property="power6", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_7", property="power7", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_8", property="power8", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_9", property="power9", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_10", property="power10", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_11", property="power11", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_12", property="power12", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_13", property="power13", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_14", property="power14", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_15", property="power15", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_16", property="power16", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_17", property="power17", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_18", property="power18", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_19", property="power19", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_20", property="power20", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_21", property="power21", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_22", property="power22", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_23", property="power23", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_24", property="power24", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_25", property="power25", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_26", property="power26", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_27", property="power27", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_28", property="power28", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_29", property="power29", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_30", property="power30", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_31", property="power31", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_32", property="power32", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_33", property="power33", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_34", property="power34", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_35", property="power35", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_36", property="power36", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_37", property="power37", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_38", property="power38", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_39", property="power39", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_40", property="power40", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_41", property="power41", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_42", property="power42", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_43", property="power43", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_44", property="power44", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_45", property="power45", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_46", property="power46", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_47", property="power47", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_48", property="power48", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_49", property="power49", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_50", property="power50", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_51", property="power51", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_52", property="power52", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_53", property="power53", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_54", property="power54", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_55", property="power55", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_56", property="power56", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_57", property="power57", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_58", property="power58", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_59", property="power59", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_60", property="power60", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_61", property="power61", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_62", property="power62", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_63", property="power63", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_64", property="power64", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_65", property="power65", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_66", property="power66", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_67", property="power67", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_68", property="power68", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_69", property="power69", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_70", property="power70", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_71", property="power71", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_72", property="power72", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_73", property="power73", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_74", property="power74", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_75", property="power75", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_76", property="power76", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_77", property="power77", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_78", property="power78", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_79", property="power79", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_80", property="power80", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_81", property="power81", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_82", property="power82", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_83", property="power83", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_84", property="power84", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_85", property="power85", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_86", property="power86", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_87", property="power87", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_88", property="power88", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_89", property="power89", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_90", property="power90", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_91", property="power91", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_92", property="power92", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_93", property="power93", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_94", property="power94", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_95", property="power95", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_96", property="power96", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_97", property="power97", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_98", property="power98", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_99", property="power99", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_100", property="power100", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_101", property="power101", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_102", property="power102", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_103", property="power103", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_104", property="power104", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_105", property="power105", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_106", property="power106", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_107", property="power107", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_108", property="power108", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_109", property="power109", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_110", property="power110", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_111", property="power111", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_112", property="power112", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_113", property="power113", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_114", property="power114", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_115", property="power115", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_116", property="power116", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_117", property="power117", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_118", property="power118", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_119", property="power119", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_120", property="power120", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_121", property="power121", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_122", property="power122", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_123", property="power123", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_124", property="power124", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_125", property="power125", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_126", property="power126", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_127", property="power127", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_128", property="power128", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_129", property="power129", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_130", property="power130", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_131", property="power131", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_132", property="power132", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_133", property="power133", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_134", property="power134", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_135", property="power135", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_136", property="power136", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_137", property="power137", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_138", property="power138", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_139", property="power139", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_140", property="power140", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_141", property="power141", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_142", property="power142", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_143", property="power143", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_144", property="power144", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_145", property="power145", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_146", property="power146", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_147", property="power147", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_148", property="power148", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_149", property="power149", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_150", property="power150", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_151", property="power151", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_152", property="power152", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_153", property="power153", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_154", property="power154", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_155", property="power155", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_156", property="power156", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_157", property="power157", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_158", property="power158", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_159", property="power159", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_160", property="power160", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_161", property="power161", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_162", property="power162", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_163", property="power163", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_164", property="power164", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_165", property="power165", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_166", property="power166", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_167", property="power167", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_168", property="power168", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_169", property="power169", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_170", property="power170", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_171", property="power171", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_172", property="power172", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_173", property="power173", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_174", property="power174", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_175", property="power175", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_176", property="power176", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_177", property="power177", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_178", property="power178", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_179", property="power179", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_180", property="power180", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_181", property="power181", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_182", property="power182", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_183", property="power183", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_184", property="power184", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_185", property="power185", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_186", property="power186", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_187", property="power187", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_188", property="power188", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_189", property="power189", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_190", property="power190", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_191", property="power191", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_192", property="power192", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_193", property="power193", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_194", property="power194", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_195", property="power195", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_196", property="power196", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_197", property="power197", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_198", property="power198", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_199", property="power199", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_200", property="power200", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_201", property="power201", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_202", property="power202", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_203", property="power203", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_204", property="power204", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_205", property="power205", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_206", property="power206", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_207", property="power207", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_208", property="power208", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_209", property="power209", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_210", property="power210", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_211", property="power211", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_212", property="power212", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_213", property="power213", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_214", property="power214", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_215", property="power215", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_216", property="power216", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_217", property="power217", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_218", property="power218", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_219", property="power219", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_220", property="power220", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_221", property="power221", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_222", property="power222", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_223", property="power223", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_224", property="power224", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_225", property="power225", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_226", property="power226", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_227", property="power227", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_228", property="power228", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_229", property="power229", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_230", property="power230", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_231", property="power231", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_232", property="power232", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_233", property="power233", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_234", property="power234", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_235", property="power235", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_236", property="power236", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_237", property="power237", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_238", property="power238", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_239", property="power239", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_240", property="power240", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_241", property="power241", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_242", property="power242", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_243", property="power243", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_244", property="power244", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_245", property="power245", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_246", property="power246", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_247", property="power247", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_248", property="power248", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_249", property="power249", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_250", property="power250", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_251", property="power251", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_252", property="power252", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_253", property="power253", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_254", property="power254", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_255", property="power255", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_256", property="power256", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_257", property="power257", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_258", property="power258", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_259", property="power259", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_260", property="power260", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_261", property="power261", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_262", property="power262", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_263", property="power263", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_264", property="power264", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_265", property="power265", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_266", property="power266", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_267", property="power267", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_268", property="power268", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_269", property="power269", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_270", property="power270", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_271", property="power271", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_272", property="power272", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_273", property="power273", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_274", property="power274", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_275", property="power275", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_276", property="power276", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_277", property="power277", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_278", property="power278", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_279", property="power279", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_280", property="power280", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_281", property="power281", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_282", property="power282", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_283", property="power283", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_284", property="power284", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_285", property="power285", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_286", property="power286", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_287", property="power287", jdbcType=JdbcType.DECIMAL),
            @Result(column="POWER_288", property="power288", jdbcType=JdbcType.DECIMAL)
    })
//    @SelectProvider(type= PoDataProvider.class, method = "powerPo")
    List<D_powerCurvePo> selectBy22Date(String start_date, String end_date);

}