package com.dao.mapper;

import com.dao.bean.D_tmpCurvePo;
import com.dao.bean.D_tmpCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_tmpCurvePoMapper {

    @Select({
        "select",
        "LD_ID, SYS_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, TMP_1, TMP_2, ",
        "TMP_3, TMP_4, TMP_5, TMP_6, TMP_7, TMP_8, TMP_9, TMP_10, TMP_11, TMP_12, TMP_13, ",
        "TMP_14, TMP_15, TMP_16, TMP_17, TMP_18, TMP_19, TMP_20, TMP_21, TMP_22, TMP_23, ",
        "TMP_24, TMP_25, TMP_26, TMP_27, TMP_28, TMP_29, TMP_30, TMP_31, TMP_32, TMP_33, ",
        "TMP_34, TMP_35, TMP_36, TMP_37, TMP_38, TMP_39, TMP_40, TMP_41, TMP_42, TMP_43, ",
        "TMP_44, TMP_45, TMP_46, TMP_47, TMP_48, TMP_49, TMP_50, TMP_51, TMP_52, TMP_53, ",
        "TMP_54, TMP_55, TMP_56, TMP_57, TMP_58, TMP_59, TMP_60, TMP_61, TMP_62, TMP_63, ",
        "TMP_64, TMP_65, TMP_66, TMP_67, TMP_68, TMP_69, TMP_70, TMP_71, TMP_72, TMP_73, ",
        "TMP_74, TMP_75, TMP_76, TMP_77, TMP_78, TMP_79, TMP_80, TMP_81, TMP_82, TMP_83, ",
        "TMP_84, TMP_85, TMP_86, TMP_87, TMP_88, TMP_89, TMP_90, TMP_91, TMP_92, TMP_93, ",
        "TMP_94, TMP_95, TMP_96, TMP_97, TMP_98, TMP_99, TMP_100, TMP_101, TMP_102, TMP_103, ",
        "TMP_104, TMP_105, TMP_106, TMP_107, TMP_108, TMP_109, TMP_110, TMP_111, TMP_112, ",
        "TMP_113, TMP_114, TMP_115, TMP_116, TMP_117, TMP_118, TMP_119, TMP_120, TMP_121, ",
        "TMP_122, TMP_123, TMP_124, TMP_125, TMP_126, TMP_127, TMP_128, TMP_129, TMP_130, ",
        "TMP_131, TMP_132, TMP_133, TMP_134, TMP_135, TMP_136, TMP_137, TMP_138, TMP_139, ",
        "TMP_140, TMP_141, TMP_142, TMP_143, TMP_144, TMP_145, TMP_146, TMP_147, TMP_148, ",
        "TMP_149, TMP_150, TMP_151, TMP_152, TMP_153, TMP_154, TMP_155, TMP_156, TMP_157, ",
        "TMP_158, TMP_159, TMP_160, TMP_161, TMP_162, TMP_163, TMP_164, TMP_165, TMP_166, ",
        "TMP_167, TMP_168, TMP_169, TMP_170, TMP_171, TMP_172, TMP_173, TMP_174, TMP_175, ",
        "TMP_176, TMP_177, TMP_178, TMP_179, TMP_180, TMP_181, TMP_182, TMP_183, TMP_184, ",
        "TMP_185, TMP_186, TMP_187, TMP_188, TMP_189, TMP_190, TMP_191, TMP_192, TMP_193, ",
        "TMP_194, TMP_195, TMP_196, TMP_197, TMP_198, TMP_199, TMP_200, TMP_201, TMP_202, ",
        "TMP_203, TMP_204, TMP_205, TMP_206, TMP_207, TMP_208, TMP_209, TMP_210, TMP_211, ",
        "TMP_212, TMP_213, TMP_214, TMP_215, TMP_216, TMP_217, TMP_218, TMP_219, TMP_220, ",
        "TMP_221, TMP_222, TMP_223, TMP_224, TMP_225, TMP_226, TMP_227, TMP_228, TMP_229, ",
        "TMP_230, TMP_231, TMP_232, TMP_233, TMP_234, TMP_235, TMP_236, TMP_237, TMP_238, ",
        "TMP_239, TMP_240, TMP_241, TMP_242, TMP_243, TMP_244, TMP_245, TMP_246, TMP_247, ",
        "TMP_248, TMP_249, TMP_250, TMP_251, TMP_252, TMP_253, TMP_254, TMP_255, TMP_256, ",
        "TMP_257, TMP_258, TMP_259, TMP_260, TMP_261, TMP_262, TMP_263, TMP_264, TMP_265, ",
        "TMP_266, TMP_267, TMP_268, TMP_269, TMP_270, TMP_271, TMP_272, TMP_273, TMP_274, ",
        "TMP_275, TMP_276, TMP_277, TMP_278, TMP_279, TMP_280, TMP_281, TMP_282, TMP_283, ",
        "TMP_284, TMP_285, TMP_286, TMP_287, TMP_288",
        "from c_stmp_tmp_c" ,
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="TMP_1", property="tmp1", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_2", property="tmp2", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_3", property="tmp3", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_4", property="tmp4", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_5", property="tmp5", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_6", property="tmp6", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_7", property="tmp7", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_8", property="tmp8", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_9", property="tmp9", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_10", property="tmp10", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_11", property="tmp11", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_12", property="tmp12", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_13", property="tmp13", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_14", property="tmp14", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_15", property="tmp15", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_16", property="tmp16", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_17", property="tmp17", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_18", property="tmp18", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_19", property="tmp19", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_20", property="tmp20", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_21", property="tmp21", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_22", property="tmp22", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_23", property="tmp23", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_24", property="tmp24", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_25", property="tmp25", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_26", property="tmp26", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_27", property="tmp27", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_28", property="tmp28", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_29", property="tmp29", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_30", property="tmp30", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_31", property="tmp31", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_32", property="tmp32", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_33", property="tmp33", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_34", property="tmp34", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_35", property="tmp35", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_36", property="tmp36", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_37", property="tmp37", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_38", property="tmp38", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_39", property="tmp39", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_40", property="tmp40", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_41", property="tmp41", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_42", property="tmp42", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_43", property="tmp43", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_44", property="tmp44", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_45", property="tmp45", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_46", property="tmp46", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_47", property="tmp47", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_48", property="tmp48", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_49", property="tmp49", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_50", property="tmp50", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_51", property="tmp51", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_52", property="tmp52", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_53", property="tmp53", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_54", property="tmp54", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_55", property="tmp55", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_56", property="tmp56", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_57", property="tmp57", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_58", property="tmp58", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_59", property="tmp59", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_60", property="tmp60", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_61", property="tmp61", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_62", property="tmp62", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_63", property="tmp63", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_64", property="tmp64", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_65", property="tmp65", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_66", property="tmp66", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_67", property="tmp67", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_68", property="tmp68", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_69", property="tmp69", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_70", property="tmp70", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_71", property="tmp71", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_72", property="tmp72", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_73", property="tmp73", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_74", property="tmp74", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_75", property="tmp75", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_76", property="tmp76", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_77", property="tmp77", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_78", property="tmp78", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_79", property="tmp79", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_80", property="tmp80", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_81", property="tmp81", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_82", property="tmp82", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_83", property="tmp83", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_84", property="tmp84", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_85", property="tmp85", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_86", property="tmp86", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_87", property="tmp87", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_88", property="tmp88", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_89", property="tmp89", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_90", property="tmp90", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_91", property="tmp91", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_92", property="tmp92", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_93", property="tmp93", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_94", property="tmp94", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_95", property="tmp95", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_96", property="tmp96", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_97", property="tmp97", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_98", property="tmp98", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_99", property="tmp99", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_100", property="tmp100", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_101", property="tmp101", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_102", property="tmp102", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_103", property="tmp103", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_104", property="tmp104", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_105", property="tmp105", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_106", property="tmp106", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_107", property="tmp107", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_108", property="tmp108", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_109", property="tmp109", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_110", property="tmp110", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_111", property="tmp111", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_112", property="tmp112", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_113", property="tmp113", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_114", property="tmp114", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_115", property="tmp115", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_116", property="tmp116", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_117", property="tmp117", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_118", property="tmp118", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_119", property="tmp119", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_120", property="tmp120", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_121", property="tmp121", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_122", property="tmp122", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_123", property="tmp123", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_124", property="tmp124", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_125", property="tmp125", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_126", property="tmp126", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_127", property="tmp127", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_128", property="tmp128", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_129", property="tmp129", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_130", property="tmp130", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_131", property="tmp131", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_132", property="tmp132", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_133", property="tmp133", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_134", property="tmp134", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_135", property="tmp135", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_136", property="tmp136", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_137", property="tmp137", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_138", property="tmp138", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_139", property="tmp139", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_140", property="tmp140", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_141", property="tmp141", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_142", property="tmp142", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_143", property="tmp143", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_144", property="tmp144", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_145", property="tmp145", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_146", property="tmp146", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_147", property="tmp147", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_148", property="tmp148", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_149", property="tmp149", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_150", property="tmp150", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_151", property="tmp151", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_152", property="tmp152", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_153", property="tmp153", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_154", property="tmp154", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_155", property="tmp155", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_156", property="tmp156", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_157", property="tmp157", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_158", property="tmp158", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_159", property="tmp159", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_160", property="tmp160", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_161", property="tmp161", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_162", property="tmp162", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_163", property="tmp163", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_164", property="tmp164", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_165", property="tmp165", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_166", property="tmp166", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_167", property="tmp167", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_168", property="tmp168", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_169", property="tmp169", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_170", property="tmp170", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_171", property="tmp171", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_172", property="tmp172", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_173", property="tmp173", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_174", property="tmp174", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_175", property="tmp175", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_176", property="tmp176", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_177", property="tmp177", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_178", property="tmp178", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_179", property="tmp179", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_180", property="tmp180", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_181", property="tmp181", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_182", property="tmp182", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_183", property="tmp183", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_184", property="tmp184", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_185", property="tmp185", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_186", property="tmp186", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_187", property="tmp187", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_188", property="tmp188", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_189", property="tmp189", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_190", property="tmp190", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_191", property="tmp191", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_192", property="tmp192", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_193", property="tmp193", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_194", property="tmp194", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_195", property="tmp195", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_196", property="tmp196", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_197", property="tmp197", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_198", property="tmp198", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_199", property="tmp199", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_200", property="tmp200", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_201", property="tmp201", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_202", property="tmp202", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_203", property="tmp203", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_204", property="tmp204", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_205", property="tmp205", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_206", property="tmp206", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_207", property="tmp207", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_208", property="tmp208", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_209", property="tmp209", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_210", property="tmp210", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_211", property="tmp211", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_212", property="tmp212", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_213", property="tmp213", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_214", property="tmp214", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_215", property="tmp215", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_216", property="tmp216", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_217", property="tmp217", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_218", property="tmp218", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_219", property="tmp219", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_220", property="tmp220", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_221", property="tmp221", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_222", property="tmp222", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_223", property="tmp223", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_224", property="tmp224", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_225", property="tmp225", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_226", property="tmp226", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_227", property="tmp227", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_228", property="tmp228", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_229", property="tmp229", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_230", property="tmp230", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_231", property="tmp231", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_232", property="tmp232", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_233", property="tmp233", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_234", property="tmp234", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_235", property="tmp235", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_236", property="tmp236", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_237", property="tmp237", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_238", property="tmp238", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_239", property="tmp239", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_240", property="tmp240", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_241", property="tmp241", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_242", property="tmp242", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_243", property="tmp243", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_244", property="tmp244", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_245", property="tmp245", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_246", property="tmp246", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_247", property="tmp247", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_248", property="tmp248", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_249", property="tmp249", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_250", property="tmp250", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_251", property="tmp251", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_252", property="tmp252", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_253", property="tmp253", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_254", property="tmp254", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_255", property="tmp255", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_256", property="tmp256", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_257", property="tmp257", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_258", property="tmp258", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_259", property="tmp259", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_260", property="tmp260", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_261", property="tmp261", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_262", property="tmp262", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_263", property="tmp263", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_264", property="tmp264", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_265", property="tmp265", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_266", property="tmp266", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_267", property="tmp267", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_268", property="tmp268", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_269", property="tmp269", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_270", property="tmp270", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_271", property="tmp271", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_272", property="tmp272", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_273", property="tmp273", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_274", property="tmp274", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_275", property="tmp275", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_276", property="tmp276", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_277", property="tmp277", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_278", property="tmp278", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_279", property="tmp279", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_280", property="tmp280", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_281", property="tmp281", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_282", property="tmp282", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_283", property="tmp283", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_284", property="tmp284", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_285", property="tmp285", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_286", property="tmp286", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_287", property="tmp287", jdbcType=JdbcType.DECIMAL),
        @Result(column="TMP_288", property="tmp288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_tmpCurvePo> selectByDate(String data_date);

    @Select({
            "select",
            "LD_ID, SYS_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, TMP_1, TMP_2, ",
            "TMP_3, TMP_4, TMP_5, TMP_6, TMP_7, TMP_8, TMP_9, TMP_10, TMP_11, TMP_12, TMP_13, ",
            "TMP_14, TMP_15, TMP_16, TMP_17, TMP_18, TMP_19, TMP_20, TMP_21, TMP_22, TMP_23, ",
            "TMP_24, TMP_25, TMP_26, TMP_27, TMP_28, TMP_29, TMP_30, TMP_31, TMP_32, TMP_33, ",
            "TMP_34, TMP_35, TMP_36, TMP_37, TMP_38, TMP_39, TMP_40, TMP_41, TMP_42, TMP_43, ",
            "TMP_44, TMP_45, TMP_46, TMP_47, TMP_48, TMP_49, TMP_50, TMP_51, TMP_52, TMP_53, ",
            "TMP_54, TMP_55, TMP_56, TMP_57, TMP_58, TMP_59, TMP_60, TMP_61, TMP_62, TMP_63, ",
            "TMP_64, TMP_65, TMP_66, TMP_67, TMP_68, TMP_69, TMP_70, TMP_71, TMP_72, TMP_73, ",
            "TMP_74, TMP_75, TMP_76, TMP_77, TMP_78, TMP_79, TMP_80, TMP_81, TMP_82, TMP_83, ",
            "TMP_84, TMP_85, TMP_86, TMP_87, TMP_88, TMP_89, TMP_90, TMP_91, TMP_92, TMP_93, ",
            "TMP_94, TMP_95, TMP_96, TMP_97, TMP_98, TMP_99, TMP_100, TMP_101, TMP_102, TMP_103, ",
            "TMP_104, TMP_105, TMP_106, TMP_107, TMP_108, TMP_109, TMP_110, TMP_111, TMP_112, ",
            "TMP_113, TMP_114, TMP_115, TMP_116, TMP_117, TMP_118, TMP_119, TMP_120, TMP_121, ",
            "TMP_122, TMP_123, TMP_124, TMP_125, TMP_126, TMP_127, TMP_128, TMP_129, TMP_130, ",
            "TMP_131, TMP_132, TMP_133, TMP_134, TMP_135, TMP_136, TMP_137, TMP_138, TMP_139, ",
            "TMP_140, TMP_141, TMP_142, TMP_143, TMP_144, TMP_145, TMP_146, TMP_147, TMP_148, ",
            "TMP_149, TMP_150, TMP_151, TMP_152, TMP_153, TMP_154, TMP_155, TMP_156, TMP_157, ",
            "TMP_158, TMP_159, TMP_160, TMP_161, TMP_162, TMP_163, TMP_164, TMP_165, TMP_166, ",
            "TMP_167, TMP_168, TMP_169, TMP_170, TMP_171, TMP_172, TMP_173, TMP_174, TMP_175, ",
            "TMP_176, TMP_177, TMP_178, TMP_179, TMP_180, TMP_181, TMP_182, TMP_183, TMP_184, ",
            "TMP_185, TMP_186, TMP_187, TMP_188, TMP_189, TMP_190, TMP_191, TMP_192, TMP_193, ",
            "TMP_194, TMP_195, TMP_196, TMP_197, TMP_198, TMP_199, TMP_200, TMP_201, TMP_202, ",
            "TMP_203, TMP_204, TMP_205, TMP_206, TMP_207, TMP_208, TMP_209, TMP_210, TMP_211, ",
            "TMP_212, TMP_213, TMP_214, TMP_215, TMP_216, TMP_217, TMP_218, TMP_219, TMP_220, ",
            "TMP_221, TMP_222, TMP_223, TMP_224, TMP_225, TMP_226, TMP_227, TMP_228, TMP_229, ",
            "TMP_230, TMP_231, TMP_232, TMP_233, TMP_234, TMP_235, TMP_236, TMP_237, TMP_238, ",
            "TMP_239, TMP_240, TMP_241, TMP_242, TMP_243, TMP_244, TMP_245, TMP_246, TMP_247, ",
            "TMP_248, TMP_249, TMP_250, TMP_251, TMP_252, TMP_253, TMP_254, TMP_255, TMP_256, ",
            "TMP_257, TMP_258, TMP_259, TMP_260, TMP_261, TMP_262, TMP_263, TMP_264, TMP_265, ",
            "TMP_266, TMP_267, TMP_268, TMP_269, TMP_270, TMP_271, TMP_272, TMP_273, TMP_274, ",
            "TMP_275, TMP_276, TMP_277, TMP_278, TMP_279, TMP_280, TMP_281, TMP_282, TMP_283, ",
            "TMP_284, TMP_285, TMP_286, TMP_287, TMP_288",
            "from c_stmp_tmp_c" ,
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="TMP_1", property="tmp1", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_2", property="tmp2", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_3", property="tmp3", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_4", property="tmp4", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_5", property="tmp5", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_6", property="tmp6", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_7", property="tmp7", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_8", property="tmp8", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_9", property="tmp9", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_10", property="tmp10", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_11", property="tmp11", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_12", property="tmp12", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_13", property="tmp13", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_14", property="tmp14", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_15", property="tmp15", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_16", property="tmp16", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_17", property="tmp17", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_18", property="tmp18", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_19", property="tmp19", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_20", property="tmp20", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_21", property="tmp21", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_22", property="tmp22", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_23", property="tmp23", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_24", property="tmp24", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_25", property="tmp25", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_26", property="tmp26", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_27", property="tmp27", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_28", property="tmp28", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_29", property="tmp29", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_30", property="tmp30", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_31", property="tmp31", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_32", property="tmp32", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_33", property="tmp33", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_34", property="tmp34", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_35", property="tmp35", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_36", property="tmp36", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_37", property="tmp37", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_38", property="tmp38", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_39", property="tmp39", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_40", property="tmp40", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_41", property="tmp41", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_42", property="tmp42", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_43", property="tmp43", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_44", property="tmp44", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_45", property="tmp45", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_46", property="tmp46", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_47", property="tmp47", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_48", property="tmp48", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_49", property="tmp49", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_50", property="tmp50", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_51", property="tmp51", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_52", property="tmp52", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_53", property="tmp53", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_54", property="tmp54", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_55", property="tmp55", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_56", property="tmp56", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_57", property="tmp57", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_58", property="tmp58", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_59", property="tmp59", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_60", property="tmp60", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_61", property="tmp61", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_62", property="tmp62", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_63", property="tmp63", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_64", property="tmp64", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_65", property="tmp65", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_66", property="tmp66", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_67", property="tmp67", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_68", property="tmp68", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_69", property="tmp69", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_70", property="tmp70", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_71", property="tmp71", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_72", property="tmp72", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_73", property="tmp73", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_74", property="tmp74", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_75", property="tmp75", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_76", property="tmp76", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_77", property="tmp77", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_78", property="tmp78", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_79", property="tmp79", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_80", property="tmp80", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_81", property="tmp81", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_82", property="tmp82", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_83", property="tmp83", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_84", property="tmp84", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_85", property="tmp85", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_86", property="tmp86", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_87", property="tmp87", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_88", property="tmp88", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_89", property="tmp89", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_90", property="tmp90", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_91", property="tmp91", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_92", property="tmp92", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_93", property="tmp93", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_94", property="tmp94", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_95", property="tmp95", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_96", property="tmp96", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_97", property="tmp97", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_98", property="tmp98", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_99", property="tmp99", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_100", property="tmp100", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_101", property="tmp101", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_102", property="tmp102", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_103", property="tmp103", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_104", property="tmp104", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_105", property="tmp105", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_106", property="tmp106", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_107", property="tmp107", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_108", property="tmp108", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_109", property="tmp109", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_110", property="tmp110", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_111", property="tmp111", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_112", property="tmp112", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_113", property="tmp113", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_114", property="tmp114", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_115", property="tmp115", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_116", property="tmp116", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_117", property="tmp117", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_118", property="tmp118", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_119", property="tmp119", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_120", property="tmp120", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_121", property="tmp121", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_122", property="tmp122", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_123", property="tmp123", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_124", property="tmp124", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_125", property="tmp125", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_126", property="tmp126", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_127", property="tmp127", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_128", property="tmp128", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_129", property="tmp129", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_130", property="tmp130", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_131", property="tmp131", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_132", property="tmp132", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_133", property="tmp133", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_134", property="tmp134", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_135", property="tmp135", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_136", property="tmp136", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_137", property="tmp137", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_138", property="tmp138", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_139", property="tmp139", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_140", property="tmp140", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_141", property="tmp141", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_142", property="tmp142", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_143", property="tmp143", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_144", property="tmp144", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_145", property="tmp145", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_146", property="tmp146", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_147", property="tmp147", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_148", property="tmp148", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_149", property="tmp149", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_150", property="tmp150", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_151", property="tmp151", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_152", property="tmp152", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_153", property="tmp153", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_154", property="tmp154", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_155", property="tmp155", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_156", property="tmp156", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_157", property="tmp157", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_158", property="tmp158", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_159", property="tmp159", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_160", property="tmp160", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_161", property="tmp161", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_162", property="tmp162", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_163", property="tmp163", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_164", property="tmp164", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_165", property="tmp165", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_166", property="tmp166", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_167", property="tmp167", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_168", property="tmp168", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_169", property="tmp169", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_170", property="tmp170", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_171", property="tmp171", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_172", property="tmp172", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_173", property="tmp173", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_174", property="tmp174", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_175", property="tmp175", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_176", property="tmp176", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_177", property="tmp177", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_178", property="tmp178", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_179", property="tmp179", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_180", property="tmp180", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_181", property="tmp181", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_182", property="tmp182", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_183", property="tmp183", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_184", property="tmp184", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_185", property="tmp185", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_186", property="tmp186", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_187", property="tmp187", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_188", property="tmp188", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_189", property="tmp189", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_190", property="tmp190", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_191", property="tmp191", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_192", property="tmp192", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_193", property="tmp193", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_194", property="tmp194", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_195", property="tmp195", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_196", property="tmp196", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_197", property="tmp197", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_198", property="tmp198", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_199", property="tmp199", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_200", property="tmp200", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_201", property="tmp201", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_202", property="tmp202", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_203", property="tmp203", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_204", property="tmp204", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_205", property="tmp205", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_206", property="tmp206", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_207", property="tmp207", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_208", property="tmp208", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_209", property="tmp209", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_210", property="tmp210", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_211", property="tmp211", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_212", property="tmp212", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_213", property="tmp213", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_214", property="tmp214", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_215", property="tmp215", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_216", property="tmp216", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_217", property="tmp217", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_218", property="tmp218", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_219", property="tmp219", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_220", property="tmp220", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_221", property="tmp221", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_222", property="tmp222", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_223", property="tmp223", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_224", property="tmp224", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_225", property="tmp225", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_226", property="tmp226", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_227", property="tmp227", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_228", property="tmp228", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_229", property="tmp229", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_230", property="tmp230", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_231", property="tmp231", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_232", property="tmp232", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_233", property="tmp233", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_234", property="tmp234", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_235", property="tmp235", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_236", property="tmp236", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_237", property="tmp237", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_238", property="tmp238", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_239", property="tmp239", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_240", property="tmp240", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_241", property="tmp241", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_242", property="tmp242", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_243", property="tmp243", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_244", property="tmp244", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_245", property="tmp245", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_246", property="tmp246", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_247", property="tmp247", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_248", property="tmp248", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_249", property="tmp249", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_250", property="tmp250", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_251", property="tmp251", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_252", property="tmp252", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_253", property="tmp253", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_254", property="tmp254", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_255", property="tmp255", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_256", property="tmp256", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_257", property="tmp257", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_258", property="tmp258", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_259", property="tmp259", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_260", property="tmp260", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_261", property="tmp261", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_262", property="tmp262", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_263", property="tmp263", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_264", property="tmp264", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_265", property="tmp265", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_266", property="tmp266", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_267", property="tmp267", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_268", property="tmp268", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_269", property="tmp269", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_270", property="tmp270", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_271", property="tmp271", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_272", property="tmp272", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_273", property="tmp273", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_274", property="tmp274", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_275", property="tmp275", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_276", property="tmp276", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_277", property="tmp277", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_278", property="tmp278", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_279", property="tmp279", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_280", property="tmp280", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_281", property="tmp281", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_282", property="tmp282", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_283", property="tmp283", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_284", property="tmp284", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_285", property="tmp285", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_286", property="tmp286", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_287", property="tmp287", jdbcType=JdbcType.DECIMAL),
            @Result(column="TMP_288", property="tmp288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_tmpCurvePo> selectBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

}