package com.dao.mapper;

import com.dao.bean.D_volRatioCurvePo;
import com.dao.bean.D_volRatioCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_volRatioCurvePoMapper {

    @Select({
        "select",
        "LD_ID, SYS_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_VOLRATIO_1, ",
        "HAR_VOLRATIO_2, HAR_VOLRATIO_3, HAR_VOLRATIO_4, HAR_VOLRATIO_5, HAR_VOLRATIO_6, ",
        "HAR_VOLRATIO_7, HAR_VOLRATIO_8, HAR_VOLRATIO_9, HAR_VOLRATIO_10, HAR_VOLRATIO_11, ",
        "HAR_VOLRATIO_12, HAR_VOLRATIO_13, HAR_VOLRATIO_14, HAR_VOLRATIO_15, HAR_VOLRATIO_16, ",
        "HAR_VOLRATIO_17, HAR_VOLRATIO_18, HAR_VOLRATIO_19, HAR_VOLRATIO_20, HAR_VOLRATIO_21, ",
        "HAR_VOLRATIO_22, HAR_VOLRATIO_23, HAR_VOLRATIO_24, HAR_VOLRATIO_25, HAR_VOLRATIO_26, ",
        "HAR_VOLRATIO_27, HAR_VOLRATIO_28, HAR_VOLRATIO_29, HAR_VOLRATIO_30, HAR_VOLRATIO_31, ",
        "HAR_VOLRATIO_32, HAR_VOLRATIO_33, HAR_VOLRATIO_34, HAR_VOLRATIO_35, HAR_VOLRATIO_36, ",
        "HAR_VOLRATIO_37, HAR_VOLRATIO_38, HAR_VOLRATIO_39, HAR_VOLRATIO_40, HAR_VOLRATIO_41, ",
        "HAR_VOLRATIO_42, HAR_VOLRATIO_43, HAR_VOLRATIO_44, HAR_VOLRATIO_45, HAR_VOLRATIO_46, ",
        "HAR_VOLRATIO_47, HAR_VOLRATIO_48, HAR_VOLRATIO_49, HAR_VOLRATIO_50, HAR_VOLRATIO_51, ",
        "HAR_VOLRATIO_52, HAR_VOLRATIO_53, HAR_VOLRATIO_54, HAR_VOLRATIO_55, HAR_VOLRATIO_56, ",
        "HAR_VOLRATIO_57, HAR_VOLRATIO_58, HAR_VOLRATIO_59, HAR_VOLRATIO_60, HAR_VOLRATIO_61, ",
        "HAR_VOLRATIO_62, HAR_VOLRATIO_63, HAR_VOLRATIO_64, HAR_VOLRATIO_65, HAR_VOLRATIO_66, ",
        "HAR_VOLRATIO_67, HAR_VOLRATIO_68, HAR_VOLRATIO_69, HAR_VOLRATIO_70, HAR_VOLRATIO_71, ",
        "HAR_VOLRATIO_72, HAR_VOLRATIO_73, HAR_VOLRATIO_74, HAR_VOLRATIO_75, HAR_VOLRATIO_76, ",
        "HAR_VOLRATIO_77, HAR_VOLRATIO_78, HAR_VOLRATIO_79, HAR_VOLRATIO_80, HAR_VOLRATIO_81, ",
        "HAR_VOLRATIO_82, HAR_VOLRATIO_83, HAR_VOLRATIO_84, HAR_VOLRATIO_85, HAR_VOLRATIO_86, ",
        "HAR_VOLRATIO_87, HAR_VOLRATIO_88, HAR_VOLRATIO_89, HAR_VOLRATIO_90, HAR_VOLRATIO_91, ",
        "HAR_VOLRATIO_92, HAR_VOLRATIO_93, HAR_VOLRATIO_94, HAR_VOLRATIO_95, HAR_VOLRATIO_96, ",
        "HAR_VOLRATIO_97, HAR_VOLRATIO_98, HAR_VOLRATIO_99, HAR_VOLRATIO_100, HAR_VOLRATIO_101, ",
        "HAR_VOLRATIO_102, HAR_VOLRATIO_103, HAR_VOLRATIO_104, HAR_VOLRATIO_105, HAR_VOLRATIO_106, ",
        "HAR_VOLRATIO_107, HAR_VOLRATIO_108, HAR_VOLRATIO_109, HAR_VOLRATIO_110, HAR_VOLRATIO_111, ",
        "HAR_VOLRATIO_112, HAR_VOLRATIO_113, HAR_VOLRATIO_114, HAR_VOLRATIO_115, HAR_VOLRATIO_116, ",
        "HAR_VOLRATIO_117, HAR_VOLRATIO_118, HAR_VOLRATIO_119, HAR_VOLRATIO_120, HAR_VOLRATIO_121, ",
        "HAR_VOLRATIO_122, HAR_VOLRATIO_123, HAR_VOLRATIO_124, HAR_VOLRATIO_125, HAR_VOLRATIO_126, ",
        "HAR_VOLRATIO_127, HAR_VOLRATIO_128, HAR_VOLRATIO_129, HAR_VOLRATIO_130, HAR_VOLRATIO_131, ",
        "HAR_VOLRATIO_132, HAR_VOLRATIO_133, HAR_VOLRATIO_134, HAR_VOLRATIO_135, HAR_VOLRATIO_136, ",
        "HAR_VOLRATIO_137, HAR_VOLRATIO_138, HAR_VOLRATIO_139, HAR_VOLRATIO_140, HAR_VOLRATIO_141, ",
        "HAR_VOLRATIO_142, HAR_VOLRATIO_143, HAR_VOLRATIO_144, HAR_VOLRATIO_145, HAR_VOLRATIO_146, ",
        "HAR_VOLRATIO_147, HAR_VOLRATIO_148, HAR_VOLRATIO_149, HAR_VOLRATIO_150, HAR_VOLRATIO_151, ",
        "HAR_VOLRATIO_152, HAR_VOLRATIO_153, HAR_VOLRATIO_154, HAR_VOLRATIO_155, HAR_VOLRATIO_156, ",
        "HAR_VOLRATIO_157, HAR_VOLRATIO_158, HAR_VOLRATIO_159, HAR_VOLRATIO_160, HAR_VOLRATIO_161, ",
        "HAR_VOLRATIO_162, HAR_VOLRATIO_163, HAR_VOLRATIO_164, HAR_VOLRATIO_165, HAR_VOLRATIO_166, ",
        "HAR_VOLRATIO_167, HAR_VOLRATIO_168, HAR_VOLRATIO_169, HAR_VOLRATIO_170, HAR_VOLRATIO_171, ",
        "HAR_VOLRATIO_172, HAR_VOLRATIO_173, HAR_VOLRATIO_174, HAR_VOLRATIO_175, HAR_VOLRATIO_176, ",
        "HAR_VOLRATIO_177, HAR_VOLRATIO_178, HAR_VOLRATIO_179, HAR_VOLRATIO_180, HAR_VOLRATIO_181, ",
        "HAR_VOLRATIO_182, HAR_VOLRATIO_183, HAR_VOLRATIO_184, HAR_VOLRATIO_185, HAR_VOLRATIO_186, ",
        "HAR_VOLRATIO_187, HAR_VOLRATIO_188, HAR_VOLRATIO_189, HAR_VOLRATIO_190, HAR_VOLRATIO_191, ",
        "HAR_VOLRATIO_192, HAR_VOLRATIO_193, HAR_VOLRATIO_194, HAR_VOLRATIO_195, HAR_VOLRATIO_196, ",
        "HAR_VOLRATIO_197, HAR_VOLRATIO_198, HAR_VOLRATIO_199, HAR_VOLRATIO_200, HAR_VOLRATIO_201, ",
        "HAR_VOLRATIO_202, HAR_VOLRATIO_203, HAR_VOLRATIO_204, HAR_VOLRATIO_205, HAR_VOLRATIO_206, ",
        "HAR_VOLRATIO_207, HAR_VOLRATIO_208, HAR_VOLRATIO_209, HAR_VOLRATIO_210, HAR_VOLRATIO_211, ",
        "HAR_VOLRATIO_212, HAR_VOLRATIO_213, HAR_VOLRATIO_214, HAR_VOLRATIO_215, HAR_VOLRATIO_216, ",
        "HAR_VOLRATIO_217, HAR_VOLRATIO_218, HAR_VOLRATIO_219, HAR_VOLRATIO_220, HAR_VOLRATIO_221, ",
        "HAR_VOLRATIO_222, HAR_VOLRATIO_223, HAR_VOLRATIO_224, HAR_VOLRATIO_225, HAR_VOLRATIO_226, ",
        "HAR_VOLRATIO_227, HAR_VOLRATIO_228, HAR_VOLRATIO_229, HAR_VOLRATIO_230, HAR_VOLRATIO_231, ",
        "HAR_VOLRATIO_232, HAR_VOLRATIO_233, HAR_VOLRATIO_234, HAR_VOLRATIO_235, HAR_VOLRATIO_236, ",
        "HAR_VOLRATIO_237, HAR_VOLRATIO_238, HAR_VOLRATIO_239, HAR_VOLRATIO_240, HAR_VOLRATIO_241, ",
        "HAR_VOLRATIO_242, HAR_VOLRATIO_243, HAR_VOLRATIO_244, HAR_VOLRATIO_245, HAR_VOLRATIO_246, ",
        "HAR_VOLRATIO_247, HAR_VOLRATIO_248, HAR_VOLRATIO_249, HAR_VOLRATIO_250, HAR_VOLRATIO_251, ",
        "HAR_VOLRATIO_252, HAR_VOLRATIO_253, HAR_VOLRATIO_254, HAR_VOLRATIO_255, HAR_VOLRATIO_256, ",
        "HAR_VOLRATIO_257, HAR_VOLRATIO_258, HAR_VOLRATIO_259, HAR_VOLRATIO_260, HAR_VOLRATIO_261, ",
        "HAR_VOLRATIO_262, HAR_VOLRATIO_263, HAR_VOLRATIO_264, HAR_VOLRATIO_265, HAR_VOLRATIO_266, ",
        "HAR_VOLRATIO_267, HAR_VOLRATIO_268, HAR_VOLRATIO_269, HAR_VOLRATIO_270, HAR_VOLRATIO_271, ",
        "HAR_VOLRATIO_272, HAR_VOLRATIO_273, HAR_VOLRATIO_274, HAR_VOLRATIO_275, HAR_VOLRATIO_276, ",
        "HAR_VOLRATIO_277, HAR_VOLRATIO_278, HAR_VOLRATIO_279, HAR_VOLRATIO_280, HAR_VOLRATIO_281, ",
        "HAR_VOLRATIO_282, HAR_VOLRATIO_283, HAR_VOLRATIO_284, HAR_VOLRATIO_285, HAR_VOLRATIO_286, ",
        "HAR_VOLRATIO_287, HAR_VOLRATIO_288",
        "from c_mhai_volratio_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="HAR_VOLRATIO_1", property="harVolratio1", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_2", property="harVolratio2", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_3", property="harVolratio3", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_4", property="harVolratio4", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_5", property="harVolratio5", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_6", property="harVolratio6", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_7", property="harVolratio7", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_8", property="harVolratio8", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_9", property="harVolratio9", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_10", property="harVolratio10", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_11", property="harVolratio11", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_12", property="harVolratio12", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_13", property="harVolratio13", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_14", property="harVolratio14", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_15", property="harVolratio15", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_16", property="harVolratio16", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_17", property="harVolratio17", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_18", property="harVolratio18", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_19", property="harVolratio19", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_20", property="harVolratio20", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_21", property="harVolratio21", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_22", property="harVolratio22", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_23", property="harVolratio23", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_24", property="harVolratio24", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_25", property="harVolratio25", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_26", property="harVolratio26", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_27", property="harVolratio27", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_28", property="harVolratio28", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_29", property="harVolratio29", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_30", property="harVolratio30", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_31", property="harVolratio31", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_32", property="harVolratio32", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_33", property="harVolratio33", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_34", property="harVolratio34", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_35", property="harVolratio35", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_36", property="harVolratio36", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_37", property="harVolratio37", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_38", property="harVolratio38", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_39", property="harVolratio39", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_40", property="harVolratio40", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_41", property="harVolratio41", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_42", property="harVolratio42", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_43", property="harVolratio43", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_44", property="harVolratio44", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_45", property="harVolratio45", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_46", property="harVolratio46", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_47", property="harVolratio47", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_48", property="harVolratio48", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_49", property="harVolratio49", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_50", property="harVolratio50", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_51", property="harVolratio51", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_52", property="harVolratio52", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_53", property="harVolratio53", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_54", property="harVolratio54", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_55", property="harVolratio55", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_56", property="harVolratio56", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_57", property="harVolratio57", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_58", property="harVolratio58", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_59", property="harVolratio59", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_60", property="harVolratio60", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_61", property="harVolratio61", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_62", property="harVolratio62", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_63", property="harVolratio63", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_64", property="harVolratio64", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_65", property="harVolratio65", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_66", property="harVolratio66", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_67", property="harVolratio67", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_68", property="harVolratio68", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_69", property="harVolratio69", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_70", property="harVolratio70", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_71", property="harVolratio71", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_72", property="harVolratio72", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_73", property="harVolratio73", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_74", property="harVolratio74", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_75", property="harVolratio75", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_76", property="harVolratio76", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_77", property="harVolratio77", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_78", property="harVolratio78", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_79", property="harVolratio79", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_80", property="harVolratio80", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_81", property="harVolratio81", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_82", property="harVolratio82", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_83", property="harVolratio83", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_84", property="harVolratio84", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_85", property="harVolratio85", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_86", property="harVolratio86", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_87", property="harVolratio87", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_88", property="harVolratio88", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_89", property="harVolratio89", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_90", property="harVolratio90", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_91", property="harVolratio91", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_92", property="harVolratio92", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_93", property="harVolratio93", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_94", property="harVolratio94", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_95", property="harVolratio95", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_96", property="harVolratio96", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_97", property="harVolratio97", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_98", property="harVolratio98", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_99", property="harVolratio99", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_100", property="harVolratio100", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_101", property="harVolratio101", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_102", property="harVolratio102", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_103", property="harVolratio103", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_104", property="harVolratio104", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_105", property="harVolratio105", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_106", property="harVolratio106", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_107", property="harVolratio107", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_108", property="harVolratio108", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_109", property="harVolratio109", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_110", property="harVolratio110", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_111", property="harVolratio111", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_112", property="harVolratio112", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_113", property="harVolratio113", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_114", property="harVolratio114", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_115", property="harVolratio115", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_116", property="harVolratio116", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_117", property="harVolratio117", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_118", property="harVolratio118", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_119", property="harVolratio119", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_120", property="harVolratio120", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_121", property="harVolratio121", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_122", property="harVolratio122", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_123", property="harVolratio123", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_124", property="harVolratio124", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_125", property="harVolratio125", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_126", property="harVolratio126", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_127", property="harVolratio127", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_128", property="harVolratio128", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_129", property="harVolratio129", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_130", property="harVolratio130", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_131", property="harVolratio131", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_132", property="harVolratio132", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_133", property="harVolratio133", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_134", property="harVolratio134", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_135", property="harVolratio135", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_136", property="harVolratio136", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_137", property="harVolratio137", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_138", property="harVolratio138", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_139", property="harVolratio139", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_140", property="harVolratio140", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_141", property="harVolratio141", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_142", property="harVolratio142", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_143", property="harVolratio143", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_144", property="harVolratio144", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_145", property="harVolratio145", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_146", property="harVolratio146", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_147", property="harVolratio147", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_148", property="harVolratio148", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_149", property="harVolratio149", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_150", property="harVolratio150", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_151", property="harVolratio151", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_152", property="harVolratio152", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_153", property="harVolratio153", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_154", property="harVolratio154", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_155", property="harVolratio155", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_156", property="harVolratio156", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_157", property="harVolratio157", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_158", property="harVolratio158", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_159", property="harVolratio159", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_160", property="harVolratio160", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_161", property="harVolratio161", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_162", property="harVolratio162", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_163", property="harVolratio163", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_164", property="harVolratio164", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_165", property="harVolratio165", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_166", property="harVolratio166", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_167", property="harVolratio167", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_168", property="harVolratio168", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_169", property="harVolratio169", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_170", property="harVolratio170", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_171", property="harVolratio171", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_172", property="harVolratio172", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_173", property="harVolratio173", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_174", property="harVolratio174", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_175", property="harVolratio175", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_176", property="harVolratio176", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_177", property="harVolratio177", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_178", property="harVolratio178", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_179", property="harVolratio179", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_180", property="harVolratio180", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_181", property="harVolratio181", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_182", property="harVolratio182", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_183", property="harVolratio183", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_184", property="harVolratio184", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_185", property="harVolratio185", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_186", property="harVolratio186", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_187", property="harVolratio187", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_188", property="harVolratio188", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_189", property="harVolratio189", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_190", property="harVolratio190", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_191", property="harVolratio191", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_192", property="harVolratio192", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_193", property="harVolratio193", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_194", property="harVolratio194", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_195", property="harVolratio195", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_196", property="harVolratio196", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_197", property="harVolratio197", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_198", property="harVolratio198", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_199", property="harVolratio199", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_200", property="harVolratio200", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_201", property="harVolratio201", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_202", property="harVolratio202", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_203", property="harVolratio203", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_204", property="harVolratio204", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_205", property="harVolratio205", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_206", property="harVolratio206", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_207", property="harVolratio207", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_208", property="harVolratio208", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_209", property="harVolratio209", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_210", property="harVolratio210", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_211", property="harVolratio211", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_212", property="harVolratio212", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_213", property="harVolratio213", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_214", property="harVolratio214", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_215", property="harVolratio215", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_216", property="harVolratio216", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_217", property="harVolratio217", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_218", property="harVolratio218", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_219", property="harVolratio219", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_220", property="harVolratio220", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_221", property="harVolratio221", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_222", property="harVolratio222", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_223", property="harVolratio223", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_224", property="harVolratio224", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_225", property="harVolratio225", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_226", property="harVolratio226", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_227", property="harVolratio227", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_228", property="harVolratio228", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_229", property="harVolratio229", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_230", property="harVolratio230", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_231", property="harVolratio231", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_232", property="harVolratio232", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_233", property="harVolratio233", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_234", property="harVolratio234", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_235", property="harVolratio235", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_236", property="harVolratio236", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_237", property="harVolratio237", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_238", property="harVolratio238", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_239", property="harVolratio239", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_240", property="harVolratio240", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_241", property="harVolratio241", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_242", property="harVolratio242", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_243", property="harVolratio243", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_244", property="harVolratio244", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_245", property="harVolratio245", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_246", property="harVolratio246", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_247", property="harVolratio247", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_248", property="harVolratio248", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_249", property="harVolratio249", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_250", property="harVolratio250", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_251", property="harVolratio251", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_252", property="harVolratio252", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_253", property="harVolratio253", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_254", property="harVolratio254", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_255", property="harVolratio255", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_256", property="harVolratio256", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_257", property="harVolratio257", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_258", property="harVolratio258", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_259", property="harVolratio259", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_260", property="harVolratio260", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_261", property="harVolratio261", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_262", property="harVolratio262", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_263", property="harVolratio263", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_264", property="harVolratio264", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_265", property="harVolratio265", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_266", property="harVolratio266", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_267", property="harVolratio267", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_268", property="harVolratio268", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_269", property="harVolratio269", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_270", property="harVolratio270", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_271", property="harVolratio271", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_272", property="harVolratio272", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_273", property="harVolratio273", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_274", property="harVolratio274", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_275", property="harVolratio275", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_276", property="harVolratio276", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_277", property="harVolratio277", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_278", property="harVolratio278", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_279", property="harVolratio279", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_280", property="harVolratio280", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_281", property="harVolratio281", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_282", property="harVolratio282", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_283", property="harVolratio283", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_284", property="harVolratio284", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_285", property="harVolratio285", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_286", property="harVolratio286", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_287", property="harVolratio287", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAR_VOLRATIO_288", property="harVolratio288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_volRatioCurvePo> selectVolRatioCurveByDate(String data_date);

    @Select({
            "select",
            "LD_ID, SYS_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, HAR_VOLRATIO_1, ",
            "HAR_VOLRATIO_2, HAR_VOLRATIO_3, HAR_VOLRATIO_4, HAR_VOLRATIO_5, HAR_VOLRATIO_6, ",
            "HAR_VOLRATIO_7, HAR_VOLRATIO_8, HAR_VOLRATIO_9, HAR_VOLRATIO_10, HAR_VOLRATIO_11, ",
            "HAR_VOLRATIO_12, HAR_VOLRATIO_13, HAR_VOLRATIO_14, HAR_VOLRATIO_15, HAR_VOLRATIO_16, ",
            "HAR_VOLRATIO_17, HAR_VOLRATIO_18, HAR_VOLRATIO_19, HAR_VOLRATIO_20, HAR_VOLRATIO_21, ",
            "HAR_VOLRATIO_22, HAR_VOLRATIO_23, HAR_VOLRATIO_24, HAR_VOLRATIO_25, HAR_VOLRATIO_26, ",
            "HAR_VOLRATIO_27, HAR_VOLRATIO_28, HAR_VOLRATIO_29, HAR_VOLRATIO_30, HAR_VOLRATIO_31, ",
            "HAR_VOLRATIO_32, HAR_VOLRATIO_33, HAR_VOLRATIO_34, HAR_VOLRATIO_35, HAR_VOLRATIO_36, ",
            "HAR_VOLRATIO_37, HAR_VOLRATIO_38, HAR_VOLRATIO_39, HAR_VOLRATIO_40, HAR_VOLRATIO_41, ",
            "HAR_VOLRATIO_42, HAR_VOLRATIO_43, HAR_VOLRATIO_44, HAR_VOLRATIO_45, HAR_VOLRATIO_46, ",
            "HAR_VOLRATIO_47, HAR_VOLRATIO_48, HAR_VOLRATIO_49, HAR_VOLRATIO_50, HAR_VOLRATIO_51, ",
            "HAR_VOLRATIO_52, HAR_VOLRATIO_53, HAR_VOLRATIO_54, HAR_VOLRATIO_55, HAR_VOLRATIO_56, ",
            "HAR_VOLRATIO_57, HAR_VOLRATIO_58, HAR_VOLRATIO_59, HAR_VOLRATIO_60, HAR_VOLRATIO_61, ",
            "HAR_VOLRATIO_62, HAR_VOLRATIO_63, HAR_VOLRATIO_64, HAR_VOLRATIO_65, HAR_VOLRATIO_66, ",
            "HAR_VOLRATIO_67, HAR_VOLRATIO_68, HAR_VOLRATIO_69, HAR_VOLRATIO_70, HAR_VOLRATIO_71, ",
            "HAR_VOLRATIO_72, HAR_VOLRATIO_73, HAR_VOLRATIO_74, HAR_VOLRATIO_75, HAR_VOLRATIO_76, ",
            "HAR_VOLRATIO_77, HAR_VOLRATIO_78, HAR_VOLRATIO_79, HAR_VOLRATIO_80, HAR_VOLRATIO_81, ",
            "HAR_VOLRATIO_82, HAR_VOLRATIO_83, HAR_VOLRATIO_84, HAR_VOLRATIO_85, HAR_VOLRATIO_86, ",
            "HAR_VOLRATIO_87, HAR_VOLRATIO_88, HAR_VOLRATIO_89, HAR_VOLRATIO_90, HAR_VOLRATIO_91, ",
            "HAR_VOLRATIO_92, HAR_VOLRATIO_93, HAR_VOLRATIO_94, HAR_VOLRATIO_95, HAR_VOLRATIO_96, ",
            "HAR_VOLRATIO_97, HAR_VOLRATIO_98, HAR_VOLRATIO_99, HAR_VOLRATIO_100, HAR_VOLRATIO_101, ",
            "HAR_VOLRATIO_102, HAR_VOLRATIO_103, HAR_VOLRATIO_104, HAR_VOLRATIO_105, HAR_VOLRATIO_106, ",
            "HAR_VOLRATIO_107, HAR_VOLRATIO_108, HAR_VOLRATIO_109, HAR_VOLRATIO_110, HAR_VOLRATIO_111, ",
            "HAR_VOLRATIO_112, HAR_VOLRATIO_113, HAR_VOLRATIO_114, HAR_VOLRATIO_115, HAR_VOLRATIO_116, ",
            "HAR_VOLRATIO_117, HAR_VOLRATIO_118, HAR_VOLRATIO_119, HAR_VOLRATIO_120, HAR_VOLRATIO_121, ",
            "HAR_VOLRATIO_122, HAR_VOLRATIO_123, HAR_VOLRATIO_124, HAR_VOLRATIO_125, HAR_VOLRATIO_126, ",
            "HAR_VOLRATIO_127, HAR_VOLRATIO_128, HAR_VOLRATIO_129, HAR_VOLRATIO_130, HAR_VOLRATIO_131, ",
            "HAR_VOLRATIO_132, HAR_VOLRATIO_133, HAR_VOLRATIO_134, HAR_VOLRATIO_135, HAR_VOLRATIO_136, ",
            "HAR_VOLRATIO_137, HAR_VOLRATIO_138, HAR_VOLRATIO_139, HAR_VOLRATIO_140, HAR_VOLRATIO_141, ",
            "HAR_VOLRATIO_142, HAR_VOLRATIO_143, HAR_VOLRATIO_144, HAR_VOLRATIO_145, HAR_VOLRATIO_146, ",
            "HAR_VOLRATIO_147, HAR_VOLRATIO_148, HAR_VOLRATIO_149, HAR_VOLRATIO_150, HAR_VOLRATIO_151, ",
            "HAR_VOLRATIO_152, HAR_VOLRATIO_153, HAR_VOLRATIO_154, HAR_VOLRATIO_155, HAR_VOLRATIO_156, ",
            "HAR_VOLRATIO_157, HAR_VOLRATIO_158, HAR_VOLRATIO_159, HAR_VOLRATIO_160, HAR_VOLRATIO_161, ",
            "HAR_VOLRATIO_162, HAR_VOLRATIO_163, HAR_VOLRATIO_164, HAR_VOLRATIO_165, HAR_VOLRATIO_166, ",
            "HAR_VOLRATIO_167, HAR_VOLRATIO_168, HAR_VOLRATIO_169, HAR_VOLRATIO_170, HAR_VOLRATIO_171, ",
            "HAR_VOLRATIO_172, HAR_VOLRATIO_173, HAR_VOLRATIO_174, HAR_VOLRATIO_175, HAR_VOLRATIO_176, ",
            "HAR_VOLRATIO_177, HAR_VOLRATIO_178, HAR_VOLRATIO_179, HAR_VOLRATIO_180, HAR_VOLRATIO_181, ",
            "HAR_VOLRATIO_182, HAR_VOLRATIO_183, HAR_VOLRATIO_184, HAR_VOLRATIO_185, HAR_VOLRATIO_186, ",
            "HAR_VOLRATIO_187, HAR_VOLRATIO_188, HAR_VOLRATIO_189, HAR_VOLRATIO_190, HAR_VOLRATIO_191, ",
            "HAR_VOLRATIO_192, HAR_VOLRATIO_193, HAR_VOLRATIO_194, HAR_VOLRATIO_195, HAR_VOLRATIO_196, ",
            "HAR_VOLRATIO_197, HAR_VOLRATIO_198, HAR_VOLRATIO_199, HAR_VOLRATIO_200, HAR_VOLRATIO_201, ",
            "HAR_VOLRATIO_202, HAR_VOLRATIO_203, HAR_VOLRATIO_204, HAR_VOLRATIO_205, HAR_VOLRATIO_206, ",
            "HAR_VOLRATIO_207, HAR_VOLRATIO_208, HAR_VOLRATIO_209, HAR_VOLRATIO_210, HAR_VOLRATIO_211, ",
            "HAR_VOLRATIO_212, HAR_VOLRATIO_213, HAR_VOLRATIO_214, HAR_VOLRATIO_215, HAR_VOLRATIO_216, ",
            "HAR_VOLRATIO_217, HAR_VOLRATIO_218, HAR_VOLRATIO_219, HAR_VOLRATIO_220, HAR_VOLRATIO_221, ",
            "HAR_VOLRATIO_222, HAR_VOLRATIO_223, HAR_VOLRATIO_224, HAR_VOLRATIO_225, HAR_VOLRATIO_226, ",
            "HAR_VOLRATIO_227, HAR_VOLRATIO_228, HAR_VOLRATIO_229, HAR_VOLRATIO_230, HAR_VOLRATIO_231, ",
            "HAR_VOLRATIO_232, HAR_VOLRATIO_233, HAR_VOLRATIO_234, HAR_VOLRATIO_235, HAR_VOLRATIO_236, ",
            "HAR_VOLRATIO_237, HAR_VOLRATIO_238, HAR_VOLRATIO_239, HAR_VOLRATIO_240, HAR_VOLRATIO_241, ",
            "HAR_VOLRATIO_242, HAR_VOLRATIO_243, HAR_VOLRATIO_244, HAR_VOLRATIO_245, HAR_VOLRATIO_246, ",
            "HAR_VOLRATIO_247, HAR_VOLRATIO_248, HAR_VOLRATIO_249, HAR_VOLRATIO_250, HAR_VOLRATIO_251, ",
            "HAR_VOLRATIO_252, HAR_VOLRATIO_253, HAR_VOLRATIO_254, HAR_VOLRATIO_255, HAR_VOLRATIO_256, ",
            "HAR_VOLRATIO_257, HAR_VOLRATIO_258, HAR_VOLRATIO_259, HAR_VOLRATIO_260, HAR_VOLRATIO_261, ",
            "HAR_VOLRATIO_262, HAR_VOLRATIO_263, HAR_VOLRATIO_264, HAR_VOLRATIO_265, HAR_VOLRATIO_266, ",
            "HAR_VOLRATIO_267, HAR_VOLRATIO_268, HAR_VOLRATIO_269, HAR_VOLRATIO_270, HAR_VOLRATIO_271, ",
            "HAR_VOLRATIO_272, HAR_VOLRATIO_273, HAR_VOLRATIO_274, HAR_VOLRATIO_275, HAR_VOLRATIO_276, ",
            "HAR_VOLRATIO_277, HAR_VOLRATIO_278, HAR_VOLRATIO_279, HAR_VOLRATIO_280, HAR_VOLRATIO_281, ",
            "HAR_VOLRATIO_282, HAR_VOLRATIO_283, HAR_VOLRATIO_284, HAR_VOLRATIO_285, HAR_VOLRATIO_286, ",
            "HAR_VOLRATIO_287, HAR_VOLRATIO_288",
            "from c_mhai_volratio_c",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="HAR_VOLRATIO_1", property="harVolratio1", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_2", property="harVolratio2", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_3", property="harVolratio3", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_4", property="harVolratio4", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_5", property="harVolratio5", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_6", property="harVolratio6", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_7", property="harVolratio7", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_8", property="harVolratio8", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_9", property="harVolratio9", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_10", property="harVolratio10", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_11", property="harVolratio11", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_12", property="harVolratio12", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_13", property="harVolratio13", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_14", property="harVolratio14", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_15", property="harVolratio15", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_16", property="harVolratio16", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_17", property="harVolratio17", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_18", property="harVolratio18", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_19", property="harVolratio19", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_20", property="harVolratio20", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_21", property="harVolratio21", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_22", property="harVolratio22", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_23", property="harVolratio23", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_24", property="harVolratio24", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_25", property="harVolratio25", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_26", property="harVolratio26", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_27", property="harVolratio27", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_28", property="harVolratio28", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_29", property="harVolratio29", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_30", property="harVolratio30", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_31", property="harVolratio31", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_32", property="harVolratio32", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_33", property="harVolratio33", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_34", property="harVolratio34", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_35", property="harVolratio35", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_36", property="harVolratio36", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_37", property="harVolratio37", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_38", property="harVolratio38", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_39", property="harVolratio39", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_40", property="harVolratio40", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_41", property="harVolratio41", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_42", property="harVolratio42", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_43", property="harVolratio43", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_44", property="harVolratio44", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_45", property="harVolratio45", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_46", property="harVolratio46", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_47", property="harVolratio47", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_48", property="harVolratio48", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_49", property="harVolratio49", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_50", property="harVolratio50", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_51", property="harVolratio51", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_52", property="harVolratio52", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_53", property="harVolratio53", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_54", property="harVolratio54", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_55", property="harVolratio55", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_56", property="harVolratio56", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_57", property="harVolratio57", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_58", property="harVolratio58", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_59", property="harVolratio59", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_60", property="harVolratio60", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_61", property="harVolratio61", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_62", property="harVolratio62", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_63", property="harVolratio63", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_64", property="harVolratio64", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_65", property="harVolratio65", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_66", property="harVolratio66", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_67", property="harVolratio67", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_68", property="harVolratio68", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_69", property="harVolratio69", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_70", property="harVolratio70", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_71", property="harVolratio71", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_72", property="harVolratio72", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_73", property="harVolratio73", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_74", property="harVolratio74", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_75", property="harVolratio75", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_76", property="harVolratio76", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_77", property="harVolratio77", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_78", property="harVolratio78", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_79", property="harVolratio79", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_80", property="harVolratio80", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_81", property="harVolratio81", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_82", property="harVolratio82", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_83", property="harVolratio83", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_84", property="harVolratio84", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_85", property="harVolratio85", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_86", property="harVolratio86", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_87", property="harVolratio87", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_88", property="harVolratio88", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_89", property="harVolratio89", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_90", property="harVolratio90", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_91", property="harVolratio91", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_92", property="harVolratio92", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_93", property="harVolratio93", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_94", property="harVolratio94", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_95", property="harVolratio95", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_96", property="harVolratio96", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_97", property="harVolratio97", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_98", property="harVolratio98", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_99", property="harVolratio99", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_100", property="harVolratio100", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_101", property="harVolratio101", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_102", property="harVolratio102", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_103", property="harVolratio103", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_104", property="harVolratio104", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_105", property="harVolratio105", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_106", property="harVolratio106", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_107", property="harVolratio107", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_108", property="harVolratio108", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_109", property="harVolratio109", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_110", property="harVolratio110", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_111", property="harVolratio111", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_112", property="harVolratio112", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_113", property="harVolratio113", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_114", property="harVolratio114", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_115", property="harVolratio115", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_116", property="harVolratio116", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_117", property="harVolratio117", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_118", property="harVolratio118", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_119", property="harVolratio119", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_120", property="harVolratio120", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_121", property="harVolratio121", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_122", property="harVolratio122", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_123", property="harVolratio123", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_124", property="harVolratio124", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_125", property="harVolratio125", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_126", property="harVolratio126", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_127", property="harVolratio127", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_128", property="harVolratio128", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_129", property="harVolratio129", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_130", property="harVolratio130", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_131", property="harVolratio131", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_132", property="harVolratio132", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_133", property="harVolratio133", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_134", property="harVolratio134", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_135", property="harVolratio135", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_136", property="harVolratio136", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_137", property="harVolratio137", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_138", property="harVolratio138", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_139", property="harVolratio139", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_140", property="harVolratio140", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_141", property="harVolratio141", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_142", property="harVolratio142", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_143", property="harVolratio143", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_144", property="harVolratio144", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_145", property="harVolratio145", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_146", property="harVolratio146", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_147", property="harVolratio147", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_148", property="harVolratio148", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_149", property="harVolratio149", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_150", property="harVolratio150", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_151", property="harVolratio151", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_152", property="harVolratio152", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_153", property="harVolratio153", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_154", property="harVolratio154", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_155", property="harVolratio155", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_156", property="harVolratio156", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_157", property="harVolratio157", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_158", property="harVolratio158", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_159", property="harVolratio159", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_160", property="harVolratio160", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_161", property="harVolratio161", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_162", property="harVolratio162", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_163", property="harVolratio163", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_164", property="harVolratio164", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_165", property="harVolratio165", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_166", property="harVolratio166", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_167", property="harVolratio167", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_168", property="harVolratio168", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_169", property="harVolratio169", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_170", property="harVolratio170", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_171", property="harVolratio171", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_172", property="harVolratio172", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_173", property="harVolratio173", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_174", property="harVolratio174", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_175", property="harVolratio175", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_176", property="harVolratio176", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_177", property="harVolratio177", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_178", property="harVolratio178", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_179", property="harVolratio179", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_180", property="harVolratio180", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_181", property="harVolratio181", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_182", property="harVolratio182", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_183", property="harVolratio183", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_184", property="harVolratio184", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_185", property="harVolratio185", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_186", property="harVolratio186", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_187", property="harVolratio187", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_188", property="harVolratio188", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_189", property="harVolratio189", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_190", property="harVolratio190", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_191", property="harVolratio191", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_192", property="harVolratio192", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_193", property="harVolratio193", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_194", property="harVolratio194", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_195", property="harVolratio195", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_196", property="harVolratio196", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_197", property="harVolratio197", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_198", property="harVolratio198", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_199", property="harVolratio199", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_200", property="harVolratio200", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_201", property="harVolratio201", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_202", property="harVolratio202", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_203", property="harVolratio203", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_204", property="harVolratio204", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_205", property="harVolratio205", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_206", property="harVolratio206", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_207", property="harVolratio207", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_208", property="harVolratio208", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_209", property="harVolratio209", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_210", property="harVolratio210", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_211", property="harVolratio211", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_212", property="harVolratio212", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_213", property="harVolratio213", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_214", property="harVolratio214", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_215", property="harVolratio215", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_216", property="harVolratio216", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_217", property="harVolratio217", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_218", property="harVolratio218", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_219", property="harVolratio219", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_220", property="harVolratio220", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_221", property="harVolratio221", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_222", property="harVolratio222", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_223", property="harVolratio223", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_224", property="harVolratio224", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_225", property="harVolratio225", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_226", property="harVolratio226", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_227", property="harVolratio227", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_228", property="harVolratio228", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_229", property="harVolratio229", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_230", property="harVolratio230", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_231", property="harVolratio231", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_232", property="harVolratio232", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_233", property="harVolratio233", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_234", property="harVolratio234", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_235", property="harVolratio235", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_236", property="harVolratio236", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_237", property="harVolratio237", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_238", property="harVolratio238", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_239", property="harVolratio239", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_240", property="harVolratio240", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_241", property="harVolratio241", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_242", property="harVolratio242", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_243", property="harVolratio243", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_244", property="harVolratio244", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_245", property="harVolratio245", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_246", property="harVolratio246", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_247", property="harVolratio247", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_248", property="harVolratio248", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_249", property="harVolratio249", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_250", property="harVolratio250", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_251", property="harVolratio251", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_252", property="harVolratio252", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_253", property="harVolratio253", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_254", property="harVolratio254", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_255", property="harVolratio255", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_256", property="harVolratio256", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_257", property="harVolratio257", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_258", property="harVolratio258", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_259", property="harVolratio259", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_260", property="harVolratio260", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_261", property="harVolratio261", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_262", property="harVolratio262", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_263", property="harVolratio263", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_264", property="harVolratio264", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_265", property="harVolratio265", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_266", property="harVolratio266", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_267", property="harVolratio267", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_268", property="harVolratio268", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_269", property="harVolratio269", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_270", property="harVolratio270", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_271", property="harVolratio271", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_272", property="harVolratio272", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_273", property="harVolratio273", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_274", property="harVolratio274", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_275", property="harVolratio275", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_276", property="harVolratio276", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_277", property="harVolratio277", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_278", property="harVolratio278", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_279", property="harVolratio279", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_280", property="harVolratio280", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_281", property="harVolratio281", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_282", property="harVolratio282", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_283", property="harVolratio283", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_284", property="harVolratio284", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_285", property="harVolratio285", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_286", property="harVolratio286", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_287", property="harVolratio287", jdbcType=JdbcType.DECIMAL),
            @Result(column="HAR_VOLRATIO_288", property="harVolratio288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_volRatioCurvePo> selectVolRatioCurveBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

}