package com.dao.mapper;

import com.dao.bean.D_volCurvePo;
import com.dao.bean.D_volCurvePoKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_volCurvePoMapper {

    @Select({
        "select",
        "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, VOL_1, VOL_2, ",
        "VOL_3, VOL_4, VOL_5, VOL_6, VOL_7, VOL_8, VOL_9, VOL_10, VOL_11, VOL_12, VOL_13, ",
        "VOL_14, VOL_15, VOL_16, VOL_17, VOL_18, VOL_19, VOL_20, VOL_21, VOL_22, VOL_23, ",
        "VOL_24, VOL_25, VOL_26, VOL_27, VOL_28, VOL_29, VOL_30, VOL_31, VOL_32, VOL_33, ",
        "VOL_34, VOL_35, VOL_36, VOL_37, VOL_38, VOL_39, VOL_40, VOL_41, VOL_42, VOL_43, ",
        "VOL_44, VOL_45, VOL_46, VOL_47, VOL_48, VOL_49, VOL_50, VOL_51, VOL_52, VOL_53, ",
        "VOL_54, VOL_55, VOL_56, VOL_57, VOL_58, VOL_59, VOL_60, VOL_61, VOL_62, VOL_63, ",
        "VOL_64, VOL_65, VOL_66, VOL_67, VOL_68, VOL_69, VOL_70, VOL_71, VOL_72, VOL_73, ",
        "VOL_74, VOL_75, VOL_76, VOL_77, VOL_78, VOL_79, VOL_80, VOL_81, VOL_82, VOL_83, ",
        "VOL_84, VOL_85, VOL_86, VOL_87, VOL_88, VOL_89, VOL_90, VOL_91, VOL_92, VOL_93, ",
        "VOL_94, VOL_95, VOL_96, VOL_97, VOL_98, VOL_99, VOL_100, VOL_101, VOL_102, VOL_103, ",
        "VOL_104, VOL_105, VOL_106, VOL_107, VOL_108, VOL_109, VOL_110, VOL_111, VOL_112, ",
        "VOL_113, VOL_114, VOL_115, VOL_116, VOL_117, VOL_118, VOL_119, VOL_120, VOL_121, ",
        "VOL_122, VOL_123, VOL_124, VOL_125, VOL_126, VOL_127, VOL_128, VOL_129, VOL_130, ",
        "VOL_131, VOL_132, VOL_133, VOL_134, VOL_135, VOL_136, VOL_137, VOL_138, VOL_139, ",
        "VOL_140, VOL_141, VOL_142, VOL_143, VOL_144, VOL_145, VOL_146, VOL_147, VOL_148, ",
        "VOL_149, VOL_150, VOL_151, VOL_152, VOL_153, VOL_154, VOL_155, VOL_156, VOL_157, ",
        "VOL_158, VOL_159, VOL_160, VOL_161, VOL_162, VOL_163, VOL_164, VOL_165, VOL_166, ",
        "VOL_167, VOL_168, VOL_169, VOL_170, VOL_171, VOL_172, VOL_173, VOL_174, VOL_175, ",
        "VOL_176, VOL_177, VOL_178, VOL_179, VOL_180, VOL_181, VOL_182, VOL_183, VOL_184, ",
        "VOL_185, VOL_186, VOL_187, VOL_188, VOL_189, VOL_190, VOL_191, VOL_192, VOL_193, ",
        "VOL_194, VOL_195, VOL_196, VOL_197, VOL_198, VOL_199, VOL_200, VOL_201, VOL_202, ",
        "VOL_203, VOL_204, VOL_205, VOL_206, VOL_207, VOL_208, VOL_209, VOL_210, VOL_211, ",
        "VOL_212, VOL_213, VOL_214, VOL_215, VOL_216, VOL_217, VOL_218, VOL_219, VOL_220, ",
        "VOL_221, VOL_222, VOL_223, VOL_224, VOL_225, VOL_226, VOL_227, VOL_228, VOL_229, ",
        "VOL_230, VOL_231, VOL_232, VOL_233, VOL_234, VOL_235, VOL_236, VOL_237, VOL_238, ",
        "VOL_239, VOL_240, VOL_241, VOL_242, VOL_243, VOL_244, VOL_245, VOL_246, VOL_247, ",
        "VOL_248, VOL_249, VOL_250, VOL_251, VOL_252, VOL_253, VOL_254, VOL_255, VOL_256, ",
        "VOL_257, VOL_258, VOL_259, VOL_260, VOL_261, VOL_262, VOL_263, VOL_264, VOL_265, ",
        "VOL_266, VOL_267, VOL_268, VOL_269, VOL_270, VOL_271, VOL_272, VOL_273, VOL_274, ",
        "VOL_275, VOL_276, VOL_277, VOL_278, VOL_279, VOL_280, VOL_281, VOL_282, VOL_283, ",
        "VOL_284, VOL_285, VOL_286, VOL_287, VOL_288",
        "from c_mmxu_vol_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="VOL_1", property="vol1", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_2", property="vol2", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_3", property="vol3", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_4", property="vol4", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_5", property="vol5", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_6", property="vol6", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_7", property="vol7", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_8", property="vol8", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_9", property="vol9", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_10", property="vol10", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_11", property="vol11", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_12", property="vol12", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_13", property="vol13", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_14", property="vol14", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_15", property="vol15", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_16", property="vol16", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_17", property="vol17", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_18", property="vol18", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_19", property="vol19", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_20", property="vol20", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_21", property="vol21", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_22", property="vol22", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_23", property="vol23", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_24", property="vol24", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_25", property="vol25", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_26", property="vol26", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_27", property="vol27", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_28", property="vol28", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_29", property="vol29", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_30", property="vol30", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_31", property="vol31", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_32", property="vol32", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_33", property="vol33", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_34", property="vol34", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_35", property="vol35", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_36", property="vol36", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_37", property="vol37", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_38", property="vol38", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_39", property="vol39", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_40", property="vol40", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_41", property="vol41", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_42", property="vol42", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_43", property="vol43", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_44", property="vol44", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_45", property="vol45", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_46", property="vol46", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_47", property="vol47", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_48", property="vol48", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_49", property="vol49", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_50", property="vol50", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_51", property="vol51", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_52", property="vol52", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_53", property="vol53", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_54", property="vol54", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_55", property="vol55", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_56", property="vol56", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_57", property="vol57", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_58", property="vol58", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_59", property="vol59", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_60", property="vol60", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_61", property="vol61", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_62", property="vol62", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_63", property="vol63", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_64", property="vol64", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_65", property="vol65", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_66", property="vol66", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_67", property="vol67", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_68", property="vol68", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_69", property="vol69", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_70", property="vol70", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_71", property="vol71", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_72", property="vol72", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_73", property="vol73", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_74", property="vol74", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_75", property="vol75", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_76", property="vol76", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_77", property="vol77", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_78", property="vol78", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_79", property="vol79", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_80", property="vol80", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_81", property="vol81", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_82", property="vol82", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_83", property="vol83", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_84", property="vol84", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_85", property="vol85", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_86", property="vol86", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_87", property="vol87", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_88", property="vol88", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_89", property="vol89", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_90", property="vol90", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_91", property="vol91", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_92", property="vol92", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_93", property="vol93", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_94", property="vol94", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_95", property="vol95", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_96", property="vol96", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_97", property="vol97", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_98", property="vol98", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_99", property="vol99", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_100", property="vol100", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_101", property="vol101", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_102", property="vol102", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_103", property="vol103", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_104", property="vol104", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_105", property="vol105", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_106", property="vol106", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_107", property="vol107", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_108", property="vol108", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_109", property="vol109", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_110", property="vol110", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_111", property="vol111", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_112", property="vol112", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_113", property="vol113", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_114", property="vol114", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_115", property="vol115", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_116", property="vol116", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_117", property="vol117", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_118", property="vol118", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_119", property="vol119", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_120", property="vol120", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_121", property="vol121", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_122", property="vol122", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_123", property="vol123", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_124", property="vol124", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_125", property="vol125", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_126", property="vol126", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_127", property="vol127", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_128", property="vol128", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_129", property="vol129", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_130", property="vol130", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_131", property="vol131", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_132", property="vol132", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_133", property="vol133", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_134", property="vol134", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_135", property="vol135", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_136", property="vol136", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_137", property="vol137", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_138", property="vol138", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_139", property="vol139", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_140", property="vol140", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_141", property="vol141", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_142", property="vol142", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_143", property="vol143", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_144", property="vol144", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_145", property="vol145", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_146", property="vol146", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_147", property="vol147", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_148", property="vol148", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_149", property="vol149", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_150", property="vol150", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_151", property="vol151", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_152", property="vol152", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_153", property="vol153", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_154", property="vol154", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_155", property="vol155", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_156", property="vol156", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_157", property="vol157", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_158", property="vol158", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_159", property="vol159", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_160", property="vol160", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_161", property="vol161", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_162", property="vol162", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_163", property="vol163", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_164", property="vol164", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_165", property="vol165", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_166", property="vol166", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_167", property="vol167", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_168", property="vol168", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_169", property="vol169", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_170", property="vol170", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_171", property="vol171", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_172", property="vol172", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_173", property="vol173", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_174", property="vol174", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_175", property="vol175", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_176", property="vol176", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_177", property="vol177", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_178", property="vol178", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_179", property="vol179", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_180", property="vol180", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_181", property="vol181", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_182", property="vol182", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_183", property="vol183", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_184", property="vol184", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_185", property="vol185", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_186", property="vol186", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_187", property="vol187", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_188", property="vol188", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_189", property="vol189", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_190", property="vol190", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_191", property="vol191", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_192", property="vol192", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_193", property="vol193", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_194", property="vol194", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_195", property="vol195", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_196", property="vol196", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_197", property="vol197", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_198", property="vol198", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_199", property="vol199", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_200", property="vol200", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_201", property="vol201", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_202", property="vol202", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_203", property="vol203", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_204", property="vol204", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_205", property="vol205", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_206", property="vol206", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_207", property="vol207", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_208", property="vol208", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_209", property="vol209", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_210", property="vol210", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_211", property="vol211", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_212", property="vol212", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_213", property="vol213", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_214", property="vol214", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_215", property="vol215", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_216", property="vol216", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_217", property="vol217", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_218", property="vol218", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_219", property="vol219", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_220", property="vol220", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_221", property="vol221", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_222", property="vol222", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_223", property="vol223", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_224", property="vol224", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_225", property="vol225", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_226", property="vol226", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_227", property="vol227", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_228", property="vol228", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_229", property="vol229", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_230", property="vol230", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_231", property="vol231", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_232", property="vol232", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_233", property="vol233", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_234", property="vol234", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_235", property="vol235", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_236", property="vol236", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_237", property="vol237", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_238", property="vol238", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_239", property="vol239", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_240", property="vol240", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_241", property="vol241", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_242", property="vol242", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_243", property="vol243", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_244", property="vol244", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_245", property="vol245", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_246", property="vol246", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_247", property="vol247", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_248", property="vol248", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_249", property="vol249", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_250", property="vol250", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_251", property="vol251", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_252", property="vol252", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_253", property="vol253", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_254", property="vol254", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_255", property="vol255", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_256", property="vol256", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_257", property="vol257", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_258", property="vol258", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_259", property="vol259", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_260", property="vol260", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_261", property="vol261", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_262", property="vol262", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_263", property="vol263", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_264", property="vol264", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_265", property="vol265", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_266", property="vol266", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_267", property="vol267", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_268", property="vol268", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_269", property="vol269", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_270", property="vol270", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_271", property="vol271", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_272", property="vol272", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_273", property="vol273", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_274", property="vol274", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_275", property="vol275", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_276", property="vol276", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_277", property="vol277", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_278", property="vol278", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_279", property="vol279", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_280", property="vol280", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_281", property="vol281", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_282", property="vol282", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_283", property="vol283", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_284", property="vol284", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_285", property="vol285", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_286", property="vol286", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_287", property="vol287", jdbcType=JdbcType.DECIMAL),
        @Result(column="VOL_288", property="vol288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_volCurvePo> selectVolByDate(String data_date);

}