package com.dao.mapper;

import com.dao.bean.D_vUnbalanceCurvePo;
import com.dao.bean.D_vUnbalanceCurvePoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface D_vUnbalanceCurvePoMapper {

    @Select({
        "select",
        "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, U_UNBALANCE_1, ",
        "U_UNBALANCE_2, U_UNBALANCE_3, U_UNBALANCE_4, U_UNBALANCE_5, U_UNBALANCE_6, U_UNBALANCE_7, ",
        "U_UNBALANCE_8, U_UNBALANCE_9, U_UNBALANCE_10, U_UNBALANCE_11, U_UNBALANCE_12, ",
        "U_UNBALANCE_13, U_UNBALANCE_14, U_UNBALANCE_15, U_UNBALANCE_16, U_UNBALANCE_17, ",
        "U_UNBALANCE_18, U_UNBALANCE_19, U_UNBALANCE_20, U_UNBALANCE_21, U_UNBALANCE_22, ",
        "U_UNBALANCE_23, U_UNBALANCE_24, U_UNBALANCE_25, U_UNBALANCE_26, U_UNBALANCE_27, ",
        "U_UNBALANCE_28, U_UNBALANCE_29, U_UNBALANCE_30, U_UNBALANCE_31, U_UNBALANCE_32, ",
        "U_UNBALANCE_33, U_UNBALANCE_34, U_UNBALANCE_35, U_UNBALANCE_36, U_UNBALANCE_37, ",
        "U_UNBALANCE_38, U_UNBALANCE_39, U_UNBALANCE_40, U_UNBALANCE_41, U_UNBALANCE_42, ",
        "U_UNBALANCE_43, U_UNBALANCE_44, U_UNBALANCE_45, U_UNBALANCE_46, U_UNBALANCE_47, ",
        "U_UNBALANCE_48, U_UNBALANCE_49, U_UNBALANCE_50, U_UNBALANCE_51, U_UNBALANCE_52, ",
        "U_UNBALANCE_53, U_UNBALANCE_54, U_UNBALANCE_55, U_UNBALANCE_56, U_UNBALANCE_57, ",
        "U_UNBALANCE_58, U_UNBALANCE_59, U_UNBALANCE_60, U_UNBALANCE_61, U_UNBALANCE_62, ",
        "U_UNBALANCE_63, U_UNBALANCE_64, U_UNBALANCE_65, U_UNBALANCE_66, U_UNBALANCE_67, ",
        "U_UNBALANCE_68, U_UNBALANCE_69, U_UNBALANCE_70, U_UNBALANCE_71, U_UNBALANCE_72, ",
        "U_UNBALANCE_73, U_UNBALANCE_74, U_UNBALANCE_75, U_UNBALANCE_76, U_UNBALANCE_77, ",
        "U_UNBALANCE_78, U_UNBALANCE_79, U_UNBALANCE_80, U_UNBALANCE_81, U_UNBALANCE_82, ",
        "U_UNBALANCE_83, U_UNBALANCE_84, U_UNBALANCE_85, U_UNBALANCE_86, U_UNBALANCE_87, ",
        "U_UNBALANCE_88, U_UNBALANCE_89, U_UNBALANCE_90, U_UNBALANCE_91, U_UNBALANCE_92, ",
        "U_UNBALANCE_93, U_UNBALANCE_94, U_UNBALANCE_95, U_UNBALANCE_96, U_UNBALANCE_97, ",
        "U_UNBALANCE_98, U_UNBALANCE_99, U_UNBALANCE_100, U_UNBALANCE_101, U_UNBALANCE_102, ",
        "U_UNBALANCE_103, U_UNBALANCE_104, U_UNBALANCE_105, U_UNBALANCE_106, U_UNBALANCE_107, ",
        "U_UNBALANCE_108, U_UNBALANCE_109, U_UNBALANCE_110, U_UNBALANCE_111, U_UNBALANCE_112, ",
        "U_UNBALANCE_113, U_UNBALANCE_114, U_UNBALANCE_115, U_UNBALANCE_116, U_UNBALANCE_117, ",
        "U_UNBALANCE_118, U_UNBALANCE_119, U_UNBALANCE_120, U_UNBALANCE_121, U_UNBALANCE_122, ",
        "U_UNBALANCE_123, U_UNBALANCE_124, U_UNBALANCE_125, U_UNBALANCE_126, U_UNBALANCE_127, ",
        "U_UNBALANCE_128, U_UNBALANCE_129, U_UNBALANCE_130, U_UNBALANCE_131, U_UNBALANCE_132, ",
        "U_UNBALANCE_133, U_UNBALANCE_134, U_UNBALANCE_135, U_UNBALANCE_136, U_UNBALANCE_137, ",
        "U_UNBALANCE_138, U_UNBALANCE_139, U_UNBALANCE_140, U_UNBALANCE_141, U_UNBALANCE_142, ",
        "U_UNBALANCE_143, U_UNBALANCE_144, U_UNBALANCE_145, U_UNBALANCE_146, U_UNBALANCE_147, ",
        "U_UNBALANCE_148, U_UNBALANCE_149, U_UNBALANCE_150, U_UNBALANCE_151, U_UNBALANCE_152, ",
        "U_UNBALANCE_153, U_UNBALANCE_154, U_UNBALANCE_155, U_UNBALANCE_156, U_UNBALANCE_157, ",
        "U_UNBALANCE_158, U_UNBALANCE_159, U_UNBALANCE_160, U_UNBALANCE_161, U_UNBALANCE_162, ",
        "U_UNBALANCE_163, U_UNBALANCE_164, U_UNBALANCE_165, U_UNBALANCE_166, U_UNBALANCE_167, ",
        "U_UNBALANCE_168, U_UNBALANCE_169, U_UNBALANCE_170, U_UNBALANCE_171, U_UNBALANCE_172, ",
        "U_UNBALANCE_173, U_UNBALANCE_174, U_UNBALANCE_175, U_UNBALANCE_176, U_UNBALANCE_177, ",
        "U_UNBALANCE_178, U_UNBALANCE_179, U_UNBALANCE_180, U_UNBALANCE_181, U_UNBALANCE_182, ",
        "U_UNBALANCE_183, U_UNBALANCE_184, U_UNBALANCE_185, U_UNBALANCE_186, U_UNBALANCE_187, ",
        "U_UNBALANCE_188, U_UNBALANCE_189, U_UNBALANCE_190, U_UNBALANCE_191, U_UNBALANCE_192, ",
        "U_UNBALANCE_193, U_UNBALANCE_194, U_UNBALANCE_195, U_UNBALANCE_196, U_UNBALANCE_197, ",
        "U_UNBALANCE_198, U_UNBALANCE_199, U_UNBALANCE_200, U_UNBALANCE_201, U_UNBALANCE_202, ",
        "U_UNBALANCE_203, U_UNBALANCE_204, U_UNBALANCE_205, U_UNBALANCE_206, U_UNBALANCE_207, ",
        "U_UNBALANCE_208, U_UNBALANCE_209, U_UNBALANCE_210, U_UNBALANCE_211, U_UNBALANCE_212, ",
        "U_UNBALANCE_213, U_UNBALANCE_214, U_UNBALANCE_215, U_UNBALANCE_216, U_UNBALANCE_217, ",
        "U_UNBALANCE_218, U_UNBALANCE_219, U_UNBALANCE_220, U_UNBALANCE_221, U_UNBALANCE_222, ",
        "U_UNBALANCE_223, U_UNBALANCE_224, U_UNBALANCE_225, U_UNBALANCE_226, U_UNBALANCE_227, ",
        "U_UNBALANCE_228, U_UNBALANCE_229, U_UNBALANCE_230, U_UNBALANCE_231, U_UNBALANCE_232, ",
        "U_UNBALANCE_233, U_UNBALANCE_234, U_UNBALANCE_235, U_UNBALANCE_236, U_UNBALANCE_237, ",
        "U_UNBALANCE_238, U_UNBALANCE_239, U_UNBALANCE_240, U_UNBALANCE_241, U_UNBALANCE_242, ",
        "U_UNBALANCE_243, U_UNBALANCE_244, U_UNBALANCE_245, U_UNBALANCE_246, U_UNBALANCE_247, ",
        "U_UNBALANCE_248, U_UNBALANCE_249, U_UNBALANCE_250, U_UNBALANCE_251, U_UNBALANCE_252, ",
        "U_UNBALANCE_253, U_UNBALANCE_254, U_UNBALANCE_255, U_UNBALANCE_256, U_UNBALANCE_257, ",
        "U_UNBALANCE_258, U_UNBALANCE_259, U_UNBALANCE_260, U_UNBALANCE_261, U_UNBALANCE_262, ",
        "U_UNBALANCE_263, U_UNBALANCE_264, U_UNBALANCE_265, U_UNBALANCE_266, U_UNBALANCE_267, ",
        "U_UNBALANCE_268, U_UNBALANCE_269, U_UNBALANCE_270, U_UNBALANCE_271, U_UNBALANCE_272, ",
        "U_UNBALANCE_273, U_UNBALANCE_274, U_UNBALANCE_275, U_UNBALANCE_276, U_UNBALANCE_277, ",
        "U_UNBALANCE_278, U_UNBALANCE_279, U_UNBALANCE_280, U_UNBALANCE_281, U_UNBALANCE_282, ",
        "U_UNBALANCE_283, U_UNBALANCE_284, U_UNBALANCE_285, U_UNBALANCE_286, U_UNBALANCE_287, ",
        "U_UNBALANCE_288",
        "from c_msqi_u_unbalance_c",
        "where DATA_DATE = #{dataDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
        @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
        @Result(column="U_UNBALANCE_1", property="uUnbalance1", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_2", property="uUnbalance2", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_3", property="uUnbalance3", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_4", property="uUnbalance4", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_5", property="uUnbalance5", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_6", property="uUnbalance6", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_7", property="uUnbalance7", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_8", property="uUnbalance8", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_9", property="uUnbalance9", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_10", property="uUnbalance10", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_11", property="uUnbalance11", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_12", property="uUnbalance12", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_13", property="uUnbalance13", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_14", property="uUnbalance14", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_15", property="uUnbalance15", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_16", property="uUnbalance16", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_17", property="uUnbalance17", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_18", property="uUnbalance18", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_19", property="uUnbalance19", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_20", property="uUnbalance20", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_21", property="uUnbalance21", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_22", property="uUnbalance22", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_23", property="uUnbalance23", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_24", property="uUnbalance24", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_25", property="uUnbalance25", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_26", property="uUnbalance26", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_27", property="uUnbalance27", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_28", property="uUnbalance28", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_29", property="uUnbalance29", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_30", property="uUnbalance30", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_31", property="uUnbalance31", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_32", property="uUnbalance32", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_33", property="uUnbalance33", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_34", property="uUnbalance34", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_35", property="uUnbalance35", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_36", property="uUnbalance36", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_37", property="uUnbalance37", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_38", property="uUnbalance38", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_39", property="uUnbalance39", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_40", property="uUnbalance40", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_41", property="uUnbalance41", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_42", property="uUnbalance42", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_43", property="uUnbalance43", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_44", property="uUnbalance44", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_45", property="uUnbalance45", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_46", property="uUnbalance46", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_47", property="uUnbalance47", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_48", property="uUnbalance48", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_49", property="uUnbalance49", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_50", property="uUnbalance50", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_51", property="uUnbalance51", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_52", property="uUnbalance52", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_53", property="uUnbalance53", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_54", property="uUnbalance54", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_55", property="uUnbalance55", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_56", property="uUnbalance56", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_57", property="uUnbalance57", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_58", property="uUnbalance58", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_59", property="uUnbalance59", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_60", property="uUnbalance60", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_61", property="uUnbalance61", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_62", property="uUnbalance62", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_63", property="uUnbalance63", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_64", property="uUnbalance64", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_65", property="uUnbalance65", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_66", property="uUnbalance66", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_67", property="uUnbalance67", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_68", property="uUnbalance68", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_69", property="uUnbalance69", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_70", property="uUnbalance70", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_71", property="uUnbalance71", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_72", property="uUnbalance72", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_73", property="uUnbalance73", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_74", property="uUnbalance74", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_75", property="uUnbalance75", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_76", property="uUnbalance76", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_77", property="uUnbalance77", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_78", property="uUnbalance78", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_79", property="uUnbalance79", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_80", property="uUnbalance80", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_81", property="uUnbalance81", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_82", property="uUnbalance82", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_83", property="uUnbalance83", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_84", property="uUnbalance84", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_85", property="uUnbalance85", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_86", property="uUnbalance86", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_87", property="uUnbalance87", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_88", property="uUnbalance88", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_89", property="uUnbalance89", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_90", property="uUnbalance90", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_91", property="uUnbalance91", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_92", property="uUnbalance92", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_93", property="uUnbalance93", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_94", property="uUnbalance94", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_95", property="uUnbalance95", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_96", property="uUnbalance96", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_97", property="uUnbalance97", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_98", property="uUnbalance98", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_99", property="uUnbalance99", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_100", property="uUnbalance100", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_101", property="uUnbalance101", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_102", property="uUnbalance102", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_103", property="uUnbalance103", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_104", property="uUnbalance104", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_105", property="uUnbalance105", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_106", property="uUnbalance106", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_107", property="uUnbalance107", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_108", property="uUnbalance108", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_109", property="uUnbalance109", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_110", property="uUnbalance110", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_111", property="uUnbalance111", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_112", property="uUnbalance112", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_113", property="uUnbalance113", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_114", property="uUnbalance114", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_115", property="uUnbalance115", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_116", property="uUnbalance116", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_117", property="uUnbalance117", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_118", property="uUnbalance118", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_119", property="uUnbalance119", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_120", property="uUnbalance120", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_121", property="uUnbalance121", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_122", property="uUnbalance122", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_123", property="uUnbalance123", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_124", property="uUnbalance124", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_125", property="uUnbalance125", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_126", property="uUnbalance126", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_127", property="uUnbalance127", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_128", property="uUnbalance128", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_129", property="uUnbalance129", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_130", property="uUnbalance130", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_131", property="uUnbalance131", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_132", property="uUnbalance132", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_133", property="uUnbalance133", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_134", property="uUnbalance134", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_135", property="uUnbalance135", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_136", property="uUnbalance136", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_137", property="uUnbalance137", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_138", property="uUnbalance138", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_139", property="uUnbalance139", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_140", property="uUnbalance140", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_141", property="uUnbalance141", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_142", property="uUnbalance142", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_143", property="uUnbalance143", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_144", property="uUnbalance144", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_145", property="uUnbalance145", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_146", property="uUnbalance146", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_147", property="uUnbalance147", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_148", property="uUnbalance148", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_149", property="uUnbalance149", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_150", property="uUnbalance150", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_151", property="uUnbalance151", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_152", property="uUnbalance152", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_153", property="uUnbalance153", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_154", property="uUnbalance154", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_155", property="uUnbalance155", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_156", property="uUnbalance156", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_157", property="uUnbalance157", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_158", property="uUnbalance158", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_159", property="uUnbalance159", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_160", property="uUnbalance160", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_161", property="uUnbalance161", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_162", property="uUnbalance162", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_163", property="uUnbalance163", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_164", property="uUnbalance164", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_165", property="uUnbalance165", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_166", property="uUnbalance166", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_167", property="uUnbalance167", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_168", property="uUnbalance168", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_169", property="uUnbalance169", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_170", property="uUnbalance170", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_171", property="uUnbalance171", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_172", property="uUnbalance172", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_173", property="uUnbalance173", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_174", property="uUnbalance174", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_175", property="uUnbalance175", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_176", property="uUnbalance176", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_177", property="uUnbalance177", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_178", property="uUnbalance178", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_179", property="uUnbalance179", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_180", property="uUnbalance180", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_181", property="uUnbalance181", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_182", property="uUnbalance182", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_183", property="uUnbalance183", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_184", property="uUnbalance184", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_185", property="uUnbalance185", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_186", property="uUnbalance186", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_187", property="uUnbalance187", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_188", property="uUnbalance188", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_189", property="uUnbalance189", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_190", property="uUnbalance190", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_191", property="uUnbalance191", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_192", property="uUnbalance192", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_193", property="uUnbalance193", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_194", property="uUnbalance194", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_195", property="uUnbalance195", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_196", property="uUnbalance196", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_197", property="uUnbalance197", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_198", property="uUnbalance198", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_199", property="uUnbalance199", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_200", property="uUnbalance200", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_201", property="uUnbalance201", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_202", property="uUnbalance202", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_203", property="uUnbalance203", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_204", property="uUnbalance204", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_205", property="uUnbalance205", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_206", property="uUnbalance206", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_207", property="uUnbalance207", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_208", property="uUnbalance208", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_209", property="uUnbalance209", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_210", property="uUnbalance210", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_211", property="uUnbalance211", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_212", property="uUnbalance212", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_213", property="uUnbalance213", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_214", property="uUnbalance214", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_215", property="uUnbalance215", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_216", property="uUnbalance216", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_217", property="uUnbalance217", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_218", property="uUnbalance218", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_219", property="uUnbalance219", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_220", property="uUnbalance220", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_221", property="uUnbalance221", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_222", property="uUnbalance222", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_223", property="uUnbalance223", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_224", property="uUnbalance224", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_225", property="uUnbalance225", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_226", property="uUnbalance226", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_227", property="uUnbalance227", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_228", property="uUnbalance228", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_229", property="uUnbalance229", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_230", property="uUnbalance230", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_231", property="uUnbalance231", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_232", property="uUnbalance232", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_233", property="uUnbalance233", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_234", property="uUnbalance234", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_235", property="uUnbalance235", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_236", property="uUnbalance236", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_237", property="uUnbalance237", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_238", property="uUnbalance238", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_239", property="uUnbalance239", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_240", property="uUnbalance240", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_241", property="uUnbalance241", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_242", property="uUnbalance242", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_243", property="uUnbalance243", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_244", property="uUnbalance244", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_245", property="uUnbalance245", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_246", property="uUnbalance246", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_247", property="uUnbalance247", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_248", property="uUnbalance248", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_249", property="uUnbalance249", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_250", property="uUnbalance250", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_251", property="uUnbalance251", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_252", property="uUnbalance252", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_253", property="uUnbalance253", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_254", property="uUnbalance254", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_255", property="uUnbalance255", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_256", property="uUnbalance256", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_257", property="uUnbalance257", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_258", property="uUnbalance258", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_259", property="uUnbalance259", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_260", property="uUnbalance260", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_261", property="uUnbalance261", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_262", property="uUnbalance262", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_263", property="uUnbalance263", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_264", property="uUnbalance264", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_265", property="uUnbalance265", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_266", property="uUnbalance266", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_267", property="uUnbalance267", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_268", property="uUnbalance268", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_269", property="uUnbalance269", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_270", property="uUnbalance270", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_271", property="uUnbalance271", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_272", property="uUnbalance272", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_273", property="uUnbalance273", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_274", property="uUnbalance274", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_275", property="uUnbalance275", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_276", property="uUnbalance276", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_277", property="uUnbalance277", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_278", property="uUnbalance278", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_279", property="uUnbalance279", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_280", property="uUnbalance280", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_281", property="uUnbalance281", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_282", property="uUnbalance282", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_283", property="uUnbalance283", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_284", property="uUnbalance284", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_285", property="uUnbalance285", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_286", property="uUnbalance286", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_287", property="uUnbalance287", jdbcType=JdbcType.DECIMAL),
        @Result(column="U_UNBALANCE_288", property="uUnbalance288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_vUnbalanceCurvePo> selectVunbalanceByDate(String data_date);

    @Select({
            "select",
            "SYS_ID, LD_ID, DATA_DATE, DATA_TYPE, DATA_INTERVAL, DATA_POINT, U_UNBALANCE_1, ",
            "U_UNBALANCE_2, U_UNBALANCE_3, U_UNBALANCE_4, U_UNBALANCE_5, U_UNBALANCE_6, U_UNBALANCE_7, ",
            "U_UNBALANCE_8, U_UNBALANCE_9, U_UNBALANCE_10, U_UNBALANCE_11, U_UNBALANCE_12, ",
            "U_UNBALANCE_13, U_UNBALANCE_14, U_UNBALANCE_15, U_UNBALANCE_16, U_UNBALANCE_17, ",
            "U_UNBALANCE_18, U_UNBALANCE_19, U_UNBALANCE_20, U_UNBALANCE_21, U_UNBALANCE_22, ",
            "U_UNBALANCE_23, U_UNBALANCE_24, U_UNBALANCE_25, U_UNBALANCE_26, U_UNBALANCE_27, ",
            "U_UNBALANCE_28, U_UNBALANCE_29, U_UNBALANCE_30, U_UNBALANCE_31, U_UNBALANCE_32, ",
            "U_UNBALANCE_33, U_UNBALANCE_34, U_UNBALANCE_35, U_UNBALANCE_36, U_UNBALANCE_37, ",
            "U_UNBALANCE_38, U_UNBALANCE_39, U_UNBALANCE_40, U_UNBALANCE_41, U_UNBALANCE_42, ",
            "U_UNBALANCE_43, U_UNBALANCE_44, U_UNBALANCE_45, U_UNBALANCE_46, U_UNBALANCE_47, ",
            "U_UNBALANCE_48, U_UNBALANCE_49, U_UNBALANCE_50, U_UNBALANCE_51, U_UNBALANCE_52, ",
            "U_UNBALANCE_53, U_UNBALANCE_54, U_UNBALANCE_55, U_UNBALANCE_56, U_UNBALANCE_57, ",
            "U_UNBALANCE_58, U_UNBALANCE_59, U_UNBALANCE_60, U_UNBALANCE_61, U_UNBALANCE_62, ",
            "U_UNBALANCE_63, U_UNBALANCE_64, U_UNBALANCE_65, U_UNBALANCE_66, U_UNBALANCE_67, ",
            "U_UNBALANCE_68, U_UNBALANCE_69, U_UNBALANCE_70, U_UNBALANCE_71, U_UNBALANCE_72, ",
            "U_UNBALANCE_73, U_UNBALANCE_74, U_UNBALANCE_75, U_UNBALANCE_76, U_UNBALANCE_77, ",
            "U_UNBALANCE_78, U_UNBALANCE_79, U_UNBALANCE_80, U_UNBALANCE_81, U_UNBALANCE_82, ",
            "U_UNBALANCE_83, U_UNBALANCE_84, U_UNBALANCE_85, U_UNBALANCE_86, U_UNBALANCE_87, ",
            "U_UNBALANCE_88, U_UNBALANCE_89, U_UNBALANCE_90, U_UNBALANCE_91, U_UNBALANCE_92, ",
            "U_UNBALANCE_93, U_UNBALANCE_94, U_UNBALANCE_95, U_UNBALANCE_96, U_UNBALANCE_97, ",
            "U_UNBALANCE_98, U_UNBALANCE_99, U_UNBALANCE_100, U_UNBALANCE_101, U_UNBALANCE_102, ",
            "U_UNBALANCE_103, U_UNBALANCE_104, U_UNBALANCE_105, U_UNBALANCE_106, U_UNBALANCE_107, ",
            "U_UNBALANCE_108, U_UNBALANCE_109, U_UNBALANCE_110, U_UNBALANCE_111, U_UNBALANCE_112, ",
            "U_UNBALANCE_113, U_UNBALANCE_114, U_UNBALANCE_115, U_UNBALANCE_116, U_UNBALANCE_117, ",
            "U_UNBALANCE_118, U_UNBALANCE_119, U_UNBALANCE_120, U_UNBALANCE_121, U_UNBALANCE_122, ",
            "U_UNBALANCE_123, U_UNBALANCE_124, U_UNBALANCE_125, U_UNBALANCE_126, U_UNBALANCE_127, ",
            "U_UNBALANCE_128, U_UNBALANCE_129, U_UNBALANCE_130, U_UNBALANCE_131, U_UNBALANCE_132, ",
            "U_UNBALANCE_133, U_UNBALANCE_134, U_UNBALANCE_135, U_UNBALANCE_136, U_UNBALANCE_137, ",
            "U_UNBALANCE_138, U_UNBALANCE_139, U_UNBALANCE_140, U_UNBALANCE_141, U_UNBALANCE_142, ",
            "U_UNBALANCE_143, U_UNBALANCE_144, U_UNBALANCE_145, U_UNBALANCE_146, U_UNBALANCE_147, ",
            "U_UNBALANCE_148, U_UNBALANCE_149, U_UNBALANCE_150, U_UNBALANCE_151, U_UNBALANCE_152, ",
            "U_UNBALANCE_153, U_UNBALANCE_154, U_UNBALANCE_155, U_UNBALANCE_156, U_UNBALANCE_157, ",
            "U_UNBALANCE_158, U_UNBALANCE_159, U_UNBALANCE_160, U_UNBALANCE_161, U_UNBALANCE_162, ",
            "U_UNBALANCE_163, U_UNBALANCE_164, U_UNBALANCE_165, U_UNBALANCE_166, U_UNBALANCE_167, ",
            "U_UNBALANCE_168, U_UNBALANCE_169, U_UNBALANCE_170, U_UNBALANCE_171, U_UNBALANCE_172, ",
            "U_UNBALANCE_173, U_UNBALANCE_174, U_UNBALANCE_175, U_UNBALANCE_176, U_UNBALANCE_177, ",
            "U_UNBALANCE_178, U_UNBALANCE_179, U_UNBALANCE_180, U_UNBALANCE_181, U_UNBALANCE_182, ",
            "U_UNBALANCE_183, U_UNBALANCE_184, U_UNBALANCE_185, U_UNBALANCE_186, U_UNBALANCE_187, ",
            "U_UNBALANCE_188, U_UNBALANCE_189, U_UNBALANCE_190, U_UNBALANCE_191, U_UNBALANCE_192, ",
            "U_UNBALANCE_193, U_UNBALANCE_194, U_UNBALANCE_195, U_UNBALANCE_196, U_UNBALANCE_197, ",
            "U_UNBALANCE_198, U_UNBALANCE_199, U_UNBALANCE_200, U_UNBALANCE_201, U_UNBALANCE_202, ",
            "U_UNBALANCE_203, U_UNBALANCE_204, U_UNBALANCE_205, U_UNBALANCE_206, U_UNBALANCE_207, ",
            "U_UNBALANCE_208, U_UNBALANCE_209, U_UNBALANCE_210, U_UNBALANCE_211, U_UNBALANCE_212, ",
            "U_UNBALANCE_213, U_UNBALANCE_214, U_UNBALANCE_215, U_UNBALANCE_216, U_UNBALANCE_217, ",
            "U_UNBALANCE_218, U_UNBALANCE_219, U_UNBALANCE_220, U_UNBALANCE_221, U_UNBALANCE_222, ",
            "U_UNBALANCE_223, U_UNBALANCE_224, U_UNBALANCE_225, U_UNBALANCE_226, U_UNBALANCE_227, ",
            "U_UNBALANCE_228, U_UNBALANCE_229, U_UNBALANCE_230, U_UNBALANCE_231, U_UNBALANCE_232, ",
            "U_UNBALANCE_233, U_UNBALANCE_234, U_UNBALANCE_235, U_UNBALANCE_236, U_UNBALANCE_237, ",
            "U_UNBALANCE_238, U_UNBALANCE_239, U_UNBALANCE_240, U_UNBALANCE_241, U_UNBALANCE_242, ",
            "U_UNBALANCE_243, U_UNBALANCE_244, U_UNBALANCE_245, U_UNBALANCE_246, U_UNBALANCE_247, ",
            "U_UNBALANCE_248, U_UNBALANCE_249, U_UNBALANCE_250, U_UNBALANCE_251, U_UNBALANCE_252, ",
            "U_UNBALANCE_253, U_UNBALANCE_254, U_UNBALANCE_255, U_UNBALANCE_256, U_UNBALANCE_257, ",
            "U_UNBALANCE_258, U_UNBALANCE_259, U_UNBALANCE_260, U_UNBALANCE_261, U_UNBALANCE_262, ",
            "U_UNBALANCE_263, U_UNBALANCE_264, U_UNBALANCE_265, U_UNBALANCE_266, U_UNBALANCE_267, ",
            "U_UNBALANCE_268, U_UNBALANCE_269, U_UNBALANCE_270, U_UNBALANCE_271, U_UNBALANCE_272, ",
            "U_UNBALANCE_273, U_UNBALANCE_274, U_UNBALANCE_275, U_UNBALANCE_276, U_UNBALANCE_277, ",
            "U_UNBALANCE_278, U_UNBALANCE_279, U_UNBALANCE_280, U_UNBALANCE_281, U_UNBALANCE_282, ",
            "U_UNBALANCE_283, U_UNBALANCE_284, U_UNBALANCE_285, U_UNBALANCE_286, U_UNBALANCE_287, ",
            "U_UNBALANCE_288",
            "from c_msqi_u_unbalance_c ",
            "where DATA_DATE >= #{start_date,jdbcType=TIMESTAMP} and DATA_DATE <= #{end_date,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="SYS_ID", property="sysId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="LD_ID", property="ldId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="DATA_DATE", property="dataDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="DATA_INTERVAL", property="dataInterval", jdbcType=JdbcType.TINYINT),
            @Result(column="DATA_POINT", property="dataPoint", jdbcType=JdbcType.SMALLINT),
            @Result(column="U_UNBALANCE_1", property="uUnbalance1", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_2", property="uUnbalance2", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_3", property="uUnbalance3", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_4", property="uUnbalance4", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_5", property="uUnbalance5", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_6", property="uUnbalance6", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_7", property="uUnbalance7", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_8", property="uUnbalance8", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_9", property="uUnbalance9", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_10", property="uUnbalance10", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_11", property="uUnbalance11", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_12", property="uUnbalance12", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_13", property="uUnbalance13", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_14", property="uUnbalance14", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_15", property="uUnbalance15", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_16", property="uUnbalance16", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_17", property="uUnbalance17", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_18", property="uUnbalance18", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_19", property="uUnbalance19", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_20", property="uUnbalance20", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_21", property="uUnbalance21", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_22", property="uUnbalance22", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_23", property="uUnbalance23", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_24", property="uUnbalance24", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_25", property="uUnbalance25", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_26", property="uUnbalance26", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_27", property="uUnbalance27", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_28", property="uUnbalance28", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_29", property="uUnbalance29", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_30", property="uUnbalance30", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_31", property="uUnbalance31", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_32", property="uUnbalance32", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_33", property="uUnbalance33", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_34", property="uUnbalance34", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_35", property="uUnbalance35", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_36", property="uUnbalance36", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_37", property="uUnbalance37", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_38", property="uUnbalance38", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_39", property="uUnbalance39", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_40", property="uUnbalance40", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_41", property="uUnbalance41", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_42", property="uUnbalance42", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_43", property="uUnbalance43", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_44", property="uUnbalance44", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_45", property="uUnbalance45", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_46", property="uUnbalance46", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_47", property="uUnbalance47", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_48", property="uUnbalance48", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_49", property="uUnbalance49", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_50", property="uUnbalance50", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_51", property="uUnbalance51", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_52", property="uUnbalance52", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_53", property="uUnbalance53", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_54", property="uUnbalance54", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_55", property="uUnbalance55", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_56", property="uUnbalance56", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_57", property="uUnbalance57", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_58", property="uUnbalance58", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_59", property="uUnbalance59", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_60", property="uUnbalance60", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_61", property="uUnbalance61", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_62", property="uUnbalance62", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_63", property="uUnbalance63", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_64", property="uUnbalance64", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_65", property="uUnbalance65", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_66", property="uUnbalance66", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_67", property="uUnbalance67", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_68", property="uUnbalance68", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_69", property="uUnbalance69", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_70", property="uUnbalance70", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_71", property="uUnbalance71", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_72", property="uUnbalance72", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_73", property="uUnbalance73", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_74", property="uUnbalance74", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_75", property="uUnbalance75", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_76", property="uUnbalance76", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_77", property="uUnbalance77", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_78", property="uUnbalance78", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_79", property="uUnbalance79", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_80", property="uUnbalance80", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_81", property="uUnbalance81", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_82", property="uUnbalance82", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_83", property="uUnbalance83", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_84", property="uUnbalance84", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_85", property="uUnbalance85", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_86", property="uUnbalance86", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_87", property="uUnbalance87", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_88", property="uUnbalance88", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_89", property="uUnbalance89", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_90", property="uUnbalance90", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_91", property="uUnbalance91", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_92", property="uUnbalance92", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_93", property="uUnbalance93", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_94", property="uUnbalance94", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_95", property="uUnbalance95", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_96", property="uUnbalance96", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_97", property="uUnbalance97", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_98", property="uUnbalance98", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_99", property="uUnbalance99", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_100", property="uUnbalance100", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_101", property="uUnbalance101", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_102", property="uUnbalance102", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_103", property="uUnbalance103", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_104", property="uUnbalance104", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_105", property="uUnbalance105", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_106", property="uUnbalance106", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_107", property="uUnbalance107", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_108", property="uUnbalance108", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_109", property="uUnbalance109", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_110", property="uUnbalance110", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_111", property="uUnbalance111", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_112", property="uUnbalance112", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_113", property="uUnbalance113", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_114", property="uUnbalance114", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_115", property="uUnbalance115", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_116", property="uUnbalance116", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_117", property="uUnbalance117", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_118", property="uUnbalance118", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_119", property="uUnbalance119", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_120", property="uUnbalance120", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_121", property="uUnbalance121", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_122", property="uUnbalance122", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_123", property="uUnbalance123", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_124", property="uUnbalance124", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_125", property="uUnbalance125", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_126", property="uUnbalance126", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_127", property="uUnbalance127", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_128", property="uUnbalance128", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_129", property="uUnbalance129", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_130", property="uUnbalance130", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_131", property="uUnbalance131", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_132", property="uUnbalance132", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_133", property="uUnbalance133", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_134", property="uUnbalance134", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_135", property="uUnbalance135", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_136", property="uUnbalance136", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_137", property="uUnbalance137", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_138", property="uUnbalance138", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_139", property="uUnbalance139", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_140", property="uUnbalance140", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_141", property="uUnbalance141", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_142", property="uUnbalance142", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_143", property="uUnbalance143", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_144", property="uUnbalance144", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_145", property="uUnbalance145", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_146", property="uUnbalance146", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_147", property="uUnbalance147", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_148", property="uUnbalance148", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_149", property="uUnbalance149", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_150", property="uUnbalance150", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_151", property="uUnbalance151", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_152", property="uUnbalance152", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_153", property="uUnbalance153", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_154", property="uUnbalance154", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_155", property="uUnbalance155", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_156", property="uUnbalance156", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_157", property="uUnbalance157", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_158", property="uUnbalance158", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_159", property="uUnbalance159", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_160", property="uUnbalance160", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_161", property="uUnbalance161", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_162", property="uUnbalance162", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_163", property="uUnbalance163", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_164", property="uUnbalance164", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_165", property="uUnbalance165", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_166", property="uUnbalance166", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_167", property="uUnbalance167", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_168", property="uUnbalance168", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_169", property="uUnbalance169", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_170", property="uUnbalance170", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_171", property="uUnbalance171", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_172", property="uUnbalance172", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_173", property="uUnbalance173", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_174", property="uUnbalance174", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_175", property="uUnbalance175", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_176", property="uUnbalance176", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_177", property="uUnbalance177", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_178", property="uUnbalance178", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_179", property="uUnbalance179", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_180", property="uUnbalance180", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_181", property="uUnbalance181", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_182", property="uUnbalance182", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_183", property="uUnbalance183", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_184", property="uUnbalance184", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_185", property="uUnbalance185", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_186", property="uUnbalance186", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_187", property="uUnbalance187", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_188", property="uUnbalance188", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_189", property="uUnbalance189", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_190", property="uUnbalance190", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_191", property="uUnbalance191", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_192", property="uUnbalance192", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_193", property="uUnbalance193", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_194", property="uUnbalance194", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_195", property="uUnbalance195", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_196", property="uUnbalance196", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_197", property="uUnbalance197", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_198", property="uUnbalance198", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_199", property="uUnbalance199", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_200", property="uUnbalance200", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_201", property="uUnbalance201", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_202", property="uUnbalance202", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_203", property="uUnbalance203", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_204", property="uUnbalance204", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_205", property="uUnbalance205", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_206", property="uUnbalance206", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_207", property="uUnbalance207", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_208", property="uUnbalance208", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_209", property="uUnbalance209", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_210", property="uUnbalance210", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_211", property="uUnbalance211", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_212", property="uUnbalance212", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_213", property="uUnbalance213", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_214", property="uUnbalance214", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_215", property="uUnbalance215", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_216", property="uUnbalance216", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_217", property="uUnbalance217", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_218", property="uUnbalance218", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_219", property="uUnbalance219", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_220", property="uUnbalance220", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_221", property="uUnbalance221", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_222", property="uUnbalance222", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_223", property="uUnbalance223", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_224", property="uUnbalance224", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_225", property="uUnbalance225", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_226", property="uUnbalance226", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_227", property="uUnbalance227", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_228", property="uUnbalance228", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_229", property="uUnbalance229", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_230", property="uUnbalance230", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_231", property="uUnbalance231", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_232", property="uUnbalance232", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_233", property="uUnbalance233", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_234", property="uUnbalance234", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_235", property="uUnbalance235", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_236", property="uUnbalance236", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_237", property="uUnbalance237", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_238", property="uUnbalance238", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_239", property="uUnbalance239", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_240", property="uUnbalance240", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_241", property="uUnbalance241", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_242", property="uUnbalance242", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_243", property="uUnbalance243", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_244", property="uUnbalance244", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_245", property="uUnbalance245", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_246", property="uUnbalance246", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_247", property="uUnbalance247", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_248", property="uUnbalance248", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_249", property="uUnbalance249", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_250", property="uUnbalance250", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_251", property="uUnbalance251", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_252", property="uUnbalance252", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_253", property="uUnbalance253", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_254", property="uUnbalance254", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_255", property="uUnbalance255", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_256", property="uUnbalance256", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_257", property="uUnbalance257", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_258", property="uUnbalance258", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_259", property="uUnbalance259", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_260", property="uUnbalance260", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_261", property="uUnbalance261", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_262", property="uUnbalance262", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_263", property="uUnbalance263", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_264", property="uUnbalance264", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_265", property="uUnbalance265", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_266", property="uUnbalance266", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_267", property="uUnbalance267", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_268", property="uUnbalance268", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_269", property="uUnbalance269", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_270", property="uUnbalance270", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_271", property="uUnbalance271", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_272", property="uUnbalance272", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_273", property="uUnbalance273", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_274", property="uUnbalance274", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_275", property="uUnbalance275", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_276", property="uUnbalance276", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_277", property="uUnbalance277", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_278", property="uUnbalance278", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_279", property="uUnbalance279", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_280", property="uUnbalance280", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_281", property="uUnbalance281", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_282", property="uUnbalance282", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_283", property="uUnbalance283", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_284", property="uUnbalance284", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_285", property="uUnbalance285", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_286", property="uUnbalance286", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_287", property="uUnbalance287", jdbcType=JdbcType.DECIMAL),
            @Result(column="U_UNBALANCE_288", property="uUnbalance288", jdbcType=JdbcType.DECIMAL)
    })
    List<D_vUnbalanceCurvePo> selectVunbalanceBy2Date(@Param("start_date")String start_date, @Param("end_date")String end_date);

}