spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;characterEncoding=utf8
#        username: root
#        password: 123
        url: jdbc:mysql://192.168.254.98:3306/test?useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;characterEncoding=utf8
        username: test
        password: test
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
      view:
        prefix: /view/
        suffix: .html
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true

#    cache:
#        cache-names: redisDemo
#        redis:
#          host: localhost
#          port: 3306
#          pool.max-idle: 8
#          pool.min-idle: 1
#          pool.max-active: 8
#          pool.max-wait: -1
#mybatis:
#  typeAliasesPackage: com.dao.model

logging:
      file: D:/logs/task.log
      level:
        root: INFO
        org:
          springframework:
                    web: INFO
#      pattern:
#        console: %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
#        file: %d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n
#        level: user:%X{user} %5p
server:
    port: 8088
    tomcat:
        uri-encoding: UTF-8



